import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js";

const firebaseConfig={apiKey:"AIzaSyA1svbzlhdjiiDMyRIgqQq1jSu_F8li3Bw",authDomain:"zisa-spelletjesmaker-pro.firebaseapp.com",projectId:"zisa-spelletjesmaker-pro",storageBucket:"zisa-spelletjesmaker-pro.appspot.com",messagingSenderId:"828063957776",appId:"1:828063957776:web:8d8686b478846fe980db95"};
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const joinPlayClass=httpsCallable(getFunctions(app,"europe-west1"),"joinPlayClass");
const loading=document.getElementById("loadingState"),error=document.getElementById("errorState"),menu=document.getElementById("gameMenu"),grid=document.getElementById("gradeGrid");

function deviceId(){let id=localStorage.getItem("zisa_play_device_id");if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem("zisa_play_device_id",id)}return id}
function code(){const fromUrl=new URLSearchParams(location.search).get("code");if(fromUrl)sessionStorage.setItem("zisa_play_code",fromUrl);return fromUrl||sessionStorage.getItem("zisa_play_code")||""}
function messageFor(err){const raw=String(err?.message||err?.details||"");if(raw.includes("50 gekoppelde"))return["De toestelgrens is bereikt","Vraag je leerkracht om een oud toestel te verwijderen."];if(raw.includes("30 leerlingen"))return["Er oefenen al 30 leerlingen","Probeer over enkele minuten opnieuw."];if(raw.includes("abonnement"))return["De leerlingentoegang is niet actief","Het PRO-abonnement van je leerkracht is verlopen of niet actief."];return["Deze QR-code werkt niet","Vraag je leerkracht om de QR-code na te kijken."]}
function gradeCard(n,label,description){const a=document.createElement("a");a.className="grade-card";a.href=`./games/start_leerjaar${n}.html`;a.innerHTML=`<span class="grade-number">${n}</span><h3>${label}</h3><p>${description}</p><b>Bekijk de spellen →</b>`;return a}
async function open(){loading.hidden=false;error.hidden=true;menu.hidden=true;try{const localPreview=['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).get('preview')==='1';const data=localPreview?{config:{grade1:true,grade2:true,grade3:true},registeredCount:24}:(await joinPlayClass({code:code(),deviceId:deviceId()})).data||{};sessionStorage.setItem("zisa_play_allowed","1");grid.replaceChildren();if(data.config?.grade1)grid.append(gradeCard(1,"Eerste leerjaar","Splitsen en hoofdrekenen op een speelse manier."));if(data.config?.grade2)grid.append(gradeCard(2,"Tweede leerjaar","Hoofdrekenen en de tafels verder inoefenen."));if(data.config?.grade3)grid.append(gradeCard(3,"Derde leerjaar","Tafels en rekenvaardigheden automatiseren."));document.getElementById("deviceNote").textContent=`${data.registeredCount} van 50 gekoppelde toestellen · maximaal 30 leerlingen tegelijk`;loading.hidden=true;menu.hidden=false}catch(err){console.error(err);const[t,m]=messageFor(err);document.getElementById("errorTitle").textContent=t;document.getElementById("errorMessage").textContent=m;loading.hidden=true;error.hidden=false}}
document.getElementById("retryButton").addEventListener("click",open);open();
