const $=id=>document.getElementById(id);
const rows=[{name:'Piano',icon:'🎹',color:'#de6d36'},{name:'Gitaar',icon:'🎸',color:'#d44e7b'},{name:'Bas',icon:'♪',color:'#289a8e'},{name:'Xylofoon',icon:'♫',color:'#9b69c5'},...['Hoogst','Hoog','Midden','Laag','Laagst'].map((name,i)=>({name,icon:'♪',color:['#c45591','#8253ba','#4967bf','#238eab','#29977e'][i]}))];
let pattern=rows.map(()=>Array(16).fill(false)),mode='rhythm',length=8,ctx,master,playing=false,timer=null,step=0,audioRun=0;const activeSounds=new Set();
const missions={free:['Kies een instrument. Tik een paar klanken en druk op Afspelen.','Kies een idee. Maak je muziek en verander daarna één ding. Wat klinkt anders?'],beat:['Maak een ritme waarop je kunt stappen. Laat ook vakjes leeg.','Maak een stapritme met twee klanken. Stap op de tel en klap jouw ritme erbij.'],sleep:['Maak zachte muziek voor een slapende beer. Probeer eerst luid en zacht.','Maak muziek voor een beer die in slaap valt. Probeer jouw stukje eerst gewoon en daarna zachter. Wat past beter?'],party:['Maak snelle feestmuziek. Probeer eerst een traag en een snel tempo.','Maak feestmuziek met een duidelijk ritme. Verander het tempo en vertel wat het best bij het feest past.'],rain:['Welke klanken lijken op regen? Probeer de klanken en maak een regenbui.','Kies klanken voor een regenbui. Maak een stukje en bedenk hoe je een zachtere bui laat horen.']};
const sampleFiles=['piano-C4','piano-D4','piano-E4','piano-G4','piano-A4','guitar-acoustic-C4','guitar-acoustic-D4','guitar-acoustic-E4','guitar-acoustic-G4','guitar-acoustic-A4','xylophone-C5','xylophone-G5','bass-electric-E2','bass-electric-G2'];const buffers={};let loading;
async function audio(){if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.7;master.connect(ctx.destination)}await ctx.resume();if(!loading){$('playState').textContent='Instrumenten laden…';loading=Promise.all(sampleFiles.map(async f=>{const r=await fetch('audio/'+f+'.mp3');if(!r.ok)throw Error('sample');buffers[f]=await ctx.decodeAudioData(await r.arrayBuffer())})).catch(e=>{loading=null;throw e})}await loading;master.gain.setTargetAtTime(.7,ctx.currentTime,.01);return ctx}
function tone(row,time,amp=.45,duration=1.1,instrument){let file,rate=1;const inst=instrument||$('melodyInstrument').value;
if(row<4){file=['piano-C4','guitar-acoustic-C4','bass-electric-E2','xylophone-C5'][row];if(row===2)rate=Math.pow(2,-4/12)}else{const semitone=[9,7,4,2,0][row-4];if(inst==='piano'||inst==='guitar-acoustic'){file=inst+'-'+['A4','G4','E4','D4','C4'][row-4]}else if(inst==='bass-electric'){const base=semitone>=7?7:4;file=inst+(base===7?'-G2':'-E2');rate=Math.pow(2,(semitone-base)/12)}else{const base=semitone>=7?7:0;file='xylophone'+(base===7?'-G5':'-C5');rate=Math.pow(2,(semitone-base)/12)}}
const source=ctx.createBufferSource();source.buffer=buffers[file];source.playbackRate.value=rate;const g=ctx.createGain();source.connect(g);g.connect(master);const level=Math.max(.001,amp*.8);g.gain.setValueAtTime(level,time);g.gain.setValueAtTime(level,time+Math.max(.06,duration-.25));g.gain.exponentialRampToValueAtTime(.0001,time+duration);activeSounds.add(source);source.start(time);source.stop(time+duration+.02);source.onended=()=>{activeSounds.delete(source);source.disconnect();g.disconnect()}}
function pulseTone(time,accent){const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=accent?1300:950;g.gain.setValueAtTime(.06,time);g.gain.exponentialRampToValueAtTime(.0001,time+.025);o.connect(g);g.connect(master);activeSounds.add(o);o.start(time);o.stop(time+.03);o.onended=()=>{activeSounds.delete(o);o.disconnect();g.disconnect()}}
function activeRows(){return mode==='rhythm'?[0,1,2,3]:[4,5,6,7,8]}
function renderGrid(){const g=$('grid');g.replaceChildren();const narrow=window.innerWidth<640;const cols=length===16&&narrow?8:length;g.style.gridTemplateColumns=`${narrow?'76px':'112px'} repeat(${cols},minmax(0,1fr))`;
for(let start=0;start<length;start+=cols){const blank=document.createElement('span');g.append(blank);for(let j=start;j<Math.min(start+cols,length);j++){let n=document.createElement('span');n.className='beat-number';n.dataset.beat=j;n.textContent=j+1;g.append(n)}for(const r of activeRows()){let l=document.createElement('div');l.className='row-label';const b=document.createElement('button');b.textContent=rows[r].icon;b.setAttribute('aria-label','Beluister '+rows[r].name);b.onclick=async()=>{stop();await audio();tone(r,ctx.currentTime+.02,Number($('volume').value)/100)};l.append(b,document.createTextNode(rows[r].name));g.append(l);for(let j=start;j<Math.min(start+cols,length);j++){const b=document.createElement('button');b.className='cell'+(pattern[r][j]?' on':'')+(j%4===0?' group-start':'');b.style.setProperty('--color',rows[r].color);b.dataset.beat=j;b.setAttribute('aria-label',`${rows[r].name}, tel ${j+1}`);b.setAttribute('aria-pressed',pattern[r][j]);b.onclick=()=>{pattern[r][j]=!pattern[r][j];b.classList.toggle('on',pattern[r][j]);b.setAttribute('aria-pressed',pattern[r][j]);if(typeof renderSimple==='function')renderSimple();if(!playing&&pattern[r][j])audio().then(()=>tone(r,ctx.currentTime+.02,Number($('volume').value)/100)).catch(audioError)};g.append(b)}}}}
function clearHighlight(){document.querySelectorAll('.now').forEach(e=>e.classList.remove('now'))}
function stop(){audioRun++;playing=false;clearTimeout(timer);timer=null;for(const sound of activeSounds){try{sound.stop()}catch(e){}}activeSounds.clear();clearHighlight();$('play').textContent='▶ Afspelen';$('playState').textContent='Gestopt';$('concertStatus').textContent='';if(ctx&&master){master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setTargetAtTime(.0001,ctx.currentTime,.01)}}
function audioError(){stop();$('playState').textContent='Geluid lukt niet. Probeer opnieuw.';$('concertStatus').textContent='Geluid lukt niet. Probeer opnieuw.'}
async function play(){stop();if(!pattern.some(r=>r.slice(0,length).some(Boolean))){$('playState').textContent='Kies eerst enkele klankvakjes.';$('concertStatus').textContent='Maak eerst een stukje bij Muziek maken.';return}const run=audioRun;try{await audio();if(run!==audioRun)return;master.gain.setTargetAtTime(.7,ctx.currentTime,.01);playing=true;step=0;$('play').textContent='♫ Speelt…';const tick=()=>{if(!playing||run!==audioRun)return;clearHighlight();document.querySelectorAll(`[data-beat="${step}"]`).forEach(e=>e.classList.add('now'));const t=ctx.currentTime+.015;pattern.forEach((r,i)=>{if(r[step])tone(i,t,Number($('volume').value)/100,Math.min(1.2,60000/Number($('tempo').value)/1000*.92))});if($('pulse').checked)pulseTone(t,step%4===0);$('playState').textContent=`Tel ${step+1} van ${length}`;$('concertStatus').textContent=`Speelt: ${$('songName').value.trim()||'Mijn muziekstuk'} · tel ${step+1}`;step++;if(step===length){if($('loop').checked)step=0;else{timer=setTimeout(stop,60000/Number($('tempo').value));return}}timer=setTimeout(tick,60000/Number($('tempo').value))};tick()}catch(e){audioError()}}
function switchView(id){stop();document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('.tab').forEach(e=>{e.classList.toggle('active',e.dataset.view===id);e.setAttribute('aria-current',e.dataset.view===id?'page':'false')})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('play').onclick=play;$('stop').onclick=stop;$('concertPlay').onclick=play;$('concertStop').onclick=stop;$('backToMake').onclick=()=>switchView('make');
function setMode(m){mode=m;$('rhythmTab').setAttribute('aria-pressed',m==='rhythm');$('melodyTab').setAttribute('aria-pressed',m==='melody');$('gridHelp').textContent=m==='rhythm'?'Tik een vakje aan voor een klank. Een leeg vakje is stil.':'Van laag naar hoog: kies tonen. Ritme en melodie spelen samen.';renderGrid()}
$('melodyInstrument').onchange=stop;$('rhythmTab').onclick=()=>setMode('rhythm');$('melodyTab').onclick=()=>setMode('melody');$('length').onchange=()=>{stop();length=Number($('length').value);renderGrid()};$('clear').onclick=()=>{stop();if(pattern.some(r=>r.some(Boolean))&&!confirm('Alle klankvakjes wissen?'))return;pattern=rows.map(()=>Array(16).fill(false));renderGrid();$('playState').textContent='Klaar voor een nieuw stukje'};
$('example').onclick=()=>{stop();if(pattern.some(r=>r.some(Boolean))&&!confirm('Jouw stukje vervangen door het voorbeeld?'))return;pattern=rows.map(()=>Array(16).fill(false));[0,4,8,12].forEach(j=>pattern[0][j]=true);[2,6,10,14].forEach(j=>pattern[1][j]=true);[0,2,4,6,8,10,12,14].forEach((j,i)=>pattern[[8,6,5,6][i%4]][j]=true);renderGrid();$('playState').textContent='Voorbeeld klaar. Druk op Afspelen.'};
function missionText(){return missions[$('mission').value][$('age').value==='6'?0:1]}function updateMission(){$('missionText').textContent=missionText()}$('age').onchange=updateMission;$('mission').onchange=updateMission;$('readMission').onclick=()=>{stop();if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(missionText());u.lang='nl-BE';u.rate=.85;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='nl-BE')||voices.find(v=>v.lang.startsWith('nl'))||null;speechSynthesis.speak(u)};if(!window.speechSynthesis){$('readMission').hidden=true}
$('tempo').oninput=()=>{$('tempoWord').textContent=+$('tempo').value<84?'Traag':+$('tempo').value<120?'Rustig':'Snel'};$('volume').oninput=()=>{$('volumeWord').textContent=+$('volume').value<30?'Zacht':+$('volume').value<60?'Gewoon':'Luid'};
const questions=[{q:'In welk stukje hoor je een gitaar?',choices:['Stukje A','Stukje B'],correct:1,kind:'timbre',why:'B is een akoestische gitaar. A is een piano.'},{q:'Welk stukje gaat sneller?',choices:['Stukje A','Stukje B'],correct:1,kind:'tempo',why:'B heeft minder tijd tussen de klanken. Het tempo is sneller.'},{q:'Welk stukje klinkt zachter?',choices:['Stukje A','Stukje B'],correct:0,kind:'volume',why:'A klinkt zachter. Het ritme en het tempo zijn hetzelfde.'},{q:'Welke melodie gaat omhoog?',choices:['Stukje A','Stukje B'],correct:1,kind:'pitch',why:'In B gaan de tonen van laag naar hoog.'},{q:'In welk ritme hoor je een stilte?',choices:['Stukje A','Stukje B'],correct:0,kind:'rest',why:'In A ontbreekt één klank. De tel gaat door, maar je hoort even niets.'}];let question=0,heard=new Set(),questionBusy=false;
function showQuestion(){heard.clear();questionBusy=false;const q=questions[question];$('questionCount').textContent=`Luistervraag ${question+1} van ${questions.length}`;$('questionTitle').textContent=q.q;$('feedback').textContent='Luister eerst naar A en B.';$('answers').replaceChildren();q.choices.forEach((text,i)=>{const b=document.createElement('button');b.textContent=text;b.disabled=true;b.onclick=()=>{if(questionBusy)return;const right=i===q.correct;$('feedback').textContent=right?'Goed gehoord! '+q.why:'Luister nog eens. '+(q.kind==='tempo'?'Let op de tijd tussen de klanken.':q.kind==='volume'?'Let op hoe luid de klanken zijn.':q.kind==='pitch'?'Hoor je de tonen stijgen of dalen?':q.kind==='timbre'?'Denk aan het tokkelen op snaren.':'Hoor je op elke tel een klank?');b.classList.toggle('chosen',right)};$('answers').append(b)})}
async function hear(which){stop();const run=audioRun;questionBusy=true;$('answers').querySelectorAll('button').forEach(b=>b.disabled=true);try{await audio();if(run!==audioRun)return;master.gain.setTargetAtTime(.7,ctx.currentTime,.01);const q=questions[question],spacing=q.kind==='tempo'?(which===0?.8:.4):.7;for(let i=0;i<4;i++){if(q.kind==='rest'&&which===0&&i===2)continue;const r=q.kind==='pitch'?(which===0?[4,5,6,8][i]:[8,6,5,4][i]):q.kind==='timbre'?which:0;tone(r,ctx.currentTime+.05+i*spacing,q.kind==='volume'?(which===0?.15:.65):.45,spacing*.9)}$('feedback').textContent=`Je luistert naar ${which===0?'A':'B'}…`;timer=setTimeout(()=>{if(run!==audioRun)return;questionBusy=false;heard.add(which);$('feedback').textContent=heard.size===2?'Welk antwoord kies je?':'Luister ook naar het andere stukje.';$('answers').querySelectorAll('button').forEach(b=>b.disabled=heard.size!==2)},spacing*4*1000+200)}catch(e){questionBusy=false;$('feedback').textContent='Geluid lukt niet. Tik nog eens op Luister.'}}
$('hearA').onclick=()=>hear(0);$('hearB').onclick=()=>hear(1);$('nextQuestion').onclick=()=>{stop();question=(question+1)%questions.length;showQuestion()};
const goals=[['MV.011','Bouwstenen herkennen','Luistervragen: tempo, dynamiek, melodielijn en ritme. Laat ook de doorgaande tel ervaren.'],['MV.018','Bouwstenen gebruiken','Maak een klankstuk bij een gevoel, situatie of verhaal. Verken eerst de gekozen bouwsteen.'],['MV.023 / MV.025','Technieken herkennen en gebruiken','Componeren, luisteren en een grafische partituur zelf uitvoeren.'],['MV.002','Betekenis verwoorden','Laat vertellen wat de muziek uitdrukt en waarom.'],['MV.091 / MV.092','Presenteren en afstemmen','Laat leerlingen presenteren of samen spelen en hun bijdragen op elkaar afstemmen.'],['MV.094 / MV.095','Reflecteren','Bespreek eigen werk en dat van klasgenoten met de vragen bij Laten horen.'],['MV.097','Muzische grondhouding','Observeer experimenteren, durf, eigen keuzes en openheid voor anderen.']];const table=document.createElement('table');table.innerHTML='<thead><tr><th>Doel</th><th>Focus</th><th>Activiteit / observatie</th></tr></thead>';const tbody=document.createElement('tbody');goals.forEach(row=>{const tr=document.createElement('tr');row.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});tbody.append(tr)});table.append(tbody);$('goalTable').append(table);$('teacherOpen').onclick=()=>{stop();$('teacher').showModal()};$('teacherClose').onclick=()=>$('teacher').close();
window.addEventListener('resize',renderGrid);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();window.speechSynthesis?.cancel()}});renderGrid();showQuestion();
