let cursor=0;let rests=Array(16).fill(false);const history=[];
const instruments={piano:'Piano','guitar-acoustic':'Gitaar',xylophone:'Xylofoon','bass-electric':'Basgitaar'};
const keyLabels=['Laag','Lager midden','Midden','Hoger midden','Hoog'];
function saveStep(){history.push({pattern:pattern.map(r=>r.slice()),rests:rests.slice(),cursor});if(history.length>40)history.shift();$('undo').disabled=false}
function renderSimple(){const strip=$('songStrip');strip.replaceChildren();let count=0;for(let j=0;j<length;j++){const melody=[8,7,6,5,4].filter(r=>pattern[r][j]);const rhythm=[0,1,2,3].some(r=>pattern[r][j]);const r=melody[0],index=r===undefined?-1:8-r;if(index>=0)count++;const b=document.createElement('button');b.className='song-slot'+(index>=0?' filled':'')+(j===cursor?' selected':'');b.dataset.beat=j;if(index>=0)b.style.setProperty('--slot',rows[r].color);b.setAttribute('aria-label',`Vakje ${j+1}: ${index>=0?keyLabels[index]:rests[j]?'stilte':'leeg'}${rhythm?', met ritmeklank':''}. Tik om te veranderen.`);const num=document.createElement('small');num.textContent=j+1;const sym=document.createElement('span');sym.className='slot-symbol';sym.textContent=melody.length>1?'♫':index>=0?'♪':rests[j]?'—':rhythm?'♫':'+';const label=document.createElement('span');label.textContent=melody.length>1?'Samen':index>=0?String(index+1):rests[j]?'Stil':rhythm?'Ritme':'';b.append(num,sym,label);b.onclick=()=>{if(playing)stop();cursor=j;renderSimple();$('easyStatus').textContent=`Vakje ${j+1} gekozen. Tik op een klanktoets om dit te veranderen.`;if(index>=0)previewNote(r)};strip.append(b)}$('sequenceCount').textContent=`${count} / ${length} klanken`;document.querySelectorAll('[data-instrument]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.instrument===$('melodyInstrument').value));$('undo').disabled=history.length===0}
const oldRenderGrid=renderGrid;renderGrid=function(){oldRenderGrid();renderSimple()};
async function previewNote(row){try{const run=audioRun;await audio();if(run!==audioRun)return;tone(row,ctx.currentTime+.02,Number($('volume').value)/100,1.5)}catch(e){audioError();$('easyStatus').textContent='De klanken konden niet laden. Probeer nog eens.'}}
function addNote(row){if(cursor>=length){$('easyStatus').textContent='Je rij is vol! Druk op Afspelen, of tik een vakje aan om het te veranderen.';return}if(playing)stop();saveStep();const position=cursor;for(let r=4;r<9;r++)pattern[r][cursor]=r===row;rests[cursor]=row===null;cursor++;renderGrid();$('easyStatus').textContent=cursor<length?`Vakje ${position+1} gevuld. Kies de volgende klank.`:'Je muziekje is klaar! Druk op Afspelen. Een vakje veranderen? Tik het aan.';if(row!==null)previewNote(row)}
for(let i=0;i<5;i++){const row=8-i,b=document.createElement('button');b.className='sound-key';b.style.setProperty('--key',rows[row].color);b.setAttribute('aria-label',`Voeg klank ${i+1} toe: ${keyLabels[i]}`);b.innerHTML=`<span>${i+1}</span><b>${i===0?'Laag':i===4?'Hoog':'♪'}</b>`;b.onclick=()=>addNote(row);$('soundKeys').append(b)}const restButton=document.createElement('button');restButton.className='rest-key';restButton.innerHTML='<span>—</span><b>Stilte</b>';restButton.onclick=()=>addNote(null);$('soundKeys').append(restButton);
async function chooseInstrument(value){stop();$('melodyInstrument').value=value;renderSimple();const run=audioRun;$('easyStatus').textContent=`${instruments[value]} laden…`;try{await audio();if(run!==audioRun)return;const t=ctx.currentTime+.02;[8,6,5].forEach((r,i)=>tone(r,t+i*.45,.6,1.3,value));$('easyStatus').textContent=`Dit is de ${instruments[value].toLowerCase()}. Je hele melodie speelt met dit instrument.`;$('playState').textContent='Kies een klanktoets om te beginnen.'}catch(e){audioError();$('easyStatus').textContent='Laden lukt niet. Tik nog eens op het instrument.'}}
document.querySelectorAll('[data-instrument]').forEach(b=>b.onclick=()=>chooseInstrument(b.dataset.instrument));$('melodyInstrument').onchange=()=>chooseInstrument($('melodyInstrument').value);
$('undo').onclick=()=>{if(!history.length)return;stop();const previous=history.pop();pattern=previous.pattern;rests=previous.rests;cursor=Math.min(previous.cursor,length);renderGrid();$('easyStatus').textContent='De vorige verandering is ongedaan gemaakt.'};
$('clear').onclick=()=>{stop();saveStep();pattern=rows.map(()=>Array(16).fill(false));rests=Array(16).fill(false);cursor=0;renderGrid();$('easyStatus').textContent='Een lege rij. Tik op een klanktoets om te beginnen.';$('playState').textContent='Je kunt wissen ongedaan maken.'};
async function easyExample(){stop();saveStep();pattern=rows.map(()=>Array(16).fill(false));rests=Array(16).fill(false);[8,6,5,6,7,8,5,8].forEach((r,j)=>pattern[r][j]=true);cursor=8;renderGrid();$('easyStatus').textContent='Luister: laag en hoog wisselen af. Kies daarna een ander instrument en druk opnieuw op Afspelen.';await play()}
$('easyExample').onclick=easyExample;$('example').onclick=easyExample;
$('length').onchange=()=>{stop();length=Number($('length').value);cursor=Math.min(cursor,length);renderGrid();$('easyStatus').textContent=`Je muziekstuk heeft ${length} vakjes.`};
const originalPlay=play;play=async function(){if(!pattern.some(r=>r.slice(0,length).some(Boolean))){$('easyStatus').textContent='Tik eerst op een paar gekleurde toetsen, of kies Hoor een voorbeeld.'}await originalPlay()};$('play').onclick=play;$('concertPlay').onclick=play;
renderSimple();updateMission();
