'use strict';
const $=id=>document.getElementById(id),KINDS={one:{label:'Eén klap',marks:'●',count:1},two:{label:'Twee klappen',marks:'● ●',count:2},four:{label:'Vier klappen',marks:'● ● ● ●',count:4},rest:{label:'Stilte',marks:'—',count:0}},EXAMPLES=[['one','one','rest','one','rest','one','one','rest'],['one','two','one','two','two','rest','two','one'],['two','four','one','rest','four','two','rest','one']];
function notation(count){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 120 68');svg.setAttribute('class','notation');svg.setAttribute('aria-hidden','true');const add=(tag,attrs,parent=svg)=>{const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));parent.append(e);return e};if(!count){const g=add('g',{});add('path',{d:'M58 9 L69 22 L57 34 L67 45 Q49 39 57 59 Q39 47 53 38 L47 30 L61 20 Z',fill:'currentColor'},g);return svg}const xs=count===1?[54]:count===2?[32,83]:[17,44,71,98];for(const x of xs){const g=add('g',{});add('ellipse',{cx:x,cy:51,rx:8,ry:5,transform:'rotate(-20 '+x+' 51)',fill:'currentColor'},g);add('path',{d:'M'+(x+7)+' 50 V13',stroke:'currentColor','stroke-width':2.6,fill:'none'},g)}if(count>1){add('path',{d:'M'+(xs[0]+7)+' 13 H'+(xs.at(-1)+7),stroke:'currentColor','stroke-width':6});if(count===4)add('path',{d:'M'+(xs[0]+7)+' 23 H'+(xs.at(-1)+7),stroke:'currentColor','stroke-width':6})}return svg}
const LESSONS=[
[['one','one','one','one'],['one','one','rest','one'],['rest','one','rest','one'],['one','rest','one','rest'],['one','one','one','rest'],['rest','one','one','one'],['one','rest','rest','one'],['one','rest','one','one']],
[['two','one','one','one'],['one','two','one','two'],['two','two','one','one'],['one','two','rest','two'],['two','rest','two','one'],['rest','two','one','two'],['two','one','two','rest'],['two','two','two','one']],
[['four','one','two','one'],['two','four','one','rest'],['one','two','four','one'],['four','two','rest','two'],['two','one','four','two'],['rest','four','two','one'],['four','four','two','one'],['two','four','rest','four']]
];
let activity='training',playPattern=[],shownRow=-1,svgMarks=[],cursor;
function rowSVG(row){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 840 160');svg.setAttribute('role','img');svg.setAttribute('aria-label',row.map(k=>KINDS[k].label).join(', '));const add=(tag,attrs,parent=svg,text)=>{const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;parent.append(e);return e};
add('path',{d:'M15 115 H825 M15 91 V139 M825 91 V139',stroke:'#666','stroke-width':2,fill:'none'});cursor=add('rect',{x:20,y:7,width:23,height:137,fill:'#d9efff',visibility:'hidden'});svgMarks=[];
row.forEach((kind,beat)=>{const count=KINDS[kind].count,n=Math.max(1,count),xs=[];for(let j=0;j<n;j++){const x=50+beat*190+j*190/n;xs.push(x);add('text',{x,y:28,'text-anchor':'middle',fill:j===0?'#388abe':'#777','font-size':21,'font-family':'Arial'},svg,j===0?String(beat+1):count===2?'&':['','e','&','a'][j]);const g=add('g',{color:'#171717'});if(count){add('ellipse',{cx:x,cy:115,rx:9,ry:6,transform:'rotate(-20 '+x+' 115)',fill:'currentColor'},g);add('path',{d:'M'+(x+8)+' 114 V62',stroke:'currentColor','stroke-width':3},g)}else{add('path',{d:'M'+(x-3)+' 77 l11 13 -12 12 10 11 q-18 -6 -10 14 q-18 -12 -4 -21 l-6 -8 14 -10 Z',fill:'currentColor'},g)}svgMarks.push({beat,sub:j,count:n,x,g})}if(count>1){add('path',{d:'M'+(xs[0]+8)+' 62 H'+(xs.at(-1)+8),stroke:'#171717','stroke-width':7});if(count===4)add('path',{d:'M'+(xs[0]+8)+' 74 H'+(xs.at(-1)+8),stroke:'#171717','stroke-width':7})}});return svg}
function showRow(rowIndex=0){shownRow=rowIndex;const src=running?playPattern:activity==='training'?LESSONS[Number($('example').value)].flat():pattern;$('singleScore').replaceChildren(rowSVG(src.slice(rowIndex*4,rowIndex*4+4)));}
function pointAt(index,fraction){const row=Math.floor(index/4);if(shownRow!==row)showRow(row);for(const m of svgMarks){const on=m.beat===index%4&&m.sub===Math.min(m.count-1,Math.floor(fraction*m.count));m.g.setAttribute('color',on?'#2088be':'#171717');if(on){cursor.setAttribute('x',m.x-13);cursor.setAttribute('visibility','visible')}}}
function switchActivity(next){stop();activity=next;$('rhythmApp').classList.toggle('training',next==='training');$('trainingTab').setAttribute('aria-pressed',String(next==='training'));$('createTab').setAttribute('aria-pressed',String(next==='create'));$('levelHelp').textContent=next==='training'?'8 ritmes per level. Eerst luisteren, dan naklappen.':'Kies notenkaarten en tik op de tellen. Oefen daarna je eigen ritme.';draw();}
let pattern=[...EXAMPLES[0]],brush='one',cells=[],ctx,cache={},sources=[],running=false,paused=false,runId=0,raf=0,timeline=[],origin=0,seconds=.75,mode='echo';
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function draw(){ $('rhythmBoard').replaceChildren();cells=[];for(let row=0;row<pattern.length/4;row++){const line=element('div',undefined,'rhythm-row');line.append(element('span',String(row+1),'row-label'));for(let col=0;col<4;col++){const i=row*4+col,k=KINDS[pattern[i]],b=element('button',undefined,'beat');b.setAttribute('aria-label','Regel '+(row+1)+', tel '+(col+1)+': '+k.label);b.append(element('span',String(col+1),'number'));const marks=notation(k.count);b.append(marks,element('small',k.label));b.onclick=()=>{if($('rhythmApp').classList.contains('presenting'))return;if(running)stop();pattern[i]=brush;draw();$('status').textContent='Je ritme is aangepast. Luister hoe het klinkt.'};line.append(b);cells.push(b)}$('rhythmBoard').append(line)}$('pieceTitle').textContent=activity==='training'?'Level '+(Number($('example').value)+1):$('title').value.trim()||'Mijn klapritme';showRow(0)}
for(const [id,k]of Object.entries(KINDS)){const b=element('button');b.append(notation(k.count),element('small',k.label));b.dataset.kind=id;b.setAttribute('aria-pressed',id===brush?'true':'false');b.onclick=()=>{brush=id;[...$('palette').children].forEach(e=>e.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true')};$('palette').append(b)}
function level(){const n=Number($('example').value);[...$('palette').children].forEach(b=>b.hidden=(b.dataset.kind==='two'&&n<1)||(b.dataset.kind==='four'&&n<2));if((brush==='two'&&n<1)||(brush==='four'&&n<2))$('palette').children[0].click()}
$('example').onchange=()=>{stop();level();draw()};$('trainingTab').onclick=()=>switchActivity('training');$('createTab').onclick=()=>switchActivity('create');
function resetLights(){cells.forEach(c=>{c.classList.remove('current');[...c.children[1].children].forEach(n=>n.classList.remove('hit'))});[...$('pulse').children].forEach(e=>e.classList.remove('active'))}
function stop(message='Tik op Start als je nog eens wilt klappen.'){runId++;running=false;paused=false;cancelAnimationFrame(raf);for(const s of sources){try{s.stop()}catch{}}sources=[];resetLights();for(const id of ['tempo','sound','length','loadExample','open','title','example','trainingTab','createTab','metronome','clapHelp'])$(id).disabled=false;$('stop').disabled=true;$('pause').disabled=true;$('pause').textContent='Ⅱ Pauze';$('practice').textContent='▶ Start';$('practice').disabled=false;$('listen').disabled=false;$('perform').disabled=false;$('phase').textContent='👂 Eerst luisteren, dan ben jij!';$('rhythmApp').dataset.phase='idle';$('actionCue').classList.remove('on');$('clapIcon').textContent='👂';$('clapWord').textContent='Klaar?';if(cursor)cursor.setAttribute('visibility','hidden');$('status').textContent=message}
async function prepare(){ctx??=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const names=[$('sound').value,'hand-clap-single.wav'];return Promise.all(names.map(async name=>{if(!cache[name]){const r=await fetch('audio/'+name);if(!r.ok)throw Error();cache[name]=await ctx.decodeAudioData(await r.arrayBuffer())}return cache[name]}))}
function track(s){sources.push(s);s.onended=()=>{sources=sources.filter(x=>x!==s)}}
function hit(time,buffer,volume=1,slot=seconds){const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=buffer;const length=Math.min(buffer.duration,slot);g.gain.setValueAtTime(volume,time);g.gain.setValueAtTime(volume,time+Math.max(0,length-.015));g.gain.linearRampToValueAtTime(0,time+length);s.connect(g);g.connect(ctx.destination);track(s);s.start(time);s.stop(time+length)}
function tick(time,strong=false){const s=ctx.createOscillator(),g=ctx.createGain();s.frequency.value=strong?1000:700;g.gain.setValueAtTime(.06,time);g.gain.exponentialRampToValueAtTime(.001,time+.04);s.connect(g).connect(ctx.destination);track(s);s.start(time);s.stop(time+.045)}
function buildTimeline(p,m){const result=[];for(let r=0;r<p.length/4;r++){const phases=m==='echo'?['listen','answer']:[m];for(const phase of phases){if(phase==='answer')for(let n=4;n>0;n--)result.push({index:r*4,phase:'ready',count:0,countdown:n});for(let j=0;j<4;j++)result.push({index:r*4+j,phase,count:KINDS[p[r*4+j]].count})}}return result}
function animate(){if(!running||paused)return;const beat=(ctx.currentTime-origin)/seconds;resetLights();if(beat<0){$('phase').textContent='Bijna beginnen…';$('rhythmApp').dataset.phase='count';$('clapIcon').textContent=String(Math.max(1,Math.min(4,Math.ceil(-beat))));$('clapWord').textContent='Bijna beginnen';$('barLabel').textContent='Vier tellen vooraf'}else if(beat>=timeline.length){const again=$('repeat').checked;stop('Goed geoefend! Nog een keer, of probeer een ander level.');$('phase').textContent='⭐ Goed geklapt!';$('clapIcon').textContent='⭐';$('clapWord').textContent='Klaar!';if(again)start(mode);return}else{const ix=Math.floor(beat),step=timeline[ix],fraction=beat-ix,c=cells[step.index];if(step.phase==='ready'){if(shownRow!==Math.floor(step.index/4))showRow(Math.floor(step.index/4));if(cursor)cursor.setAttribute('visibility','hidden');svgMarks.forEach(m=>m.g.setAttribute('color','#171717'));$('rhythmApp').dataset.phase='ready';$('phase').textContent='Jouw beurt komt eraan!';$('actionCue').classList.remove('on');$('clapIcon').textContent=String(step.countdown);$('clapWord').textContent='Klaar om te klappen?';$('barLabel').textContent='Oefening '+(Math.floor(step.index/4)+1)+' · bijna beginnen';raf=requestAnimationFrame(animate);return}if(activity==='create'&&c)c.classList.add('current');pointAt(step.index,fraction);$('pulse').children[step.index%4].classList.add('active');$('rhythmApp').dataset.phase=step.phase;
$('phase').textContent=step.phase==='listen'?'👂 Kijk en luister':'👏 Nu jij! Klap maar mee';
const pulse=step.count>0&&(fraction*step.count)%1<.5;
$('actionCue').classList.toggle('on',pulse);
$('clapIcon').textContent=step.count===0?'🤫':step.phase==='listen'?'👂':'👏';
$('clapWord').textContent=step.count===0?'Stil':step.phase==='listen'?'Luister':pulse?'Klap!':'…';$('barLabel').textContent=(activity==='training'?'Oefening ':'Regel ')+(Math.floor(step.index/4)+1)+' / '+(playPattern.length/4)+' · tel '+(step.index%4+1);if(activity==='create'&&c&&step.count)c.children[1].children[Math.min(step.count-1,Math.floor(fraction*step.count))].classList.add('hit')}
raf=requestAnimationFrame(animate)}
function scheduleTimeline(buffer){timeline.forEach((step,i)=>{const t=origin+i*seconds;if(step.phase==='ready'&&$('metronome').checked)tick(t,step.countdown===4);if(step.phase==='listen'||(step.phase==='answer'&&$('clapHelp').checked))for(let n=0;n<step.count;n++)hit(t+n*seconds/step.count,step.phase==='answer'?buffer[1]:buffer[0],1,seconds/step.count)})}
async function start(nextMode){stop('Klank laden…');$('stop').disabled=false;mode=nextMode;const token=runId;try{const buffer=await prepare();if(token!==runId)return;seconds=60/Number($('tempo').value);playPattern=activity==='training'?LESSONS[Number($('example').value)].flat():[...pattern];timeline=buildTimeline(playPattern,mode);origin=ctx.currentTime+.1+4*seconds;if($('metronome').checked)for(let i=0;i<4;i++)tick(origin+(i-4)*seconds,i===0);scheduleTimeline(buffer);running=true;showRow(0);$('stop').disabled=false;$('pause').disabled=false;$('practice').textContent='↻ Opnieuw';$('status').textContent=mode==='echo'?'Blauw: luister. Daarna 4, 3, 2, 1… Groen: nu klap jij!':mode==='listen'?'Luister naar je hele ritme.':'Klap je ritme zelf. De aanwijzer helpt je.';animate()}catch{stop('De klank kon niet laden. Controleer je verbinding en probeer opnieuw.')}}
async function togglePause(){
 if(!running||!ctx)return;
 const token=runId,resume=paused;paused=!paused;cancelAnimationFrame(raf);$('pause').disabled=true;
 try{await (resume?ctx.resume():ctx.suspend());if(token!==runId)return;
 $('pause').textContent=resume?'Ⅱ Pauze':'▶ Verder';
 if(resume){animate()}else{$('phase').textContent='Ⅱ Pauze';$('clapIcon').textContent='Ⅱ';$('clapWord').textContent='Neem je tijd';$('actionCue').classList.remove('on');$('status').textContent='Tik op Verder om door te gaan. Of kies een ander level.'}
 }catch{stop('Pauzeren lukte niet. Tik op Start om opnieuw te beginnen.')}finally{if(token===runId)$('pause').disabled=false}
}
$('pause').onclick=togglePause;
for(const id of ['tempo','sound','metronome','clapHelp'])$(id).onchange=()=>stop('Instelling aangepast. Tik op Start.');
$('practice').onclick=()=>start('echo');$('listen').onclick=()=>start('listen');$('perform').onclick=()=>start('perform');$('stop').onclick=()=>stop();$('title').oninput=()=>{$('pieceTitle').textContent=$('title').value.trim()||'Mijn klapritme'};$('length').onchange=()=>{stop();const n=Number($('length').value)*4;pattern=Array.from({length:n},(_,i)=>pattern[i]||'rest');draw()};$('loadExample').onclick=()=>{stop();pattern=[...EXAMPLES[Number($('example').value)]];$('length').value='2';$('title').value='Mijn klapritme';draw()};
$('present').onclick=async()=>{$('rhythmApp').classList.add('presenting');$('exitPresent').hidden=false;try{await $('rhythmApp').requestFullscreen?.()}catch{}$('status').textContent='Stel je ritme voor. Kies ‘Luister & klap na’ om de klas te laten antwoorden.'};$('exitPresent').onclick=async()=>{$('rhythmApp').classList.remove('presenting');$('exitPresent').hidden=true;if(document.fullscreenElement)await document.exitFullscreen()};
function validate(data){if(!data||data.format!=='zisa-ritme-1'||typeof data.title!=='string'||data.title.length>60||!Array.isArray(data.pattern)||![4,8,12,16].includes(data.pattern.length)||!data.pattern.every(x=>Object.hasOwn(KINDS,x))||![60,80,100].includes(data.tempo))throw Error('invalid');return data}
$('save').onclick=()=>{const data={format:'zisa-ritme-1',title:$('title').value.trim()||'Mijn klapritme',pattern,tempo:Number($('tempo').value)},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=element('a');a.href=url;a.download='mijn-ritme.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Je ritmebestand is klaargezet om te downloaden. Open het later met ‘Open een ritme’.'};$('open').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;stop();try{if(f.size>10000)throw Error();const d=validate(JSON.parse(await f.text()));activity='create';$('rhythmApp').classList.remove('training');$('trainingTab').setAttribute('aria-pressed','false');$('createTab').setAttribute('aria-pressed','true');pattern=[...d.pattern];$('title').value=d.title;$('length').value=String(pattern.length/4);$('tempo').value=String(d.tempo);draw();$('status').textContent='Je ritme is geopend. Klaar om te oefenen of voor te stellen.'}catch{$('status').textContent='Dit is geen geldig Zisa-ritmebestand. Kies een bestand dat je hier hebt bewaard.'}$('file').value=''};
level();
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',()=>stop());draw();
