'use strict';
const el=id=>document.getElementById(id);
const natural=[60,62,64,65,67,69,71,72],noteNames=['do','re','mi','fa','sol','la','si','do'],letters=['C','D','E','F','G','A','B','C'];
const colors=['#de3e45','#e77a2e','#edc62d','#9cc538','#329a4e','#8052ae','#c84389','#de3e45'];
const instruments={boom:{name:'Boomwhackers',icon:'▥',color:'#dd575e',hint:'Tik op de buizen. Een lange buis klinkt laag, een korte buis klinkt hoog.'},piano:{name:'Piano',icon:'🎹',color:'#6d5bba',hint:'Speel op de toetsen. Je mag ook verschillende toetsen samen indrukken.'},guitar:{name:'Gitaar',icon:'🎸',color:'#ba8142',hint:'Tik op een snaar en luister hoe ze klinkt.'},xylo:{name:'Xylofoon',icon:'♫',color:'#389e94',hint:'Tik op de staafjes. Van links naar rechts hoor je laag naar hoog.'},drums:{name:'Drumpads',icon:'🥁',color:'#c85891',hint:'Maak een ritme met de grote trom, snare, hi-hat en handklap.'},bass:{name:'Basgitaar',icon:'♪',color:'#4f80b7',hint:'Speel lage klanken als basis voor je muziek.'},own:{name:'Eigen geluid',icon:'🎤',color:'#319a83',hint:'Maak zelf een klank en gebruik die in je muziek.'}};
let selected='boom',tracks=[],current=null,phase='idle',origin=0,playBase=0,nextCycle=0,raf=0,serial=0,operation=0,context,master,compressor,exporting=false;
const buffers=new Map(),pending=new Map(),sources=new Set(),buses=new Map();let sampleId=null,recorder=null,micStream=null,micTimer=null,micBusy=false,micOperation=0;
const beatSeconds=()=>60/Number(el('bpm').value),beats=()=>Number(el('bars').value),duration=()=>beats()*beatSeconds();
function tell(s){el('status').textContent=s}
function getContext(){if(!context){context=new(window.AudioContext||window.webkitAudioContext)();compressor=context.createDynamicsCompressor();compressor.threshold.value=-12;compressor.ratio.value=4;master=context.createGain();master.gain.value=.72;compressor.connect(master);master.connect(context.destination)}return context}
async function unlock(){const c=getContext();if(c.state!=='running')await c.resume();return c}
function definition(inst,note,sample){if(inst==='own')return{key:sample||sampleId,rate:1};if(inst==='drums')return{key:'drum-'+['kick','snare','hat','clap'][note]+'.wav',rate:1};if(inst==='boom'){const near=natural.reduce((a,b)=>Math.abs(a-note)<=Math.abs(b-note)?a:b);return{key:'boom-'+['C4','D4','E4','F4','G4','A4','B4','C5'][natural.indexOf(near)]+'.wav',rate:2**((note-near)/12)}}if(inst==='piano'||inst==='guitar'){const near=natural.reduce((a,b)=>Math.abs(a-note)<=Math.abs(b-note)?a:b);return{key:(inst==='piano'?'piano':'guitar-acoustic')+'-'+['C4','D4','E4','F4','G4','A4','B4','C5'][natural.indexOf(near)]+'.mp3',rate:2**((note-near)/12)}}if(inst==='xylo'){const base=note<66?60:67;return{key:'xylophone-'+(base===60?'C5':'G5')+'.mp3',rate:2**((note-base)/12)}}const base=note<66?64:67;return{key:'bass-electric-'+(base===64?'E2':'G2')+'.mp3',rate:2**((note-base)/12)}}
async function loadKey(key){if(!key)throw Error('Neem eerst een eigen geluid op.');if(buffers.has(key))return buffers.get(key);if(pending.has(key))return pending.get(key);const p=(async()=>{const r=await fetch('audio/'+key);if(!r.ok)throw Error('Een instrumentklank kon niet laden. Probeer opnieuw.');const b=await getContext().decodeAudioData(await r.arrayBuffer());buffers.set(key,b);return b})().finally(()=>pending.delete(key));pending.set(key,p);return p}
async function ready(inst){await unlock();const notes=inst==='drums'?[0,1,2,3]:natural;await Promise.all([...new Set(notes.map(n=>definition(inst,n).key))].map(loadKey))}
function bus(track){if(!buses.has(track.id)){const g=context.createGain();g.gain.value=track.muted?0:track.volume;g.connect(compressor);buses.set(track.id,g)}return buses.get(track.id)}
function sound(c,dest,event,when,limit=2.2,live=false){const def=definition(event.instrument,event.note,event.sample);const buffer=buffers.get(def.key);if(!buffer)return null;const s=c.createBufferSource(),g=c.createGain();s.buffer=buffer;s.playbackRate.value=def.rate;const naturalDuration=buffer.duration/def.rate;const length=Math.min(naturalDuration,event.instrument==='own'?5:limit);const amp=(event.velocity??.7)*.8;g.gain.setValueAtTime(amp,when);g.gain.setValueAtTime(amp,when+Math.max(.008,length-.09));g.gain.linearRampToValueAtTime(0,when+length);s.connect(g);g.connect(dest);s.start(when);s.stop(when+length+.01);if(live){sources.add(s);s.onended=()=>{sources.delete(s);s.disconnect();g.disconnect()}}return s}
function clickSound(when,strong){const o=context.createOscillator(),g=context.createGain();o.frequency.value=strong?1150:850;g.gain.setValueAtTime(.08,when);g.gain.exponentialRampToValueAtTime(.0001,when+.03);o.connect(g);g.connect(compressor);sources.add(o);o.start(when);o.stop(when+.035);o.onended=()=>{sources.delete(o);o.disconnect();g.disconnect()}}
function silence(){for(const s of sources){try{s.stop()}catch{}}sources.clear();for(const g of buses.values())g.disconnect();buses.clear();document.querySelectorAll('.hit').forEach(p=>p.classList.remove('hit'))}
function saveCurrent(){if(current?.events.length){tracks.push(current);tell('Partij opgenomen! Kies een ander instrument om samen te spelen.')}else if(current)tell('Je speelde nog geen klanken. Probeer het opnieuw.');current=null}
function stop(save=true){operation++;cancelAnimationFrame(raf);if(phase==='record'&&save)saveCurrent();else current=null;phase='idle';silence();el('liveTrack').hidden=true;renderTracks();updateControls();el('clock').textContent='00:00';if(el('record').textContent!=='● Neem een partij op')el('record').textContent='● Neem een partij op'}
function updateControls(){const busy=phase!=='idle'||exporting||micBusy;el('record').disabled=busy||tracks.length>=8;el('play').disabled=busy||!tracks.length;el('stop').disabled=phase==='idle';el('download').disabled=busy||!tracks.some(t=>!t.muted&&t.events.length);el('clear').disabled=busy||!tracks.length;el('demo').disabled=busy;el('bars').disabled=busy||tracks.length>0;el('bpm').disabled=busy;el('repeat').disabled=phase==='record'||phase==='count';el('micRecord').disabled=busy||phase!=='idle';el('micStop').disabled=!micBusy;document.querySelectorAll('[data-inst]').forEach(b=>b.disabled=phase==='record'||phase==='count'||exporting||micBusy);document.querySelectorAll('.track-controls button').forEach(b=>b.disabled=phase==='record'||phase==='count'||exporting)}
function eventColor(ev){return ev.instrument==='boom'||ev.instrument==='xylo'?colors[natural.indexOf(ev.note)]||instruments[ev.instrument].color:instruments[ev.instrument].color}
function trackRow(t,live=false){const row=document.createElement('div');row.className='track'+(t.muted?' muted':'')+(live?' recording':'');const label=document.createElement('div');label.className='track-name';const icon=document.createElement('span');icon.className='track-icon';icon.textContent=instruments[t.instrument].icon;const text=document.createElement('div');const name=document.createElement('b');name.textContent=live?'Opnemen…':t.name;const sub=document.createElement('small');sub.textContent=live?'Speel nu!':`${t.events.length} klanken`;text.append(name,sub);label.append(icon,text);const visual=document.createElement('div');visual.className='track-visual';for(const e of t.events){const mark=document.createElement('span');mark.className='event';mark.style.left=Math.min(99,e.beat/beats()*100)+'%';mark.style.setProperty('--event-color',eventColor(e));mark.style.height=(10+e.velocity*20)+'px';mark.title=instruments[e.instrument].name;visual.append(mark)}const head=document.createElement('div');head.className='playhead';head.hidden=phase==='idle';visual.append(head);const controls=document.createElement('div');controls.className='track-controls';if(!live){const mute=document.createElement('button');mute.textContent=t.muted?'🔇':'🔊';mute.title=t.muted?'Zet deze partij aan':'Zet deze partij stil';mute.setAttribute('aria-label',mute.title+': '+t.name);mute.setAttribute('aria-pressed',t.muted);mute.onclick=()=>{t.muted=!t.muted;const g=buses.get(t.id);if(g)g.gain.setTargetAtTime(t.muted?0:t.volume,context.currentTime,.02);renderTracks();updateControls()};const vol=document.createElement('input');vol.type='range';vol.min='0';vol.max='100';vol.value=t.volume*100;vol.setAttribute('aria-label','Volume van '+t.name);vol.oninput=()=>{t.volume=Number(vol.value)/100;const g=buses.get(t.id);if(g)g.gain.setTargetAtTime(t.muted?0:t.volume,context.currentTime,.02)};const del=document.createElement('button');del.textContent='✕';del.setAttribute('aria-label','Verwijder '+t.name);del.onclick=()=>ask('Partij verwijderen?',`Wil je ${t.name} uit je muziekstuk verwijderen?`,()=>{stop();tracks=tracks.filter(v=>v.id!==t.id);renderTracks();updateControls();tell('Partij verwijderd.')});controls.append(mute,vol,del)}row.append(label,visual,controls);return row}
function renderTracks(){el('trackCount').textContent=`${tracks.length} ${tracks.length===1?'partij':'partijen'}`;el('tracks').replaceChildren();if(!tracks.length){const empty=document.createElement('div');empty.className='empty';empty.innerHTML='<span>♫</span><p>Je band begint met één instrument.</p><small>Probeer hieronder wat klanken. Klaar? Druk op ‘Neem een partij op’.</small>';el('tracks').append(empty)}else tracks.forEach(t=>el('tracks').append(trackRow(t)));renderRuler()}
function renderRuler(){el('ruler').replaceChildren();for(let i=0;i<beats();i+=beats()>16?4:2){const label=document.createElement('span');label.textContent=i+1;el('ruler').append(label)}}
function scheduleTracks(base){for(const t of tracks){const dest=bus(t);for(const e of t.events)sound(context,dest,e,base+e.beat*beatSeconds(),Math.min(2.2,duration()-e.beat*beatSeconds()+.05),true)}}
async function startRecord(){if(phase!=='idle'||tracks.length>=8||exporting||micBusy)return;phase='loading';updateControls();const token=++operation;tell('Instrumentklanken laden…');try{await ready(selected);if(token!==operation)return;silence();const count=beatSeconds();origin=context.currentTime+.1+4*count;current={id:++serial,name:instruments[selected].name+' '+(tracks.length+1),instrument:selected,volume:.8,muted:false,events:[]};phase='count';for(let i=0;i<4;i++)clickSound(origin-(4-i)*count,i===0);scheduleTracks(origin);if(el('metronome').checked)for(let i=0;i<beats();i++)clickSound(origin+i*count,i%4===0);updateControls();raf=requestAnimationFrame(frame)}catch(e){stop(false);tell(e.message||'Geluid laden lukt niet. Probeer opnieuw.')}}
async function playAll(){if(!tracks.length||phase!=='idle'||exporting||micBusy)return;phase='loading';updateControls();const token=++operation;try{await unlock();if(token!==operation)return;silence();playBase=context.currentTime+.1;origin=playBase;nextCycle=playBase+duration();phase='play';scheduleTracks(playBase);tell('Jouw band speelt!');updateControls();raf=requestAnimationFrame(frame)}catch(e){stop(false);tell('Afspelen lukt niet. Probeer opnieuw.')}}
function frame(){if(phase==='idle')return;const now=context.currentTime;if(phase==='count'){const left=Math.min(4,Math.ceil((origin-now)/beatSeconds()));if(left>0){tell(`Tel mee: ${5-left}… Straks mag je spelen!`);el('record').textContent=`Klaar? ${left}`;el('clock').textContent=String(left)}else{phase='record';tell('Opname loopt. Speel op je instrument!');el('record').textContent='● Je speelt nu';el('liveTrack').hidden=false;el('liveTrack').replaceChildren(trackRow(current,true))}}
if(phase==='record'||phase==='play'){const total=duration();if(phase==='record'&&now>=origin+total){stop(true);return}if(phase==='play'){if(el('repeat').checked){if(now+.15>=nextCycle){scheduleTracks(nextCycle);nextCycle+=total}}else if(now>=playBase+total+.25){stop(false);tell('Klaar! Voeg een partij toe of download je muziek.');return}}const elapsed=Math.max(0,now-origin);const position=phase==='play'&&el('repeat').checked?elapsed%total:Math.min(elapsed,total);const pct=position/total*100;document.querySelectorAll('.playhead').forEach(h=>{h.hidden=false;h.style.left=pct+'%'});el('clock').textContent=`${String(Math.floor(position/60)).padStart(2,'0')}:${String(Math.floor(position%60)).padStart(2,'0')}`;document.querySelectorAll('.pad').forEach(p=>{const n=Number(p.dataset.note);const hit=tracks.some(t=>!t.muted&&t.events.some(e=>e.instrument===selected&&e.note===n&&position-e.beat*beatSeconds()>=0&&position-e.beat*beatSeconds()<.15));if(hit)p.classList.add('hit');else if(!p.dataset.pressed)p.classList.remove('hit')})}raf=requestAnimationFrame(frame)}
async function hit(note,pad){if(exporting||phase==='count'||phase==='loading'||micBusy)return;const inst=selected;try{await ready(inst);const when=context.currentTime+.008;const event={instrument:inst,note,sample:inst==='own'?sampleId:undefined,velocity:Number(el('strength').value)/100,beat:0};sound(context,compressor,event,when,inst==='own'?5:1.8,true);el('stop').disabled=false;if(phase==='record'&&current){const position=(when-origin)/beatSeconds();if(position>=0&&position<beats()){event.beat=position;current.events.push(event);el('liveTrack').replaceChildren(trackRow(current,true))}}pad.classList.add('hit');setTimeout(()=>{if(!pad.dataset.pressed)pad.classList.remove('hit')},160);const index=natural.indexOf(note);el('playingNote').textContent=inst==='drums'?['Grote trom','Snare','Hi-hat','Handklap'][note]:inst==='own'?'Jouw eigen geluid':instruments[inst].name+' · '+(index<0?'tussentoon':el('noteNames').checked?noteNames[index]:`klank ${index+1}`)}catch(e){tell(e.message||'De klank kon niet laden. Tik opnieuw.')}}
function makePad(note,cls,label){const b=document.createElement('button');b.className='pad '+cls;b.dataset.note=note;b.setAttribute('aria-label',instruments[selected].name+' '+label);b.onpointerdown=e=>{e.preventDefault();b.dataset.pressed='1';hit(note,b)};const release=()=>{delete b.dataset.pressed;setTimeout(()=>b.classList.remove('hit'),90)};b.onpointerup=release;b.onpointercancel=release;b.onpointerleave=release;b.onclick=e=>{if(e.detail===0)hit(note,b)};b.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.repeat){e.preventDefault();hit(note,b)}};return b}
function renderInstrument(){el('instrumentName').textContent=instruments[selected].name;el('instrumentHint').textContent=instruments[selected].hint;document.querySelectorAll('[data-inst]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.inst===selected));el('fiveWrap').hidden=!['boom','xylo'].includes(selected);el('playSurface').hidden=selected==='own';el('micPanel').hidden=selected!=='own';const surface=el('playSurface');surface.replaceChildren();surface.className='play-surface';const show=el('noteNames').checked;
if(selected==='boom'||selected==='xylo'){surface.classList.add(selected==='boom'?'tubes':'xylo');natural.forEach((n,i)=>{if(el('five').checked&&[3,6,7].includes(i))return;const b=makePad(n,selected==='boom'?'tube':'bar',show?noteNames[i]:`klank ${i+1}`);b.style.setProperty('--color',colors[i]);b.style.setProperty('--height',(195-i*12)+'px');const top=document.createElement('b');top.textContent=show?noteNames[i]:i+1;const low=document.createElement('small');low.textContent=i===0?'laag':i===7?'hoog':show?letters[i]:'';b.append(top,low);surface.append(b)})}
if(selected==='piano'){surface.classList.add('keyboard');natural.forEach((n,i)=>{const b=makePad(n,'key',show?noteNames[i]:`klank ${i+1}`);b.textContent=show?noteNames[i]:i+1;surface.append(b)});[[61,1],[63,2],[66,4],[68,5],[70,6]].forEach(([n,pos])=>{const b=makePad(n,'key black','tussentoon');b.style.left=(pos*12.5-3.75)+'%';b.textContent=show?['C♯','D♯','F♯','G♯','A♯'][[61,63,66,68,70].indexOf(n)]:'';surface.append(b)})}
if(selected==='guitar'||selected==='bass'){surface.classList.add('strings');const ns=selected==='guitar'?[60,62,64,67,69,72]:[60,64,67,72];ns.forEach((n,i)=>{const b=makePad(n,'string','snaar '+(i+1));b.style.setProperty('--thickness',(5-i*.55)+'px');b.textContent=show?noteNames[natural.indexOf(n)]:'Snaar '+(i+1);surface.append(b)});el('instrumentHint').textContent='Tik op een snaar. Deze speelgitaar gebruikt klanken die makkelijk bij elkaar passen.'}
if(selected==='drums'){surface.classList.add('drumpads');['Grote trom','Snare','Hi-hat','Handklap'].forEach((name,i)=>{const b=makePad(i,'drumpad',name);const icon=document.createElement('span');icon.textContent=['🥁','◉','✦','👏'][i];const text=document.createElement('b');text.textContent=name;b.append(icon,text);surface.append(b)})}
if(selected==='own'){el('micPad').replaceChildren();if(sampleId){const b=makePad(60,'own-pad','mijn geluid');b.textContent='▶ Speel mijn geluid';el('micPad').append(b)}}el('playingNote').textContent='Vrij proberen mag altijd.'}
for(const [id,inst] of Object.entries(instruments)){const b=document.createElement('button');b.dataset.inst=id;b.textContent=inst.icon+' '+inst.name;b.setAttribute('aria-pressed',id===selected);b.onclick=async()=>{selected=id;renderInstrument();if(id!=='own'){tell('Tik om '+inst.name.toLowerCase()+' te horen.');try{await ready(id)}catch(e){tell(e.message)}}};el('instrumentTabs').append(b)}
el('noteNames').onchange=renderInstrument;el('five').onchange=renderInstrument;el('record').onclick=startRecord;el('play').onclick=playAll;el('stop').onclick=()=>{if(phase==='count')tell('Opname geannuleerd.');else if(phase==='play')tell('Gestopt.');stop(true)};el('bars').onchange=renderTracks;el('bpm').onchange=()=>tell('Tempo aangepast. Je gespeelde ritme blijft behouden.');
function ask(title,text,action){el('askTitle').textContent=title;el('askText').textContent=text;el('askYes').onclick=()=>{el('ask').close();action()};el('ask').showModal()}el('askCancel').onclick=()=>el('ask').close();el('clear').onclick=()=>ask('Opnieuw beginnen?','Alle partijen verdwijnen. Download je muziek eerst als je die wilt bewaren.',()=>{stop(false);tracks=[];renderTracks();updateControls();tell('Een lege studio. Welk instrument kies je?')});
async function demo(){const go=async()=>{stop(false);phase='loading';updateControls();const token=++operation;tell('Voorbeeld laden…');try{await Promise.all([ready('boom'),ready('drums')]);if(token!==operation)return;el('bars').value='16';el('bpm').value='100';tracks=[{id:++serial,name:'Boomwhackermelodie',instrument:'boom',volume:.8,muted:false,events:[60,64,67,64,62,60,67,60,64,67,69,67,64,62,60,60].map((note,beat)=>({instrument:'boom',note,beat,velocity:.7}))},{id:++serial,name:'Drumritme',instrument:'drums',volume:.5,muted:false,events:Array.from({length:8},(_,i)=>({instrument:'drums',note:i%2?1:0,beat:i*2,velocity:.7}))}];phase='idle';renderTracks();updateControls();await playAll()}catch(e){stop(false);tell(e.message)}};if(tracks.length)ask('Voorbeeld openen?','Het voorbeeld vervangt jouw partijen. Download je eigen muziek eerst om ze te bewaren.',go);else await go()};el('demo').onclick=demo;
function releaseMic(){if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}clearTimeout(micTimer)}
function finishMic(){if(recorder&&recorder.state==='recording'){recorder.stop();el('micStatus').textContent='Je geluid wordt klaargezet…'}releaseMic()}
el('micRecord').onclick=async()=>{if(phase!=='idle'||micBusy||exporting)return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){el('micStatus').textContent='Deze browser kan geen microfoonopname maken. Probeer een recente browser.';return}micBusy=true;const token=++micOperation;updateControls();el('micStatus').textContent='Geef toestemming voor je microfoon als je browser dit vraagt.';try{await unlock();const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(token!==micOperation){stream.getTracks().forEach(t=>t.stop());return}micStream=stream;const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>{releaseMic();micBusy=false;updateControls();el('micStatus').textContent='Opnemen is mislukt. Probeer opnieuw.'};recorder.onstop=async()=>{releaseMic();try{const blob=new Blob(chunks,{type:recorder.mimeType});if(!blob.size)throw Error('empty');const buffer=await context.decodeAudioData(await blob.arrayBuffer());if(buffer.duration<.08)throw Error('short');sampleId='own-'+(++serial);buffers.set(sampleId,buffer);el('micStatus').textContent='Je geluid is klaar! Tik hieronder om het te horen. Neem daarna een partij op.';renderInstrument()}catch(e){el('micStatus').textContent='Dit geluid kon niet worden gelezen. Neem het opnieuw op.'}finally{micBusy=false;updateControls()}};recorder.start();el('micStatus').textContent='De microfoon neemt op… Druk op Klaar. Na 5 seconden stopt het vanzelf.';micTimer=setTimeout(finishMic,5000)}catch(e){releaseMic();micBusy=false;updateControls();el('micStatus').textContent=e.name==='NotAllowedError'?'Geen microfoontoegang. Je kunt de andere instrumenten gewoon gebruiken.':'De microfoon kon niet starten. Controleer of een andere app hem gebruikt.'}};el('micStop').onclick=()=>{if(recorder?.state==='recording')finishMic();else{micOperation++;micBusy=false;releaseMic();updateControls();el('micStatus').textContent='Microfoonopname geannuleerd.'}};
function encodeWav(buffer){const data=buffer.getChannelData(0),out=new ArrayBuffer(44+data.length*2),view=new DataView(out);const txt=(p,t)=>{for(let i=0;i<t.length;i++)view.setUint8(p+i,t.charCodeAt(i))};txt(0,'RIFF');view.setUint32(4,36+data.length*2,true);txt(8,'WAVE');txt(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);txt(36,'data');view.setUint32(40,data.length*2,true);let peak=0;for(const v of data)peak=Math.max(peak,Math.abs(v));const scale=peak>.96?.96/peak:1;for(let i=0;i<data.length;i++){const v=Math.max(-1,Math.min(1,data[i]*scale));view.setInt16(44+i*2,v<0?v*32768:v*32767,true)}return new Blob([out],{type:'audio/wav'})}
el('download').onclick=async()=>{if(phase!=='idle'||exporting||!tracks.some(t=>!t.muted))return;exporting=true;updateControls();tell('Je muziekbestand wordt gemaakt…');try{const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;const total=duration()+.25;const c=new Offline(1,Math.ceil(44100*total),44100);const comp=c.createDynamicsCompressor();comp.threshold.value=-12;comp.ratio.value=4;const gain=c.createGain();gain.gain.value=.72;comp.connect(gain);gain.connect(c.destination);for(const track of tracks){if(track.muted)continue;const g=c.createGain();g.gain.value=track.volume;g.connect(comp);for(const event of track.events)sound(c,g,event,event.beat*beatSeconds(),Math.min(2.2,duration()-event.beat*beatSeconds()+.05))}const rendered=await c.startRendering();const blob=encodeWav(rendered);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(el('title').value.trim()||'Mijn muziekstuk').replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,60)+'.wav';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);tell('Je WAV-bestand is klaar. Je browser downloadt of opent het bestand.')}catch(e){tell('Downloaden is niet gelukt. Probeer opnieuw in een recente browser.')}finally{exporting=false;updateControls()}};
el('teacherButton').onclick=()=>{stop(true);el('teacher').showModal()};el('closeTeacher').onclick=()=>el('teacher').close();document.addEventListener('visibilitychange',()=>{if(document.hidden){stop(true);if(micBusy){if(recorder?.state==='recording')finishMic();else{micOperation++;micBusy=false;releaseMic();updateControls()}}}});window.addEventListener('pagehide',()=>{releaseMic();silence()});window.addEventListener('beforeunload',e=>{if(tracks.length||current?.events.length){e.preventDefault();e.returnValue=''}});
renderTracks();renderInstrument();updateControls();
