(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  let flashTimer=null,flashVisible=false,flashIndex=0,flashOrder=[14,10,17,12,19,15,11,20,13,18,16];
  function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
  function hideFlash(){clearTimeout(flashTimer);flashTimer=null;flashVisible=false;$('ten-frames').hidden=true;$('flash-cover').hidden=false;$('flash-hold').setAttribute('aria-pressed','false');$('flash-hold').textContent='Blijf tonen';}
  function mode(value){['flash','divide','practice'].forEach(id=>$(id).hidden=id!==value);document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===value)));hideFlash();}
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
  function renderFlash(){hideFlash();$('flash-index').textContent=`Getalbeeld ${flashIndex+1} van 11`;$('flash-cover').textContent='Klaar om te kijken?';$('flash-result').textContent='';$('flash-answer').textContent='Toon getal';$('ten-frames').replaceChildren();for(let frame=0;frame<2;frame++){const grid=document.createElement('div');grid.className='ten-frame';for(let i=0;i<10;i++){const cell=document.createElement('div');cell.className='cell';if(frame*10+i<flashOrder[flashIndex]){const dot=document.createElement('span');dot.className='dot';cell.append(dot);}grid.append(cell);}$('ten-frames').append(grid);}}
  function showFlash(){clearTimeout(flashTimer);flashVisible=true;$('ten-frames').hidden=false;$('flash-cover').hidden=true;$('flash-result').textContent='';$('flash-answer').textContent='Toon getal';}
  $('flash-start').onclick=()=>{showFlash();$('flash-hold').setAttribute('aria-pressed','false');$('flash-hold').textContent='Blijf tonen';flashTimer=setTimeout(()=>{hideFlash();$('flash-cover').textContent='Schrijf het getal op je wisbord.';},Number($('flash-time').value)*1000);};
  $('flash-hold').onclick=()=>{if(flashVisible){hideFlash();}else{showFlash();$('flash-hold').setAttribute('aria-pressed','true');$('flash-hold').textContent='Verberg beeld';}};
  $('flash-answer').onclick=()=>{const show=!$('flash-result').textContent;$('flash-result').textContent=show?`Het getal is ${flashOrder[flashIndex]}.`:'';$('flash-answer').textContent=show?'Verberg getal':'Toon getal';};
  function nextFlash(d){flashIndex=(flashIndex+d+11)%11;renderFlash();}$('flash-prev').onclick=()=>nextFlash(-1);$('flash-next').onclick=()=>nextFlash(1);$('flash-shuffle').onclick=()=>{shuffle(flashOrder);flashIndex=0;renderFlash();};
  let quantity=8,locations=Array(8).fill('pool'),selected=null,history=[],showCounts=false,terms=false,lastDigit=false;
  const lists={even:[],odd:[]};
  function save(){history.push([...locations]);if(history.length>100)history.shift();}
  function resetQuantity(value){quantity=value;locations=Array(value).fill('pool');selected=null;history=[];$('quantity').value=value;$('divide-result').textContent='';$('column-feedback').textContent='';renderTokens();}
  function renderTokens(){for(const zone of ['pool','left','right']){const container=$(zone+'-tokens');container.replaceChildren();locations.forEach((location,i)=>{if(location!==zone)return;const token=document.createElement('button');token.className='token'+(selected===i?' selected':'');token.dataset.token=i;token.setAttribute('aria-label',`Voorwerp ${i+1}`);token.setAttribute('aria-pressed',String(selected===i));container.append(token);});$(zone+'-count').textContent=showCounts?`(${locations.filter(x=>x===zone).length})`:'';}$('divide-undo').disabled=!history.length;$('pair-step').disabled=locations.filter(x=>x==='pool').length<2;document.querySelectorAll('[data-destination]').forEach(b=>b.disabled=selected===null);}
  function move(id,zone){if(locations[id]===zone)return;save();locations[id]=zone;selected=null;$('divide-result').textContent='';renderTokens();}
  $('prepare').onclick=()=>{const n=Number($('quantity').value);if(!Number.isInteger(n)||n<1||n>20){$('quantity').reportValidity();return;}resetQuantity(n);};
  $('reset-groups').onclick=()=>resetQuantity(quantity);$('divide-undo').onclick=()=>{if(history.length){locations=history.pop();selected=null;$('divide-result').textContent='';renderTokens();}};
  $('pair-step').onclick=()=>{const ids=locations.map((zone,i)=>zone==='pool'?i:-1).filter(i=>i>=0);if(ids.length<2)return;save();locations[ids[0]]='left';locations[ids[1]]='right';selected=null;$('divide-result').textContent='';renderTokens();};
  $('counts').onclick=()=>{showCounts=!showCounts;$('counts').textContent=showCounts?'Verberg aantallen':'Toon aantallen';$('counts').setAttribute('aria-pressed',String(showCounts));renderTokens();};
  document.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{if(selected!==null)move(selected,b.dataset.destination);});
  let drag=null,ghost=null;
  const board=$('board');board.addEventListener('pointerdown',event=>{const token=event.target.closest('[data-token]');if(!token||event.button!==0)return;event.preventDefault();drag={id:Number(token.dataset.token),pointer:event.pointerId,x:event.clientX,y:event.clientY,moved:false};board.setPointerCapture(event.pointerId);});
  board.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.pointer)return;if(Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>8)drag.moved=true;if(!drag.moved)return;if(!ghost){ghost=document.createElement('div');ghost.className='token token-ghost';ghost.setAttribute('aria-hidden','true');document.body.append(ghost);}ghost.style.left=event.clientX-24+'px';ghost.style.top=event.clientY-24+'px';});
  function endDrag(event){if(!drag||event.pointerId!==drag.pointer)return;const d=drag;drag=null;ghost?.remove();ghost=null;if(event.type==='pointerup'){if(d.moved){const zone=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-zone]');if(zone)move(d.id,zone.dataset.zone);}else{selected=selected===d.id?null:d.id;renderTokens();}}}
  ['pointerup','pointercancel','lostpointercapture'].forEach(type=>board.addEventListener(type,endDrag));
  board.addEventListener('click',event=>{const token=event.target.closest('[data-token]');if(token&&event.detail===0){const id=Number(token.dataset.token);selected=selected===id?null:id;renderTokens();}});
  $('check-groups').onclick=()=>{const left=locations.filter(x=>x==='left').length,right=locations.filter(x=>x==='right').length,pool=quantity-left-right;if(pool===0&&left===right)$('divide-result').textContent=`${left} en ${right}: twee even grote groepen. ${quantity} is even (paar).`;else if(pool===1&&left===right)$('divide-result').textContent=`${left} en ${right}, met één over. ${quantity} is oneven (onpaar).`;else if(pool===0&&Math.abs(left-right)===1)$('divide-result').textContent=`${left} en ${right}: één voorwerp kan niet eerlijk verdeeld worden. ${quantity} is oneven (onpaar).`;else $('divide-result').textContent='Probeer verder: leg telkens één voorwerp in elke groep.';};
  $('columns-toggle').onclick=()=>{const show=$('columns').hidden;$('columns').hidden=!show;$('divide').classList.toggle('with-columns',show);$('columns-toggle').textContent=show?'Verberg kolommen':'Toon kolommen';$('columns-toggle').setAttribute('aria-expanded',String(show));};
  function renderColumns(){for(const type of ['even','odd']){const container=$(type+'-numbers');container.replaceChildren();lists[type].forEach(n=>{const button=document.createElement('button');button.title='Verwijder dit getal';button.setAttribute('aria-label',`Verwijder ${n}`);const digits=String(n);button.append(document.createTextNode(digits.slice(0,-1)));const last=document.createElement('span');last.textContent=digits.slice(-1);last.className=lastDigit?'digit-emphasis':'';button.append(last);button.onclick=()=>{lists[type]=lists[type].filter(x=>x!==n);renderColumns();};container.append(button);});}$('even-heading').textContent=terms?'Even (paar)':'Kolom 1';$('odd-heading').textContent=terms?'Oneven (onpaar)':'Kolom 2';}
  function addNumber(type){const correct=quantity%2===0?'even':'odd';if(type!==correct){$('column-feedback').textContent='Bekijk de verdeling nog eens. Past dit getal in deze kolom?';return;}if(!lists[type].includes(quantity))lists[type].push(quantity);$('column-feedback').textContent=`${quantity} staat in de kolom.`;renderColumns();}
  $('add-even').onclick=()=>addNumber('even');$('add-odd').onclick=()=>addNumber('odd');$('clear-columns').onclick=()=>{lists.even=[];lists.odd=[];$('column-feedback').textContent='';renderColumns();};
  $('terms').onclick=()=>{terms=!terms;$('terms').setAttribute('aria-pressed',String(terms));$('terms').textContent=terms?'Verberg namen':'Toon even / oneven';renderColumns();};$('last-digit').onclick=()=>{lastDigit=!lastDigit;$('last-digit').setAttribute('aria-pressed',String(lastDigit));renderColumns();};
  let practiceOrder=[8,5,12,9,16,3,20,7,14,1,18,11,4,17,6,15,2,19,10,13],practiceIndex=0,choice=null,reveal=false;
  function renderPractice(){const n=practiceOrder[practiceIndex];const correct=n%2===0?'even':'odd';for(const kind of ['even','odd']){const button=$('pick-'+kind),isAnswer=reveal&&kind===correct;button.classList.toggle('answer-lit',isAnswer);button.classList.toggle('answer-muted',reveal&&!isAnswer);button.textContent=(isAnswer?'✓ ':'')+(kind==='even'?'Even · paar':'Oneven · onpaar');}$('practice-number').textContent=n;$('practice-index').textContent=`Getal ${practiceIndex+1} van 20`;$('pick-even').setAttribute('aria-pressed',String(choice==='even'));$('pick-odd').setAttribute('aria-pressed',String(choice==='odd'));$('practice-result').textContent=reveal?`${n} is ${n%2===0?'even (paar)':'oneven (onpaar)'}.`:'';$('practice-check').textContent=reveal?'Verberg antwoord':'Toon antwoord';}
  function nextPractice(d){practiceIndex=(practiceIndex+d+20)%20;choice=null;reveal=false;renderPractice();}$('practice-prev').onclick=()=>nextPractice(-1);$('practice-next').onclick=()=>nextPractice(1);$('practice-shuffle').onclick=()=>{shuffle(practiceOrder);practiceIndex=0;choice=null;reveal=false;renderPractice();};$('pick-even').onclick=()=>{choice='even';reveal=false;renderPractice();};$('pick-odd').onclick=()=>{choice='odd';reveal=false;renderPractice();};$('practice-check').onclick=()=>{reveal=!reveal;renderPractice();};$('practice-explain').onclick=()=>{resetQuantity(practiceOrder[practiceIndex]);mode('divide');};
  $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('message').textContent='Gebruik eventueel F11 voor volledig scherm.';}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Verlaat volledig scherm':'Volledig scherm';});renderFlash();renderTokens();renderColumns();renderPractice();
})();
