(() => {
  'use strict';
  const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
  const node=(tag,attrs={},text)=>{const el=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text!==undefined)el.textContent=text;return el;};
  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{['paper','blocks','dots','figures'].forEach(id=>$(id).hidden=id!==button.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});
  let folds=0,closed=false,apart=false,part=null,paperAnswer=false;
  function renderPaper(){const svg=$('sheet');svg.replaceChildren();const cols=[1,2,2,4][folds],rows=folds>=2?2:1,w=600/cols,h=424/rows,count=2**folds;
    if(closed){const x=500-w/2,y=280-h/2;for(let i=Math.min(count,4)-1;i>=0;i--)svg.append(node('rect',{x:x+i*5,y:y+i*4,width:w,height:h,rx:3,fill:i?'#e6e2d3':'#fffdf5',stroke:'#8a9b99','stroke-width':3}));svg.append(node('path',{d:`M${x+10} ${y+h-5}H${x+w-10}`,stroke:'#c7b686','stroke-width':3}));}
    else{for(let i=0;i<count;i++){const col=i%cols,row=Math.floor(i/cols),gap=apart?22:0,x=200+col*w+(col-(cols-1)/2)*gap,y=68+row*h+(row-(rows-1)/2)*gap;const g=node('g',{role:'button',tabindex:0,'aria-label':`Wijs deel ${i+1} aan`,'aria-pressed':String(part===i)});g.append(node('rect',{x,y,width:w,height:h,rx:apart?4:0,fill:part===i?'#f4d787':'#fffdf5',stroke:part===i?'#a66e20':'#8a9b99','stroke-width':part===i?5:2}));const select=()=>{part=part===i?null:i;renderPaper();};g.onclick=select;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};svg.append(g);}}
    $('fold').disabled=folds===3;$('fold').textContent=folds?'Vouw nog eens in twee':'Vouw in twee';$('unfold').disabled=!folds;$('unfold').textContent=closed?'Vouw open':'Vouw dicht';$('separate').disabled=!folds||closed;$('separate').textContent=apart?'Leg samen tot één geheel':'Delen uit elkaar';$('separate').setAttribute('aria-pressed',String(apart));$('clear-part').disabled=part===null;$('paper-question').textContent=closed?'Leg de hoekpunten op elkaar. Vouw het blad daarna open.':folds?'Tik op een deel. Kun je ook een ander gelijk deel aanwijzen?':'Dit blad is het geheel.';$('paper-answer').textContent=paperAnswer?'Verberg aantal delen':'Toon aantal delen';$('paper-result').textContent=paperAnswer?(folds?`${count} gelijke delen. Samen vormen ze het hele blad.`:'Eén geheel: het hele blad.'):'';}
  $('fold').onclick=()=>{if(folds<3){folds++;closed=true;apart=false;part=null;paperAnswer=false;renderPaper();}};$('unfold').onclick=()=>{closed=!closed;apart=false;part=null;renderPaper();};$('separate').onclick=()=>{apart=!apart;renderPaper();};$('whole').onclick=()=>{folds=0;closed=false;apart=false;part=null;paperAnswer=false;renderPaper();};$('paper-answer').onclick=()=>{paperAnswer=!paperAnswer;renderPaper();};$('clear-part').onclick=()=>{part=null;renderPaper();};
  let amount=18,groups=3,locations=Array(18).fill('pool'),selected=null,history=[],counts=false,discussed=false;
  let slots=locations.map((_,i)=>i);
  function place(id,zone){const used=new Set(locations.map((z,i)=>z===zone&&i!==id?slots[i]:-1));let slot=0;while(used.has(slot))slot++;locations[id]=zone;slots[id]=slot;}
  function renderBlocks(){const destinations=['pool',...Array.from({length:groups},(_,i)=>String(i))];$('cards').replaceChildren();$('cards').style.setProperty('--cards',Math.min(groups,3));for(let i=0;i<groups;i++){const card=document.createElement('div');card.className='zone';card.dataset.zone=String(i);const title=document.createElement('h3');title.textContent=`Kaart ${i+1}`;const tokens=document.createElement('div');tokens.className='blocks-grid';tokens.id='card-'+i;const info=document.createElement('p');info.className='card-part';info.textContent=counts?`${locations.filter(x=>x===String(i)).length} blokjes`:'';const target=document.createElement('button');target.dataset.destination=String(i);target.textContent='Leg op deze kaart';target.disabled=selected===null;target.onclick=()=>{if(selected!==null)move(selected,String(i));};card.append(title,tokens,info,target);$('cards').append(card);}
    for(const zone of destinations){const container=zone==='pool'?$('pool'):$('card-'+zone);container.replaceChildren();locations.forEach((location,i)=>{if(location!==zone)return;const b=document.createElement('button');b.className='block'+(selected===i?' selected':'');b.dataset.block=i;const columns=zone==='pool'?10:5;b.style.gridColumn=String(slots[i]%columns+1);b.style.gridRow=String(Math.floor(slots[i]/columns)+1);b.setAttribute('aria-label',`Blokje ${i+1}`);b.setAttribute('aria-pressed',String(selected===i));container.append(b);});}$('total-count').textContent=counts?`(${amount} blokjes, nog ${locations.filter(x=>x==='pool').length} te verdelen)`:'';$('undo').disabled=!history.length;$('round').disabled=locations.filter(x=>x==='pool').length<groups;$('block-board').querySelector('[data-destination="pool"]').disabled=selected===null;if(!discussed)$('blocks-result').textContent='';}
  function save(){history.push({locations:[...locations],slots:[...slots]});if(history.length>100)history.shift();discussed=false;}
  function move(i,zone){if(locations[i]===zone)return;save();place(i,zone);selected=null;renderBlocks();}
  function reset(){locations=Array(amount).fill('pool');slots=locations.map((_,i)=>i);selected=null;history=[];discussed=false;renderBlocks();}
  $('prepare').onclick=()=>{const a=Number($('amount').value),g=Number($('groups').value);if(!Number.isInteger(a)||a<1||a>30){$('amount').reportValidity();return;}if(!Number.isInteger(g)||g<2||g>6){$('groups').reportValidity();return;}amount=a;groups=g;reset();};$('restart').onclick=reset;$('undo').onclick=()=>{if(history.length){const previous=history.pop();locations=previous.locations;slots=previous.slots;selected=null;discussed=false;renderBlocks();}};$('counts').onclick=()=>{counts=!counts;$('counts').setAttribute('aria-pressed',String(counts));$('counts').textContent=counts?'Verberg aantallen':'Toon aantallen';renderBlocks();};
  $('round').onclick=()=>{const ids=locations.map((z,i)=>z==='pool'?i:-1).filter(i=>i>=0);if(ids.length<groups)return;save();for(let i=0;i<groups;i++)place(ids[i],String(i));selected=null;renderBlocks();};$('block-board').querySelector('[data-destination="pool"]').onclick=()=>{if(selected!==null)move(selected,'pool');};
  $('check').onclick=()=>{const sizes=Array.from({length:groups},(_,i)=>locations.filter(x=>x===String(i)).length),left=locations.filter(x=>x==='pool').length;discussed=true;if(!left&&sizes.every(n=>n===sizes[0]))$('blocks-result').textContent=`Het geheel is ${amount} blokjes. Er zijn ${groups} gelijke delen, met ${sizes[0]} blokjes in elk deel.`;else if(left&&left<groups&&sizes.every(n=>n===sizes[0]))$('blocks-result').textContent=`Op elke kaart liggen ${sizes[0]} blokjes, maar er ${left===1?'blijft nog 1 blokje':'blijven nog '+left+' blokjes'} over. Het hele aantal is nog niet in gelijke delen verdeeld.`;else $('blocks-result').textContent='Kijk naar alle kaarten. Is alles verdeeld en ligt er op elke kaart evenveel?';};
  let drag=null,ghost=null;const board=$('block-board');board.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-block]');if(!b||e.button!==0)return;e.preventDefault();drag={id:Number(b.dataset.block),pointer:e.pointerId,x:e.clientX,y:e.clientY,moved:false};board.setPointerCapture(e.pointerId);});board.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;if(!drag.moved)return;if(!ghost){board.querySelector('[data-block="'+drag.id+'"]').style.opacity='0';ghost=document.createElement('div');ghost.className='block block-ghost';document.body.append(ghost);}ghost.style.left=e.clientX-21+'px';ghost.style.top=e.clientY-21+'px';});function finish(e){if(!drag||drag.pointer!==e.pointerId)return;const d=drag;board.querySelector('[data-block="'+d.id+'"]')?.style.removeProperty('opacity');drag=null;ghost?.remove();ghost=null;if(e.type!=='pointerup')return;if(d.moved){const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-zone]');if(zone)move(d.id,zone.dataset.zone);}else{selected=selected===d.id?null:d.id;renderBlocks();}}['pointerup','pointercancel','lostpointercapture'].forEach(t=>board.addEventListener(t,finish));board.addEventListener('click',e=>{const b=e.target.closest('[data-block]');if(b&&e.detail===0){const i=Number(b.dataset.block);selected=selected===i?null:i;renderBlocks();}});
  let dotParts=0,dotAnswer=false,dotSelected=null;
  function renderDots(){const svg=$('dot-board');svg.replaceChildren();for(let row=0;row<3;row++){const g=node('g',{role:'button',tabindex:0,'aria-label':`Wijs rij ${row+1} aan`,'aria-pressed':String(dotSelected===row)});g.append(node('rect',{x:195,y:53+row*112,width:410,height:98,rx:18,fill:dotSelected===row?'#fff0c4':'transparent',stroke:row<dotParts?'#be7a29':'transparent','stroke-width':4}));for(let col=0;col<4;col++)g.append(node('circle',{cx:250+col*100,cy:102+row*112,r:28,fill:'#297e9c'}));const select=()=>{dotSelected=dotSelected===row?null:row;renderDots();};g.onclick=select;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};svg.append(g);}$('dot-step').disabled=dotParts===3;$('dot-step').textContent=dotParts?'Toon volgend deel':'Toon één deel';$('dot-answer').textContent=dotAnswer?'Verberg antwoord':'Toon antwoord';$('dots-result').textContent=dotAnswer?'Het geheel is 12 stippen. In elk van de 3 gelijke delen zitten 4 stippen.':'';}
  $('dot-step').onclick=()=>{dotParts=Math.min(3,dotParts+1);renderDots();};$('dot-reset').onclick=()=>{dotParts=0;dotSelected=null;dotAnswer=false;renderDots();};$('dot-answer').onclick=()=>{dotAnswer=!dotAnswer;renderDots();};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('message').textContent='Gebruik eventueel F11 voor volledig scherm.';}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Verlaat volledig scherm':'Volledig scherm';});renderPaper();renderBlocks();renderDots();
})();
