(() => {
'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
function el(tag,a={},text){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(a))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
const rect=(g,x,y,w,h,fill='#fff',attrs={})=>g.appendChild(el('rect',{x,y,width:w,height:h,fill,stroke:'#456572','stroke-width':2,...attrs}));
const label=(g,x,y,t,size=26,attrs={})=>g.appendChild(el('text',{x,y,'font-size':size,'text-anchor':'middle',...attrs},t));
const line=(g,x1,y1,x2,y2,attrs={})=>g.appendChild(el('line',{x1,y1,x2,y2,stroke:'#456572','stroke-width':3,...attrs}));
function point(svg,e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(n=>{n.setAttribute('aria-pressed',String(n===b));$(n.dataset.tab).hidden=n!==b;});});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('message').textContent='Gebruik eventueel F11 voor volledig scherm.';}};
// Van een geheel naar twee helften en weer terug. De leerkracht onthult elke stap.
let stripStep=0,stripAnswer=false,half=0;
const stripTitles=['Dit is het geheel.','Verdeel de strook in twee gelijke delen.','Toon één helft.','Neem die helft twee keer.','Zijn helften altijd even groot?','Is dit eerlijk verdeeld?'];
const stripAnswers=['De hele strook is het geheel.','Beide delen zijn even groot. Elk deel is één helft.','De andere helft is even groot. Samen zijn er twee helften.','Twee keer dezelfde helft vormt weer het geheel: het dubbel.','Beide gekleurde delen zijn een helft. De helft van het kleinere geheel is kleiner.','Nee. Twee delen zijn pas helften als ze even groot zijn.'];
function strips(){const g=$('strip-board');g.replaceChildren();$('strip-title').textContent=stripTitles[stripStep];$('strip-progress').textContent=`Stap ${stripStep+1} van 6`;$('strip-back').disabled=stripStep===0;$('strip-next').disabled=stripStep===5;$('strip-result').textContent=stripAnswer?stripAnswers[stripStep]:'';$('strip-reveal').textContent=stripAnswer?'Verberg uitleg':'Bespreek';$('strip-hint').textContent=stripStep===2?'Tik op een deel. Kun je ook de andere helft tonen?':stripStep===4?'Wat is bij elke strook het geheel?':stripStep===0?'We leren de helft en het dubbel nemen. Wat is het geheel?':'Laat de kinderen uitleggen wat ze zien.';
 if(stripStep===4){[[140,80,720],[140,225,440]].forEach(([x,y,w])=>{rect(g,x,y,w/2,65,'#72bfa2');rect(g,x+w/2,y,w/2,65,'white');});return;}
 const x=140,y=120,w=720,h=120;
 if(stripStep===0){rect(g,x,y,w,h,'#66abc1');return;}
 if(stripStep===5){rect(g,x,y,240,h,'#72bfa2');rect(g,x+240,y,480,h,'white');return;}
 for(let i=0;i<2;i++)rect(g,x+i*(w/2+(stripStep===3?20:0)),y,w/2,h,stripStep===1?'#66abc1':stripStep===2?(i===half?'#72bfa2':'white'):(i===0?'#72bfa2':'#66abc1'),{'data-half':i,tabindex:0,role:'button','aria-label':i===0?'Linker helft':'Rechter helft'});
 if(stripStep===3&&stripAnswer)label(g,510,300,'één helft + één helft = het geheel',28);
}
$('strip-next').onclick=()=>{stripStep=Math.min(5,stripStep+1);stripAnswer=false;strips();};$('strip-back').onclick=()=>{stripStep=Math.max(0,stripStep-1);stripAnswer=false;strips();};$('strip-reset').onclick=()=>{stripStep=0;half=0;stripAnswer=false;strips();};$('strip-reveal').onclick=()=>{stripAnswer=!stripAnswer;strips();};
function chooseHalf(e){const n=e.target.closest('[data-half]');if(n&&stripStep===2){half=Number(n.dataset.half);strips();}}
$('strip-board').onclick=chooseHalf;$('strip-board').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseHalf(e);}};
// Vaste plaats per blokje: het gekozen blokje beweegt, de andere schuiven niet op.
let blockKind='half',amount=14,locations=[],slots=[],copies=0,copySlots=[],counts=false,selected=null,blockHistory=[],drag=null;
function saveBlocks(){blockHistory.push({locations:[...locations],slots:[...slots],copies,copySlots:[...copySlots]});}
function clearBlockResult(){$('block-result').textContent='';}
function prepare(){blockKind=$('block-kind').value;const n=Number($('block-amount').value);if(!Number.isInteger(n)||n<(blockKind==='half'?2:1)||n>(blockKind==='half'?20:10)||(blockKind==='half'&&n%2)){$('block-result').textContent=blockKind==='half'?'Kies een even aantal van 2 tot 20.':'Kies een aantal van 1 tot 10.';return;}amount=n;locations=Array(n).fill('pool');slots=Array.from({length:n},(_,i)=>i);copies=0;copySlots=[];selected=null;blockHistory=[];counts=false;clearBlockResult();blocks();}
function moveBlock(id,zone){if(locations[id]===zone)return;saveBlocks();const used=new Set(slots.filter((_,i)=>locations[i]===zone));let slot=0;while(used.has(slot))slot++;locations[id]=zone;slots[id]=zone==='pool'?id:slot;selected=null;clearBlockResult();blocks();}
function blockRect(g,x,y,id,extra={}){return rect(g,x,y,32,32,'#66abc1',{rx:5,'data-id':id,tabindex:0,role:'button','aria-label':`Blokje ${Number(id)+1}`,class:selected===id?'selected-block':'',...extra});}
function blocks(){const g=$('block-board');g.replaceChildren();$('block-title').textContent=blockKind==='half'?`Neem de helft van ${amount} blokjes.`:`Maak het dubbel van ${amount} blokjes.`;$('block-action').textContent=blockKind==='half'?'Eén op elke kaart':'Nog één blokje';$('block-action').disabled=blockKind==='half'?locations.filter(z=>z==='pool').length<2:copies>=amount;$('block-undo').disabled=!blockHistory.length;$('block-counts').setAttribute('aria-pressed',String(counts));$('block-counts').textContent=counts?'Verberg aantallen':'Toon aantallen';$('block-hint').textContent=blockKind==='half'?'Sleep een blokje naar een kaart. Of tik op een blokje en daarna op een kaart.':'Sleep het reserveblokje naar de lege kaart of gebruik ‘Nog één blokje’. Tik op een toegevoegd blokje om het weg te nemen.';
 if(blockKind==='half'){
   [['pool',30,30,300,290,'Het geheel'],['left',370,30,285,290,'Kaart 1'],['right',685,30,285,290,'Kaart 2']].forEach(([zone,x,y,w,h,t])=>{rect(g,x,y,w,h,zone==='pool'?'#fff8e7':'white',{'data-zone':zone,rx:15});label(g,x+w/2,65,t,24,{'pointer-events':'none'});if(counts)label(g,x+w/2,307,locations.filter(z=>z===zone).length,24,{'pointer-events':'none'});});
   locations.forEach((zone,id)=>{const start=zone==='pool'?60:zone==='left'?395:710;blockRect(g,start+(slots[id]%5)*45,90+Math.floor(slots[id]/5)*43,id);});
 }else{
   rect(g,70,45,330,260,'white',{rx:15});rect(g,580,45,330,260,'white',{rx:15,'data-zone':'copy'});label(g,235,80,'Eén keer',25);label(g,745,80,'Nog een keer evenveel',25);label(g,490,185,'+',50);
   for(let i=0;i<amount;i++)rect(g,110+(i%5)*48,110+Math.floor(i/5)*48,32,32,'#66abc1',{rx:5});
   for(const i of copySlots)blockRect(g,620+(i%5)*48,110+Math.floor(i/5)*48,i,{'data-copy':i,fill:'#72bfa2'});
   blockRect(g,470,245,'reserve',{'aria-label':'Sleep een extra blokje',fill:'#72bfa2'});
   if(counts){label(g,235,280,amount,26);label(g,745,280,copies,26);}
 }
}
function addCopy(){if(copies>=amount)return;saveBlocks();let slot=0;while(copySlots.includes(slot))slot++;copySlots.push(slot);copies=copySlots.length;clearBlockResult();blocks();}
const blockBoard=$('block-board');
blockBoard.addEventListener('pointerdown',e=>{const token=e.target.closest('[data-id]');if(!token)return;e.preventDefault();drag={id:token.dataset.id,start:point(blockBoard,e),moved:false,token,ghost:null};blockBoard.setPointerCapture(e.pointerId);});
blockBoard.addEventListener('pointermove',e=>{if(!drag)return;const p=point(blockBoard,e);if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>7){drag.moved=true;if(!drag.ghost){drag.ghost=drag.token.cloneNode(true);drag.ghost.removeAttribute('data-id');drag.ghost.setAttribute('pointer-events','none');blockBoard.append(drag.ghost);if(drag.id!=='reserve')drag.token.style.opacity='0';}drag.ghost.setAttribute('x',p.x-16);drag.ghost.setAttribute('y',p.y-16);}});
blockBoard.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;d.ghost?.remove();d.token.style.opacity='';if(d.moved){const p=point(blockBoard,e);if(p.y>=30&&p.y<=320){if(blockKind==='half'){const zone=p.x>=30&&p.x<=330?'pool':p.x>=370&&p.x<=655?'left':p.x>=685&&p.x<=970?'right':null;if(zone)moveBlock(Number(d.id),zone);}else if(d.id==='reserve'&&p.x>=580&&p.x<=910)addCopy();}}else if(blockKind==='half'){selected=Number(d.id);blocks();}else if(d.id==='reserve')addCopy();else{saveBlocks();copySlots=copySlots.filter(i=>i!==Number(d.id));copies=copySlots.length;clearBlockResult();blocks();}});
blockBoard.addEventListener('pointercancel',()=>{if(drag){drag.ghost?.remove();drag.token.style.opacity='';drag=null;}});
blockBoard.onclick=e=>{if(blockKind!=='half'||selected===null)return;const zone=e.target.closest('[data-zone]');if(zone)moveBlock(selected,zone.dataset.zone);};
blockBoard.onkeydown=e=>{if(e.key!=='Enter'&&e.key!==' ')return;const token=e.target.closest('[data-id]');if(!token)return;e.preventDefault();if(blockKind==='half'){selected=Number(token.dataset.id);blocks();}else if(token.dataset.id==='reserve')addCopy();else{saveBlocks();copySlots=copySlots.filter(i=>i!==Number(token.dataset.id));copies=copySlots.length;clearBlockResult();blocks();}};
$('block-kind').onchange=()=>{const isHalf=$('block-kind').value==='half';$('block-amount').min=isHalf?2:1;$('block-amount').max=isHalf?20:10;$('block-amount').step=isHalf?2:1;$('block-amount').value=isHalf?14:7;prepare();};$('block-prepare').onclick=prepare;$('block-reset').onclick=prepare;
$('block-undo').onclick=()=>{const old=blockHistory.pop();if(old){({locations,slots,copies,copySlots}=old);selected=null;clearBlockResult();blocks();}};
$('block-counts').onclick=()=>{counts=!counts;blocks();};$('block-action').onclick=()=>{if(blockKind==='double'){addCopy();return;}const ids=locations.map((z,i)=>z==='pool'?i:-1).filter(i=>i>=0).slice(0,2);if(ids.length!==2)return;saveBlocks();ids.forEach((id,i)=>{const zone=i?'right':'left';let slot=0;const used=new Set(slots.filter((_,k)=>locations[k]===zone));while(used.has(slot))slot++;locations[id]=zone;slots[id]=slot;});clearBlockResult();blocks();};
$('block-check').onclick=()=>{let text;if(blockKind==='half'){const a=locations.filter(z=>z==='left').length,b=locations.filter(z=>z==='right').length;text=locations.includes('pool')?'Er liggen nog blokjes bij het geheel. Verdeel ze allemaal.':a!==b?'Op de kaarten ligt niet evenveel. Maak twee gelijke delen.':`De helft van ${amount} is ${a}. Twee helften samen: ${a} + ${b} = ${amount}.`;}else text=copies!==amount?'Leg op de tweede kaart evenveel blokjes als op de eerste.':`Het dubbel van ${amount} is ${amount*2}. ${amount} + ${amount} = ${amount*2}.`;$('block-result').textContent=text;};
// Andere voorbeelden dan in het werkboek, afwisselend per soort.
const exercises=[
 {kind:'divide',shape:'square',q:'Verdeel het vierkant in twee gelijke delen. Kleur één helft.'},
 {kind:'grid',n:2,q:'Teken het dubbel van deze strook op de ruitjes.'},
 {kind:'color',n:8,q:'Kleur de helft van deze 8 blaadjes.'},
 {kind:'draw',n:3,shape:'circle',task:'double',q:'Hier staan 3 cirkels. Teken het dubbel in het lege vak.'},
 {kind:'statements',n:6,half:false,q:'Welke zinnen kloppen? Er kan meer dan één juist antwoord zijn.'},
 {kind:'number',n:18,half:true,q:'Er liggen 18 steentjes. Je neemt de helft. Hoeveel neem je?'},
 {kind:'divide',shape:'rectangle',q:'Verdeel deze rechthoek op een andere manier. Kleur één helft.'},
 {kind:'grid',n:4,q:'Teken het dubbel van deze strook op de ruitjes.'},
 {kind:'color',n:14,q:'Kleur de helft van deze 14 blaadjes.'},
 {kind:'draw',n:10,shape:'triangle',task:'half',q:'Teken 10 driehoeken. Omkring de helft.'},
 {kind:'statements',n:16,half:true,q:'Welke zinnen kloppen? Er kan meer dan één juist antwoord zijn.'},
 {kind:'number',n:6,half:false,q:'In een doos zitten 6 knopen. Je neemt het dubbel. Hoeveel zijn dat?'}
];
let list=exercises,index=0,tool='touch',revealed=false,selections=new Set(),choiceSet=new Set(),history=[],pointer=null,stroke=null;
const current=()=>list[index],ink=$('ink'),solution=$('solution'),practiceBoard=$('practice-board');
function dot(g,x,y,shape='circle',attrs={}){return g.appendChild(shape==='triangle'?el('path',{d:`M${x} ${y-19}L${x+20} ${y+17}L${x-20} ${y+17}Z`,fill:'white',stroke:'#456572','stroke-width':2,...attrs}):el('circle',{cx:x,cy:y,r:18,fill:'white',stroke:'#456572','stroke-width':2,...attrs}));}
function positions(n,x=125,y=75,cols=7,gap=100){return Array.from({length:n},(_,i)=>[x+(i%cols)*gap,y+Math.floor(i/cols)*85]);}
function statements(e){const h=e.n/2;return e.half?[{text:`${h} is de helft van ${e.n}.`,ok:true},{text:`De helft van ${h} is ${e.n}.`,ok:false},{text:`De helft van ${e.n} is ${h}.`,ok:true}]:[{text:`Het dubbel van ${e.n/2} is ${e.n}.`,ok:true},{text:`${e.n} is het dubbel van ${e.n/2}.`,ok:true},{text:`Het dubbel van ${e.n} is ${e.n/2}.`,ok:false}];}
function save(){history.push({ink:ink.innerHTML,selections:[...selections],choices:[...choiceSet]});}
function selectTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===tool)));}
function drawPractice(){const e=current(),g=$('exercise');practiceBoard.setAttribute('viewBox',e.kind==='statements'?'0 0 1000 160':'0 0 1000 320');g.replaceChildren();solution.replaceChildren();ink.style.opacity=revealed?'.15':'1';$('question').textContent=e.q;$('progress').textContent=`Oefening ${index+1} van ${list.length}`;$('practice').classList.toggle('has-choices',e.kind==='statements');$('choices').replaceChildren();$('answer').textContent=revealed?'Verberg voorbeeldantwoord':'Toon voorbeeldantwoord';$('practice-check').hidden=!['grid','color','statements'].includes(e.kind);
 $('practice-hint').textContent=e.kind==='divide'?'Teken een verdeellijn. Kleur met de kleurstift één helft. Er zijn meerdere oplossingen.':e.kind==='grid'?'Tik op ruitjes in het lege vak. Maak twee keer de lengte van de blauwe strook.':e.kind==='color'?'Tik op een blaadje om het te kleuren. Tik opnieuw om de kleur weg te doen.':e.kind==='draw'?'Teken zelf of gebruik de stempels. Met de groene pen kun je omkringen.':e.kind==='statements'?'Kruis alle juiste zinnen aan.':'Schrijf je antwoord op de lijn of op je wisbord.';
 if(e.kind==='divide'){const w=e.shape==='square'?240:480,x=500-w/2;rect(g,x,40,w,240,'white');for(let i=1;i<w/40;i++)line(g,x+i*40,40,x+i*40,280,{stroke:'#9ab8c2','stroke-width':1,'stroke-dasharray':'4 4'});for(let y=80;y<280;y+=40)line(g,x,y,x+w,y,{stroke:'#9ab8c2','stroke-width':1,'stroke-dasharray':'4 4'});}
 if(e.kind==='grid'){const size=42;label(g,150,65,'Deze strook',24);for(let i=0;i<e.n;i++)rect(g,60+i*size,110,size,size,'#66abc1');label(g,330,145,'→',44);for(let r=0;r<3;r++)for(let c=0;c<10;c++){const id=r*10+c;rect(g,420+c*size,75+r*size,size,size,selections.has(id)?'#72bfa2':'white',{'data-cell':id,stroke:'#8baebc','stroke-width':1.5,tabindex:0,role:'button','aria-label':`Ruitje ${id+1}`});}}
 if(e.kind==='color')positions(e.n,170,100).forEach(([x,y],i)=>g.append(el('path',{d:`M${x-24} ${y+15}Q${x-27} ${y-25} ${x+25} ${y-23}Q${x+30} ${y+27} ${x-24} ${y+15}Z`,fill:selections.has(i)?'#72bfa2':'white',stroke:'#456572','stroke-width':2,'data-cell':i,tabindex:0,role:'button','aria-label':`Blaadje ${i+1}`})));
 if(e.kind==='draw'){if(e.task==='double'){positions(e.n,70,100,3,70).forEach(([x,y])=>dot(g,x,y,e.shape));label(g,340,150,'→',44);rect(g,410,25,550,265,'none',{rx:10,stroke:'#bdcfd0'});}else{line(g,40,290,960,290,{stroke:'#bdcfd0'});}}
 if(e.kind==='number'){label(g,210,160,e.half?`De helft van ${e.n} is`:`Het dubbel van ${e.n} is`,32,{'text-anchor':'start'});line(g,565,180,840,180,{stroke:'#bdcfd0'});}
 if(e.kind==='statements'){positions(e.n,e.half?130:400,35,e.half?8:3,e.half?95:100).forEach(([x,y],i)=>dot(g,x,y,'circle',{fill:e.half&&i<e.n/2?'#72bfa2':'#66abc1'}));if(e.half)line(g,85,77,850,77,{'stroke-dasharray':'5 4'});statements(e).forEach((s,i)=>{const b=document.createElement('button');b.textContent=(choiceSet.has(i)?'☑ ':'☐ ')+s.text;b.setAttribute('aria-pressed',String(choiceSet.has(i)));if(revealed)b.className=s.ok?'correct':choiceSet.has(i)?'incorrect':'';b.onclick=()=>{if(revealed)return;save();choiceSet.has(i)?choiceSet.delete(i):choiceSet.add(i);$('practice-result').textContent='';drawPractice();};$('choices').append(b);});}
 if(revealed)answerExample();
}
function answerExample(){const e=current(),g=solution;let text='';if(e.kind==='divide'){const w=e.shape==='square'?240:480,x=500-w/2;if(e.shape==='square'){rect(g,x,40,w,120,'#72bfa2',{'fill-opacity':.4,stroke:'none'});line(g,x,160,x+w,160,{stroke:'#28705d','stroke-width':4,'stroke-dasharray':'8 5'});}else{rect(g,x,40,w/2,240,'#72bfa2',{'fill-opacity':.4,stroke:'none'});line(g,500,40,500,280,{stroke:'#28705d','stroke-width':4,'stroke-dasharray':'8 5'});}text='Eén van de twee gelijke delen is de helft. Ook de andere helft is juist.';}
 if(e.kind==='grid'){for(let i=0;i<e.n*2;i++)rect(g,420+i*42,117,42,42,'#72bfa2',{'fill-opacity':.6,stroke:'#28705d'});text=`Het dubbel van ${e.n} ruitjes is ${e.n*2} ruitjes. De strook is twee keer zo lang.`;}
 if(e.kind==='color'){positions(e.n,170,100).slice(0,e.n/2).forEach(([x,y])=>g.append(el('path',{d:`M${x-24} ${y+15}Q${x-27} ${y-25} ${x+25} ${y-23}Q${x+30} ${y+27} ${x-24} ${y+15}Z`,fill:'#72bfa2','fill-opacity':.8,stroke:'#28705d','stroke-width':2})));text=`De helft van ${e.n} is ${e.n/2}. Je mag ook andere blaadjes kiezen.`;}
 if(e.kind==='draw'){if(e.task==='double'){positions(e.n*2,475,100,5,85).forEach(([x,y])=>dot(g,x,y,e.shape,{stroke:'#28705d'}));text=`Het dubbel van ${e.n} is ${e.n*2}: ${e.n} + ${e.n}.`;}else{positions(e.n,230,85,5,120).forEach(([x,y])=>dot(g,x,y,e.shape));g.append(el('ellipse',{cx:470,cy:85,rx:300,ry:36,fill:'none',stroke:'#28705d','stroke-width':4}));text=`De helft van ${e.n} is ${e.n/2}. Omkring ${e.n/2} van je ${e.n} figuren.`;}}
 if(e.kind==='number'){const n=e.half?e.n/2:e.n*2;label(g,700,160,n,42,{fill:'#28705d'});text=e.half?`De helft van ${e.n} is ${n}.`:`Het dubbel van ${e.n} is ${n}.`;}
 if(e.kind==='statements')text='De groene zinnen kloppen. Ze zeggen hetzelfde op een andere manier.';
 $('practice-result').textContent=text;
}
function fresh(){revealed=false;selections.clear();choiceSet.clear();history=[];ink.replaceChildren();$('practice-result').textContent='';selectTool(['divide','draw','number'].includes(current().kind)?'pen':'touch');drawPractice();}
$('prev').onclick=()=>{index=(index+list.length-1)%list.length;fresh();};$('next').onclick=()=>{index=(index+1)%list.length;fresh();};$('practice-kind').onchange=()=>{list=$('practice-kind').value==='mixed'?exercises:exercises.filter(e=>e.kind===$('practice-kind').value);index=0;fresh();};$('answer').onclick=()=>{revealed=!revealed;$('practice-result').textContent='';drawPractice();};
$('practice-check').onclick=()=>{const e=current();if(e.kind==='statements'){const ok=statements(e).every((s,i)=>s.ok===choiceSet.has(i));$('practice-result').textContent=ok?'Juist! Lees de juiste zinnen hardop.':'Lees elke zin nog eens. Kijk goed naar de volgorde van de getallen.';}else if(e.kind==='color')$('practice-result').textContent=selections.size===e.n/2?'Juist: je hebt één helft gekleurd.':'Zijn er evenveel gekleurde als ongekleurde blaadjes?';else if(e.kind==='grid'){if(ink.children.length){$('practice-result').textContent='Bespreek samen: is de getekende strook twee keer zo lang? Tel de ruitjes.';return;}const ids=[...selections].sort((a,b)=>a-b);const ok=ids.length===e.n*2&&ids.every((id,i)=>id===ids[0]+i&&Math.floor(id/10)===Math.floor(ids[0]/10));$('practice-result').textContent=ok?'Juist: je strook is twee keer zo lang.':'Maak één aaneengesloten strook die twee keer zo lang is.';}};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));
function toggleCell(target){const id=Number(target.dataset.cell);save();selections.has(id)?selections.delete(id):selections.add(id);$('practice-result').textContent='';drawPractice();}
practiceBoard.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.hasAttribute('data-cell')&&!revealed){e.preventDefault();toggleCell(e.target);}};
function rub(p){for(const n of [...ink.children]){const b=n.getBBox();if(p.x>=b.x-15&&p.x<=b.x+b.width+15&&p.y>=b.y-15&&p.y<=b.y+b.height+15){if(n.tagName==='path'&&n.getTotalLength){let hit=false;for(let d=0;d<n.getTotalLength();d+=5){const q=n.getPointAtLength(d);if(Math.hypot(p.x-q.x,p.y-q.y)<20){hit=true;break;}}if(hit)n.remove();}else n.remove();}}}
practiceBoard.addEventListener('pointerdown',e=>{if(pointer!==null||e.button!==0||revealed)return;const p=point(practiceBoard,e);if(tool==='touch'){const n=e.target.closest('[data-cell]');if(n)toggleCell(n);return;}e.preventDefault();save();pointer=e.pointerId;practiceBoard.setPointerCapture(pointer);if(tool==='circle'||tool==='triangle'){dot(ink,p.x,p.y,tool);return;}if(tool==='eraser'){rub(p);return;}stroke=el('path',{d:`M${p.x} ${p.y}l.1 .1`,fill:'none',stroke:tool==='pen'?'#243b45':'#28705d','stroke-width':tool==='paint'?26:4,'stroke-opacity':tool==='paint'?.3:1,'stroke-linecap':'round','stroke-linejoin':'round'});ink.append(stroke);});
practiceBoard.addEventListener('pointermove',e=>{if(pointer!==e.pointerId)return;const p=point(practiceBoard,e);if(tool==='eraser')rub(p);else if(stroke)stroke.setAttribute('d',stroke.getAttribute('d')+`L${p.x} ${p.y}`);});['pointerup','pointercancel','lostpointercapture'].forEach(type=>practiceBoard.addEventListener(type,()=>{pointer=null;stroke=null;}));
$('ink-undo').onclick=()=>{const old=history.pop();if(old){ink.innerHTML=old.ink;selections=new Set(old.selections);choiceSet=new Set(old.choices);revealed=false;$('practice-result').textContent='';drawPractice();}};$('ink-clear').onclick=()=>{save();ink.replaceChildren();selections.clear();choiceSet.clear();revealed=false;$('practice-result').textContent='';drawPractice();};
strips();prepare();fresh();
})();
