const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const paid={email:'alice@example.com',status:'betaald',source:'koop',invoiceSeries:'live',invoiceNumber:'2026-0001',invoiceStoragePath:'Facturen/live/2026/2026-0001.pdf',amountEUR:'40.00'};
function setup(){
 const rows={orders:{own:paid,other:{...paid,email:'bob@example.com',invoiceNumber:'2026-0002',invoiceStoragePath:'Facturen/live/2026/2026-0002.pdf'},conflict:{...paid,uid:'bob'},test:{...paid,invoiceSeries:'test'},school:{...paid,source:'school'},unpaid:{...paid,status:'open'},reading:{...paid,invoiceStoragePath:'Facturen/live/Zisa Lezen/2026/2026-0001.pdf'},traversal:{...paid,invoiceStoragePath:'Facturen/live/2026/../2026-0001.pdf'}},Orders:{own:paid},Bestellingen:{own:paid}};
 const users={alice:{uid:'alice',email:'alice@example.com',emailVerified:true},bob:{uid:'bob',email:'bob@example.com',emailVerified:true},unverified:{uid:'unverified',email:'alice@example.com',emailVerified:false},disabled:{uid:'disabled',email:'alice@example.com',emailVerified:true,disabled:true}};
 const downloads=[];let reads=0;
 const db={collection:name=>{assert(['orders','Orders','Bestellingen'].includes(name));return {doc:id=>({get:async()=>{reads++;return {data:()=>rows[name][id]};}}),where:(field,op,value)=>({get:async()=>{reads++;return {docs:Object.entries(rows[name]).filter(([,v])=>v[field]===value).map(([id,v])=>({id,data:()=>v}))};}})}}};
 const modules={'firebase-functions/v2/https':{onRequest:(_,fn)=>fn},'firebase-admin/auth':{getAuth:()=>({verifyIdToken:async(token,revoked)=>{assert.equal(revoked,true);if(!users[token])throw Error();return {uid:token};},getUser:async uid=>users[uid]})},'firebase-admin/firestore':{getFirestore:()=>db},'firebase-admin/storage':{getStorage:()=>({bucket:()=>({file:path=>({download:async()=>{downloads.push(path);return [Buffer.from('%PDF-test')];}})})})}};
 const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/pro-invoices.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>{assert(modules[n]);return modules[n];},Buffer});
 return {downloads,get reads(){return reads},exports,request:async(body,token='alice',origin='https://tools.jufzisa.be')=>{const res={statusCode:200,headers:{},set(k,v){this.headers[k]=v;return this;},status(n){this.statusCode=n;return this;},json(body){this.body=body;return this;},send(body){this.body=body;return this;},end(){return this;}};await exports.proInvoices({method:'POST',headers:{origin,...(token?{authorization:'Bearer '+token}:{})},body},res);return res;}};
}
test('list contains only own paid live Pro invoices, deduplicated across collections',async()=>{const s=setup(),r=await s.request({action:'list'});assert.equal(r.statusCode,200);assert.deepEqual(Array.from(r.body.invoices,x=>x.id),['own']);assert(!JSON.stringify(r.body).includes('invoiceStoragePath'));assert.equal(s.downloads.length,0);});
test('altering order ID cannot download another buyer invoice',async()=>{const s=setup();for(const collection of ['orders','Orders','Bestellingen'])assert.equal((await s.request({action:'download',collection,id:'own'},'bob')).statusCode,404);assert.equal(s.downloads.length,0);});
test('UID conflict cannot be bypassed by matching email',async()=>{const s=setup();assert.equal((await s.request({action:'download',collection:'orders',id:'conflict'})).statusCode,404);assert.equal(s.downloads.length,0);});
test('test, school, unpaid, reading and traversal PDFs cannot be downloaded',async()=>{const s=setup();for(const id of ['test','school','unpaid','reading','traversal','missing'])assert.equal((await s.request({action:'download',collection:'orders',id})).statusCode,404);assert.equal(s.downloads.length,0);});
test('unauthenticated, unverified and disabled users cannot read invoice records',async()=>{for(const token of ['', 'bad','unverified','disabled']){const s=setup();assert([401,403].includes((await s.request({action:'list'},token)).statusCode));assert.equal(s.reads,0);assert.equal(s.downloads.length,0);}});
test('caller cannot select other collections or arbitrary storage paths',async()=>{const s=setup();for(const body of [{action:'download',collection:'readingTestInvoices',id:'own'},{action:'download',collection:'orders',id:'../own'},{action:'download',path:paid.invoiceStoragePath}])assert.equal((await s.request(body)).statusCode,404);assert.equal(s.reads,0);});
test('own PDF is streamed privately; no public or signed URL is generated',async()=>{const s=setup(),r=await s.request({action:'download',collection:'orders',id:'own'});assert.equal(r.statusCode,200);assert.equal(r.headers['Content-Type'],'application/pdf');assert.equal(r.headers['Cache-Control'],'private, no-store');assert.deepEqual(s.downloads,[paid.invoiceStoragePath]);assert.equal(r.body.toString(),'%PDF-test');});
test('untrusted web origin is refused before authentication or database access',async()=>{const s=setup();assert.equal((await s.request({action:'list'},'alice','https://evil.example')).statusCode,403);assert.equal(s.reads,0);});
