const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
function setup(mode='live',extra={}){
 const calls=[];const user={uid:'buyer',email:'buyer@example.test',emailVerified:true,disabled:false};
 const env={READING_LIVE_ENABLED:'true',READING_LIVE_SALES_OPEN:'false',READING_LIVE_MOLLIE_PROFILE_ID:'pfl_fixture',READING_LIVE_RETURN_URL:'https://tools.jufzisa.be/lezen/mijn-account.html',READING_LIVE_WEBHOOK_URL:'https://europe-west1-zisa-spelletjesmaker-pro.cloudfunctions.net/readingLiveMollieWebhook',READING_TEST_ENABLED:'true',READING_MOLLIE_PROFILE_ID:'pfl_fixture',READING_RETURN_URL:'https://tools.jufzisa.be/lezen/mijn-account.html?test=1',READING_WEBHOOK_URL:'https://example.test/readingMollieWebhook',...extra};
 const db={collection:name=>({doc:id=>({get:async()=>({data:()=>({ready:true,ownerKey:'zisa-spelletjesmaker-pro:other',path:'private.pdf'})})})}),runTransaction:async fn=>fn({get:async()=>({data:()=>({})}),set:()=>{}})};
 const service={status:async()=>({allowed:false}),checkout:async()=>{calls.push('checkout');return {checkoutUrl:'https://www.mollie.com/fake'};},student:async()=>{calls.push('student')}};
 const overrides={'firebase-functions/v2/https':{onRequest:(_,f)=>f},'firebase-functions/v2/scheduler':{onSchedule:(_,f)=>f},'firebase-functions/v2/firestore':{onDocumentCreated:(_,f)=>f},'firebase-functions/params':{defineSecret:()=>({value:()=>mode+'_fixture'})},'firebase-admin/auth':{getAuth:()=>({getUser:async()=>user})},'firebase-admin/firestore':{getFirestore:()=>db},'firebase-admin/storage':{getStorage:()=>({bucket:()=>({file:()=>{calls.push('download');throw Error('Unexpected download')}})})},'./reading-security':{readingAuthenticator:()=>async()=>({project:'zisa-spelletjesmaker-pro',uid:user.uid})},'./reading-service':{createReadingService:()=>service},'./reading-invoice-store':{readingInvoiceStore:()=>()=>{}},'./reading-admin':{},'./reading-verification':{},'./reading-ledger':{},'./reading-environment':require('./lib/reading-environment'),'./reading-invoice':require('./lib/reading-invoice')};
 const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/reading-http.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>overrides[n]||require(n),process:{env},URL,Buffer});
 const api=exports.createReadingFunctions(async()=>false,{},mode);
 async function request(action,body={},headers={}){let status=200,result;const res={set(){return this},status(n){status=n;return this},json(v){result=v;return this},end(){},type(){return this},send(v){result=v;return this}};await api.readingApi({method:'POST',path:'/'+action,body,get:n=>headers[n]||''},res);return {status,result}};
 return {request,calls,user};
}
test('public live checkout is closed and account reflects unavailable checkout',async()=>{const s=setup();assert.equal((await s.request('checkout')).status,403);assert.equal(s.calls.length,0);assert.equal((await s.request('account')).result.checkoutAvailable,false)});
test('only configured pilot can start real checkout while sales closed',async()=>{const s=setup('live',{READING_LIVE_EMAILS:'buyer@example.test'});assert.equal((await s.request('checkout')).status,200);assert.deepEqual(s.calls,['checkout'])});
test('live processing is disabled by default gate',async()=>{const s=setup('live',{READING_LIVE_ENABLED:'false'});assert.equal((await s.request('account')).status,503);assert.equal(s.calls.length,0)});
test('student token cannot call checkout, account or invoices',async()=>{const s=setup();for(const route of ['checkout','account','invoice'])assert.equal((await s.request(route,{}, {'X-Reading-Token':'example'})).status,403);assert.equal(s.calls.length,0)});
test('live account cannot download another buyer invoice or test invoice',async()=>{const s=setup();assert.equal((await s.request('invoice',{id:'reading-live-tr_other'})).status,403);assert.notEqual((await s.request('invoice',{id:'reading-test-tr_other'})).status,200);assert(!s.calls.includes('download'))});
test('test allowlist remains mandatory even when public live sales enabled',async()=>{const s=setup('test',{READING_LIVE_SALES_OPEN:'true'});assert.equal((await s.request('checkout')).status,403);assert.equal(s.calls.length,0)});
