'use strict';
function uid(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}
const icons={text:'<path d="M4 5h16M12 5v16M8 21h8M4 5v3M20 5v3"/>',send:'<path d="m22 2-7 20-4-9-9-4zM22 2 11 13"/>',pencil:'<path d="m15 5 4 4M4 20l4-1L20 7a2.8 2.8 0 0 0-4-4L4 15zM4 15l5 5"/>',brush:'<path d="m14 6 4 4M10 13 19 3a1.4 1.4 0 0 1 2 2l-9 10M10 13c-5-1-6 3-5 5-1 2-3 2-3 2 7 2 11-1 10-5z"/>',fill:'<path d="m4 10 7-7 9 9-8 8a2 2 0 0 1-3 0L3 14a2 2 0 0 1 1-4zM3 12h17M7 2l6 6M20 16s-3 3-3 4a3 3 0 0 0 6 0c0-1-3-4-3-4z"/>',eraser:'<path d="m14 3 7 7a2 2 0 0 1 0 3l-8 8H8l-6-6a2 2 0 0 1 0-3l9-9a2 2 0 0 1 3 0zM7 7l10 10M13 21h9"/>',line:'<path d="m4 20 16-16"/><circle cx="4" cy="20" r="1"/><circle cx="20" cy="4" r="1"/>',circle:'<circle cx="12" cy="12" r="9"/>',rectangle:'<rect x="3" y="4" width="18" height="16" rx="1"/>',undo:'<path d="M4 5v6h6M4 11c2-7 15-7 16 1 1 6-6 9-10 7"/>',redo:'<path d="M20 5v6h-6M20 11C18 4 5 4 4 12c-1 6 6 9 10 7"/>',new:'<path d="M14 2H5v20h14V7zM14 2v6h5M8 15h8M12 11v8"/>',save:'<path d="M4 3h14l3 3v15H3V3zM7 3v6h10V3M7 21v-8h10v8"/>',hand:'<path d="M8 12V5a2 2 0 0 1 4 0v6-8a2 2 0 0 1 4 0v8-5a2 2 0 0 1 4 0v9c0 5-3 7-7 7-3 0-5-2-7-5l-3-4a2 2 0 0 1 3-3l2 2"/>'};
const svg=n=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[n]+'</svg>';
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));
const $=s=>document.querySelector(s),canvas=$('#canvas'),view=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
const paint=document.createElement('canvas');paint.width=W;paint.height=H;const ctx=paint.getContext('2d',{willReadFrequently:true});
const toolList=[['pencil','Potlood'],['brush','Penseel'],['fill','Verfemmer'],['eraser','Gom'],['text','Tekst'],['line','Lijn'],['circle','Cirkel'],['rectangle','Rechthoek']];
let tool='pencil',color='#253537',size=4,active=null,start=null,last=null,base=null,undo=[],redo=[],texts=[],selected=null,moved=false,editing=null,revision=0,pendingSubmission=null;
const hints={pencil:'Kies een kleur en teken op het witte blad.',brush:'Schilder met een dikke, ronde penseel.',fill:'Tik in een gesloten vorm om ze in te kleuren.',eraser:'Veeg met de gom over je tekening. Tekst weghalen? Kies Tekst.',text:'Tik om te typen of tekst te wijzigen. Sleep tekst om ze te verplaatsen.',line:'Sleep met je vinger om een rechte lijn te tekenen.',circle:'Sleep met je vinger om een cirkel of ovaal te tekenen.',rectangle:'Sleep met je vinger om een rechthoek te tekenen.'};
function chooseTool(id){tool=id;selected=null;document.querySelectorAll('[data-tool]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.tool===id));$('#tool-name').textContent=toolList.find(t=>t[0]===id)[1];$('#hint').textContent=hints[id];document.querySelectorAll('[data-size]').forEach(x=>x.disabled=['fill','text'].includes(id));render();}
for(const [id,label] of toolList){const b=document.createElement('button');b.dataset.tool=id;b.innerHTML=svg(id)+'<span>'+label+'</span>';b.setAttribute('aria-label',label);b.setAttribute('aria-pressed',id===tool);b.onclick=()=>chooseTool(id);$('#tools').append(b);}
const colors=[['#253537','Zwart'],['#ffffff','Wit'],['#e44343','Rood'],['#f68b30','Oranje'],['#ffd344','Geel'],['#76bd4a','Lichtgroen'],['#168565','Groen'],['#36bfe0','Lichtblauw'],['#3268ce','Blauw'],['#8257b6','Paars'],['#ed85b3','Roze'],['#916044','Bruin']];
function swatch(hex,name){const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=hex;b.dataset.color=hex;b.style.setProperty('--check',['Wit','Geel','Lichtgroen','Lichtblauw','Roze','Oranje'].includes(name)?'#233c3b':'white');b.setAttribute('aria-label',name);b.title=name;return b;}
let textColor=color;
for(const [hex,name] of colors){const b=swatch(hex,name);b.setAttribute('aria-pressed',hex===color);b.onclick=()=>{color=hex;$('#current-color').style.background=color;$('#color-name').textContent=name;$('#palette').querySelectorAll('.swatch').forEach(x=>x.setAttribute('aria-pressed',x===b));};$('#palette').append(b);const t=swatch(hex,name);t.onclick=()=>{textColor=hex;textPreview();};$('#text-colors').append(t);}
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{size=Number(b.dataset.size);document.querySelectorAll('[data-size]').forEach(x=>x.setAttribute('aria-pressed',x===b));});
function fit(){const a=$('.paper-area'),s=getComputedStyle(a),w=a.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),h=a.clientHeight-parseFloat(s.paddingTop)-parseFloat(s.paddingBottom),r=Math.max(0,Math.min(w/W,h/H));canvas.style.width=W*r+'px';canvas.style.height=H*r+'px';}new ResizeObserver(fit).observe($('.paper-area'));
function blank(){ctx.fillStyle='white';ctx.fillRect(0,0,W,H);texts=[];selected=null;render();}
function font(t){return `${t.italic?'italic ':''}${t.bold?'bold ':''}${t.size}px ${t.font}`;}
function layout(t){view.font=font(t);const lines=[];for(const paragraph of t.value.split('\n')){let line='';for(const char of paragraph){if(view.measureText(line+char).width>Math.min(1000,W-40)&&line){lines.push(line);line='';}line+=char;}lines.push(line);}const width=Math.max(30,...lines.map(l=>view.measureText(l).width));return{lines,width,height:lines.length*t.size*1.25};}
function bound(t){const b=layout(t);t.x=Math.max(20,Math.min(W-b.width-20,t.x));t.y=Math.max(15,Math.min(H-b.height-15,t.y));return b;}
function render(selection=true){view.clearRect(0,0,W,H);view.drawImage(paint,0,0);view.textBaseline='top';for(const t of texts){const b=layout(t);view.font=font(t);view.fillStyle=t.color;b.lines.forEach((l,i)=>view.fillText(l,t.x,t.y+i*t.size*1.25));if(selection&&selected===t.id&&tool==='text'){view.save();view.strokeStyle='#116a60';view.lineWidth=2;view.setLineDash([7,5]);view.strokeRect(t.x-6,t.y-6,b.width+12,b.height+12);view.restore();}}}
function snap(){return{image:ctx.getImageData(0,0,W,H),texts:structuredClone(texts)};}function apply(s){ctx.putImageData(s.image,0,0);texts=structuredClone(s.texts);selected=null;render();}
function refresh(){$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length;}
function changed(){revision++;pendingSubmission=null;}
function remember(image){undo.push(image);if(undo.length>16)undo.shift();redo=[];changed();refresh();}
function restore(from,to){if(active!==null||!from.length)return;to.push(snap());apply(from.pop());changed();refresh();}
$('#undo').onclick=()=>restore(undo,redo);$('#redo').onclick=()=>restore(redo,undo);refresh();
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(W-1,(e.clientX-r.left)*W/r.width)),y:Math.max(0,Math.min(H-1,(e.clientY-r.top)*H/r.height))};}
function setup(){ctx.strokeStyle=ctx.fillStyle=tool==='eraser'?'#ffffff':color;ctx.lineWidth=tool==='eraser'?Math.max(20,size*3):tool==='brush'?size*3:size;ctx.lineCap='round';ctx.lineJoin='round';}
function dot(p){setup();ctx.beginPath();ctx.arc(p.x,p.y,ctx.lineWidth/2,0,Math.PI*2);ctx.fill();}
function stroke(a,b){setup();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
function shape(p){ctx.putImageData(base.image,0,0);setup();ctx.beginPath();if(tool==='line'){ctx.moveTo(start.x,start.y);ctx.lineTo(p.x,p.y);}else if(tool==='rectangle'){ctx.rect(start.x,start.y,p.x-start.x,p.y-start.y);}else{ctx.ellipse((p.x+start.x)/2,(p.y+start.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);}ctx.stroke();}
function fill(p){const im=ctx.getImageData(0,0,W,H),d=im.data,x=Math.floor(p.x),y=Math.floor(p.y),idx=(y*W+x)*4,t=[d[idx],d[idx+1],d[idx+2]],c=[parseInt(color.slice(1,3),16),parseInt(color.slice(3,5),16),parseInt(color.slice(5,7),16)];if(t.every((v,i)=>Math.abs(v-c[i])<=10))return;const seen=new Uint8Array(W*H),stack=new Int32Array(W*H);let top=0;stack[top++]=y*W+x;seen[y*W+x]=1;const matches=i=>Math.abs(d[i*4]-t[0])<=48&&Math.abs(d[i*4+1]-t[1])<=48&&Math.abs(d[i*4+2]-t[2])<=48;while(top){const n=stack[--top];if(!matches(n))continue;const i=n*4;d[i]=c[0];d[i+1]=c[1];d[i+2]=c[2];d[i+3]=255;const nx=n%W;function add(v){if(!seen[v]){seen[v]=1;stack[top++]=v;}}if(nx>0)add(n-1);if(nx<W-1)add(n+1);if(n>=W)add(n-W);if(n<W*(H-1))add(n+W);}ctx.putImageData(im,0,0);}
function hit(p){return [...texts].reverse().find(t=>{const b=layout(t);return p.x>=t.x-12&&p.x<=t.x+b.width+12&&p.y>=t.y-12&&p.y<=t.y+b.height+12;});}
canvas.addEventListener('pointerdown',e=>{if(active!==null||e.button>0)return;e.preventDefault();active=e.pointerId;canvas.setPointerCapture(active);start=last=point(e);base=snap();moved=false;if(tool==='text'){selected=hit(start)?.id??null;}else if(tool==='fill'){fill(start);}else if(['pencil','brush','eraser'].includes(tool)){dot(start);}render();});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==active)return;e.preventDefault();const p=point(e);if(Math.hypot(p.x-start.x,p.y-start.y)>8)moved=true;if(tool==='text'){const t=texts.find(t=>t.id===selected),old=base.texts.find(t=>t.id===selected);if(t&&old&&moved){t.x=old.x+p.x-start.x;t.y=old.y+p.y-start.y;bound(t);}}else if(tool==='fill')return;else if(['pencil','brush','eraser'].includes(tool)){const events=e.getCoalescedEvents?.();for(const ev of (events?.length?events:[e])){const q=point(ev);stroke(last,q);last=q;}}else shape(p);render();});
function finish(e,cancel=false){if(e.pointerId!==active)return;let openText=false;if(cancel)apply(base);else if(tool==='text'){if(moved&&selected)remember(base);else if(!moved)openText=true;}else{if(['line','circle','rectangle'].includes(tool))shape(point(e));remember(base);}active=null;base=null;render();if(openText)editText(selected,start);}
canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));canvas.addEventListener('lostpointercapture',e=>{if(active===e.pointerId)finish(e,true);});
let textPoint={x:30,y:30};
function editText(id,p){editing=id;textPoint=p;const t=texts.find(t=>t.id===id);$('#words').value=t?.value??'';$('#font').value=t?.font??'Arial';$('#font-size').value=t?.size??44;$('#bold').setAttribute('aria-pressed',!!t?.bold);$('#italic').setAttribute('aria-pressed',!!t?.italic);textColor=t?.color??color;$('#delete-text').hidden=!id;$('#text-error').textContent='';textPreview();$('#text-dialog').showModal();$('#words').focus();}
function textSettings(){return{value:$('#words').value.trim(),font:$('#font').value,size:Number($('#font-size').value),bold:$('#bold').getAttribute('aria-pressed')==='true',italic:$('#italic').getAttribute('aria-pressed')==='true',color:textColor};}
function textPreview(){const t=textSettings(),p=$('#text-preview');p.textContent=t.value||'Mijn tekst';p.style.font=font({...t,size:Math.min(t.size,36)});p.style.color=t.color;$('#text-colors').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.color===textColor));}
for(const id of ['words','font','font-size'])$('#'+id).addEventListener('input',textPreview);
for(const id of ['bold','italic'])$('#'+id).onclick=()=>{const b=$('#'+id);b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')!=='true');textPreview();};
$('#cancel-text').onclick=()=>$('#text-dialog').close();$('#delete-text').onclick=()=>{remember(snap());texts=texts.filter(t=>t.id!==editing);selected=null;render();$('#text-dialog').close();};
$('#text-form').onsubmit=e=>{e.preventDefault();const t=textSettings();if(!t.value)return;if(layout(t).height>H-30){$('#text-error').textContent='Je tekst past niet. Kies kleinere letters of maak je tekst korter.';return;}remember(snap());const old=texts.find(x=>x.id===editing);if(old){Object.assign(old,t);bound(old);selected=old.id;}else{const n={...t,id:uid(),x:textPoint.x,y:textPoint.y};bound(n);texts.push(n);selected=n.id;}render();$('#text-dialog').close();};
$('#new').onclick=()=>$('#confirm').showModal();$('#cancel').onclick=()=>$('#confirm').close();$('#clear').onclick=()=>{remember(snap());blank();$('#confirm').close();};
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
async function png(){render(false);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));render();if(!blob)throw new Error('Bewaren lukte niet. Probeer nog eens.');return blob;}
$('#save').onclick=async()=>{try{const blob=await png(),name='mijn-tekening.png',file=new File([blob],name,{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'Mijn tekening'});return;}catch(e){if(e.name==='AbortError')return;}}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('Je tekening is klaargezet als afbeelding.');}catch(e){toast(e.message);}};
const params=new URLSearchParams(location.search);$('#class-code').value=(params.get('klas')||'').toUpperCase().slice(0,8);if(params.has('klas'))$('.teacher-link').hidden=true;if(params.has('voordoen')){$('#send').hidden=true;$('.teacher-link').textContent='Terug naar werkjes';}
$('#send').onclick=()=>{$('#send-status').textContent='';$('#submit-send').disabled=false;$('#send-dialog').showModal();($('#pupil-name').value?$('#class-code'):$('#pupil-name')).focus();};
let sending=false;$('#cancel-send').onclick=()=>{if(!sending)$('#send-dialog').close();};$('#send-dialog').addEventListener('cancel',e=>{if(sending)e.preventDefault();});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?restore(redo,undo):restore(undo,redo);}});
window.addEventListener('beforeunload',e=>{if(undo.length){e.preventDefault();e.returnValue='';}});
blank();fit();
