// Reviewable UI only. No auth calls, browser entitlements, payment requests or persisted demo state.
const views = {
  login: ['Welkom bij Zisa Lezen', 'Meld je aan om je boeken en je abonnement te openen.', `
    <section class="card"><h2>Aanmelden</h2><label>E-mailadres<input type="email" autocomplete="off" disabled placeholder="Je e-mailadres"></label><label>Wachtwoord<input type="password" autocomplete="off" disabled placeholder="Je wachtwoord"></label><button disabled>Aanmelden</button><p class="small">Wachtwoord vergeten? Je kunt straks een herstellink aanvragen.</p></section>
    <section class="card"><h2>Nog geen leesaccount?</h2><p>Maak eerst een account aan en bevestig je e-mailadres. Daarna kun je het abonnement afsluiten.</p><p>Je gebruikt dit account voor je leesboeken en om je abonnement te beheren.</p><button disabled>Leesaccount maken</button></section>`],
  checkout: ['Je leesabonnement', 'Alle beschikbare leesboeken, opdrachten en woordverklaringen.', `
    <section class="card offer"><h2>Zisa Lezen</h2><p class="price">€3,99 <span>per maand</span></p><p>Automatisch verlengd · maandelijks opzegbaar</p><label class="consent"><input type="checkbox" disabled>Ik kies voor €3,99 per maand en geef toestemming voor automatische maandelijkse betalingen tot ik opzeg.</label><button disabled>Abonneren en betalen — €3,99 per maand</button><p class="small">Je betaalt op de beveiligde betaalpagina van Mollie.</p></section>
    <section class="card"><h2>Gegevens voor je factuur</h2><label>Naam<input disabled placeholder="Naam op de factuur"></label><label>Adres<input disabled placeholder="Straat, huisnummer, postcode en gemeente"></label><label>School of organisatie (optioneel)<input disabled></label><label>Ondernemingsnummer (indien van toepassing)<input disabled></label><p>Na iedere geslaagde maandbetaling krijg je je factuur per e-mail. Je vindt die ook terug in je leesaccount.</p><h2>Na je betaling</h2><p>Zodra de betaling bevestigd is, kun je Zisa Lezen openen.</p><p>Opzeggen doe je vanuit je leesaccount. Je houdt toegang tot het einde van je betaalde periode.</p></section>`],
  waiting: ['We controleren je betaling', 'Je hoeft niet opnieuw te betalen.', `<section class="card"><h2>Even geduld</h2><p>We wachten op de bevestiging van Mollie. Alleen terugkeren van de betaalpagina betekent nog niet dat de betaling gelukt is.</p><button disabled>Betaalstatus vernieuwen</button><p class="small">Je kunt deze pagina sluiten en later weer aanmelden.</p></section>`],
  active: ['Mijn Zisa Lezen', 'Je boeken staan klaar.', `<section class="card"><span class="status">Abonnement actief</span><h2>Je leesboeken</h2><button disabled>Open Zisa Lezen</button><h2>Lezen op een ander toestel</h2><p>Gebruik je persoonlijke leeslink of QR-code. Leerlingen kunnen hiermee alleen lezen.</p><button disabled>Toon leeslink en QR-code</button><button disabled>Leeslink vervangen</button><p class="small">Na het vervangen werkt de oude link niet meer.</p></section><section class="card"><h2>Mijn abonnement</h2><p class="price">€3,99 <span>per maand</span></p><dl><dt>Volgende betaling (voorbeeld)</dt><dd>27 oktober 2026</dd></dl><p>Je abonnement wordt automatisch verlengd.</p><button disabled>Abonnement opzeggen</button><p class="small">Bij opzegging kun je in dit voorbeeld blijven lezen tot 27 oktober 2026. Daarna stopt de toegang.</p><button disabled>Afmelden</button></section>`],
  canceled: ['Je abonnement is opgezegd', 'Je kunt je betaalde periode nog uitlezen.', `<section class="card"><h2>Je leesboeken</h2><p>In dit voorbeeld kun je nog lezen tot <strong>27 oktober 2026</strong>.</p><button disabled>Open Zisa Lezen</button></section><section class="card"><h2>Automatische verlenging gestopt</h2><p>We hebben je opzegging bevestigd. Je ontvangt daarvan ook een e-mail.</p><p class="small">Een betaling die al in behandeling was, wordt afzonderlijk gecontroleerd.</p></section>`],
  expired: ['Je leesabonnement is afgelopen', 'Je kunt nog aanmelden om je account te bekijken.', `<section class="card"><h2>Weer verder lezen?</h2><p>Sluit opnieuw een leesabonnement af voor €3,99 per maand. Je krijgt toegang zodra je betaling bevestigd is.</p><button disabled>Opnieuw abonneren</button></section>`],
  failed: ['Je betaling is niet gelukt', 'Er is voor deze betaling geen nieuwe leesperiode toegevoegd.', `<section class="card"><h2>Controleer je betaling</h2><p>Je behoudt eventuele toegang waarvoor je al betaald hebt. We tonen hier straks hoe je de betaling kunt herstellen zonder dubbel te betalen.</p><button disabled>Betaling bekijken</button></section>`],
};
const invoices = `<section class="card"><h2>Mijn facturen</h2><p>Na elke geslaagde maandbetaling staat hier je factuur. Je krijgt die ook per e-mail.</p><a class="outline" href="voorbeeldfactuur.pdf" target="_blank" rel="noopener">Bekijk de voorbeeldfactuur (PDF)</a><p class="small">Dit is een fictief voorbeeld, geen echte factuur. Facturen blijven in je account beschikbaar nadat je leesabonnement stopt.</p></section>`;
for (const state of ['active', 'canceled', 'expired', 'failed']) views[state][2] += invoices;
function render() {
  const [title, intro, markup] = views[document.querySelector('#scenario').value] || views.login;
  document.querySelector('#title').textContent = title;
  document.querySelector('#intro').textContent = intro;
  document.querySelector('#view').innerHTML = markup; // Only fixed, developer-owned templates above.
}
document.querySelector('#scenario').addEventListener('change', render);
render();
