// Offline walkthrough: no Firebase imports, credentials, storage, billing calls or mail.
const local=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
const books=local?'../zisa-lezen-m3-compleet/?gratis=1':'../zisa-lezen-m3-compleet/?ontdek=1';
let canceled=false,quantity=1,peppol=false;
let teacherEmails=[],selectedTeacher='collega@example.com';
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const total=()=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(quantity*399/100);
const scope=()=>quantity===1?'één leerkracht en de eigen klas':`${quantity} leerkrachten, elk met de eigen klas`;
const peppolFields=()=>`<label class="consent"><input id="demoPeppol" type="checkbox" ${peppol?'checked':''}>Ik wil een factuur via Peppol voor de school</label><div id="demoPeppolFields" ${peppol?'':'hidden'}><label>Officiële schoolnaam<input readonly value="Voorbeeldschool"></label><label>Factuuradres school of schoolbestuur<input readonly value="Voorbeeldstraat 12, 1000 Brussel"></label><label>Facturatie-e-mail<input readonly value="school@example.com"></label><label>Peppol-ID<input readonly value="0208:ondernemingsnummer"></label><label>GLN-nummer (optioneel)<input readonly placeholder="Alleen invullen indien nodig"></label><label>Bestelreferentie (optioneel)<input readonly placeholder="Bijvoorbeeld een bestelbonnummer"></label><p class="hint">Fictieve voorbeeldgegevens. Juf Zisa verstuurt de factuur via Peppol; een eventuele PDF-mail is een kopie van dezelfde factuur.</p></div>`;
const button=(text,to,secondary=false)=>`<a class="demo-button${secondary?' secondary':''}" href="#${to}">${text}</a>`;
const singleInvoice='<a class="demo-button secondary" href="voorbeeldfactuur.pdf" target="_blank" rel="noopener">Open de voorbeeldfactuur (PDF)</a>';
const invoice=()=>quantity===1?singleInvoice:button('Bekijk de gezamenlijke voorbeeldfactuur','schoolfactuur',true);
const steps=[['aanmelden','1. Account'],['gegevens','2. Gegevens'],['betaling','3. Betalen'],['gelukt','4. Bevestiging'],['mail','5. E-mail'],['boeken','6. Lezen']];
const views={
 school:()=>`<div class="card"><h1>Zisa Lezen voor de school</h1><p>Bestel samen voor meerdere leerkrachten. Elke leerkracht gebruikt een eigen account en klas-QR. Leerlingen lezen op school en thuis.</p><form id="schoolForm"><label>Aantal leerkrachten<input id="schoolQuantity" type="number" min="2" max="100" step="1" required value="${Math.max(2,quantity)}"></label><p>€3,99 per leerkracht per maand. Eén factuur per betaalperiode.</p><p class="price" id="schoolTotal"></p><button class="demo-button" type="submit">Bekijk de schoolbestelling</button></form><p class="hint">Dit is een demonstratie van de schoolbestelling. Er wordt niets besteld of betaald.</p>${button('Voor één leerkracht bestellen','individueel',true)}</div>`,
 collegas:()=>`<div class="card"><h1>Nodig je leerkrachten uit</h1><p>Je school heeft <strong>${quantity} leerkrachtplaatsen</strong>. Vul voor elke collega een eigen e-mailadres in. Wil je zelf ook lezen? Vul dan je eigen e-mailadres bij één van de plaatsen in.</p><form id="teachersForm">${Array.from({length:quantity},(_,i)=>`<label for="teacher-${i}">E-mailadres leerkracht ${i+1}</label><input id="teacher-${i}" type="email" maxlength="254" autocomplete="off" placeholder="leerkracht${i+1}@voorbeeldschool.be">`).join('')}<p class="hint">Je mag plaatsen leeg laten en later invullen. Gebruik gerust fictieve adressen: niets wordt verstuurd of bewaard na het herladen van de pagina.</p><p id="teacherError" role="alert"></p><button class="demo-button" type="submit">Bekijk de uitnodigingen — demo</button></form>${button('Terug naar het schoolaccount','account',true)}</div>`,
 uitnodigingen:()=>`<div class="card"><h1>Uitnodigingen bekijken</h1><p><strong>Dit is een voorbeeld. Er zijn geen e-mails verstuurd.</strong></p><p>Elke ingevulde collega zou een eigen uitnodiging ontvangen om een account te maken of zich aan te melden. De school betaalt; de leerkracht hoeft niets te betalen.</p>${teacherEmails.map((email,i)=>email?`<button class="demo-button secondary" data-teacher="${i}">Bekijk de mail voor ${escapeHTML(email)}</button>`:'').join('')}<p>${quantity-teacherEmails.filter(Boolean).length} van de ${quantity} plaatsen nog niet ingevuld.</p>${button('E-mailadressen aanpassen','collegas',true)}${button('Naar het schoolaccount','account',true)}</div>`,
 uitnodiging:()=>`<div class="card"><p class="eyebrow">Voorbeeld — niet verstuurd</p><h1>Je school nodigt je uit voor Zisa Lezen</h1><p>Aan: <strong>${escapeHTML(selectedTeacher)}</strong></p><p>Je school heeft een leerkrachtplaats voor jou voorzien. Meld je aan of maak een account met het uitgenodigde e-mailadres. Je hoeft zelf geen abonnement te betalen.</p>${button('Bekijk mijn leerkrachtomgeving','leerkracht')}</div>`,
 leerkracht:()=>`<div class="card"><h1>Zisa Lezen voor mijn klas</h1><p>Je school betaalt je leerkrachtplaats. Je leerlingen mogen ook thuis lezen. Deel de klas-QR alleen met je eigen klas.</p>${button('Open de leesboeken','boeken')}${button('Mijn klas-QR bekijken','leerling',true)}<p class="hint">Als leerkracht zie je geen facturen of betaalgegevens van de school. Deze demonstratie gebruikt voorbeeldgegevens.</p></div>`,
 schoolfactuur:()=>`<div class="card"><p class="eyebrow">Voorbeeld — geen echte factuur</p><h1>Gezamenlijke schoolfactuur</h1><p>Voorbeeldschool · Voorbeeldstraat 12, 1000 Brussel<br>school@example.com</p><p>Periode: 27 september tot 27 oktober 2026</p><p>${quantity} leerkrachten × €3,99 = <strong>${total()}</strong></p><p>Iedere leerkracht krijgt toegang voor de eigen klas, op school en thuis.</p>${peppol?'<p>Via Peppol aangevraagd. In jouw beheer verschijnt: <strong>Nog via Peppol te versturen</strong>.</p>':''}<p class="hint">De schoolkoppeling is lokaal voorbereid, maar staat nog niet online. Dit voorbeeld boekt niets in.</p>${quantity===4?'<a class="demo-button secondary" href="voorbeeldschoolfactuur.pdf" target="_blank" rel="noopener">Open de PDF voor vier leerkrachten (voorbeeld)</a>':''}${button('Terug naar mijn account','account',true)}</div>`,
 aanmelden:()=>`<div class="card"><p class="eyebrow">Je leesabonnement starten</p><h1>Welkom bij Zisa Lezen</h1><p>Maak een account aan of meld je aan met je bestaande account.</p>${button('Ik ben nieuw — account maken','registreren')}${button('Ik heb al een account — aanmelden','inloggen',true)}${button('Voor meerdere collega’s bestellen','school',true)}<p class="hint">In deze demonstratie hoef je niets echt in te vullen.</p></div>`,
 registreren:()=>`<div class="card"><h1>Maak je leesaccount</h1><label>E-mailadres<input readonly value="voorbeeld@example.com" autocomplete="off"></label><label>Wachtwoord<input readonly value="••••••••••••" autocomplete="off"></label><p class="hint">Dit zijn fictieve gegevens. Er wordt geen account aangemaakt.</p>${button('Account maken','bevestigmail')}${button('Terug','aanmelden',true)}</div>`,
 bevestigmail:()=>`<div class="card"><p class="eyebrow">Voorbeeld van de eerste e-mail</p><h1>Bevestig je e-mailadres</h1><div class="mail-head">Aan: voorbeeld@example.com<br>Onderwerp: Bevestig je account bij Zisa Lezen</div><p>Welkom bij Zisa Lezen! Klik hieronder om je e-mailadres te bevestigen.</p>${button('Bevestig mijn e-mailadres','gegevens')}<p class="hint">Je bekijkt de e-mail hier als voorbeeld. Er is niets verstuurd.</p></div>`,
 inloggen:()=>`<div class="card"><h1>Aanmelden bij Zisa Lezen</h1><label>E-mailadres<input readonly value="voorbeeld@example.com" autocomplete="off"></label><label>Wachtwoord<input readonly value="••••••••••••" autocomplete="off"></label>${button('Aanmelden en verder naar de aankoop','gegevens')}${button('Wachtwoord vergeten','herstellen',true)}<p class="hint">Een actief Pro-account hoeft geen apart leesabonnement te kopen.</p></div>`,
 herstellen:()=>`<div class="card"><h1>Wachtwoord herstellen</h1><p>In de echte omgeving ontvang je een herstellink per e-mail. Voor deze demonstratie kun je meteen verder.</p>${button('Terug naar aanmelden','inloggen')}</div>`,
 gegevens:()=>`<div class="card"><h1>Je leesabonnement</h1><p class="price">${total()} <span>per maand</span></p><p>Voor ${scope()}. Leerlingen mogen op school én thuis oefenen, zonder tijdslimiet of eigen account.</p><label>Naam op de factuur<input readonly value="Voorbeeldklant"></label><label>Factuuradres<input readonly value="Voorbeeldstraat 12, 1000 Brussel"></label><label>School of organisatie (optioneel)<input readonly placeholder="Niet ingevuld in dit voorbeeld"></label><label>Ondernemingsnummer (indien van toepassing)<input readonly placeholder="Niet ingevuld in dit voorbeeld"></label>${peppolFields()}<label class="consent"><input id="demoConsent" type="checkbox">Ik kies voor ${total()} per maand, automatisch verlengd tot ik opzeg. Ik kan maandelijks opzeggen.</label><button id="payNext" class="demo-button" disabled>Verder naar betaling</button><p class="hint">Ook na aanvinken wordt niets echt betaald.</p></div>`,
 betaling:()=>`<div class="card"><p class="eyebrow">Nagebootste betaalstap</p><h1>Je betaling</h1><p>Hier zou de koper de beveiligde betaalpagina van Mollie openen. Dit scherm laat alleen de stap zien; de echte vormgeving komt van Mollie.</p><div class="payment-method"><strong>Bancontact</strong><br>Zisa Lezen · eerste maand <strong>${total()}</strong> (${quantity} leerkracht${quantity===1?'':'en'})</div><p>Na de eerste betaling volgen automatische maandbetalingen tot je opzegt.</p>${button('Doe alsof de betaling gelukt is','gelukt')}${button('Bekijk een mislukte betaling','mislukt',true)}</div>`,
 mislukt:()=>`<div class="card"><h1>De betaling is niet gelukt</h1><p>Je abonnement is nog niet gestart. Er is geen betaalde toegang toegevoegd.</p>${button('Opnieuw proberen in de demo','betaling')}${button('Terug naar mijn gegevens','gegevens',true)}</div>`,
 gelukt:()=>`<div class="card"><p class="success">✓ Betaling bevestigd (voorbeeld)</p><h1>${quantity>1?'Je schoolabonnement staat klaar!':'Je kunt beginnen met lezen!'}</h1>${quantity>1?'<p>Vul nu de e-mailadressen van je leerkrachten in, zodat elke collega een eigen uitnodiging kan krijgen.</p>'+button('Vul de e-mailadressen van de leerkrachten in','collegas'):''}<p>Je leesabonnement is actief. Je factuur en de link naar Zisa Lezen staan ook in je bevestigingsmail.</p>${button('Open Zisa Lezen','boeken')}${button('Bekijk de bevestigingsmail','mail',true)}${invoice()}${button('Bekijk mijn account','account',true)}</div>`,
 mail:()=>`<div class="card"><p class="eyebrow">Voorbeeld van de bevestigingsmail</p><h1>Welkom bij Zisa Lezen</h1><div class="mail-head">Van: Juf Zisa<br>Aan: voorbeeld@example.com<br>Onderwerp: Je leesabonnement en je factuur</div><p>Bedankt voor je aankoop! Je hebt toegang tot de leesboeken en opdrachten van Zisa Lezen.</p><p>Je betaalde periode loopt in dit voorbeeld van <strong>27 september tot 27 oktober 2026</strong>. Je abonnement wordt automatisch verlengd voor ${total()} per maand tot je opzegt.</p>${button('Open Zisa Lezen','boeken')}${invoice()}${quantity>1?button('Nodig je leerkrachten uit','collegas'):''}${button('Mijn abonnement beheren','account',true)}<p class="hint">In de echte mail zit de factuur als PDF-bijlage. Deze mail is niet verzonden.</p>${button('Probeer de mailknop als je niet meer bent aangemeld','later',true)}</div>`,
 later:()=>`<div class="card"><p class="eyebrow">Terugkomen vanuit je e-mail</p><h1>Aanmelden bij Zisa Lezen</h1><p>Je bent niet meer aangemeld. Na aanmelden open je meteen de boekenkast.</p><label>E-mailadres<input readonly value="voorbeeld@example.com" autocomplete="off"></label><label>Wachtwoord<input readonly value="••••••••••••" autocomplete="off"></label>${button('Aanmelden en meteen lezen','boeken')}</div>`,
 boeken:()=>`<div class="wide"><div class="book-actions">${button('Mijn account','account',true)}${button('Bevestigingsmail bekijken','mail',true)}${button('Later opnieuw aanmelden proberen','later',true)}</div><p class="hint">Dit zijn de echte leesboeken in een voorbeeldvenster. ${local?'Je kunt een AVI-niveau, verhaal en opdrachten openen.':'Online worden hier de ontdekboeken getoond.'}</p><iframe src="${books}" title="Boekenkast van Zisa Lezen" allow="fullscreen"></iframe></div>`,
 account:()=>`<div class="cards"><section class="card"><h1>Mijn Zisa Lezen</h1><p class="success">${canceled?'Opgezegd · lezen tot 27 oktober 2026':'Abonnement actief (voorbeeld)'}</p>${button('Open Zisa Lezen','boeken')}${button('Leeslink voor leerlingen bekijken','leerling',true)}${quantity>1?button('Leerkrachten uitnodigen of beheren','collegas',true):''}${button('Afmelden en later terugkomen','later',true)}</section><section class="card"><h2>Mijn abonnement</h2><p class="price">${total()} <span>per maand</span></p><p>Voor ${scope()}. Leerlingen mogen op school én thuis oefenen, zonder tijdslimiet of eigen account.</p><p>${canceled?'De automatische verlenging is gestopt.':'Volgende betaling in dit voorbeeld: 27 oktober 2026.'}</p>${!canceled?button('Abonnement opzeggen','opzeggen',true):''}<h2>Mijn facturen</h2>${peppol?'<p>Factuur via Peppol aangevraagd voor de school.</p>':''}${invoice()}</section></div>`,
 leerling:()=>`<div class="card"><h1>Lezen voor leerlingen</h1><p>In de echte omgeving krijg je hier je persoonlijke leeslink en QR-code. Die geven alleen toegang tot de boeken, zonder wachtwoord van de leerkracht. Deel je klas-QR met je eigen leerlingen: ze kunnen op school én thuis oefenen zolang je leestoegang actief is. Er zijn geen aparte leerlingaccounts, tijdslimieten of apparaatlimieten.</p>${button('Bekijk wat een leerling opent','boeken')}${button('Terug naar mijn account','account',true)}<p class="hint">In deze demonstratie wordt geen persoonlijke toegangscode aangemaakt.</p></div>`,
 opzeggen:()=>`<div class="card"><h1>Wil je opzeggen?</h1><p>Je stopt de automatische verlenging. Je kunt nog lezen tot <strong>27 oktober 2026</strong> in dit voorbeeld.</p>${button('Ja, stop de verlenging in de demo','opgezegd')}${button('Nee, ik behoud mijn abonnement','account',true)}</div>`,
 opgezegd:()=>`<div class="card"><h1>Je abonnement is opgezegd</h1><p>De automatische verlenging is gestopt. Je behoudt je betaalde leestoegang tot 27 oktober 2026. In de echte omgeving krijg je een bevestiging per e-mail.</p>${button('Terug naar mijn account','account')}${button('Blijf lezen','boeken',true)}</div>`,
};
function render(){if(location.hash==='#schoolvoorbeeld'){quantity=4;location.hash='collegas';return;}if(location.hash==='#individueel'){quantity=1;location.hash='aanmelden';return;}const name=location.hash.slice(1)||'aanmelden';if(name==='aanmelden')canceled=false;if(name==='opgezegd')canceled=true;const current=steps.some(s=>s[0]===name)?name:['registreren','bevestigmail','inloggen','herstellen'].includes(name)?'aanmelden':name;
 document.getElementById('steps').innerHTML=steps.map(([id,label])=>`<a href="#${id}" ${id===current?'aria-current="step"':''}>${label}</a>`).join('');
 document.getElementById('screen').innerHTML=(views[name]||views.aanmelden)();
 if(name==='collegas'){
   const inputs=Array.from({length:quantity},(_,i)=>document.getElementById(`teacher-${i}`));
   inputs.forEach((input,i)=>{input.value=teacherEmails[i]||'';input.oninput=()=>{input.setCustomValidity('');teacherEmails[i]=input.value;};});
   document.getElementById('teachersForm').onsubmit=e=>{e.preventDefault();const seen=new Set();let count=0;
     for(const input of inputs){input.setCustomValidity('');const email=input.value.trim().toLowerCase();if(!email)continue;
       if(seen.has(email)){input.setCustomValidity('Dit e-mailadres staat al bij een andere leerkracht.');input.reportValidity();return;}seen.add(email);count++;}
     if(!count){document.getElementById('teacherError').textContent='Vul minstens één e-mailadres in om een uitnodiging te bekijken.';inputs[0].focus();return;}
     teacherEmails=inputs.map(input=>input.value.trim());location.hash='uitnodigingen';};
 }
 if(name==='uitnodigingen')document.querySelectorAll('[data-teacher]').forEach(b=>{b.onclick=()=>{selectedTeacher=teacherEmails[Number(b.dataset.teacher)];location.hash='uitnodiging';};});
 if(name==='school'){const q=document.getElementById('schoolQuantity');const update=()=>{document.getElementById('schoolTotal').textContent=q.checkValidity()?new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(Number(q.value)*399/100)+' per maand':'Kies 2 tot 100 leerkrachten.';};q.oninput=update;update();document.getElementById('schoolForm').onsubmit=e=>{e.preventDefault();if(!q.reportValidity())return;quantity=Number(q.value);teacherEmails=teacherEmails.slice(0,quantity);location.hash='gegevens';};}
 if(name==='gegevens'){document.getElementById('demoPeppol').onchange=e=>{peppol=e.target.checked;document.getElementById('demoPeppolFields').hidden=!peppol;};document.getElementById('demoConsent').onchange=e=>{document.getElementById('payNext').disabled=!e.target.checked;};document.getElementById('payNext').onclick=()=>{location.hash='betaling';};}
 window.scrollTo(0,0);
}
window.addEventListener('hashchange',render);render();
