
'use strict';
const $=id=>document.getElementById(id);const modes={silent:{label:'Stil werken',limit:45},whisper:{label:'Fluisteren',limit:57},together:{label:'Samenwerken',limit:70}};let mode='silent',running=false,demo=false,starting=false,stream=null,ctx=null,analyser=null,source=null,raf=0,buffer=null,smooth=0,last=0,over=0,under=0,state='idle',demoStart=0,lastBell=-Infinity,changedAt=0,animal=true,selectedView='animal',startGeneration=0;
function limits(){const yellow=modes[mode].limit;return{yellow,red:yellow+20}}
function track(){const {yellow,red}=limits();$('track').style.background=`linear-gradient(to right,#35a274 0%,#35a274 ${yellow}%,#edbd4d ${yellow}%,#edbd4d ${red}%,#e46560 ${red}%,#e46560 100%)`}
function show(next){if(state===next)return;state=next;$('trafficLight').dataset.mood=next;$('trafficLight').setAttribute('aria-label',({idle:'Stoplicht staat uit',green:'Groen: rustig',yellow:'Oranje: wat zachter',red:'Rood: te luid'})[next]);changedAt=performance.now();$('character').dataset.mood=next;$('character').setAttribute('aria-label',next==='red'?'Zebra is boos wakker':next==='yellow'?'Zebra opent slaperig de ogen':'Zebra slaapt');const content={idle:['Klaar voor de rust?','Zet de microfoon aan en laat de meter meeluisteren.','#19845d','#e6f5ec'],green:['Fijn, zo is het goed!',mode==='silent'?'We werken rustig verder.':mode==='whisper'?'We overleggen met een fluisterstem.':'We praten zacht met ons groepje.','#19845d','#e6f5ec'],yellow:['Een beetje zachter','Denk aan je stem. We houden het rustig.','#9c6b04','#fff2ca'],red:['Oei, het is te luid!','Even stil… en dan rustig verder.','#c3443e','#ffe8e5']};if(animal){content.idle[0]='Ssst… zebra slaapt';content.idle[1]='Zet de microfoon aan. Kunnen we zebra laten slapen?';content.green[0]='Zebra slaapt heerlijk';content.green[1]='Goed zo! We houden het rustig.';content.yellow[0]='Zebra wordt wakker…';content.yellow[1]='Wat zachter, zijn ogen gaan al open.';content.red[0]='Oei! Zebra is wakker!';content.red[1]='Even stil… dan kan hij weer slapen.'}if(selectedView==='light'){content.green[0]='Goed zo, het is rustig!';content.yellow[0]='Opgelet, dit kan rustiger!';content.red[0]='Maak het weer stil';content.green[1]=content.yellow[1]=content.red[1]=''}const c=content[next];$('headline').textContent=c[0];$('officerSpeech').textContent=selectedView==='light'?c[0]:'';$('subtitle').textContent=c[1];document.documentElement.style.setProperty('--signal',c[2]);document.documentElement.style.setProperty('--wash',c[3]);if(next==='red'&&!demo&&$('sound').checked)bell()}
function bell(){if(!ctx||ctx.state!=='running'||performance.now()-lastBell<10000)return;lastBell=performance.now();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=660;gain.gain.setValueAtTime(0,ctx.currentTime);gain.gain.linearRampToValueAtTime(.055,ctx.currentTime+.025);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.5)}
function characterFrame(){const index=state==='yellow'?2:state==='red'?5:0;$('sprite').style.backgroundPosition=(index%3)*50+'% '+Math.floor(index/3)*100+'%'}
function frame(now){if(!running&&!demo)return;const dt=Math.min(100,now-last||16);last=now;let value;if(demo){const t=((now-demoStart)/1000)%14;value=t<4?19:t<7?limits().yellow+9:t<11?97:19}else{analyser.getFloatTimeDomainData(buffer);let sum=0;for(const v of buffer)sum+=v*v;const db=20*Math.log10(Math.max(.000001,Math.sqrt(sum/buffer.length)));value=Math.max(0,Math.min(100,(db+75)/.6+(Number($('sensitivity').value)-50)*.65))}smooth+=(value-smooth)*(1-Math.exp(-dt/220));$('needle').style.left=smooth+'%';$('track').setAttribute('aria-valuenow',Math.round(smooth));document.querySelectorAll('.bars i').forEach((el,i)=>el.style.height=(20+smooth*(i===2?1:i===1||i===3?.72:.4))+'px');const {yellow,red}=limits();if(smooth>=red){over+=dt;under=0;if(over>=Number($('delay').value)*1000)show('red');else if(state!=='red')show('yellow')}else{over=0;if(state==='red'){under+=dt;if(under>1200)show(smooth>=yellow?'yellow':'green')}else if(smooth>=yellow)show('yellow');else if(smooth<yellow-3||state==='idle')show('green')}characterFrame(now);raf=requestAnimationFrame(frame)}
function error(message){$('error').textContent=message;$('error').hidden=false}
function stop(){startGeneration++;running=false;demo=false;cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(source)source.disconnect();source=null;if(ctx){ctx.close().catch(()=>{});ctx=null}analyser=null;over=under=smooth=last=0;show('idle');$('sprite').style.backgroundPosition='0% 0%';$('start').textContent='Microfoon aanzetten';$('demo').textContent='Uitproberen';$('connection').textContent='Microfoon staat uit';$('needle').style.left='0%';$('track').setAttribute('aria-valuenow','0');document.querySelectorAll('.bars i').forEach(el=>el.style.height='')}
$('start').onclick=async()=>{if(starting)return;if(running){stop();return}stop();$('error').hidden=true;if(!navigator.mediaDevices?.getUserMedia){error('Deze weergave biedt geen microfoontoegang. Gebruik de zelfstandige versie op je eigen beveiligde website in een browser. De demo en de timer werken ook zonder microfoon.');return}starting=true;const generation=startGeneration;const cancelled=()=>generation!==startGeneration||document.hidden;$('start').disabled=true;$('demo').disabled=true;$('connection').textContent='Wachten op toestemming…';try{const Audio=window.AudioContext||window.webkitAudioContext;const pendingCtx=new Audio();ctx=pendingCtx;await pendingCtx.resume();if(cancelled())return;const pendingStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(cancelled()){pendingStream.getTracks().forEach(t=>t.stop());if(pendingCtx.state!=='closed')await pendingCtx.close();return}stream=pendingStream;source=ctx.createMediaStreamSource(stream);analyser=ctx.createAnalyser();analyser.fftSize=2048;source.connect(analyser);buffer=new Float32Array(analyser.fftSize);running=true;$('start').textContent='Microfoon stoppen';$('connection').textContent='Microfoon luistert';stream.getAudioTracks()[0].onended=()=>{if(running){stop();error('De microfoon is gestopt. Zet hem opnieuw aan om verder te meten.')}};show('green');characterFrame(performance.now());raf=requestAnimationFrame(frame)}catch(e){stop();error(e.name==='NotAllowedError'?'Geen toegang tot de microfoon. Sta microfoongebruik toe via de site-instellingen van je browser en probeer opnieuw.':e.name==='NotFoundError'?'Geen microfoon gevonden. Sluit een microfoon aan of gebruik een laptop of tablet met microfoon.':'De microfoon kon niet starten. Controleer of hij beschikbaar is en probeer opnieuw.')}finally{starting=false;$('start').disabled=false;$('demo').disabled=false}};
$('demo').onclick=()=>{if(demo){stop();return}stop();$('error').hidden=true;demo=true;demoStart=performance.now();$('connection').textContent='Demo · geen echte meting';$('demo').textContent='Demo stoppen';show('green');characterFrame(performance.now());raf=requestAnimationFrame(frame)};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('modeTag').textContent=modes[mode].label;over=under=0;track();if(running||demo){state='';show('green')}});$('sensitivity').oninput=()=>{$('sensitivityValue').value=$('sensitivity').value+'%';over=0};$('delay').oninput=()=>{$('delayValue').value=$('delay').value+($('delay').value==='1'?' seconde':' seconden');over=0};$('focus').onclick=()=>{const focus=document.body.classList.toggle('focus');$('focus').textContent=focus?'Instellingen tonen':'Bordweergave';$('focus').setAttribute('aria-pressed',String(focus))};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('focus'))$('focus').click()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&timerState==='running'){pauseTimer();$('timerCaption').textContent='Gepauzeerd · scherm was niet actief'}if(document.hidden&&(running||demo||starting)){stop();error('De meting is gepauzeerd omdat het scherm niet meer actief was. Zet de microfoon opnieuw aan.')}});window.addEventListener('pagehide',stop);function view(choice){selectedView=choice;animal=choice==='animal';$('scene').hidden=!animal;$('character').hidden=!animal;$('orb').hidden=choice!=='meter';$('trafficLight').hidden=choice!=='light';for(const name of ['animal','meter','light'])$(name+'View').setAttribute('aria-pressed',String(name===choice));const previous=state;state='';show(previous)}$('animalView').onclick=()=>view('animal');$('meterView').onclick=()=>view('meter');$('lightView').onclick=()=>view('light');track();state='';show('idle');

let timerState='ready',timerTotal=600000,timerRemaining=600000,timerDeadline=0,timerTick=null,alarmCtx=null,alarmNodes=[];
function renderTimer(){const seconds=Math.max(0,Math.ceil(timerRemaining/1000));$('timeDigits').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('timeFill').style.width=Math.max(0,Math.min(100,100*timerRemaining/timerTotal))+'%';$('timerStart').textContent=timerState==='running'?'Pauzeren':timerState==='paused'?'Verder':timerState==='done'?'Nog een keer':'Start timer';$('minutes').disabled=timerState==='running'||timerState==='paused';document.querySelectorAll('[data-minutes]').forEach(b=>b.disabled=$('minutes').disabled);$('timerBox').classList.toggle('done',timerState==='done')}
function stopSignal(){for(const node of alarmNodes){try{node.stop()}catch(e){}}alarmNodes=[]}
async function prepareSignal(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error();if(!alarmCtx||alarmCtx.state==='closed')alarmCtx=new Audio();await alarmCtx.resume();if(alarmCtx.state!=='running')throw new Error();return true}catch(e){$('timerMessage').textContent='Het geluid kon niet starten. De timer geeft wel een zichtbare eindmelding. Probeer de knop voor het eindsignaal.';return false}}
function endSignal(){if(!alarmCtx||alarmCtx.state!=='running')return;stopSignal();const start=alarmCtx.currentTime;[660,880,1046,880,660,880,1046,1320].forEach((hz,i)=>{const o=alarmCtx.createOscillator(),g=alarmCtx.createGain(),t=start+i*.43;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.17,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.65);o.connect(g);g.connect(alarmCtx.destination);o.start(t);o.stop(t+.7);alarmNodes.push(o)})}
function finishTimer(){clearInterval(timerTick);timerTick=null;timerRemaining=0;timerState='done';stop();$('timerCaption').textContent='Klaar! De werktijd is voorbij.';renderTimer();if($('timerSound').checked)endSignal()}
function tickTimer(){if(timerState!=='running')return;timerRemaining=Math.max(0,timerDeadline-Date.now());if(timerRemaining<=0)finishTimer();else renderTimer()}
function pauseTimer(){if(timerState!=='running')return;timerRemaining=Math.max(0,timerDeadline-Date.now());if(timerRemaining===0){finishTimer();return}timerState='paused';clearInterval(timerTick);timerTick=null;$('timerCaption').textContent='Even pauze';renderTimer()}
function resetTimer(){clearInterval(timerTick);timerTick=null;stopSignal();const raw=Number($('minutes').value);const minutes=Number.isFinite(raw)?Math.max(1,Math.min(120,Math.round(raw))):10;$('minutes').value=String(minutes);timerTotal=minutes*60000;timerRemaining=timerTotal;timerState='ready';$('timerCaption').textContent='Tijd om rustig te werken';renderTimer()}
$('timerEnabled').onchange=()=>{const enabled=$('timerEnabled').checked;$('timerBox').hidden=!enabled;$('timerSettings').hidden=!enabled;resetTimer()};$('minutes').onchange=resetTimer;document.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{$('minutes').value=b.dataset.minutes;resetTimer()});$('timerReset').onclick=resetTimer;$('timerStart').onclick=()=>{if(timerState==='running'){pauseTimer();return}if(timerState==='done')resetTimer();if($('timerSound').checked)prepareSignal();stopSignal();timerDeadline=Date.now()+timerRemaining;timerState='running';$('timerCaption').textContent='Nog even rustig werken…';timerTick=setInterval(tickTimer,200);renderTimer()};$('testSignal').onclick=async()=>{if(await prepareSignal())endSignal()};window.addEventListener('pagehide',()=>{if(timerState==='running')pauseTimer();stopSignal();if(alarmCtx)alarmCtx.close().catch(()=>{})});renderTimer();

$('timerSound').onchange=()=>{if(!$('timerSound').checked)stopSignal();else prepareSignal()};
