'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Pencil,Plus,Printer,Monitor,Download,RefreshCw,Copy,LockKeyhole,ArrowLeft,ImageIcon,Check,SquareArrowOutUpRight} from 'lucide-react';
import QRCode from 'qrcode';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
type Lesson={id:string;code:string;title:string;open:number;total:number;created_at?:number};
type Work={id:string;name:string;created_at:number};
async function api<T=Record<string,unknown>>(path:string,options?:RequestInit){const r=await fetch('/api/atelier/'+path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||'Het laden lukt niet.');return data;}
export default function Teacher(){
 const [lessons,setLessons]=useState<Lesson[]>([]),[current,setCurrent]=useState(''),[works,setWorks]=useState<Work[]>([]),[selected,setSelected]=useState<string[]>([]);
 const [error,setError]=useState(''),[status,setStatus]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[showNew,setShowNew]=useState(false),[title,setTitle]=useState(''),[qr,setQr]=useState(''),[link,setLink]=useState(''),[showCode,setShowCode]=useState(false),[preview,setPreview]=useState<Work|null>(null),[printWorks,setPrintWorks]=useState<Work[]>([]),[printing,setPrinting]=useState(false),[demo,setDemo]=useState(false);
 const currentRef=useRef(current),printRef=useRef<HTMLDivElement>(null);currentRef.current=current;const lesson=lessons.find(l=>l.id===current);
 const loadLessons=useCallback(async()=>{const data=await api<{lessons:Lesson[]}>('lessons');setLessons(data.lessons);setCurrent(old=>old&&data.lessons.some((l:Lesson)=>l.id===old)?old:data.lessons[0]?.id||'');setLoaded(true);},[]);
 useEffect(()=>{loadLessons().catch(e=>{setError(e.message);setLoaded(true);});},[loadLessons]);
 const loadWorks=useCallback(async(id:string)=>{const data=await api<{works:Work[]}>(`lessons/${id}/works`);if(currentRef.current===id){setWorks(data.works);setLessons(prev=>prev.map(l=>l.id===id?{...l,total:data.works.length}:l));setError('');}},[]);
 useEffect(()=>{setSelected([]);setWorks([]);if(!current)return;let alive=true;const refresh=()=>{if(!document.hidden&&alive)loadWorks(current).catch(e=>{if(alive)setError(e.message);});};refresh();const timer=setInterval(refresh,6000);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[current,loadWorks]);
 useEffect(()=>{let alive=true;setQr('');if(!lesson){setLink('');return;}const url=new URL('/atelier.html',location.origin);url.searchParams.set('klas',lesson.code);setLink(url.href);QRCode.toDataURL(url.href,{width:320,margin:4,errorCorrectionLevel:'M',color:{dark:'#102923',light:'#ffffff'}}).then(data=>{if(alive)setQr(data);}).catch(()=>{if(alive)setStatus('Gebruik de klascode of de leerlinglink.');});return()=>{alive=false;};},[lesson?.code]);
 async function createLesson(e:React.FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);setError('');try{const created=await api<Lesson>('lessons',{method:'POST',body:JSON.stringify({title})});await loadLessons();setCurrent(created.id);setTitle('');setShowNew(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function toggle(){if(!lesson)return;setBusy(true);try{await api('lessons/'+lesson.id,{method:'PATCH',body:JSON.stringify({open:!lesson.open})});await loadLessons();setStatus(lesson.open?'De les is gesloten. De werkjes blijven bewaard.':'De leerlingen kunnen weer insturen.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(link);setStatus('Leerlinglink gekopieerd.');}catch{setShowCode(true);setStatus('Selecteer en kopieer de leerlinglink.');}}
 async function print(list:Work[]){if(!list.length)return;setPrinting(true);setPrintWorks(list);setError('');try{await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));const images=Array.from(printRef.current?.querySelectorAll('img')||[]);await Promise.all(images.map(img=>img.decode()));window.print();}catch{setError('Niet alle afbeeldingen konden laden. Probeer opnieuw af te drukken.');}finally{setPrinting(false);}}
 function select(id:string){setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);}
 const chosen=selected.length?works.filter(w=>selected.includes(w.id)):works;
 return <><div className={'teacher-app'+(demo?' demo-mode':'')}>
 <header className="teacher-header"><a className="brand" href="/"><span><Pencil/></span><div><strong>Digitale missies</strong><small>Leerkracht</small></div></a><div className="header-actions"><a className="secondary" href="/kijken">▶ Filmpjes bedienen</a><button onClick={()=>setDemo(!demo)} className={demo?'primary':'secondary'}>{demo?<ArrowLeft size={19}/>:<Monitor size={19}/>} {demo?'Naar de werkjes':'Voordoen op het bord'}</button><a href="/doelen" className="secondary">Leerplandoelen per missie</a></div></header>
 {demo?<section className="demo"><iframe src="/atelier.html?voordoen=1" title="Tekenatelier om voor te doen op het smartboard" allow="clipboard-write; web-share"/><p>Dit is hetzelfde tekenatelier als op de iPads. De werkjes blijven op de achtergrond binnenkomen.</p></section>:<main className="teacher-main">
 <div className="intro"><div><div className="eyebrow">JOUW KLASATELIER</div><h1>De werkjes van je klas</h1><p>Start een les, deel de code en ontvang de tekeningen.</p></div><button className="primary" onClick={()=>{setError('');setShowNew(true);}}><Plus size={20}/> Nieuwe les</button></div>
 {error&&<div className="error" role="alert">{error} <button onClick={()=>{setError('');loadLessons().then(()=>{if(current)return loadWorks(current);}).catch(e=>setError(e.message));}}>Opnieuw proberen</button>{error.includes('Meld je')&&<a href="/">Terug naar de spelletjesmaker</a>}</div>}
 {status&&<div className="notice" role="status">{status}<button onClick={()=>setStatus('')} aria-label="Melding sluiten">×</button></div>}
 {!loaded?<p className="empty">Je lessen worden geladen…</p>:!lesson?<section className="first-lesson"><div className="empty-icon"><ImageIcon size={36}/></div><h2>Klaar voor de eerste tekening?</h2><p>Maak een les aan, bijvoorbeeld ‘Mijn fantasiedier’.<br/>De kinderen scannen de QR-code en sturen hun werkje naar jou.</p><button className="primary" onClick={()=>setShowNew(true)}><Plus size={20}/> Start je eerste les</button></section>:<>
 <section className="lesson-bar"><div className="lesson-choice"><label id="lesson-label">Les</label><Select value={current} onValueChange={setCurrent}><SelectTrigger className="lesson-select" aria-labelledby="lesson-label"><SelectValue/></SelectTrigger><SelectContent>{lessons.map(l=><SelectItem key={l.id} value={l.id}>{l.title} · {l.total} werkjes{l.open?'':' · gesloten'}</SelectItem>)}</SelectContent></Select></div><span className={'lesson-state '+(lesson.open?'open':'')}>{lesson.open?'Ontvangt werkjes':'Gesloten'}</span><button className="text-button" onClick={toggle} disabled={busy}><LockKeyhole size={17}/>{lesson.open?'Les sluiten':'Les weer openen'}</button></section>
 <div className="class-layout"><aside className="join-card"><div className="eyebrow">VOOR DE LEERLINGEN</div><h2>Scan en teken</h2>{qr?<button className="qr-button" onClick={()=>setShowCode(true)} aria-label="QR-code groot tonen"><img src={qr} alt="QR-code voor deze les" width="220" height="220"/></button>:<p>De klascode staat hieronder.</p>}<span className="code-label">Klascode</span><button className="class-code" onClick={()=>setShowCode(true)}>{lesson.code}</button><p>De kinderen vullen bij het versturen hun voornaam in.</p><button className="secondary" onClick={()=>setShowCode(true)}><Monitor size={17}/> Groot op het bord</button><button className="text-button" onClick={copy}><Copy size={17}/> Leerlinglink kopiëren</button><a className="secondary" href={'/ontdekken?missie=bestanden&klas='+lesson.code} target="_blank" rel="noopener">Naamkaartje maken met deze klascode</a></aside>
 <section className="inbox"><div className="inbox-heading"><div><h2>Ontvangen <span>{works.length}</span></h2><p>Nieuwe werkjes verschijnen automatisch.</p></div><button className="secondary" onClick={()=>print(chosen)} disabled={!works.length||printing}><Printer size={18}/>{printing?'Laden…':selected.length?`Druk ${selected.length} af`:'Druk alles af'}</button></div>
 {works.length>0&&<div className="select-row"><label><Checkbox checked={selected.length===works.length} onCheckedChange={v=>setSelected(v?works.map(w=>w.id):[])} aria-label="Alle werkjes selecteren"/> Alles selecteren</label><span>A4 liggend · één werkje per blad</span></div>}
 {!works.length?<div className="waiting"><ImageIcon size={38}/><h3>Hier komen de werkjes</h3><p>Laat de kinderen een tekening of naamkaartje maken en naar de juf sturen.</p><button className="text-button" onClick={()=>loadWorks(current).catch(e=>setError(e.message))}><RefreshCw size={16}/> Nu controleren</button></div>:<div className="work-grid">{works.map(w=><article className={'work-card'+(selected.includes(w.id)?' selected':'')} key={w.id}><div className="work-picture"><button onClick={()=>setPreview(w)} aria-label={`Bekijk het werkje van ${w.name}`}><img src={'/api/atelier/works/'+w.id} alt={'Tekening van '+w.name} loading="lazy"/></button><label className="work-select"><Checkbox checked={selected.includes(w.id)} onCheckedChange={()=>select(w.id)} aria-label={'Selecteer '+w.name}/></label></div><div className="work-caption"><div><h3>{w.name}</h3><span>{new Date(w.created_at).toLocaleTimeString('nl-BE',{hour:'2-digit',minute:'2-digit'})}</span></div><button onClick={()=>print([w])} aria-label={'Druk het werkje van '+w.name+' af'} disabled={printing}><Printer size={19}/></button></div></article>)}</div>}
 </section></div></>}
 </main>}
 </div>
 <Dialog open={showNew} onOpenChange={v=>{if(!busy)setShowNew(v);}}><DialogContent className="atelier-modal"><DialogTitle>Een nieuwe les</DialogTitle><DialogDescription>Elk lesmoment krijgt een eigen klascode en verzameling werkjes.</DialogDescription><form onSubmit={createLesson}><label htmlFor="lesson-title">Naam van de les</label><input id="lesson-title" placeholder="Bijvoorbeeld: mijn fantasiedier" value={title} maxLength={80} onChange={e=>setTitle(e.target.value)} required autoFocus/>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Even wachten…':'Les starten'}</button></form></DialogContent></Dialog>
 <Dialog open={showCode} onOpenChange={setShowCode}><DialogContent className="atelier-modal code-modal"><DialogTitle>{lesson?.title}</DialogTitle><DialogDescription>Scan met je iPad. Teken, typ en stuur je werkje naar de juf.</DialogDescription>{qr&&<img src={qr} width="320" height="320" alt="Scan deze QR-code met je iPad"/>}<div className="big-code">{lesson?.code}</div><label htmlFor="pupil-link">Leerlinglink</label><input id="pupil-link" value={link} readOnly onFocus={e=>e.target.select()}/><div className="modal-actions"><button className="secondary" onClick={copy}><Copy size={17}/> Kopieer link</button><a className="primary" href={link} target="_blank" rel="noreferrer"><SquareArrowOutUpRight size={17}/> Open leerlingversie</a></div></DialogContent></Dialog>
 <Dialog open={!!preview} onOpenChange={v=>{if(!v)setPreview(null);}}><DialogContent className="atelier-modal preview-modal"><DialogTitle>{preview?.name}</DialogTitle><DialogDescription>{lesson?.title}</DialogDescription>{preview&&<><img className="preview-picture" src={'/api/atelier/works/'+preview.id} alt={'Tekening van '+preview.name}/><div className="modal-actions"><a className="secondary" href={'/api/atelier/works/'+preview.id} download={'tekening-'+preview.name+'.png'}><Download size={18}/> Bewaren</a><button className="primary" onClick={()=>{setPreview(null);print([preview]);}} disabled={printing}><Printer size={18}/> Afdrukken</button></div></>}</DialogContent></Dialog>
 <div className="print-area" ref={printRef}>{printWorks.map(w=><section className="print-page" key={w.id}><div><strong>{w.name}</strong><span>{lesson?.title}</span></div><img src={'/api/atelier/works/'+w.id} alt={'Werkje van '+w.name}/></section>)}</div>
 </>;
}
