'use client';
import {useState,useEffect,useRef,useReducer} from 'react';
import {Play,Pause,Square,Volume2,Volume1,Check,ArrowLeft,ArrowRight,RotateCcw,Scissors,BookOpen,QrCode,ExternalLink,RefreshCw,Cone,Layers2,Plane,Fish,UserRound,Cat,Footprints} from 'lucide-react';
import QRCode from 'qrcode';
import Listen from '@/components/listen';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {watchLessons} from './lessons';
import {watchReducer,initialWatchState} from './watch-state';
type Player={playVideo:()=>void;pauseVideo:()=>void;cueVideoById:(o:{videoId:string;startSeconds:number})=>void;seekTo:(n:number,b:boolean)=>void;getCurrentTime:()=>number;getDuration:()=>number;getPlayerState:()=>number;unMute:()=>void;isMuted:()=>boolean;destroy:()=>void;getIframe:()=>HTMLIFrameElement};
type YTAPI={Player:new(el:HTMLElement,options:Record<string,unknown>)=>Player};
declare global{interface Window{YT?:YTAPI;onYouTubeIframeAPIReady?:()=>void;}}
let ytPromise:Promise<YTAPI>|null=null;
function youtube(){if(window.YT?.Player)return Promise.resolve(window.YT);if(ytPromise)return ytPromise;ytPromise=new Promise<YTAPI>((resolve,reject)=>{const script=document.createElement('script');let done=false;const fail=()=>{if(done)return;done=true;script.remove();ytPromise=null;reject(new Error('YouTube laadt niet. Vraag je juf of meester om de verbinding te controleren.'));};const timer=setTimeout(fail,20000);window.onYouTubeIframeAPIReady=()=>{if(done)return;done=true;clearTimeout(timer);if(window.YT)resolve(window.YT);else{ytPromise=null;reject(new Error('De speler kon niet laden.'));}};script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{clearTimeout(timer);fail();};document.head.appendChild(script);});return ytPromise;}
const lessonIcons=[Cone,Layers2,Plane,Fish,UserRound,Cat,Footprints];
const time=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export default function Watch(){
 const [lessonId,setLessonId]=useState('hoedje'),[loaded,setLoaded]=useState(false),[ready,setReady]=useState(false),[playerState,setPlayerState]=useState(-1),[duration,setDuration]=useState(0),[position,setPosition]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState(''),[attempt,setAttempt]=useState(0);
 const [choosing,setChoosing]=useState(false);
 const [tips,setTips]=useState(false),[share,setShare]=useState(false),[qr,setQr]=useState(''),[link,setLink]=useState('');
 const [progress,dispatch]=useReducer(watchReducer,initialWatchState);
 const player=useRef<Player|null>(null),host=useRef<HTMLDivElement>(null),progressRef=useRef(progress),stopPending=useRef(false),played=useRef(false),currentLesson=useRef(lessonId);progressRef.current=progress;currentLesson.current=lessonId;
 const lesson=watchLessons.find(x=>x.id===lessonId)??watchLessons[0];const task=lesson.tasks[Math.min(progress.task,2)];
 useEffect(()=>{const id=new URLSearchParams(location.search).get('les');if(watchLessons.some(x=>x.id===id))setLessonId(id!);},[]);
 useEffect(()=>{let alive=true;const u=new URL('/kijken',location.origin);u.searchParams.set('les',lessonId);setLink(u.href);setQr('');QRCode.toDataURL(u.href,{width:320,margin:4,errorCorrectionLevel:'M'}).then(v=>{if(alive)setQr(v);}).catch(()=>{});return()=>{alive=false;};},[lessonId]);
 useEffect(()=>{if(!loaded)return;let alive=true;setReady(false);setError('');let timeout:ReturnType<typeof setTimeout>|undefined;youtube().then(api=>{if(!alive||!host.current)return;host.current.replaceChildren();const target=document.createElement('div');host.current.appendChild(target);player.current=new api.Player(target,{host:'https://www.youtube-nocookie.com',width:'100%',height:'100%',videoId:lesson.videoId,playerVars:{playsinline:1,controls:1,rel:0,autoplay:0,origin:location.origin,hl:'nl'},events:{onReady:()=>{if(!alive)return;clearTimeout(timeout);setReady(true);setError('');setMessage('Druk op Afspelen om te beginnen.');try{player.current?.getIframe().setAttribute('title',lesson.title+' — '+lesson.author);}catch{}},onStateChange:(e:{data:number})=>{if(!alive)return;setPlayerState(e.data);if(e.data===1){played.current=true;setMessage('');dispatch({type:'PLAY'});}if(e.data===2&&played.current&&!stopPending.current){dispatch({type:'PAUSE'});}if(e.data===0){setMessage('Het filmpje is afgelopen. Nog een opdracht te doen? Ga 10 seconden terug, speel verder en druk zelf op Pauze.');}if(stopPending.current&&(e.data===5||e.data===2)){const t=player.current?.getCurrentTime()??0;if(t<1){stopPending.current=false;setPosition(0);dispatch({type:'STOP'});setMessage('Gestopt. Het filmpje staat weer aan het begin.');}}},onAutoplayBlocked:()=>{if(alive)setMessage('Tik op de afspeelknop in het filmpje om te starten.');},onError:()=>{if(alive){setReady(false);setError('Dit filmpje kan hier niet worden afgespeeld. Vraag je juf of meester om een ander filmpje te kiezen of het bij de maker te openen.');}}}});timeout=setTimeout(()=>{if(alive)setError('Het laden duurt lang. Controleer de verbinding of probeer opnieuw.');},20000);}).catch(e=>{if(alive)setError(e.message);});
 const timer=setInterval(()=>{const p=player.current;if(!alive||!p)return;try{const t=p.getCurrentTime()||0,d=p.getDuration()||0;setPosition(t);setDuration(d);if(stopPending.current&&t<1&&[2,5,-1].includes(p.getPlayerState())){stopPending.current=false;dispatch({type:'STOP'});setMessage('Gestopt. Het filmpje staat weer aan het begin.');}}catch{}},500);
 return()=>{alive=false;clearInterval(timer);clearTimeout(timeout);try{player.current?.destroy();}catch{}player.current=null;};
 },[loaded,lessonId,attempt,lesson.videoId,lesson.title,lesson.author]);
 function reset(id=lessonId){try{player.current?.pauseVideo?.();}catch{}setLoaded(false);setReady(false);setPlayerState(-1);setPosition(0);setDuration(0);setError('');setMessage('');stopPending.current=false;played.current=false;dispatch({type:'RESET'});setLessonId(id);const u=new URL(location.href);u.searchParams.set('les',id);history.replaceState(null,'',u);}
 function play(){if(!ready||!player.current)return;stopPending.current=false;player.current.unMute();player.current.playVideo();const requested=player.current;setTimeout(()=>{if(player.current===requested&&requested.getPlayerState()!==1){setMessage('Start het beeld nog niet? Tik op de afspeelknop in het filmpje. Blijft het laden? Vraag je juf of meester om de verbinding te controleren.');}},6000);}
 function pause(){if(!ready||!player.current)return;player.current.pauseVideo();}
 function stop(){if(!ready||!player.current)return;stopPending.current=true;played.current=false;player.current.cueVideoById({videoId:lesson.videoId,startSeconds:0});setMessage('Terug naar het begin…');}
 function back(){if(!player.current)return;player.current.seekTo(Math.max(0,position-10),true);setMessage('Tien seconden terug. Kijk de stap nog eens.');}
 function done(){if(playerState!==2&&playerState!==0)return;played.current=false;dispatch({type:'TASK_DONE'});}
 async function copy(){try{await navigator.clipboard.writeText(link);setMessage('De leerlinglink is gekopieerd.');}catch{setShare(true);setMessage('Selecteer de leerlinglink om ze te kopiëren.');}}
 const paused=playerState===2||playerState===0;const working=progress.phase==='watch'||progress.phase==='do';
 const n=progress.phase==='start'||progress.phase==='listen'?1:working||progress.phase==='resume'?2+progress.task:progress.phase==='quieter'?5:6;
 const finishedLabel=lessonId==='veters'?'Ik heb geoefend':'Mijn werkje is klaar';
 const spokenTask=progress.phase==='start'||progress.phase==='listen'?'Hoor je het? Druk op Afspelen. Geen geluid? Zet het geluid met de knoppen op je iPad een beetje harder. Zacht genoeg voor jezelf, niet te luid voor de klas.':progress.phase==='watch'?task.look+' Druk zelf op Pauze. Jij kiest wanneer je tijd nodig hebt.':progress.phase==='do'?'Nu ben jij aan de beurt. '+task.do+' Neem je tijd. Het filmpje wacht.':progress.phase==='resume'?'Kijk weer verder. Druk op Afspelen. Het filmpje gaat verder waar je het stilzette.':progress.phase==='quieter'?'Een beetje zachter. Druk op Afspelen om het geluid te horen. Maak het met de knoppen op je iPad een beetje zachter. Kun je het nog horen?':progress.phase==='stop'?'We zijn klaar. Druk nu op Stop. Het filmpje stopt en gaat terug naar het begin. Pauze bewaart je plaats. Stop begint weer vooraan.':'Goed gedaan! Je hebt gekeken, gepauzeerd, verder gespeeld en gestopt. Laat aan de juf of meester zien wat je hebt gedaan.';
 return <div className="watch-app"><header className="watch-header"><a href="/" className="watch-brand"><span><Play fill="currentColor"/></span><div><strong>Filmpjes bedienen</strong><small>Zisa’s digitale missies</small></div></a><nav><a href="/"><ArrowLeft size={22}/> Missies</a><button onClick={()=>setTips(true)}><BookOpen size={18}/> Voor de leerkracht</button></nav></header>
 <main className="watch-main"><div className="watch-title"><div><span className="watch-eyebrow">KIJKEN · PAUZEREN · ZELF DOEN</span><h1>{lesson.title}</h1></div><div className="lesson-picker"><button className="qr-small" onClick={()=>setShare(true)} aria-label="QR-code voor dit filmpje"><QrCode size={24}/></button></div></div>
 <details className="watch-choices" open={choosing} onToggle={e=>setChoosing(e.currentTarget.open)}><summary>Kies een ander filmpje</summary><div className="watch-choice-grid">{watchLessons.map((l,i)=>{const Icon=lessonIcons[i]??Scissors;return <div className={'watch-choice'+(lessonId===l.id?' selected':'')} key={l.id}><button className="watch-choice-button" aria-pressed={lessonId===l.id} onClick={()=>{if(l.id!==lessonId)reset(l.id);setChoosing(false);}}><Icon size={34} aria-hidden="true"/><strong>{l.title}</strong><span>{l.tag}</span>{lessonId===l.id&&<Check className="choice-check" size={20} aria-hidden="true"/>}</button><Listen text={l.title+'. Dit leg je klaar: '+l.materials} label={'Luister: '+l.title}/></div>;})}</div></details>
 <div className="watch-layout"><section className="screen-column" aria-label="Filmpje en knoppen"><div className="video-stage">{!loaded?<div className="video-start"><div className="video-start-icon"><Play size={40} fill="currentColor"/></div><h2>Klaar om mee te doen?</h2><p>Leg je spullen klaar. Jij bedient het filmpje.</p><button className="primary" onClick={()=>setLoaded(true)}>Filmpje laden <ArrowRight size={18}/></button><small>Filmpje van {lesson.author} · via YouTube</small></div>:<div className="youtube-host" ref={host}/>}</div>
 <div className="playback-row"><span>{!loaded?'Nog niet geladen':!ready?'Speler laden…':playerState===1?'Het filmpje speelt':playerState===3?'Het filmpje wordt geladen…':playerState===2?'Op pauze':playerState===0?'Afgelopen':'Klaar om te kijken'}</span><span className="video-time">{time(position)} / {duration?time(duration):'–:––'}</span></div>
 <div className="video-controls"><button className={'video-control play-control'+(['start','listen','resume'].includes(progress.phase)?' suggested':'')} onClick={play} disabled={!ready||playerState===1}><Play fill="currentColor" size={27}/><strong>Afspelen</strong><small>▶ Play</small></button><button className={'video-control pause-control'+(progress.phase==='watch'?' suggested':'')} onClick={pause} disabled={!ready||playerState!==1}><Pause fill="currentColor" size={27}/><strong>Pauze</strong><small>Even stilzetten</small></button><button className={'video-control stop-control'+(progress.phase==='stop'?' suggested':'')} onClick={stop} disabled={!ready}><Square fill="currentColor" size={24}/><strong>Stop</strong><small>Terug naar het begin</small></button></div>
 <div className="under-controls"><button onClick={back} disabled={!ready||position<1}><RotateCcw size={17}/> 10 seconden terug</button><span>De geluidsknoppen zitten op je iPad.</span></div>
 {message&&<p className="watch-message" role="status">{message}</p>}{error&&<div className="watch-error" role="alert"><p>{error}</p><div><button onClick={()=>{setError('');setAttempt(n=>n+1);}}><RefreshCw size={16}/> Opnieuw proberen</button><a href={'https://www.youtube.com/watch?v='+lesson.videoId} target="_blank" rel="noopener noreferrer">Open bij de maker <ExternalLink size={16}/></a></div></div>}
 <div className="materials"><Scissors size={19}/><p><strong>Dit leg je klaar</strong><br/>{lesson.materials}</p></div><p className="credit">Video: <a href={lesson.sourceUrl} target="_blank" rel="noopener noreferrer">{lesson.author}</a> · Opdrachten: juf Zisa</p></section>
 <aside className={'mission-card phase-'+progress.phase} aria-label="Jouw opdracht"><div className="mission-top"><span>JOUW OPDRACHT</span><span>{progress.phase==='complete'?'Klaar!':`${n} / 6`}</span></div><Listen text={spokenTask} label="Luister naar de opdracht"/><div className="step-dots" aria-label={`Stap ${n} van 6`}>{Array.from({length:6},(_,i)=><span key={i} className={i<n-1||progress.phase==='complete'?'done':i===n-1?'active':''}/>)}</div>
 {(progress.phase==='start'||progress.phase==='listen')&&<><div className="mission-icon"><Volume2 size={35}/></div><h2>Hoor je het?</h2><p>Druk op <b>Afspelen</b>.</p><p>Geen geluid? Zet het geluid met de knoppen op je iPad een beetje harder.</p><p className="mission-note">Zacht genoeg voor jezelf, niet te luid voor de klas.</p><button className="primary" disabled={playerState!==1} onClick={()=>dispatch({type:'HEARD'})}><Check size={18}/> Ik hoor het</button><Listen text="Ik hoor het" label="Luister naar het antwoord: Ik hoor het"/></>}
 {progress.phase==='watch'&&<><div className="mission-icon"><Pause size={35}/></div><h2>{['De eerste stap','De volgende stap','Maak het af'][progress.task]}</h2><p>{task.look}</p><div className="pause-hint"><Pause size={21}/> Druk zelf op Pauze.</div><p className="mission-note">Jij kiest wanneer je tijd nodig hebt.</p></>}
 {progress.phase==='do'&&<><div className="mission-icon"><Scissors size={35}/></div><h2>Nu ben jij aan de beurt</h2><p>{task.do}</p><p className="mission-note">Neem je tijd. Het filmpje wacht.</p><button className="primary" onClick={done} disabled={!paused}><Check size={18}/> {progress.task===2?finishedLabel:'Deze stap is klaar'}</button><Listen text={progress.task===2?finishedLabel:'Deze stap is klaar'} label="Luister naar het antwoord"/>{progress.task===2&&<p className="mission-note">Nog niet klaar? Druk op Afspelen en kijk verder.</p>}</>}
 {progress.phase==='resume'&&<><div className="mission-icon"><Play size={35} fill="currentColor"/></div><h2>Kijk weer verder</h2><p>Druk op <b>Afspelen</b>.</p><p>Het filmpje gaat verder waar je het stilzette.</p><p className="mission-note">Volgende opdracht: {progress.task===1?'de volgende stap nadoen.':'je werkje afmaken.'}</p></>}
 {progress.phase==='quieter'&&<><div className="mission-icon"><Volume1 size={35}/></div><h2>Een beetje zachter</h2><p>Druk op <b>Afspelen</b> om het geluid te horen.</p><p>Maak het met de knoppen op je iPad een beetje zachter. Kun je het nog horen?</p><button className="primary" disabled={playerState!==1} onClick={()=>dispatch({type:'QUIETER'})}><Check size={18}/> Het staat zachter</button><Listen text="Het staat zachter" label="Luister naar het antwoord: Het staat zachter"/></>}
 {progress.phase==='stop'&&<><div className="mission-icon"><Square size={32} fill="currentColor"/></div><h2>We zijn klaar</h2><p>Druk nu op <b>Stop</b>.</p><p>Het filmpje stopt en gaat terug naar het begin.</p><p className="mission-note">Pauze bewaart je plaats. Stop begint weer vooraan.</p></>}
 {progress.phase==='complete'&&<><div className="mission-icon complete-icon"><Check size={40}/></div><h2>Goed gedaan!</h2><p>Je hebt gekeken, gepauzeerd, verder gespeeld en gestopt.</p><ul className="success-list"><li><Check size={17}/> Drie doe-opdrachten afgerond</li><li><Check size={17}/> Zelf op pauze gezet</li><li><Check size={17}/> Geluid geoefend op de iPad</li></ul><p>Laat aan de juf of meester zien wat je hebt gedaan.</p><button className="secondary" onClick={()=>reset()}><RotateCcw size={18}/> Nog eens oefenen</button></>}
 </aside></div></main>
 <Dialog open={tips} onOpenChange={setTips}><DialogContent className="atelier-modal watch-tips"><DialogTitle>Filmpjes bedienen in de klas</DialogTitle><DialogDescription>Voor 7- en 8-jarigen: oefenen met echte mediaknoppen terwijl ze iets maken.</DialogDescription><ol><li><b>Kies een filmpje en kijk het vooraf.</b> Er zijn drie vouwactiviteiten, drie tekenactiviteiten en een oefening veters strikken. De maker staat telkens bij het filmpje. De kinderen tekenen op papier; bij het strikken oefenen ze met hun eigen schoen. Laat kinderen zelf bepalen wanneer een stap is getoond en ze willen pauzeren.</li><li><b>Zet het mediavolume op nul.</b> De kinderen starten, maken het hoorbaar en zetten het later weer zachter. Dat oefenen gebeurt met de fysieke iPad-knoppen.</li><li><b>Deel de QR-code.</b> Die opent meteen het gekozen filmpje en de opdrachten.</li><li><b>Observeer het gebruik.</b> De tool volgt afspelen, pauze en stop. De geluidsopdrachten bevestigt het kind zelf; de tool kan de fysieke volumeknoppen niet controleren.</li></ol><p>Leg voor het vouwen het papier klaar, voor het tekenen een blad en potloden, en voor het strikken een schoen met veters. Bij veters strikken telt het oefenen: een perfecte strik is geen voorwaarde om de mediaknoppen te oefenen. Laat het kind dezelfde methode gebruiken als het al leert. Er worden in deze kijktool geen antwoorden of leerlingresultaten opgeslagen.</p><div className="source-links"><h3>Meer geschikte bronnen</h3><a href="https://meestersander.nl/instructievideo/" target="_blank" rel="noopener noreferrer">Meester Sander · korte vouwinstructies <ExternalLink size={16}/></a><a href="https://schooltv.nl/thema/knutselen" target="_blank" rel="noopener noreferrer">Schooltv · knutselen en Hoppatee! <ExternalLink size={16}/></a><a href="https://www.zappelin.nl/fenna/diy/knutselen" target="_blank" rel="noopener noreferrer">Zappelin · eenvoudige knutsels <ExternalLink size={16}/></a></div><p className="source-note">Kies een kort filmpje met duidelijke stappen, weinig materiaal en eenvoudig taalgebruik. Controleer of het op de school-iPad afspeelt. YouTube kan reclame tonen; deze tool kan die niet uitschakelen.</p><a className="text-button" href="/leerkracht">Naar je leerkrachtenscherm <ArrowRight size={17}/></a></DialogContent></Dialog>
 <Dialog open={share} onOpenChange={setShare}><DialogContent className="atelier-modal code-modal"><DialogTitle>{lesson.title}</DialogTitle><DialogDescription>Scan met de iPad om deze kijkles te openen.</DialogDescription>{qr&&<img src={qr} width="320" height="320" alt={'QR-code voor '+lesson.title}/>}<label htmlFor="watch-link">Leerlinglink</label><input id="watch-link" value={link} readOnly onFocus={e=>e.target.select()}/><button className="primary" onClick={copy}><QrCode size={18}/> Link kopiëren</button></DialogContent></Dialog>
 </div>;
}
