import {getApp,getApps} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js';
import {startOntdekAuth} from './ontdek-auth.js';

let currentUser=null,currentTrial=null;
function statusTekst(pro=false){if(pro)return'PRO actief · onbeperkt downloaden';if(currentUser&&currentTrial){const gebruikt=Number(currentTrial.byTool?.['verliefde-harten']||0),over=Math.max(0,Number(currentTrial.toolLimit||3)-gebruikt);return`${currentTrial.totalRemaining} van ${currentTrial.totalLimit} downloads over · ${over} voor Verliefde harten`;}return'Gratis account nodig voor een PDF zonder watermerk';}
startOntdekAuth({onState:({user,pro,trial})=>{currentUser=user;currentTrial=trial;document.querySelectorAll('.ontdek-download-status').forEach(el=>el.textContent=statusTekst(pro));}});
async function authorizeDownload(pages){if(!currentUser){window.openOntdekAuth?.('registreren');throw new Error('ONTDEK_LOGIN');}try{const reserve=httpsCallable(getFunctions(getApps().length?getApp():null,'europe-west1'),'reserveDiscoverDownload');const result=(await reserve({toolId:'verliefde-harten',pages})).data;currentTrial=result;document.querySelectorAll('.ontdek-download-status').forEach(el=>el.textContent=statusTekst(Boolean(result.pro)));return result;}catch(error){const raw=String(error?.message||error?.details||'');alert(raw.includes('PAGE_LIMIT')?'Kies maximaal 3 oefenvormen voor een gratis PDF. In PRO is er geen paginalimiet.':raw.includes('TOOL_LIMIT')?'Je 3 gratis downloads voor Verliefde harten zijn opgebruikt. Je kunt blijven verkennen.':'De gratis download kon niet worden gecontroleerd.');throw error;}}
window.OntdekTrial={authorizeDownload};

document.addEventListener('DOMContentLoaded',()=>{
  const uitleg=document.createElement('div');uitleg.className='ontdek-uitleg';uitleg.innerHTML='<strong>Ontdek-versie.</strong> Speel telkens 2 minuten en maak vrij werkbladen. Een gratis PDF bevat maximaal 3 pagina’s; PRO heeft geen paginalimiet. <a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank">Bekijk PRO</a>';document.body.appendChild(uitleg);
  const header=document.querySelector('.modal-header'),bar=document.createElement('div');bar.className='ontdek-werkbalk';const page=document.createElement('span');page.className='ontdek-pagina-status';const status=document.createElement('span');status.className='ontdek-download-status';status.textContent=statusTekst();const pdf=document.querySelector('#download-pdf-btn');bar.append(page,status,pdf);header?.insertAdjacentElement('afterend',bar);
  function update(){const n=document.querySelectorAll('#preview-body .werkblad-pagina').length,ok=n>0&&n<=3;page.dataset.status=ok?'goed':'teveel';page.textContent=ok?`${n} van maximaal 3 pagina${n===1?'':'’s'} · download mogelijk · PRO onbeperkt`:`${n} pagina’s · download niet mogelijk in Ontdek · PRO onbeperkt`;pdf.disabled=!ok;}
  new MutationObserver(update).observe(document.querySelector('#preview-body'),{childList:true});
  const modal=document.createElement('div');modal.className='ontdek-demo-modal';modal.innerHTML='<div class="ontdek-demo-card"><h2>Je hebt het spel ontdekt!</h2><p>De demo van twee minuten is afgelopen. In PRO kun je onbeperkt verder spelen.</p><a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank">Bekijk PRO</a><button type="button">Terug</button></div>';document.body.appendChild(modal);
  let timer;document.querySelector('#start-btn')?.addEventListener('click',()=>{clearTimeout(timer);timer=setTimeout(()=>{document.querySelector('#stop-btn')?.click();modal.classList.add('open');},120000);});document.querySelector('#stop-btn')?.addEventListener('click',()=>clearTimeout(timer));modal.querySelector('button').onclick=()=>modal.classList.remove('open');
});
