import {getApp,getApps} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js';
import {startOntdekAuth} from './ontdek-auth.js';
let currentUser=null,currentTrial=null;
function statusTekst(pro=false){if(pro)return'PRO actief · onbeperkt downloaden';if(currentUser&&currentTrial){const gebruikt=Number(currentTrial.byTool?.rekenrooster||0),over=Math.max(0,Number(currentTrial.toolLimit||3)-gebruikt);return`${currentTrial.totalRemaining} van ${currentTrial.totalLimit} downloads over · ${over} voor Rekenrooster`;}return'Gratis account nodig voor een PDF zonder watermerk';}
startOntdekAuth({onState:({user,pro,trial})=>{currentUser=user;currentTrial=trial;document.querySelectorAll('.ontdek-download-status').forEach(el=>el.textContent=statusTekst(pro));}});
function foutmelding(error){const raw=String(error?.message||error?.details||'');if(raw.includes('TOOL_LIMIT'))return'Je 3 gratis PDF-downloads voor Rekenrooster zijn opgebruikt. Je kunt blijven maken en bekijken.';if(raw.includes('TOTAL_LIMIT'))return'Je 15 gratis Ontdek-downloads zijn opgebruikt. Je kunt blijven maken en bekijken.';return'De gratis download kon niet worden gecontroleerd. Probeer het straks opnieuw.';}
async function authorizeDownload(pages){if(!currentUser){window.openOntdekAuth?.('registreren');const error=new Error('Maak eerst je gratis account. Daarna kun je de PDF zonder watermerk downloaden.');error.code='ONTDEK_LOGIN';throw error;}const app=getApps().length?getApp():null;if(!app)throw new Error('De accountverbinding is nog niet klaar.');try{const reserve=httpsCallable(getFunctions(app,'europe-west1'),'reserveDiscoverDownload');const result=(await reserve({toolId:'rekenrooster',pages})).data;currentTrial=result;document.querySelectorAll('.ontdek-download-status').forEach(el=>el.textContent=statusTekst(Boolean(result.pro)));return result;}catch(error){const wrapped=new Error(foutmelding(error));wrapped.code='ONTDEK_LIMIT';throw wrapped;}}
window.OntdekTrial={authorizeDownload,get status(){return currentTrial;}};
function blokkeer(id,tekst){const knop=document.getElementById(id);if(!knop)return;knop.classList.add('ontdek-pro-slot');knop.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();alert(tekst);},true);}
function start(){const uitleg=document.createElement('div');uitleg.className='ontdek-uitleg';uitleg.innerHTML='<strong>Ontdek-versie.</strong> Stel alle soorten rekenroosters vrij samen en bekijk ze in de preview. Je kunt 3 werkblad-PDF’s zonder watermerk downloaden. PNG en oplossingen zijn PRO. <a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank" rel="noopener">Bekijk en koop PRO</a>';document.body.insertAdjacentElement('afterbegin',uitleg);const toolbar=document.createElement('div');toolbar.className='ontdek-werkbalk';const statusrij=document.createElement('div');statusrij.className='ontdek-statusrij';const paginaStatus=document.createElement('span');paginaStatus.className='ontdek-pagina-status';paginaStatus.textContent='1 van maximaal 3 pagina · download mogelijk · PRO onbeperkt';const downloadStatus=document.createElement('span');downloadStatus.className='ontdek-download-status';downloadStatus.textContent=statusTekst(false);statusrij.append(paginaStatus,downloadStatus);const actierij=document.createElement('div');actierij.className='ontdek-actierij';['regenBtn','oplossingBtn','downloadPngBtn','downloadPdfBtn','downloadSolutionPdfBtn'].forEach(id=>{const knop=document.getElementById(id);if(knop)actierij.appendChild(knop);});toolbar.append(statusrij,actierij);document.querySelector('.app-header')?.insertAdjacentElement('afterend',toolbar);blokkeer('oplossingBtn','Oplossingen bekijken is beschikbaar in PRO. In Ontdek kun je alle rekenroosters samenstellen en bekijken.');blokkeer('downloadPngBtn','Downloaden als afbeelding is beschikbaar in PRO.');blokkeer('downloadSolutionPdfBtn','De PDF met oplossingen is beschikbaar in PRO.');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
