import {getApp,getApps} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js';
import {startOntdekAuth} from './ontdek-auth.js';
let currentUser=null,currentTrial=null;
function statusTekst(pro=false){if(pro)return'PRO actief · onbeperkt downloaden';if(currentUser&&currentTrial){const gebruikt=Number(currentTrial.byTool?.rekenspellen||0),over=Math.max(0,Number(currentTrial.toolLimit||3)-gebruikt);return`${currentTrial.totalRemaining} van ${currentTrial.totalLimit} downloads over · ${over} voor Rekenspellen`;}return'Gratis account nodig voor een PDF zonder watermerk';}
startOntdekAuth({onState:({user,pro,trial})=>{currentUser=user;currentTrial=trial;document.querySelectorAll('.ontdek-download-status').forEach(el=>el.textContent=statusTekst(pro));}});
function foutmelding(error){const raw=String(error?.message||error?.details||'');if(raw.includes('PAGE_LIMIT'))return'De bundel telt meer dan 3 PDF-pagina’s. Verwijder een werkblad of kies PRO zonder paginalimiet.';if(raw.includes('TOOL_LIMIT'))return'Je 3 gratis PDF-downloads voor Rekenspellen zijn opgebruikt. Je kunt blijven maken en bekijken.';if(raw.includes('TOTAL_LIMIT'))return'Je 15 gratis Ontdek-downloads zijn opgebruikt. Je kunt blijven maken en bekijken.';return'De gratis download kon niet worden gecontroleerd. Probeer het straks opnieuw.';}
async function authorizeDownload(pages){if(!currentUser){window.openOntdekAuth?.('registreren');const error=new Error('Maak eerst je gratis account. Daarna kun je de PDF zonder watermerk downloaden.');error.code='ONTDEK_LOGIN';throw error;}const app=getApps().length?getApp():null;if(!app)throw new Error('De accountverbinding is nog niet klaar.');try{const reserve=httpsCallable(getFunctions(app,'europe-west1'),'reserveDiscoverDownload');const result=(await reserve({toolId:'rekenspellen',pages})).data;currentTrial=result;document.querySelectorAll('.ontdek-download-status').forEach(el=>el.textContent=statusTekst(Boolean(result.pro)));return result;}catch(error){const wrapped=new Error(foutmelding(error));wrapped.code='ONTDEK_LIMIT';alert(wrapped.message);throw wrapped;}}
window.OntdekTrial={authorizeDownload,get status(){return currentTrial;}};
function schatPaginas(){let sheets=[...document.querySelectorAll('#print-output .worksheet')].filter(s=>!s.querySelector('.empty-msg'));if(!sheets.length)sheets=[...document.querySelectorAll('#preview-area .worksheet')];if(!sheets.length)return 0;const usableW=190,usableH=279,gap=4;let pages=1,curY=10;sheets.forEach((sheet,i)=>{const h=Math.min(usableW*(sheet.scrollHeight/Math.max(1,sheet.offsetWidth)),269),space=usableH-curY;if(i>0&&space<h+gap){pages++;curY=10;}else if(i>0)curY+=gap;curY+=h;});return pages;}
function start(){const uitleg=document.createElement('div');uitleg.className='ontdek-uitleg';uitleg.innerHTML='<strong>Ontdek-versie.</strong> Probeer alle vijf rekenspellen en bouw vrij een bundel van maximaal 3 PDF-pagina’s. De gewone PDF kan 3 keer gratis; PNG, afdrukken en antwoordsleutels zijn PRO. <a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank" rel="noopener">Bekijk en koop PRO</a>';document.body.insertAdjacentElement('afterbegin',uitleg);document.title='Rekenspellen Generator – Zisa Ontdek';const title=document.querySelector('.pro-header .title');if(title)title.textContent='Rekenspellen Generator — Juf Zisa Ontdek';const back=document.querySelector('.pro-header .back-link');if(back){back.href='app.html';back.textContent='← Keuzemenu alle tools';}const bar=document.querySelector('#bundel-bar');const page=document.createElement('span');page.className='ontdek-pagina-status';const download=document.createElement('span');download.className='ontdek-download-status';download.textContent=statusTekst(false);bar?.prepend(page,download);const printBtn=[...bar.querySelectorAll('button')].find(b=>b.textContent.includes('Afdrukken'));const pngBtn=[...bar.querySelectorAll('button')].find(b=>b.textContent.includes('PNG'));[printBtn,pngBtn].filter(Boolean).forEach(btn=>btn.classList.add('ontdek-pro-slot'));document.addEventListener('click',event=>{const btn=event.target.closest('button');if(!btn)return;if(btn===printBtn||btn===pngBtn){event.preventDefault();event.stopImmediatePropagation();alert(btn===printBtn?'Rechtstreeks afdrukken is beschikbaar in PRO. Gebruik in Ontdek de gewone PDF-download.':'Downloaden als PNG is beschikbaar in PRO.');}},true);const ans=document.querySelector('#show-ans');if(ans){ans.value='hidden';ans.disabled=true;ans.classList.add('ontdek-sleutel-pro');ans.closest('.field')?.querySelector('label')?.classList.add('ontdek-sleutel-pro-label');}
function update(){const pages=schatPaginas(),ok=pages<=3;page.dataset.status=ok?'goed':'teveel';page.textContent=pages?ok?`${pages} van maximaal 3 PDF-pagina${pages===1?'':'’s'} · download mogelijk · PRO onbeperkt`:`${pages} PDF-pagina’s · verwijder een werkblad · PRO onbeperkt`:'Nog geen werkblad toegevoegd · Ontdek maximaal 3 PDF-pagina’s';const pdf=[...bar.querySelectorAll('button')].find(b=>b.textContent.trim().endsWith('PDF'));if(pdf)pdf.disabled=!pages||!ok;}
new MutationObserver(()=>setTimeout(update,60)).observe(document.body,{childList:true,subtree:true});update();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
