import {getApp,getApps} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js';
import {startOntdekAuth} from './ontdek-auth.js';
const cfg=window.ONTDEK_TAAL||{},toolId=cfg.toolId||'taal-tool';
const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./taal-ontdek.css',import.meta.url).href;document.head.appendChild(style);
let currentUser=null,currentTrial=null,currentPro=false;const $all=s=>[...document.querySelectorAll(s)];
function remaining(){if(currentPro)return'PRO actief · onbeperkt';if(currentUser&&currentTrial){const used=Number(currentTrial.byTool?.[toolId]||0);return `${currentTrial.totalRemaining} van ${currentTrial.totalLimit} downloads over · ${Math.max(0,Number(currentTrial.toolLimit||3)-used)} voor deze tool`;}return'Gratis account nodig voor een PDF zonder watermerk';}
function updateStatus(){document.querySelectorAll('.ontdek-download-status').forEach(x=>x.textContent=remaining());}
startOntdekAuth({onState:({user,pro,trial})=>{currentUser=user;currentPro=pro;currentTrial=trial;updateStatus();}});
async function authorize(pages=1){if(!currentUser){window.openOntdekAuth?.('registreren');throw new Error('LOGIN');}const reserve=httpsCallable(getFunctions(getApps().length?getApp():undefined,'europe-west1'),'reserveDiscoverDownload');try{const result=(await reserve({toolId,pages})).data;currentTrial=result;currentPro=!!result.pro;updateStatus();return result;}catch(error){const raw=String(error?.message||error?.details||'');let msg='De gratis download kon niet worden gecontroleerd.';if(raw.includes('PAGE_LIMIT'))msg='Dit materiaal telt meer dan 3 PDF-pagina’s. Maak de bundel korter of kies PRO zonder paginalimiet.';if(raw.includes('TOOL_LIMIT'))msg='Je 3 gratis downloads voor deze tool zijn opgebruikt. Je kunt wel onbeperkt blijven maken en bekijken.';if(raw.includes('TOTAL_LIMIT'))msg='Je 15 gratis Ontdek-downloads zijn opgebruikt. Je kunt wel onbeperkt blijven maken en bekijken.';alert(msg);throw error;}}
function addBar(){const oudeMenuKnoppen=[...document.querySelectorAll('a,button')].filter(el=>{const tekst=el.textContent.trim().toLocaleLowerCase('nl');const href=el.getAttribute('href')||'';const onclick=el.getAttribute('onclick')||'';return (href.includes('app.html')||onclick.includes('app.html'))&&(tekst.includes('menu')||tekst.includes('alle tools'));});oudeMenuKnoppen.forEach(el=>el.hidden=true);const bar=document.createElement('div');bar.className='ontdek-trial-bar';bar.innerHTML=`<a href="/ontdek/app.html">← Keuzemenu alle tools</a><span><strong>Ontdek-versie</strong> · dezelfde werkwijze als PRO</span><span class="ontdek-page-status"></span><span class="ontdek-info ontdek-download-status">${remaining()}</span><a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank" rel="noopener">PRO bekijken</a>`;document.body.prepend(bar);}
function lock(selectors,message){selectors.forEach(sel=>$all(sel).forEach(el=>{el.classList.add('ontdek-pro-lock');el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();alert(message);},true);}));}
function pages(){if(typeof cfg.pageCount==='function')return Math.max(0,Number(cfg.pageCount())||0);return cfg.pageSelector?$all(cfg.pageSelector).filter(x=>x.offsetParent!==null).length:1;}
function markProLabels(){document.querySelectorAll('button,a,label,[role="button"],.pro-badge,.hdr-badge').forEach(el=>{if(el.classList.contains('ontdek-pro-word'))return;[...el.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE&&/\bPRO\b/i.test(n.textContent)).forEach(node=>{const parts=node.textContent.split(/(\bPRO\b)/i),frag=document.createDocumentFragment();parts.forEach(part=>{if(/^PRO$/i.test(part)){const badge=document.createElement('span');badge.className='ontdek-pro-word';badge.textContent='PRO';frag.appendChild(badge)}else frag.appendChild(document.createTextNode(part))});node.replaceWith(frag)})})}
function refresh(){markProLabels();(cfg.previewSelectors||[]).forEach(sel=>$all(sel).forEach(el=>el.classList.add('ontdek-watermarked')));const count=pages(),status=document.querySelector('.ontdek-page-status');if(status){const ok=count<=3;status.dataset.status=ok?'goed':'teveel';status.textContent=cfg.statusText||(cfg.noPageLimit?'Ontdek-demo · maximaal 2 minuten · PRO onbeperkt':count?ok?`${count} van maximaal 3 PDF-pagina’s · download mogelijk`:`${count} PDF-pagina’s · maak de bundel korter`:'Nog geen werkblad');}(cfg.pdfSelectors||[]).forEach(sel=>$all(sel).forEach(b=>{const blocked=count===0||(!cfg.noPageLimit&&count>3);if(blocked){if(!b.disabled)b.dataset.ontdekLimitDisabled='1';b.disabled=true;}else if(b.dataset.ontdekLimitDisabled==='1'){delete b.dataset.ontdekLimitDisabled;b.disabled=false;}}));}
function guardDownloads(){(cfg.pdfSelectors||[]).forEach(sel=>$all(sel).forEach(btn=>btn.addEventListener('click',async e=>{if(btn.dataset.ontdekAuthorized==='1'){delete btn.dataset.ontdekAuthorized;return;}e.preventDefault();e.stopImmediatePropagation();const count=pages();if(count>3){alert('Maximaal 3 PDF-pagina’s in Ontdek. PRO heeft geen paginalimiet.');return;}try{await authorize(Math.max(1,count));btn.dataset.ontdekAuthorized='1';btn.click();}catch{}},true)));}
function demo(){if(!cfg.demoStart)return;const modal=document.createElement('dialog');modal.className='ontdek-auth-dialog';modal.innerHTML='<div class="ontdek-auth-card"><span class="ontdek-auth-kicker">ONTDEK-DEMO</span><h2>Je hebt deze tool ontdekt!</h2><p class="ontdek-auth-intro">De demo van twee minuten is afgelopen. In PRO kun je onbeperkt doorspelen.</p><a class="ontdek-auth-primary" href="https://demo.jufzisa.be/#zg-prijzen" target="_blank" rel="noopener">Bekijk PRO</a><button class="ontdek-auth-switch" type="button">Nog eens instellen</button></div>';document.body.appendChild(modal);const label=document.createElement('strong');label.className='ontdek-demo-countdown';label.textContent='Ontdek-demo: 2:00';document.querySelector(cfg.demoLabelTarget||'.ontdek-trial-bar')?.appendChild(label);let timer,ticker,end=0;const stop=()=>{clearTimeout(timer);clearInterval(ticker);};const start=()=>{stop();end=Date.now()+120000;const tick=()=>{const sec=Math.max(0,Math.ceil((end-Date.now())/1000));label.textContent=`Ontdek-demo: ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;};tick();ticker=setInterval(tick,250);timer=setTimeout(()=>{stop();label.textContent='Ontdek-demo afgelopen';document.querySelector(cfg.demoStop)?.click();modal.showModal();},120000);};document.addEventListener('click',e=>{if(e.target.closest(cfg.demoStart))start();if(cfg.demoStop&&e.target.closest(cfg.demoStop))stop();});modal.querySelector('button').onclick=()=>{modal.close();label.textContent='Ontdek-demo: 2:00';};}
document.addEventListener('DOMContentLoaded',()=>{document.title=document.title.replace(/PRO/gi,'Ontdek');document.querySelectorAll('.pro-badge,.hdr-badge').forEach(x=>x.textContent='ONTDEK');document.querySelectorAll('.pro-banner span:not(.pro-badge),.pro-header .title').forEach(x=>x.textContent=x.textContent.replace(/PRO/gi,'Ontdek'));addBar();lock(cfg.proSelectors||[],'Deze functie is beschikbaar in PRO. In Ontdek kun je de gewone leerling-PDF gebruiken.');guardDownloads();demo();refresh();new MutationObserver(()=>setTimeout(refresh,40)).observe(document.body,{subtree:true,childList:true});});
