import {getApp,getApps} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js';
import {startOntdekAuth} from './ontdek-auth.js';

const cfg=window.ONTDEK_TIJD||{};
const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./tijd-ontdek.css',import.meta.url).href;document.head.appendChild(style);
let currentUser=null,currentTrial=null,currentPro=false;
const toolId=cfg.toolId||'tijd-tool';

function downloadStatus(){if(currentPro)return'PRO actief · onbeperkt';if(currentUser&&currentTrial){const used=Number(currentTrial.byTool?.[toolId]||0);return `${Math.max(0,Number(currentTrial.toolLimit||3)-used)} van 3 downloads voor deze tool over`;}return'Gratis account nodig voor een PDF zonder watermerk';}
function setStatus(text){document.querySelectorAll('.ontdek-tijd-status').forEach(el=>el.textContent=text||downloadStatus());}
function proInfo(message='Deze keuze is beschikbaar in PRO.'){let dialog=document.getElementById('ontdekTijdProDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='ontdekTijdProDialog';dialog.className='ontdek-pro-dialog';dialog.innerHTML='<div class="ontdek-pro-card"><h2>Deze keuze hoort bij PRO</h2><p></p><div class="ontdek-pro-actions"><button type="button">Sluiten en verder ontdekken</button><a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank" rel="noopener">Bekijk prijzen</a></div></div>';document.body.appendChild(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});}dialog.querySelector('p').textContent=message;dialog.showModal();}
window.openOntdekProInfo=proInfo;

function hideOldMenus(){document.querySelectorAll('a,button').forEach(el=>{const text=el.textContent.trim().toLowerCase();const route=(el.getAttribute('href')||'')+(el.getAttribute('onclick')||'');if(route.includes('app.html')&&(text.includes('menu')||text.includes('alle tools'))){el.hidden=true;el.style.setProperty('display','none','important');}});}
function addBar(){hideOldMenus();const bar=document.createElement('div');bar.className='ontdek-tijd-bar';bar.innerHTML=`<a href="/ontdek/app.html">← Keuzemenu alle tools</a><span><strong>Ontdek-versie</strong> · dezelfde werkwijze als PRO</span><span class="ontdek-tijd-page"></span><span class="ontdek-tijd-status">${downloadStatus()}</span><a href="https://demo.jufzisa.be/#zg-prijzen" target="_blank" rel="noopener">PRO bekijken</a>`;document.body.prepend(bar);}
function lockPro(){(cfg.proSelectors||[]).forEach(selector=>document.querySelectorAll(selector).forEach(el=>{el.classList.add('ontdek-pro-choice');el.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();proInfo('Oplossingen en antwoordsleutels zijn beschikbaar in PRO. De leerlingbundel kun je in Ontdek wel gratis downloaden binnen de limieten.');},true);}));}
function watermark(){(cfg.previewSelectors||[]).forEach(selector=>document.querySelectorAll(selector).forEach(el=>el.classList.add('ontdek-tijd-watermark')));}
function lockTimerThemes(){if(!cfg.freeThemes)return;document.querySelectorAll('.theme-buttons button[data-theme]').forEach(button=>{if(cfg.freeThemes.includes(button.dataset.theme))return;button.classList.add('ontdek-pro-choice');button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();proInfo('Dit timerthema is beschikbaar in PRO. In Ontdek kun je Regenboog en Groeiende ster volledig uitproberen.');},true);});}

async function authorizeDownload(pages){const count=Math.max(1,Number(pages)||1);reportPages(count);if(count>3)throw new Error('PAGE_LIMIT');if(!currentUser){window.openOntdekAuth?.('registreren');throw new Error('LOGIN');}const reserve=httpsCallable(getFunctions(getApps().length?getApp():undefined,'europe-west1'),'reserveDiscoverDownload');try{const result=(await reserve({toolId,pages:count})).data;currentTrial=result;currentPro=!!result.pro;setStatus();return result;}catch(error){const raw=String(error?.message||error?.details||error);let message='De gratis download kon niet worden gecontroleerd.';if(raw.includes('PAGE_LIMIT'))message='Deze bundel telt meer dan 3 PDF-pagina’s. Maak hem korter of kies PRO zonder paginalimiet.';if(raw.includes('TOOL_LIMIT'))message='Je 3 gratis downloads voor deze tool zijn opgebruikt. Je kunt wel onbeperkt blijven maken en bekijken.';if(raw.includes('TOTAL_LIMIT'))message='Je 15 gratis Ontdek-downloads zijn opgebruikt. Je kunt wel onbeperkt blijven maken en bekijken.';if(!raw.includes('LOGIN'))alert(message);throw error;}}
function reportPages(pages){const target=document.querySelector('.ontdek-tijd-page');if(!target)return;const count=Number(pages)||0;target.textContent=count<=3?`${count} van maximaal 3 PDF-pagina’s · download mogelijk`:`${count} PDF-pagina’s · te lang voor Ontdek`;target.style.color=count<=3?'#176d42':'#a12626';}
window.OntdekTijd={authorizeDownload,reportPages,proInfo};

startOntdekAuth({onState:({user,pro,trial})=>{currentUser=user;currentPro=pro;currentTrial=trial;setStatus();}});
document.addEventListener('DOMContentLoaded',()=>{document.title=document.title.replace(/PRO/gi,'Ontdek');document.querySelectorAll('.pro-badge').forEach(el=>el.textContent='ONTDEK');document.querySelectorAll('.pro-banner span:not(.pro-badge)').forEach(el=>el.textContent=el.textContent.replace(/PRO/gi,'Ontdek'));addBar();lockPro();lockTimerThemes();watermark();if(cfg.bundle){document.querySelector('.ontdek-tijd-page').textContent='Ontdek: maximaal 3 pagina’s · exacte controle bij download · PRO onbeperkt';}});
