export const worlds = [
{id:'aqua',name:'Aquarium',icon:'🐠',color:'#097f99',hint:'Een zee vol zelfbedachte bewoners',ground:'zeebodem'},
{id:'garden',name:'Bloementuin',icon:'🦋',color:'#54822a',hint:'Het kriebelt, kruipt en fladdert',ground:'grond'},
{id:'space',name:'Ruimtewereld',icon:'🪐',color:'#7053bc',hint:'Op avontuur tussen de sterren',ground:'maanbodem'},
{id:'forest',name:'Fantasiebos',icon:'🌳',color:'#28745e',hint:'Hier woont de verbeelding',ground:'bosgrond'}];
export type Motion='swim'|'fly'|'crawl'|'walk'|'float'|'tentacles'|'bubbles';
export const motions:Record<Motion,string>={swim:'Zwemmen · staart zwiept',fly:'Vliegen · vleugels klapperen',crawl:'Kruipen · lijf golft',walk:'Lopen · benen bewegen',float:'Zweven · armen wiebelen',tentacles:'Golven · tentakels bewegen',bubbles:'Zitten · bellen blazen'};
export type Template={id:string;world:string;name:string;kind:'kleur'|'ontwerp'|'vrij';motion:Motion;zone:'air'|'ground';index:number};
const names=[['Goudvis','Clownvis','Kogelvis','Maanvis','Zeepaardje','Haai','Rog','Octopus','Kwal','Zeeschildpad','Ronde vis','Lange vis','Driehoekige vis','Sluierstaartvis','Eigen kwal','Eigen octopus'],['Vlinder','Nachtvlinder','Bij','Hommel','Lieveheersbeestje','Libel','Kever','Sprinkhaan','Rups','Slak','Ronde vleugels','Puntige vleugels','Lange vleugels','Eigen kever','Eigen rups','Eigen slak'],['Eenoogwezen','Drieoogwezen','Tentakelwezen','Antennewezen','Sterrenwezen','Maanwezen','Langarmwezen','Zweefwezen','Ruimterobot','Ruimtekwal','Rond antennewezen','Lang ruimtewezen','Vierarmwezen','Eigen tentakelwezen','Eigen robot','Zweefwezen met vinnen'],['Bosmonster','Zittend draakje','Elfje','Kabouter','Boomwezen','Paddenstoelwezen','Blaadjeswezen','Pluizenbol','Fantasievogel','Eenhoorn','Rond monstertje','Langbenig monstertje','Eigen zittend draakje','Eigen elfje','Eigen boomwezen','Eigen paddenstoelwezen']];
export const templates:Template[]=worlds.flatMap((w,wi)=>[...names[wi].map((name,i)=>{let motion:Motion=wi===0?'swim':wi===1?'fly':wi===2?'float':'walk';let zone:'air'|'ground'='air';if(wi===0&&[7,8,14,15].includes(i))motion='tentacles';if(wi===0&&[7,15].includes(i))zone='ground';if(wi===1&&[4,6,7,8,9,13,14,15].includes(i)){motion='crawl';zone='ground';}if(wi===2&&[2,9,13].includes(i))motion='tentacles';if(wi===3){zone='ground';if([2,8,13].includes(i)){motion='fly';zone='air';}if([1,12].includes(i)){motion='bubbles';zone='ground';}}return {id:`${w.id}-${String(i+1).padStart(2,'0')}`,world:w.id,name,kind:i<10?'kleur':'ontwerp',motion,zone,index:i} as Template;}),{id:`${w.id}-vrij`,world:w.id,name:'Helemaal zelf bedenken',kind:'vrij',motion:wi===0?'swim':wi===1?'crawl':wi===2?'float':'walk',zone:wi===1||wi===3?'ground':'air',index:16} as Template]);
export type Creature={id:string;world:string;name:string;template:string;motion:Motion;zone:'air'|'ground';image:string;size:number;flip:boolean;pivot:number;createdAt?:string};

templates.splice(templates.findIndex(t=>t.id==='forest-02')+1,0,{id:'forest-18',world:'forest',name:'Vliegend draakje',kind:'ontwerp',motion:'fly',zone:'air',index:17});
