(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SHAPES=['vierkant','rechthoek','driehoek','trapezium','parallellogram','ruit','cirkel'];
const TOPICS={identify:{label:'Vlakke figuren herkennen',n:2},properties:{label:'Eigenschappen van vlakke figuren',n:2},draw:{label:'Zelf figuren tekenen op een 1 cm-rooster',n:2},compare:{label:'Oppervlakte vergelijken op rooster',n:1},perimeter:{label:'Omtrek berekenen',n:2},area:{label:'Oppervlakte berekenen',n:2},composite:{label:'Oppervlakte met zelfgetekende hulplijnen',n:1},similar:{label:'Gelijkvormigheid',n:1},solids:{label:'Ruimtelichamen herkennen',n:1},volume:{label:'Volume berekenen',n:1}};
let exercises=[],dragId=null;const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[rnd(0,a.length-1)],shuffle=a=>[...a].sort(()=>Math.random()-.5),id=()=>Math.random().toString(36).slice(2);
function init(){
 $('#topics').innerHTML=Object.entries(TOPICS).map(([k,v])=>`<div class="topic"><input type="checkbox" data-topic="${k}" ${['identify','properties','draw','perimeter','area'].includes(k)?'checked':''}><span>${v.label}</span><input type="number" min="0" max="10" value="${v.n}" data-count="${k}"></div>`).join('');
 $('#addType').innerHTML=Object.entries(TOPICS).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('');
 for(const box of ['perimeterShapes','areaShapes'])$( '#'+box).innerHTML=SHAPES.map(s=>`<label><input type="checkbox" value="${s}" ${['vierkant','rechthoek','driehoek'].includes(s)?'checked':''}>${cap(s)}</label>`).join('');
 $('#generate').onclick=generate;$('#add').onclick=()=>{exercises.push(make($('#addType').value));render()};$('#clear').onclick=()=>{exercises=[];render()};$('#print').onclick=()=>window.print();$('#pages').addEventListener('click',actions);$('#pages').addEventListener('dragstart',dragStart);$('#pages').addEventListener('dragover',e=>e.preventDefault());$('#pages').addEventListener('drop',drop);render();
}
const cap=s=>s[0].toUpperCase()+s.slice(1);function selected(box){const a=$$('#'+box+' input:checked').map(x=>x.value);return a.length?a:['rechthoek']}
function dim(min,max){let n=rnd(min,max);if($('#numbers').value==='decimal'&&Math.random()<.5)n+=.5;return n}
function make(type){const ex={id:id(),type};
 if(type==='identify'){ex.options=shuffle(SHAPES).slice(0,4);ex.target=pick(ex.options);ex.text=`Omcirkel de ${ex.target}.`}
 if(type==='properties'){ex.shape=pick(SHAPES);ex.text='Kijk goed naar de vlakke figuur. Duid alle juiste eigenschappen aan.';ex.props=properties(ex.shape)}
 if(type==='draw'){const tasks=[()=>{let w=rnd(3,7),h=rnd(2,5);return `Teken een rechthoek van ${w} cm lang en ${h} cm breed.`},()=>{let s=rnd(2,6);return `Teken een vierkant met zijden van ${s} cm.`},()=>`Teken een vlakke figuur met een oppervlakte van ${rnd(8,24)} cm².`,()=>`Teken twee verschillende vlakke figuren met elk een oppervlakte van ${rnd(8,18)} cm².`,()=>`Teken een rechthoek met een omtrek van ${pick([14,16,18,20,22,24])} cm.`];ex.text=pick(tasks)()}
 if(type==='compare'){ex.a=rnd(5,16);ex.b=Math.random()<.25?ex.a:rnd(5,16);ex.text='Vergelijk de oppervlakte. Schrijf <, > of =.'}
 if(type==='perimeter'){ex.shape=pick(selected('perimeterShapes'));ex.dims=shapeDims(ex.shape);ex.text='Bereken de omtrek.'}
 if(type==='area'){ex.shape=pick(selected('areaShapes'));ex.dims=shapeDims(ex.shape);ex.text='Bereken de oppervlakte.'}
 if(type==='composite'){ex.variant=pick(['house','notch','slant']);ex.text='Bereken de oppervlakte. Teken zelf hulplijnen zodat je bekende vlakke figuren krijgt.'}
 if(type==='similar'){ex.shape=pick(['driehoek','rechthoek','trapezium']);ex.text='Duid de figuur aan die gelijkvormig is met figuur A.'}
 if(type==='solids'){ex.options=shuffle(['kubus','balk','cilinder','kegel','bol','piramide']).slice(0,4);ex.target=pick(ex.options);ex.text=`Omcirkel de ${ex.target}.`}
 if(type==='volume'){ex.dims={l:dim(3,7),w:dim(2,5),h:dim(2,5)};ex.text='Bereken het volume.'}
 return ex}
function shapeDims(shape){switch(shape){case'vierkant':return{s:dim(2,6)};case'rechthoek':return{w:dim(3,8),h:dim(2,6)};case'driehoek':return{b:dim(4,8),h:dim(2,6)};case'trapezium':return{a:dim(3,6),b:dim(6,9),h:dim(2,5)};case'parallellogram':return{b:dim(4,8),s:dim(2,5),h:dim(2,5)};case'ruit':return{d1:dim(4,8),d2:dim(3,7),s:dim(3,6)};case'cirkel':return{r:dim(2,4)};}}
function generate(){exercises=[];$$('[data-topic]').forEach(c=>{if(c.checked)for(let i=0;i<+$(`[data-count="${c.dataset.topic}"]`).value;i++)exercises.push(make(c.dataset.topic))});render()}
function properties(s){const map={vierkant:['4 zijden','4 gelijke zijden','4 rechte hoeken','2 paar evenwijdige zijden','loodrechte zijden'],rechthoek:['4 zijden','4 rechte hoeken','2 paar evenwijdige zijden','overstaande zijden even lang','loodrechte zijden'],driehoek:['3 zijden','3 hoeken'],trapezium:['4 zijden','1 paar evenwijdige zijden'],parallellogram:['4 zijden','2 paar evenwijdige zijden','overstaande zijden even lang'],ruit:['4 zijden','4 gelijke zijden','2 paar evenwijdige zijden'],cirkel:['geen zijden','geen hoeken']};const falseP=['1 paar loodrechte zijden','alle hoeken zijn recht','alle zijden zijn even lang','geen evenwijdige zijden','5 zijden'];return shuffle([...map[s],...shuffle(falseP.filter(x=>!map[s].includes(x))).slice(0,3)]).slice(0,7)}
function render(){const pages=$('#pages');pages.innerHTML='';$('#empty').style.display=exercises.length?'none':'block';$('#print').disabled=!exercises.length;if(!exercises.length)return;const groups=[];let g=[];for(const ex of exercises){const large=['draw','composite','volume'].includes(ex.type);if(large){if(g.length)groups.push(g);groups.push([ex]);g=[]}else{g.push(ex);if(g.length===2){groups.push(g);g=[]}}}if(g.length)groups.push(g);groups.forEach((grp,pi)=>{const p=document.createElement('section');p.className='page';p.innerHTML=`<header class="page-header"><h1>${escapeHtml($('#title').value||'Meetkundebundel')}</h1><div class="student-fields"><span>Naam: __________________________________</span><span>Datum: __________________</span></div></header>${grp.map(exerciseHtml).join('')}<div class="control-line">Controle: deze lijn is 5 cm <span></span></div><div class="page-number">${pi+1}</div>`;pages.appendChild(p)})}
function exerciseHtml(ex){const nr=exercises.indexOf(ex)+1;return `<article class="exercise" draggable="true" data-id="${ex.id}"><div class="admin-actions"><button data-a="up">↑</button><button data-a="down">↓</button><button data-a="new">↻</button><button data-a="copy">⧉</button><button data-a="del">✕</button></div><p class="instruction"><span class="number">${nr}.</span>${ex.text}</p>${body(ex)}</article>`}
function body(ex){let h='';if(ex.type==='identify')h=`<div class="options">${ex.options.map((s,i)=>`<div class="option">${shapeSvg(s,32,25)}<b>${String.fromCharCode(65+i)}</b></div>`).join('')}</div>`;
if(ex.type==='properties')h=`<div class="shape-wrap">${shapeSvg(ex.shape,58,38)}</div><div class="properties">${ex.props.map(p=>`<div class="prop"><span class="box"></span>${p}</div>`).join('')}</div>`;
if(ex.type==='draw')h=gridSvg(16,10);
if(ex.type==='compare')h=`<div class="two-figures"><div>${filledGrid(ex.a)}<b>Figuur A</b></div><div>${filledGrid(ex.b)}<b>Figuur B</b></div></div><div class="compare-sign">A &nbsp; ____ &nbsp; B</div>`;
if(['perimeter','area'].includes(ex.type)){h=($('#askName').checked?`<div class="figure-name">Naam van de figuur: <span class="line"></span></div>`:'')+`<div class="shape-wrap">${measureShape(ex)}</div><div class="answer">Antwoord: <span class="line"></span> ${ex.type==='area'?'cm²':'cm'}</div>`}
if(ex.type==='composite')h=`<div class="shape-wrap">${compositeSvg(ex.variant)}</div><div class="answer">Antwoord: <span class="line"></span> cm²</div><div class="drawing-space"></div>`;
if(ex.type==='similar')h=`<div class="options"><div class="option"><b>A</b>${shapeSvg(ex.shape,34,27)}</div><div class="option scaled"><b>B</b>${shapeSvg(ex.shape,27,21)}</div><div class="option"><b>C</b>${distorted(ex.shape)}</div></div>`;
if(ex.type==='solids')h=`<div class="options">${ex.options.map((s,i)=>`<div class="option solid">${solidSvg(s)}<b>${String.fromCharCode(65+i)}</b></div>`).join('')}</div>`;
if(ex.type==='volume')h=`<div class="shape-wrap solid">${volumeSvg(ex.dims)}</div><div class="answer">Antwoord: <span class="line"></span> cm³</div>`;return h}
function shapeSvg(s,w=40,h=30){const p={vierkant:'<rect x="15" y="5" width="70" height="70"/>',rechthoek:'<rect x="5" y="18" width="90" height="54"/>',driehoek:'<polygon points="50,5 95,85 5,85"/>',trapezium:'<polygon points="25,10 75,10 95,85 5,85"/>',parallellogram:'<polygon points="25,10 95,10 75,85 5,85"/>',ruit:'<polygon points="50,5 95,50 50,95 5,50"/>',cirkel:'<circle cx="50" cy="50" r="42"/>'};return `<svg width="${w}mm" height="${h}mm" viewBox="0 0 100 100" fill="none" stroke="#111" stroke-width="2.5">${p[s]}</svg>`}
function gridSvg(c,r){let z='';for(let x=0;x<=c;x++)z+=`<line x1="${x}" y1="0" x2="${x}" y2="${r}"/>`;for(let y=0;y<=r;y++)z+=`<line x1="0" y1="${y}" x2="${c}" y2="${y}"/>`;return `<svg class="grid1cm" width="${c}cm" height="${r}cm" viewBox="0 0 ${c} ${r}" stroke="#aeb9c5" stroke-width=".025" fill="none">${z}</svg>`}
function filledGrid(n){let z='';const coords=[];for(let i=0;i<n;i++)coords.push([i%4,Math.floor(i/4)]);coords.forEach(([x,y])=>z+=`<rect x="${x}" y="${y}" width="1" height="1" fill="#dbe9fb" stroke="#255eaa" stroke-width=".04"/>`);for(let x=0;x<=5;x++)z+=`<line x1="${x}" y1="0" x2="${x}" y2="5"/>`;for(let y=0;y<=5;y++)z+=`<line x1="0" y1="${y}" x2="5" y2="${y}"/>`;return `<svg width="5cm" height="5cm" viewBox="0 0 5 5" stroke="#bac4cf" stroke-width=".025">${z}</svg>`}
function measureShape(ex){const d=ex.dims,s=ex.shape;let w=70,h=45,path='';if(s==='vierkant'){w=h=d.s*10;path=`<rect x="1" y="1" width="${w}" height="${h}"/>`}if(s==='rechthoek'){w=d.w*10;h=d.h*10;path=`<rect x="1" y="1" width="${w}" height="${h}"/>`}if(s==='driehoek'){w=d.b*10;h=d.h*10;path=`<polygon points="1,${h+1} ${w+1},${h+1} ${w*.58},1"/>`}if(s==='trapezium'){w=d.b*10;h=d.h*10;path=`<polygon points="${(d.b-d.a)*5+1},1 ${(d.b-d.a)*5+d.a*10+1},1 ${w+1},${h+1} 1,${h+1}"/>`}if(s==='parallellogram'){w=d.b*10;h=d.h*10;path=`<polygon points="${d.s*4+1},1 ${w+d.s*4+1},1 ${w+1},${h+1} 1,${h+1}"/>`;w+=d.s*4}if(s==='ruit'){w=d.d1*10;h=d.d2*10;path=`<polygon points="${w/2+1},1 ${w+1},${h/2+1} ${w/2+1},${h+1} 1,${h/2+1}"/>`}if(s==='cirkel'){w=h=d.r*20;path=`<circle cx="${w/2+1}" cy="${h/2+1}" r="${w/2}"/>`}return `<svg width="${(w+4)/10}cm" height="${(h+4)/10}cm" viewBox="0 0 ${w+4} ${h+4}" fill="none" stroke="#111" stroke-width="1">${path}</svg>`}
function compositeSvg(v){const paths={house:'M10 90H150V42L80 5L10 42Z',notch:'M10 10H150V90H90V55H55V90H10Z',slant:'M10 90H155L125 10H45Z'};return `<svg width="14cm" height="8cm" viewBox="0 0 165 100"><path d="${paths[v]}" fill="none" stroke="#111" stroke-width="2"/><text x="12" y="98" font-size="6">Meet de nodige lengtes met je meetlat.</text></svg>`}
function distorted(s){return `<svg width="34mm" height="27mm" viewBox="0 0 120 100" fill="none" stroke="#111" stroke-width="3"><polygon points="10,85 110,85 85,10"/></svg>`}
function solidSvg(s){const q={kubus:'<rect x="20" y="28" width="50" height="50"/><rect x="38" y="10" width="50" height="50"/><path d="M20 28L38 10M70 28L88 10M70 78L88 60M20 78L38 60"/>',balk:'<rect x="10" y="35" width="70" height="42"/><rect x="35" y="15" width="70" height="42"/><path d="M10 35L35 15M80 35L105 15M80 77L105 57M10 77L35 57"/>',cilinder:'<ellipse cx="55" cy="18" rx="30" ry="10"/><path d="M25 18V75M85 18V75"/><ellipse cx="55" cy="75" rx="30" ry="10"/>',kegel:'<ellipse cx="55" cy="78" rx="32" ry="10"/><path d="M55 8L23 78M55 8L87 78"/>',bol:'<circle cx="55" cy="48" r="38"/><ellipse cx="55" cy="48" rx="38" ry="11"/>',piramide:'<polygon points="55,7 15,82 95,82"/><path d="M55 7L70 62M15 82L70 62L95 82"/>'};return `<svg viewBox="0 0 115 95" fill="none" stroke="#111" stroke-width="2.4">${q[s]}</svg>`}
function volumeSvg(d){return `<svg width="12cm" height="7cm" viewBox="0 0 150 90" fill="none" stroke="#111" stroke-width="1.7"><rect x="15" y="28" width="85" height="48"/><rect x="42" y="10" width="85" height="48"/><path d="M15 28L42 10M100 28L127 10M100 76L127 58M15 76L42 58"/><text x="48" y="86" font-size="6">Meet lengte, breedte en hoogte.</text></svg>`}
function actions(e){const b=e.target.closest('[data-a]');if(!b)return;const card=e.target.closest('[data-id]'),i=exercises.findIndex(x=>x.id===card.dataset.id),a=b.dataset.a;if(a==='del')exercises.splice(i,1);if(a==='new')exercises[i]=make(exercises[i].type);if(a==='copy'){const c=JSON.parse(JSON.stringify(exercises[i]));c.id=id();exercises.splice(i+1,0,c)}if(a==='up'&&i>0)[exercises[i-1],exercises[i]]=[exercises[i],exercises[i-1]];if(a==='down'&&i<exercises.length-1)[exercises[i+1],exercises[i]]=[exercises[i],exercises[i+1]];render()}
function dragStart(e){const a=e.target.closest('[data-id]');if(a){dragId=a.dataset.id;a.classList.add('dragging')}}function drop(e){const t=e.target.closest('[data-id]');if(!t||!dragId)return;const from=exercises.findIndex(x=>x.id===dragId),to=exercises.findIndex(x=>x.id===t.dataset.id);const[m]=exercises.splice(from,1);exercises.splice(to,0,m);dragId=null;render()}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();})();
