/* Picture-based exercises; model answers are rendered only in solution mode. */
(() => {
  const assetBase=new URL('figuren/',document.currentScript.src);
  const types={
    flatCross:['flat','Vlakke figuren zoeken met gekleurde kruisjes'],
    flatColorTable:['flat','Vormen op de juiste plaats tekenen in een kleurentabel'],
    flatColor:['flat','Vlakke figuren kleuren volgens de legende'],
    flatPhotoMatch:['flat','Foto’s verbinden met de juiste vlakke figuur'],
    flatPhotoFind:['flat','Vlakke figuren herkennen in foto’s'],
    flatPictureFind:['flat','Vormen herkennen in samengestelde figuurtjes'],
    flatPiecesMatch:['flat','Losse vormen verbinden met een figuurtje'],
    solidHelp:['solids','Uitleg: vlakke figuren en ruimtelichamen'],
    solidSortPictures:['solids','Vlakke figuren en ruimtelichamen sorteren'],
    solidRollSlide:['solids','Ruimtelichamen: rollen en schuiven']
  };
  const palette={circle:'#087bb9',triangle:'#e97c25',square:'#ce3b32',rectangle:'#2d934e'};
  const variants={flatCross:12,flatColor:12,flatColorTable:4,flatPhotoMatch:4,flatPhotoFind:4,flatPictureFind:4,flatPiecesMatch:4,solidHelp:1,solidSortPictures:10,solidRollSlide:5};
  const names={circle:'cirkel',triangle:'driehoek',square:'vierkant',rectangle:'rechthoek'};
  const keys=Object.keys(names);
  const solids={cube:'kubus',block:'balk',sphere:'bol',cylinder:'cilinder',cone:'kegel',pyramid:'piramide'};
  const style=document.createElement('style');
  style.textContent=`.figure-extra>.editbar{position:static;transform:none;justify-content:flex-end;margin-bottom:2mm}.figure-extra-svg{display:block;width:100%;height:auto;margin:3mm auto}.figure-photo{display:block;width:100%;height:34mm}.figure-picture{display:block;width:100%;height:39mm}.figure-object-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:4mm;margin:3mm 0}.figure-object-card{text-align:center;font-size:10pt}.figure-options{text-align:left;font-size:9pt;display:grid;grid-template-columns:1fr 1fr;gap:2mm}.figure-check{display:inline-flex;width:3.5mm;height:3.5mm;border:1px solid #6d8595;color:#087bb9;align-items:center;justify-content:center;margin-right:1mm}.figure-table{width:100%;border-collapse:collapse;margin:3mm 0;font-size:10pt}.figure-table th,.figure-table td{border:1px solid #829eaf;text-align:center;height:18mm;padding:2mm}.figure-table th svg,.figure-table td svg{width:16mm;height:14mm;display:block;margin:auto}.figure-help{border:1px solid #7aafa2;border-radius:3mm;padding:4mm;margin:3mm 0;font-size:10.5pt;line-height:1.4}.figure-help h4{margin:0 0 2mm;color:#257967}.figure-help p{margin:2mm 0}.figure-solid-row{display:grid;grid-template-columns:repeat(6,1fr);gap:2mm;text-align:center;font-size:9pt}.figure-solid-row svg{width:100%;height:25mm}.figure-sort-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:4mm}.figure-sort-grid svg{width:100%;height:30mm}.figure-sort-cell{text-align:center;font-size:10pt}.figure-solution{color:#087bb9}.figure-legend{font-size:10pt;line-height:1.6;margin:2mm 0}.figure-venn-labels{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm;font-size:9pt}.figure-venn-labels div{border:1px solid #829eaf;min-height:18mm;padding:2mm;text-align:center}.figure-venn-labels b{display:block;color:#087bb9;margin-top:2mm}`;
  document.head.append(style);
  style.textContent+=`.figure-object-grid{gap:0}.figure-object-card{min-width:0;padding:2mm 2.5mm}.figure-object-card + .figure-object-card{border-left:.3mm solid #829eaf}.figure-options{column-gap:1mm;margin-top:2mm}.figure-options>div{white-space:nowrap}`;
  for(const [type,[tab,label]] of Object.entries(types)){
    const heading={flatCross:'Vormen herkennen en kleuren',flatPhotoMatch:'Vormen in foto’s en figuurtjes',solidHelp:'Vlakke figuren en ruimtelichamen',solidRollSlide:'Rollen en schuiven'}[type];
    if(heading){const h=document.createElement('h3');h.textContent=heading;document.querySelector(`[data-panel="${tab}"]`).append(h);}
    const group=document.createElement('div');group.className='group exercise-picker';group.innerHTML=`<div class="group-title" role="button" tabindex="0" aria-expanded="false">${label}</div><div class="type-count"><span class="mini">Aantal opdrachten</span><label class="field"><input id="count-${type}" type="number" min="0" max="${Math.min(8,variants[type])}" value="0" aria-label="Aantal: ${label}"></label></div>`;
    const title=group.querySelector('.group-title'),input=group.querySelector('input');const toggle=()=>{const open=group.classList.toggle('selected');title.setAttribute('aria-expanded',String(open));input.value=open?1:0;};title.onclick=toggle;title.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}};
    document.querySelector(`[data-panel="${tab}"]`).append(group);document.querySelector('#addType').add(new Option(label,type));
  }
  const baseMake=make;make=function(type,forced={}){const ex=baseMake(type,forced);if(types[type])ex.gridVariant=forced.gridVariant??n(0,variants[type]-1);return ex;};
  const baseTitle=titleFor;titleFor=t=>types[t]?.[1]||baseTitle(t);
  const baseDesired=desired;desired=function(){const out=baseDesired(),tab=document.querySelector('.tab-panel.active')?.dataset.panel;for(const [type,[group]] of Object.entries(types)){if(group!==tab)continue;const count=Math.max(0,Math.min(8,Math.floor(Number(document.querySelector('#count-'+type).value)||0)));for(let i=0;i<count;i++){const ex=makeUnique(type,{},[...state.exercises,...out]);if(ex)out.push(ex);}}return out;};
  function shape(type,x=0,y=0,size=50,fill='white',rotation=0){
    const drawing={circle:'<circle cx="30" cy="30" r="22"/>',triangle:'<path d="M30 6 55 52H5Z"/>',square:'<rect x="9" y="9" width="42" height="42"/>',rectangle:'<rect x="3" y="17" width="54" height="26"/>',oval:'<ellipse cx="30" cy="30" rx="14" ry="25"/>',hexagon:'<path d="M16 7H44L58 30 44 53H16L2 30Z"/>',pentagon:'<path d="M30 3 57 23 46 55H14L3 23Z"/>',trapezoid:'<path d="M15 10H45L57 50H3Z"/>'}[type];
    return `<svg x="${x}" y="${y}" width="${size}" height="${size}" viewBox="0 0 60 60"><g transform="rotate(${rotation} 30 30)" fill="${fill}" stroke="#333" stroke-width="1.2">${drawing}</g></svg>`;
  }
  let cropSequence=0;
  function crop(index,characters=false,x=0,y=0,w=140,h=110){
    const cols=characters?2:4,rows=characters?2:3,cw=1536/cols,ch=1024/rows;
    const sx=(index%cols)*cw,sy=Math.floor(index/cols)*ch,clipId='figure-crop-'+(++cropSequence);
    // Clip to the source cell, not just the viewport: letterboxing must not reveal its neighbours.
    return `<svg x="${x}" y="${y}" width="${w}" height="${h}" viewBox="${sx} ${sy} ${cw} ${ch}" overflow="hidden"><defs><clipPath id="${clipId}" clipPathUnits="userSpaceOnUse"><rect x="${sx}" y="${sy}" width="${cw}" height="${ch}"/></clipPath></defs><image clip-path="url(#${clipId})" href="${new URL(characters?'vormenfiguurtjes.png':'voorwerpen.png',assetBase).href}" width="1536" height="1024"/></svg>`;
  }
  const ordered=(a,v)=>a.slice(v%a.length).concat(a.slice(0,v%a.length));
  function shapeSearch(ex,coloring=false){const v=ex.gridVariant||0,entries=ordered(['circle','triangle','square','rectangle','oval','hexagon','square','circle','trapezoid','triangle','rectangle','pentagon'],v);return `<p class="prompt">${coloring?'Kleur de vormen volgens de legende. Laat de andere vormen wit.':'Zet een kruisje in elke gevraagde figuur. Laat de andere figuren leeg.'}</p><p class="figure-legend">Blauw: cirkels · Oranje: driehoeken · Rood: vierkanten · Groen: rechthoeken die geen vierkant zijn.</p><svg class="figure-extra-svg" viewBox="0 0 600 245">${entries.map((type,i)=>{const x=8+(i%6)*100,y=8+Math.floor(i/6)*120,c=palette[type],angle=(type==='square'||type==='rectangle')?(i%2?35:0):0;return shape(type,x,y,80,state.solutionMode&&coloring&&c?c:'white',angle)+(state.solutionMode&&!coloring&&c?`<path class="figure-model" d="M${x+32} ${y+32}l16 16m0-16-16 16" fill="none" stroke="${c}" stroke-width="2"/>`:'');}).join('')}</svg>`;}
  function colorWord(color,type){const words={'#e97c25':['oranje','oranje'],'#ce3b32':['rood','rode'],'#2d934e':['groen','groene'],'#087bb9':['blauw','blauwe']};return words[color][type==='square'?0:1];}
  function colorTable(ex){const v=ex.gridVariant||0,columns=ordered(keys,v),colors=ordered(['#e97c25','#ce3b32','#2d934e','#087bb9'],v+1),wanted=ordered(keys,v+2);return `<p class="prompt">Teken op de juiste plaats:</p><ul class="figure-legend" style="margin:0 0 3mm;padding-left:6mm">${colors.map((c,i)=>`<li>een <span style="color:${c}">${colorWord(c,wanted[i])}</span> ${names[wanted[i]]}${i===colors.length-1?'.':';'}</li>`).join('')}</ul><table class="figure-table"><thead><tr><th></th>${columns.map(t=>`<th>${shape(t)}</th>`).join('')}</tr></thead><tbody>${colors.map((c,i)=>`<tr><th style="background:${c};width:14mm"></th>${columns.map(t=>`<td>${state.solutionMode&&wanted[i]===t?shape(t,0,0,50,c):''}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
  function photoMatch(ex){const v=ex.gridVariant||0,objects=ordered([8,9,10,11],v),answers={8:'circle',9:'rectangle',10:'square',11:'triangle'},bottom=ordered(keys,v+1);return `<p class="prompt">Welke vlakke figuur herken je in de omtrek? Verbind elke foto met de juiste figuur.</p><svg class="figure-extra-svg" viewBox="0 0 600 280">${objects.map((id,i)=>`${crop(id,false,i*150,0,140,110)}<circle cx="${70+i*150}" cy="115" r="2"/>`).join('')}${bottom.map((t,i)=>`<circle cx="${70+i*150}" cy="200" r="2"/>${shape(t,40+i*150,210,60)}`).join('')}${state.solutionMode?objects.map((id,i)=>`<path class="figure-model" d="M${70+i*150} 115L${70+bottom.indexOf(answers[id])*150} 200" stroke="#087bb9" stroke-width="1.5"/>`).join(''):''}</svg>`;}
  const characterShapes=[['circle','triangle'],['rectangle','triangle','circle'],['square','triangle','rectangle'],['square','rectangle','circle']];
  function photoFind(ex){const entries=[{id:0,caption:'Het dak en de ramen',shapes:['triangle','square']},{id:1,caption:'De laadbak en de wielen',shapes:['rectangle','circle']},{id:2,caption:'De wijzerplaat',shapes:['circle']},{id:9,caption:'De omtrek van de kaart',shapes:['rectangle']}];return '<p class="prompt">Welke vlakke figuren herken je in de genoemde delen van de foto? Kruis aan. Kies bij een vierkant alleen ‘vierkant’.</p><div class="figure-object-grid">'+ordered(entries,ex.gridVariant||0).map(e=>`<div class="figure-object-card"><svg class="figure-photo" viewBox="0 0 140 110">${crop(e.id)}</svg><p>${e.caption}</p><div class="figure-options">${keys.map(t=>`<div><span class="figure-check">${state.solutionMode&&e.shapes.includes(t)?'×':''}</span>${names[t]}</div>`).join('')}</div></div>`).join('')+'</div>';}
  function pictureFind(ex){return '<p class="prompt">Kruis de vlakke figuren aan die je in elk figuurtje herkent. Kleine ogen tellen ook mee. Kies bij vierkanten alleen ‘vierkant’.</p><div class="figure-object-grid">'+ordered([0,1,2,3],ex.gridVariant||0).map(id=>`<div class="figure-object-card"><svg class="figure-picture" viewBox="0 0 140 110">${crop(id,true)}</svg><div class="figure-options">${keys.map(t=>`<div><span class="figure-check">${state.solutionMode&&characterShapes[id].includes(t)?'×':''}</span>${names[t]}</div>`).join('')}</div></div>`).join('')+'</div>';}
  // One entry per physical part, including each eye, window, arm and leg.
  const characterPieces=[
    [['circle',36,36,'#0088f5'],['tail',18,29,'#ff8800'],['circle',5,5,'#000000']],
    [['rectangle',19,35,'#0088f5'],['triangle',25,17,'#ff1717'],['finLeft',15,23,'#ff8800'],['finRight',15,23,'#ff8800'],['circle',12,12,'#ffe000']],
    [['square',33,33,'#ff8800'],['triangle',38,18,'#ff1717'],['rectangle',10,19,'#0088f5'],['square',9,9,'#0088f5'],['square',9,9,'#0088f5']],
    [['square',21,21,'#35c82c'],['rectangle',25,30,'#0088f5'],['rectangle',6,20,'#ff8800'],['rectangle',6,20,'#ff8800'],['rectangle',8,22,'#ff8800'],['rectangle',8,22,'#ff8800'],['circle',4.5,4.5,'#000000'],['circle',4.5,4.5,'#000000']]
  ];
  function loosePieces(id,row){return `<g class="figure-piece-set" data-character="${id}">${characterPieces[id].map(([kind,w,h,color],j)=>{
    const x=5+(j%4)*40+(38-w)/2,y=row*110+(characterPieces[id].length>4?26+Math.floor(j/4)*45:55)-h/2;
    const drawing=kind==='circle'?`<ellipse cx="${w/2}" cy="${h/2}" rx="${w/2}" ry="${h/2}"/>`:kind==='triangle'?`<path d="M${w/2} 0L${w} ${h}H0Z"/>`:kind==='tail'?`<path d="M0 0L${w} ${h/2}L0 ${h}Z"/>`:kind==='finLeft'?`<path d="M${w} 0V${h}H0Z"/>`:kind==='finRight'?`<path d="M0 0L${w} ${h}H0Z"/>`:`<rect width="${w}" height="${h}"/>`;
    return `<g class="figure-loose-piece" data-kind="${kind}" transform="translate(${x},${y})" fill="${color}" stroke="#222" stroke-width=".8">${drawing}</g>`;
  }).join('')}</g>`;}
  function piecesMatch(ex){const v=ex.gridVariant||0,left=ordered([0,1,2,3],v),right=ordered([2,0,3,1],v);return `<p class="prompt">Verbind elk groepje losse vormen met het figuurtje dat je ermee kunt maken. Gebruik alle vormen uit het groepje, elk precies één keer. De ogen tellen ook mee.</p><svg class="figure-extra-svg" viewBox="0 0 600 460">${left.map((id,i)=>`${loosePieces(id,i)}<circle cx="175" cy="${55+i*110}" r="2.5"/>`).join('')}${right.map((id,i)=>`<circle cx="405" cy="${55+i*110}" r="2.5"/>${crop(id,true,418,i*110,175,105)}`).join('')}${state.solutionMode?left.map((id,i)=>`<path class="figure-model" d="M175 ${55+i*110}L405 ${55+right.indexOf(id)*110}" stroke="#087bb9" stroke-width="1.5"/>`).join(''):''}</svg>`;}
  function help(){return `<div class="figure-help"><h4>Vlakke figuren</h4><p>Een vlakke figuur heeft lengte en breedte. We tekenen ze plat.</p><svg viewBox="0 0 400 65" style="width:100%;height:22mm">${keys.map((t,i)=>shape(t,40+i*85,0,60,'#c9deed')).join('')}</svg><h4>Ruimtelichamen</h4><p>Een ruimtelichaam heeft ook hoogte of diepte. Het neemt ruimte in.</p><div class="figure-solid-row">${Object.entries(solids).map(([t,name])=>`<div>${solidSVG(t)}${name}</div>`).join('')}</div></div>`;}
  function sort(ex){const v=ex.gridVariant||0,base=[{flat:'triangle'},{photo:4},{solid:'cube'},{photo:5},{photo:6},{solid:'cylinder'},{flat:'rectangle'},{photo:7},{flat:'circle'},{photo:3}],entries=ordered(base,v);return `<p class="prompt">Is het een vlakke figuur of een ruimtelichaam? Schrijf de nummers op de juiste plaats.</p><div class="figure-sort-grid">${entries.map((e,i)=>`<div class="figure-sort-cell"><b>${i+1}</b>${e.flat?shape(e.flat):e.solid?solidSVG(e.solid):`<svg viewBox="0 0 140 110">${crop(e.photo)}</svg>`}</div>`).join('')}</div><table class="figure-table"><tr><th>Vlakke figuren</th><td class="figure-solution">${state.solutionMode?entries.flatMap((e,i)=>e.flat?[i+1]:[]).join(' · '):''}</td></tr><tr><th>Ruimtelichamen</th><td class="figure-solution">${state.solutionMode?entries.flatMap((e,i)=>!e.flat?[i+1]:[]).join(' · '):''}</td></tr></table>`;}
  function rollSlide(ex){const entries=ordered(['sphere','cone','block','pyramid','cylinder'],ex.gridVariant||0),nums=group=>entries.flatMap((t,i)=>group.includes(t)?[i+1]:[]).join(', ');return `<p class="prompt">Schrijf de nummers in de juiste delen van de verzamelingen. Geef de drie vakken onderaan de juiste naam.</p><p class="figure-legend">Kies uit: alleen rollen · rollen en schuiven · alleen schuiven.<br>We bekijken of een lichaam kan rollen op een gebogen oppervlak of schuiven op een plat vlak.</p><div class="figure-sort-grid">${entries.map((t,i)=>`<div class="figure-sort-cell">${solidSVG(t)}<b>${i+1}</b></div>`).join('')}</div><svg class="figure-extra-svg" viewBox="0 0 600 190"><ellipse cx="230" cy="85" rx="130" ry="72" fill="none" stroke="#444"/><ellipse cx="370" cy="85" rx="130" ry="72" fill="none" stroke="#444"/><g fill="none" stroke="#829eaf"><path d="M170 135L100 185M300 130V185M430 135L500 185"/></g>${state.solutionMode?`<g class="figure-model" font-family="Arial" font-size="18" fill="#087bb9"><text x="165" y="90">${nums(['sphere'])}</text><text x="275" y="90">${nums(['cone','cylinder'])}</text><text x="400" y="90">${nums(['block','pyramid'])}</text></g>`:''}</svg><div class="figure-venn-labels">${['alleen rollen','rollen en schuiven','alleen schuiven'].map((t,i)=>`<div>Vak ${i+1}<b>${state.solutionMode?t:'................................'}</b></div>`).join('')}</div>`;}
  const builders={flatCross:ex=>shapeSearch(ex),flatColor:ex=>shapeSearch(ex,true),flatColorTable:colorTable,flatPhotoMatch:photoMatch,flatPhotoFind:photoFind,flatPictureFind:pictureFind,flatPiecesMatch:piecesMatch,solidHelp:help,solidSortPictures:sort,solidRollSlide:rollSlide};
  const baseRender=renderEx;renderEx=function(ex,index){if(!types[ex.type])return baseRender(ex,index);return `<section class="exercise figure-extra" data-id="${ex.id}" data-figure-type="${ex.type}"><div class="editbar no-print"><button data-act="up">↑</button><button data-act="down">↓</button><button data-act="replace" title="Andere opdracht">↻</button><button data-act="addsame">+ oefening</button><button data-act="delete">✕</button></div><h3>${index+1}. ${types[ex.type][1]}</h3>${builders[ex.type](ex)}</section>`;};
})();
