/* Four original scenes. Plan, elevations and answer key share one spatial model. */
(() => {
  const base=new URL('aanzichten/kijkplaatsen/',document.currentScript.src);
  const robotUrl=new URL('ruimte/robot-en-voorwerpen.png',document.currentScript.src).href;
  const scenes=[
    {id:'tuin',name:'In de tuin',names:['dennenboom','ronde struik','bloemen'],positions:[[-.7,0],[.7,0],[-.7,.8]],heights:[125,90,62],crops:[[140,20,335,602],[607,205,330,415],[1098,325,326,295],[131,640,346,336],[600,646,337,331],[1090,650,351,326]]},
    {id:'speelplaats',name:'Op de speelplaats',names:['kegel','trommel','gele bal'],positions:[[0,-.7],[0,.7],[.8,.7]],heights:[125,82,47],crops:[[87,30,374,490],[592,214,366,303],[1180,310,218,210],[81,561,383,390],[589,559,375,391],[1160,626,247,250]]},
    {id:'feest',name:'Op het feest',names:['cadeaudoos','taart','rode bal'],positions:[[-.7,0],[.7,0],[.7,-.8]],heights:[125,83,48],crops:[[119,20,326,482],[550,199,451,303],[1167,252,258,255],[101,563,365,366],[565,530,423,423],[1155,607,282,291]]},
    {id:'strand',name:'Op het strand',names:['parasol','emmer','groene bal'],positions:[[0,.7],[0,-.7],[-.8,-.7]],heights:[125,78,48],crops:[[85,40,486,562],[645,338,252,271],[1143,419,201,195],[123,626,378,372],[630,677,279,276],[1140,729,200,189]]}
  ];
  // Looking inward from north, east, south and west. Screen-right rotates with the observer.
  const axes=[{right:[-1,0],depth:[0,1]},{right:[0,-1],depth:[-1,0]},{right:[1,0],depth:[0,-1]},{right:[0,1],depth:[1,0]}];
  const types={viewpointMatch:['Wie ziet wat? Verbind.','Verbind elke kijkplaats met het juiste beeld.'],viewpointNumber:['Wat zie je vanaf deze plaats?','Schrijf bij elke prent het nummer van de juiste kijkplaats.']};
  const owns=t=>!!types[t]||t==='viewpointHelp';
  function projection(scene,side){const a=axes[side];return scene.positions.map(([x,y],id)=>({id,x:x*a.right[0]+y*a.right[1],depth:x*a.depth[0]+y*a.depth[1]})).sort((a,b)=>b.depth-a.depth||a.id-b.id);}
  function sprite(scene,id,plan,x,y,w,h){
    const crop=scene.crops?.[id+(plan?3:0)]||[id*512,plan?512:0,512,512];
    return `<svg style="overflow:hidden" x="${x}" y="${y}" width="${w}" height="${h}" viewBox="${crop.join(' ')}" preserveAspectRatio="xMidYMax meet"><image href="${new URL(scene.id+'.png',base).href}" width="1536" height="1024"/></svg>`;
  }
  function view(scene,side){
    return `<svg class="viewpoint-view" viewBox="0 0 300 180" role="img" aria-label="Aanzicht van de opstelling">${projection(scene,side).map(p=>{
      const h=scene.heights[p.id],crop=scene.crops?.[p.id],w=crop?h*crop[2]/crop[3]:h;
      return sprite(scene,p.id,false,150+p.x*88-w/2,160-p.depth*6-h,w,h);
    }).join('')}</svg>`;
  }
  function robot(pose,x,y){
    // Tight viewports remove empty sprite-sheet padding and keep all poses equally tall.
    const crops=[[145,20,283,475],[1140,20,220,478],[637,20,265,475],[170,518,235,476]];
    return `<svg style="overflow:hidden" x="${x}" y="${y}" width="60" height="90" viewBox="${crops[pose].join(' ')}" preserveAspectRatio="xMidYMid meet"><image href="${robotUrl}" width="1536" height="1024"/></svg>`;
  }
  function plan(scene){
    const places=[[200,50],[350,200],[200,350],[50,200]];
    return `<svg class="viewpoint-plan" viewBox="0 0 400 400" role="img" aria-label="Bovenaanzicht met vier genummerde kijkplaatsen"><rect x="108" y="108" width="184" height="184" rx="12" fill="#f7faf8" stroke="#91ada5"/>${scene.positions.map(([x,y],i)=>{const c=scene.crops[i],size=scene.heights[i]*c[2]/c[3]*48/88;return sprite(scene,i,true,200+x*48-size/2,200+y*48-size/2,size,size);}).join('')}${places.map(([x,y],i)=>`${robot(i,x-30,y-45)}<circle cx="${x+(i===1?-43:43)}" cy="${y}" r="11" fill="white" stroke="#364b5c"/><text x="${x+(i===1?-43:43)}" y="${y+4}" text-anchor="middle" font-size="14" font-weight="bold">${i+1}</text>`).join('')}</svg>`;
  }
  const orders=[[2,0,3,1],[1,3,0,2],[3,2,1,0],[1,0,3,2]];
  function sceneFor(ex){return scenes[ex.sceneId||0];}
  function connections(ex,solved){return solved?Object.fromEntries(orders[ex.sceneId||0].map((side,card)=>[side,card])):ex.viewConnections||{};}
  function match(ex){
    const scene=sceneFor(ex),order=orders[ex.sceneId||0],links=connections(ex,state.solutionMode);
    return `${plan(scene)}<p class="viewpoint-caption">Zo staan de voorwerpen, gezien van boven. De robots kijken naar het midden.</p><div class="viewpoint-match"><div class="viewpoint-places">${axes.map((_,i)=>`<button type="button" class="viewpoint-dot-button" data-view-start="${i}" aria-label="Verbind kijkplaats ${i+1}">${i+1}<span>●</span></button>`).join('')}</div><svg class="viewpoint-lines" viewBox="0 0 800 95" preserveAspectRatio="none">${Object.entries(links).map(([side,card])=>`<line x1="${100+Number(side)*200}" y1="3" x2="${100+Number(card)*200}" y2="92" stroke="${state.solutionMode?'#087bb9':'#344b5c'}" stroke-width="2"/>`).join('')}</svg><div class="viewpoint-cards">${order.map((side,i)=>`<div class="viewpoint-card"><button type="button" class="viewpoint-end" data-view-end="${i}" aria-label="Verbind met prent ${i+1}">●</button>${view(scene,side)}</div>`).join('')}</div></div>`;
  }
  function numbers(ex){const scene=sceneFor(ex);return `<div class="viewpoint-number-layout"><div>${plan(scene)}<p class="viewpoint-caption">De opstelling van boven. De robots kijken naar het midden.</p></div><div class="viewpoint-number-cards">${orders[ex.sceneId||0].map((side,i)=>`<div class="viewpoint-card">${view(scene,side)}<span class="viewpoint-answer ${state.solutionMode?'viewpoint-solution':''}" contenteditable="${!state.solutionMode}" data-view-answer="${i}" role="textbox" aria-label="Nummer bij prent ${i+1}">${escapeHtml(state.solutionMode?String(side+1):ex.viewAnswers?.[i]||'')}</span></div>`).join('')}</div></div>`;}
  function help(){
    const scene=scenes[0];
    return `<div class="viewpoint-help"><b>Wat zie je vanaf jouw plaats?</b><p>De tekening van boven toont waar alles staat. De robots kijken naar dezelfde voorwerpen, elk vanaf een andere kant.</p><div class="viewpoint-help-example"><div><b>De opstelling van boven</b>${plan(scene)}</div><div class="viewpoint-help-views"><div class="viewpoint-card"><b>Dit ziet robot 1</b>${view(scene,0)}<p>De ronde struik staat links.<br>De dennenboom staat rechts.</p></div><div class="viewpoint-card"><b>Dit ziet robot 3</b>${view(scene,2)}<p>De dennenboom staat links.<br>De ronde struik staat rechts.</p></div></div></div><p><b>De voorwerpen blijven staan.</b> Als jij naar de overkant gaat, verandert wat je links en rechts ziet. Een voorwerp kan ook iets achter zich verbergen: robot 1 ziet de bloemen niet, robot 3 wel.</p></div>`;
  }
  const style=document.createElement('style');style.textContent=`.viewpoint-exercise{break-inside:avoid;padding-bottom:3mm}.viewpoint-exercise>.editbar{position:static;transform:none;justify-content:flex-end}.viewpoint-plan{display:block;width:92mm;height:92mm;margin:auto}.viewpoint-caption{font-size:9pt;text-align:center;margin:1mm 0 3mm;color:#425b68}.viewpoint-view{display:block;width:100%;height:auto}.viewpoint-places,.viewpoint-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr))}.viewpoint-dot-button,.viewpoint-end{border:0;background:transparent;font:inherit;padding:0;color:#152b38;cursor:pointer}.viewpoint-dot-button{display:flex;align-items:center;flex-direction:column;font-weight:bold;gap:1mm}.viewpoint-dot-button[aria-pressed="true"]{outline:2px solid #258674;border-radius:3mm}.viewpoint-lines{display:block;width:100%;height:23mm}.viewpoint-card{min-width:0;text-align:center;border:1px solid #9db5c1;border-radius:2mm;padding:1mm;margin:0 1mm}.viewpoint-end{display:block;width:100%;line-height:4mm;margin-top:-2mm}.viewpoint-number-layout{display:grid;grid-template-columns:1fr 1.15fr;gap:3mm;align-items:center}.viewpoint-number-layout .viewpoint-plan{width:100%;height:auto}.viewpoint-number-cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:3mm}.viewpoint-answer{display:flex;width:14mm;min-height:12mm;align-items:center;justify-content:center;border:1px solid #8ba4b4;margin:1mm auto;font-size:13pt}.viewpoint-solution{color:#087bb9}.viewpoint-help{padding:4mm;border:1px solid #82b6a7;border-radius:3mm;background:#f3faf7;font-size:10.5pt;line-height:1.4}.viewpoint-notice{font-size:12px;color:#72500c;margin:2mm 0}.viewpoint-exercise h3{margin-bottom:2mm}@media print{.viewpoint-dot-button,.viewpoint-end{pointer-events:none}.viewpoint-solution{print-color-adjust:exact;-webkit-print-color-adjust:exact}}`;
  style.textContent+=`.viewpoint-help-example{display:grid;grid-template-columns:1fr 1.4fr;align-items:center;gap:3mm;text-align:center}.viewpoint-help-example .viewpoint-plan{width:64mm;height:64mm;max-width:100%}.viewpoint-help-views{display:grid;grid-template-columns:1fr 1fr;gap:2mm}.viewpoint-help-views .viewpoint-card{background:#fff;margin:0;padding:2mm}.viewpoint-help-views p{font-size:9pt;line-height:1.4;margin:1mm 0}.viewpoint-help-views b{font-size:10pt}`;
  document.head.append(style);
  const panel=document.querySelector('[data-panel="views"]');
  const section=document.createElement('div');section.className='viewpoint-picker';
  section.innerHTML='<h3>Kijken vanuit een plaats</h3><div class="mini">Vier eigen scènes: tuin, speelplaats, feest en strand. Per oefensoort maximaal vier verschillende opdrachten.</div><label class="check"><input id="viewpointHelp" type="checkbox" checked> Uitlegkader toevoegen</label>'+Object.entries(types).map(([type,[label]])=>`<div class="group exercise-picker"><div class="group-title" tabindex="0" role="button" aria-expanded="false">${label}</div><div class="type-count"><span>Aantal opdrachten (max. 4)</span><label class="field"><input id="count-${type}" type="number" min="0" max="4" value="0" aria-label="Aantal: ${label}"></label></div></div>`).join('')+'<p class="viewpoint-notice" role="status"></p>';
  panel.append(section);
  section.querySelectorAll('.group').forEach(group=>{const title=group.querySelector('.group-title'),input=group.querySelector('input');const toggle=()=>{const on=group.classList.toggle('selected');input.value=on?1:0;title.setAttribute('aria-expanded',String(on));};title.onclick=toggle;title.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();toggle();}};});
  Object.entries(types).forEach(([type,[label]])=>$('#addType').add(new Option(label,type)));
  const baseMake=make;make=function(type,forced={}){return owns(type)?{id:uid(),type,sceneId:n(0,3),...forced}:baseMake(type,forced);};
  const baseUnique=makeUnique;makeUnique=function(type,forced={},existing=state.exercises){if(!owns(type))return baseUnique(type,forced,existing);if(type==='viewpointHelp')return existing.some(e=>e.type===type)?null:make(type);const used=new Set(existing.filter(e=>e.type===type).map(e=>e.sceneId)),available=scenes.map((_,i)=>i).filter(i=>!used.has(i));return available.length?make(type,{...forced,sceneId:available[n(0,available.length-1)]}):null;};
  const baseDesired=desired;desired=function(){const out=baseDesired();if(!panel.classList.contains('active'))return out;let requested=0,added=0;for(const type of Object.keys(types)){const count=Math.max(0,Math.min(4,Math.floor(Number($('#count-'+type).value)||0)));requested+=count;for(let i=0;i<count;i++){const ex=makeUnique(type,{},[...state.exercises,...out]);if(ex){out.push(ex);added++;}}}section.querySelector('[role="status"]').textContent=requested>added?'Alle vier de scènes van deze oefensoort staan al in de bundel. Er worden geen dubbele opdrachten toegevoegd.':'';if(added&&$('#viewpointHelp').checked&&!state.exercises.some(e=>e.type==='viewpointHelp'))out.unshift(make('viewpointHelp'));return out;};
  const baseTitle=titleFor;titleFor=t=>types[t]?.[0]||(t==='viewpointHelp'?'Kijken vanuit een plaats: uitleg':baseTitle(t));
  const baseRender=renderEx;renderEx=function(ex,index){if(!owns(ex.type))return baseRender(ex,index);const full=state.exercises.filter(e=>e.type===ex.type).length>=4;const number=meetkundeAssignmentGroups().findIndex(g=>g.includes(ex))+1;return `<section class="exercise viewpoint-exercise" data-id="${ex.id}" data-view-type="${ex.type}" data-scene="${sceneFor(ex).id}"><div class="editbar no-print"><button data-act="up">↑</button><button data-act="down">↓</button>${ex.type==='viewpointHelp'?'':`${full?'':'<button data-act="replace" title="Andere scène">↻</button><button data-act="addsame">+ oefening</button>'}<button data-view-clear>Antwoorden wissen</button>`}<button data-act="delete">✕</button></div><h3>${number||index+1}. ${escapeHtml(titleFor(ex.type))}${ex.type==='viewpointHelp'?'':' — '+sceneFor(ex).name}</h3>${types[ex.type]?`<p class="prompt" data-view-prompt contenteditable="${!state.solutionMode}">${escapeHtml(ex.viewPrompt||types[ex.type][1])}</p>`:''}${ex.type==='viewpointMatch'?match(ex):ex.type==='viewpointNumber'?numbers(ex):help()}</section>`;};
  const baseBind=bindEdit;bindEdit=function(){baseBind();$$('#pages .viewpoint-exercise').forEach(section=>{const ex=state.exercises.find(e=>String(e.id)===section.dataset.id);if(!ex)return;const prompt=section.querySelector('[data-view-prompt]');if(prompt)prompt.oninput=()=>ex.viewPrompt=prompt.textContent;const clear=section.querySelector('[data-view-clear]');if(clear)clear.onclick=()=>{ex.viewConnections={};ex.viewAnswers={};render();};const replace=section.querySelector('[data-act="replace"]');if(replace)replace.onclick=()=>{const fresh=makeUnique(ex.type,{},state.exercises);if(fresh){state.exercises.splice(state.exercises.indexOf(ex),1,fresh);render();}};if(state.solutionMode)return;section.querySelectorAll('[data-view-answer]').forEach(input=>input.oninput=()=>{ex.viewAnswers??={};ex.viewAnswers[input.dataset.viewAnswer]=input.textContent;});let selected=null;section.querySelectorAll('[data-view-start]').forEach(button=>button.onclick=()=>{selected=Number(button.dataset.viewStart);section.querySelectorAll('[data-view-start]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});section.querySelectorAll('[data-view-end]').forEach(button=>button.onclick=()=>{if(selected===null)return;ex.viewConnections??={};const card=Number(button.dataset.viewEnd);for(const [side,target]of Object.entries(ex.viewConnections))if(target===card)delete ex.viewConnections[side];ex.viewConnections[selected]=card;render();});});};
  if(window.MeetkundeShared){const catalog=window.MeetkundeShared.catalog;window.MeetkundeShared.catalog=()=>[...catalog(),...Object.entries(types).map(([type,[label]])=>({group:'Aanzichten',type,label}))];}
  window.ViewpointExercises={scenes,projection,orders,connections};
})();
