export const TASKS=[{id:'bridge',at:10,count:3,title:'Maak de brug',icon:'🌉'},{id:'basket',at:73,count:3,title:'Vul de mand',icon:'🥕'},{id:'path',at:104,count:2,title:'Maak het pad',icon:'🏡'}];
export const PARTY_TASKS=[{id:'gift',at:10,count:2,title:'Pak het cadeau in',icon:'🎁'},{id:'gate',at:74,count:3,title:'Open de spoorboom',icon:'🚧'},{id:'party',at:104,count:3,title:'Maak het feest klaar',icon:'🎈'}];
export const RESCUE_TASKS=[{id:'lights',at:10,count:3,title:'Zoek het vosje',icon:'🔦'},{id:'logs',at:74,count:4,title:'Maak het spoor vrij',icon:'🪵'},{id:'beacon',at:104,count:3,title:'Licht in de vuurtoren',icon:'💡'}];
export const POST_TASKS=[{id:'load',at:10,count:3,title:'Laad de wolkenpost',icon:'📦'},...['Eerste','Tweede','Derde','Vierde'].map((name,i)=>({id:'deliver'+i,at:38+i*28,count:1,title:name+' huisje',icon:'📮'})),{id:'balloons',at:150,count:3,title:'Post voor de luchtballonnen',icon:'🎈'}];
export const GARDEN_TASKS=[{id:'water',at:10,count:3,title:'Vul de watertank',icon:'💧'},{id:'sluice1',at:42,count:2,title:'Water voor de bloemen',icon:'🌼'},{id:'sluice2',at:76,count:2,title:'Besproei de zonnebloemen',icon:'🌷'},{id:'garden',at:110,count:3,title:'Help het dorstige boompje',icon:'🌻'}];
export const STAR_TASKS=[{id:'starGate',at:10,count:2,title:'Verlicht de feestpoort',icon:'✨'},{id:'lanterns',at:43,count:3,title:'Steek de feestlichtjes aan',icon:'🏮'},{id:'bells',at:76,count:2,title:'Laat de feestklok klinken',icon:'🔔'},{id:'bigStar',at:116,count:3,title:'Laat de grote ster stralen',icon:'⭐'}];
export class Mission{
 constructor(level=1){this.level=level;this.celebrationTime=0;this.watered=0;this.gardenGrowth=[0,0,0];this.water=0;this.delivered=false;this.journeyEntry=false;this.postDelivered=0;this.birdPulse=0;this.tasks=level===6?STAR_TASKS:level===5?GARDEN_TASKS:level===4?POST_TASKS:level===3?RESCUE_TASKS:level===2?PARTY_TASKS:TASKS;this.total=this.tasks.reduce((n,t)=>n+t.count,0);this.reviewCount=0;this.repairPulse=0;this.bonus=0;this.x=0;this.speed=0;this.phase='ready';this.done=0;this.task=0;this.inTask=0;this.route=level===6?'stars':level===5?'garden':level===4?'postal':null;this.onboard=false;this.picked=level>=4;this.timer=0;this.time=0;this.delivery=0;this.justBuilt=-1;}
 drive(){if(this.phase==='ready'||this.phase==='stopped')this.phase='driving';else if(this.phase==='driving'){this.phase='stopped';this.speed=0;}}
 door(){if(this.phase==='boarding'){this.phase='entering';this.timer=3;}else if(this.phase==='arrived'){this.phase='leaving';this.timer=4;}}
 choose(route){if(this.phase==='fork'&&['high','low'].includes(route)){this.route=route;this.phase='driving';}}
 answer(){if(this.phase!=='question')return false;this.done++;this.inTask++;this.justBuilt=this.done-1;if(this.level===6){this.phase=this.task===2&&this.inTask===2?'bellReady':'building';this.timer=3;return true;}if(this.level===5){this.phase=this.task>=2||this.inTask===this.tasks[this.task].count?'valveReady':'building';this.timer=2;return true;}this.phase=this.level===4&&this.task>0&&this.task<5?'dispatchReady':'building';this.timer=this.level===4?(this.task===0?6:1.8):1.35;return true;}
 waterValve(){if(this.phase==='valveReady'){this.phase='watering';this.timer=5;}}
 dispatch(){if(this.phase==='dispatchReady'){this.phase='dispatching';this.timer=1.8;}}
 ringBell(){if(this.level===4)this.birdPulse=3;if(this.level===6&&this.phase==='bellReady'){this.phase='building';this.timer=3;}}
 launchFinale(){if(this.level===6&&this.phase==='starReady'){this.phase='celebrating';this.timer=16;this.celebrationTime=0;}}
 tick(dt){this.time+=dt;if(this.phase==='celebrating')this.celebrationTime+=dt;this.birdPulse=Math.max(0,this.birdPulse-dt);this.repairPulse=Math.max(0,this.repairPulse-dt);if(this.phase==='outbound'){this.speed+=(5-this.speed)*Math.min(1,dt*2);this.x+=this.speed*dt;if(this.x>=(this.level===4?192:145)){this.x=this.level===4?192:145;this.phase='nextLevel';}}else if(this.phase==='driving'){this.speed+=((this.level>=4?3.4:4.5)-this.speed)*Math.min(1,dt*2);this.x+=this.speed*dt;const task=this.tasks[this.task];let stop=null;if(task&&this.x>=task.at)stop=['question',task.at];if(!this.picked&&this.x>=28&&(!stop||28<stop[1]))stop=['boarding',28];if(!this.route&&this.x>=34&&(!stop||34<stop[1]))stop=['fork',34];if(this.task===this.tasks.length&&this.reviewCount>0&&this.x>=(this.level>=5?117:this.level===4?156:109))stop=['review',this.level>=5?117:this.level===4?156:109];if(this.task===this.tasks.length&&!this.reviewCount&&this.x>=(this.level>=5?120:this.level===4?160:113))stop=this.level===6?['starReady',120]:this.level>=4?['celebrating',this.level>=5?120:160]:['arrived',113];if(stop){this.phase=stop[0];this.x=stop[1];this.speed=0;if(this.phase==='arrived')this.timer=1.2;if(this.phase==='celebrating'){this.timer=this.level===5?9:4;this.celebrationTime=0;}}}
 else if(this.phase==='arrived'){this.timer-=dt;if(this.timer<=0)this.door();}
 else if(['watering','building','dispatching','reviewBuild','entering','leaving','celebrating'].includes(this.phase)){this.timer-=dt;if(this.phase==='leaving')this.delivery=1-Math.max(0,this.timer)/4;if(this.timer<=0){if(this.phase==='watering'){if(this.task===0){this.water=3;this.task++;this.inTask=0;this.phase='driving';}else{const rounds=this.task>=2?this.tasks[this.task].count:1;this.water=Math.max(0,4-this.task-this.inTask/this.tasks[this.task].count);this.gardenGrowth[this.task-1]=this.inTask/this.tasks[this.task].count;if(this.inTask===this.tasks[this.task].count){this.watered++;this.task++;this.inTask=0;this.phase='driving';}else this.phase='question';}}else if(this.phase==='dispatching'){this.postDelivered++;this.task++;this.inTask=0;this.phase='driving';}else if(this.phase==='reviewBuild'){this.phase=this.reviewCount?'review':'driving';}else if(this.phase==='building'){if(this.inTask===this.tasks[this.task].count){this.task++;this.inTask=0;this.phase='driving';}else this.phase='question';}else if(this.phase==='entering'){this.onboard=true;this.picked=true;this.phase='driving';}else{this.onboard=false;this.delivered=true;if(this.level>=2&&this.phase==='leaving'){this.phase='celebrating';this.timer=3;}else this.phase='complete';}}}
 }
}
export function trackPoint(x,route='high'){let y=.1,z=0;if(x>36&&x<66){const t=(x-36)/30,s=Math.sin(Math.PI*t)**2;if(route==='low'){const u=x<44?(x-36)/8:x>58?(66-x)/8:1;z=5.6*(.5-.5*Math.cos(Math.PI*u));}else{z=-5.6*s;y+=6.5*s;}}if(x>80&&x<98)y+=.9*Math.sin((x-80)/18*Math.PI)**2;return {x,y,z};}
