import * as T from './three.module.js';
import {createStarWorld} from './star-world.mjs?v=31';
import {createGardenWorld} from './garden-world.mjs?v=31';
import {createPostWorld} from './post-world.mjs?v=31';
const ATLAS={engine:[104,52,646,442],wagon:[825,94,679,400],station:[33,500,735,466],bridge:[812,675,691,280],rail:[950,775,480,48]};
export function createWorld(canvas){
 const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.localClippingEnabled=true;renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0xbbe8ee);const scene=new T.Scene(),camera=new T.OrthographicCamera(-13,13,8,-8,.1,100);camera.position.z=35;const ray=new T.Raycaster(),pointer=new T.Vector2();let w=0,h=0,camX=3,camY=3.5,loaded=false,tex={},train,wagon,noor,seated,door,doorGroup,doorTarget,doorHalo,basket,basketStage,house,coupling,bridge=[],pathStones=[],stoneRings=[],foodRewards=[],steam=[],tunnelFront=[],lastMode='',homeArt,marketArt,partyScene,gate,gateArm,gift,giftStage,giftBow,partyDecor=[],partyGuests=[],rescueScene,fox,foxSeat,nightShade,fireflies=[],searchGlows=[],logs=[],logLift=[],windows=[],beacon,hook,rope,foxFamily=[],craneRig,lantern,clearedLogs=[],journeyClouds=[],fogVeil,tunnelView=0,tunnelSolid,legacyScene,postWorld,gardenWorld,starWorld,normalWagon;
 const materials=[];function art(texture,rect,width,x,y,z,parent=scene,height){const image=texture.image,iw=image.width,ih=image.height;const map=texture.clone();map.repeat.set(rect[2]/iw,rect[3]/ih);map.offset.set(rect[0]/iw,1-(rect[1]+rect[3])/ih);map.needsUpdate=true;const mat=new T.MeshBasicMaterial({map,transparent:false,alphaTest:.12,alphaToCoverage:true,depthWrite:true,polygonOffset:true,polygonOffsetFactor:0,polygonOffsetUnits:-(materials.length+1),toneMapped:false});materials.push(mat);const mesh=new T.Mesh(new T.PlaneGeometry(width,height||width*rect[3]/rect[2]),mat);mesh.position.set(x,y+(height||width*rect[3]/rect[2])/2,z);parent.add(mesh);return mesh;}
 function grp(parent=scene){const g=new T.Group();parent.add(g);return g;}
 function glowTexture(){const c=document.createElement('canvas');c.width=c.height=64;const cx=c.getContext('2d'),g=cx.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,250,216,.8)');g.addColorStop(1,'rgba(255,250,216,0)');cx.fillStyle=g;cx.fillRect(0,0,64,64);return new T.CanvasTexture(c);}
 function ring(x,y,z,r=.42){const g=new T.RingGeometry(r,r+.045,40),mat=new T.MeshBasicMaterial({color:0xffd566,transparent:true,opacity:.95,depthWrite:false});const o=new T.Mesh(g,mat);o.position.set(x,y,z);scene.add(o);return o;}
 function height(x,route){if(route==='stars'){for(const [a,b,h] of [[25,33,1.1],[58,66,1.4],[92,100,1.2]])if(x>a&&x<b)return h*Math.sin((x-a)/(b-a)*Math.PI)**2;return 0;}if(route==='garden'){for(const [a,b,h] of [[17,23,1.1],[51,57,1.25],[85,91,1.1],[132,140,1.5]])if(x>a&&x<b)return h*Math.sin((x-a)/(b-a)*Math.PI)**2;return 0;}if(route==='postal'){for(const [a,b,h] of [[12,20,1.3],[40,48,1.5],[68,76,1.3],[96,104,1.5],[124,132,1.3]])if(x>a&&x<b)return h*Math.sin((x-a)/(b-a)*Math.PI)**2;return 0;}if(x>36&&x<66){const s=Math.sin((x-36)/30*Math.PI)**2;if(route==='low'){const u=x<44?(x-36)/8:x>58?(66-x)/8:1;return -.65*(.5-.5*Math.cos(Math.PI*u));}const u=x<46?(x-36)/10:x>56?(66-x)/10:1;return 8.5*(.5-.5*Math.cos(Math.PI*u));}if(x>80&&x<98)return .65*Math.sin((x-80)/18*Math.PI)**2;return 0;}
 function ribbon(from,to,route,texture,rect,depth,tileWidth,drop,thickness){const vertices=[],uvs=[];const iw=texture.image.width,ih=texture.image.height;for(let x=from;x<to;x+=tileWidth){const right=Math.min(x+tileWidth,to),y1=height(x,route)+drop,y2=height(right,route)+drop,l=rect[0]/iw,r=(rect[0]+rect[2]*(right-x)/tileWidth)/iw,top=1-rect[1]/ih,bottom=1-(rect[1]+rect[3])/ih;vertices.push(x,y1,depth,x,y1-thickness,depth,right,y2,depth,right,y2,depth,x,y1-thickness,depth,right,y2-thickness,depth);uvs.push(l,top,l,bottom,r,top,r,top,l,bottom,r,bottom);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));const o=new T.Mesh(g,new T.MeshBasicMaterial({map:texture,transparent:true,alphaTest:.12,toneMapped:false}));scene.add(o);return o;}
 function cropPiece(rect,width,x,y,z){return art(tex.kit,rect,width,x,y,z);}
 const ready=Promise.all(['landscape.png','sprites.png','train-kit.png','story-art.png','party-art.png','rescue-art.png','cloud-rail-art.png','post-art.png','garden-art.png','garden-island.png','garden-growth.png','star-sky.png','star-art.png'].map(name=>new T.TextureLoader().loadAsync(name))).then(images=>{
  [tex.sky,tex.animals,tex.kit,tex.story,tex.party,tex.rescue,tex.cloud,tex.post,tex.garden,tex.island,tex.growth,tex.nightSky,tex.stars]=images;for(const t of images){t.colorSpace=T.SRGBColorSpace;t.minFilter=T.LinearMipmapLinearFilter;}scene.background=tex.sky;
  // Rails rest on illustrated cloud banks, with an actual gap for the repair bridge.
  function cloudRun(from,to,route){const width=from===36?4:8,step=width*.68,tall=width*.325;for(let x=from;x<to;x+=step){const cx=x+step/2,c=art(tex.cloud,[23,21,1500,384],width,cx,height(cx,route)-tall*.82,.6,scene,tall);c.rotation.z=Math.atan2(height(cx+.5,route)-height(cx-.5,route),1);c.material.clippingPlanes=[new T.Plane(new T.Vector3(1,0,0),-from),new T.Plane(new T.Vector3(-1,0,0),to)];}}

  for(const [a,b] of [[-25,13.5],[21,36],[66,160]]){cloudRun(a,b,'high');ribbon(a,b,'high',tex.kit,ATLAS.rail,1.25,.35,.12,.31);}
  cloudRun(36,66,'low');cloudRun(36,66,'high');ribbon(36,66,'low',tex.kit,ATLAS.rail,1.3,.35,.12,.31);ribbon(36,66,'high',tex.kit,ATLAS.rail,2.2,.35,.12,.31);
  for(let i=0;i<22;i++){const x=-10+i*6.3;if(x>10&&x<23||x>35&&x<67||x>99)continue;const width=i%3===0?6:4.1;art(tex.story,[88,504,568,504],width,x+(i%2?1:-1),-.28,0);}
  for(const x of [23,108]){art(tex.kit,ATLAS.station,8,x,-.83,1.6);art(tex.kit,[33,879,735,87],8,x,-.83,3.5);}
  homeArt=art(tex.story,[76,14,648,481],7.5,117.5,-.24,1.7);house={doorX:116.25,footY:.1};
  marketArt=art(tex.story,[832,29,641,501],7,77.5,-.22,1.65);
  partyScene=grp();art(tex.party,[40,0,780,575],8,117.5,-.24,1.7,partyScene);
  for(let i=0;i<3;i++){const b=art(tex.party,[1030,530,420,494],1.35,114.6+i*2.7,2.5+(i%2)*1.3,2,partyScene);partyDecor.push(b);}
  for(let i=0;i<2;i++){const guest=art(tex.animals,i===0?[555,535,385,470]:[1055,490,420,520],1.15,118.2+i*1.1,.12,4,partyScene);partyGuests.push(guest);}
  gift=art(tex.party,[1010,60,450,470],.78,0,0,4.3);
  giftStage=art(tex.party,[1010,250,450,280],2.2,15.8,.25,3);
  giftBow=art(tex.party,[1010,60,450,195],2.2,15.8,1.60,3.1);
  gate=grp();gate.position.set(81,0,0);art(tex.party,[65,620,180,390],1.15,0,-.15,3.5,gate);
  gateArm=grp(gate);gateArm.position.set(0,1.55,3.6);art(tex.party,[235,690,670,70],4,-2,-.2,0,gateArm,.42);
  rescueScene=grp();
  art(tex.rescue,[40,5,490,1015],4.2,116.25,-.2,1.7,rescueScene);
  for(let i=0;i<3;i++){const y=[698,536,374][i];const win=art(tex.rescue,[265,y,55,87],.471,116.31,(-.2+(1020-y-87)*4.2/490),2.9,rescueScene);windows.push(win);}
  beacon=new T.Sprite(new T.SpriteMaterial({map:glowTexture(),transparent:true,depthWrite:false,opacity:.7}));beacon.position.set(116.3,7.2,3);beacon.scale.set(12,1.7,1);rescueScene.add(beacon);
  for(let i=0;i<3;i++){const x=15.5+i*2.7;art(tex.rescue,[1190,615,320,400],.85,x,.05,2,rescueScene);const light=new T.Sprite(new T.SpriteMaterial({map:glowTexture(),transparent:true,depthWrite:false,opacity:.6}));light.position.set(x+1.6,2.3,2.95);light.scale.set(4,5,1);rescueScene.add(light);searchGlows.push(light);}
  craneRig=grp(rescueScene);craneRig.position.y=-1.1;
  art(tex.kit,ATLAS.rail,9,83,-1.05,3.1,rescueScene,.18);
  art(tex.rescue,[790,25,730,565],6.23,83.38,.12,3.4,craneRig);
  art(tex.rescue,[700,25,90,140],.77,79.88,3.75,3.4,craneRig);
  hook=art(tex.rescue,[710,330,100,165],.85,80,1.2,3.3,rescueScene);
  rope=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(80,3.1,3.5),new T.Vector3(80,2.6,3.3)]),new T.LineBasicMaterial({color:0xbd965b}));rescueScene.add(rope);
  for(let i=0;i<4;i++){logs.push(art(tex.rescue,[600,710,565,285],2.1,79.9,.08+i*.34,3.25,rescueScene,.65));logLift.push(0);}
  lantern=art(tex.rescue,[185,105,215,148],1.843,116.32,-.2+(1020-253)*4.2/490,2.9,rescueScene);
  for(let i=0;i<4;i++)clearedLogs.push(art(tex.rescue,[600,710,565,285],2.1,86,-1.0+i*.21,3.6,rescueScene,.65));
  for(let i=0;i<2;i++)foxFamily.push(art(tex.animals,[1055,490,420,520],1.3,118+i*1.25,.12,4,rescueScene));
  nightShade=new T.Mesh(new T.PlaneGeometry(60,50),new T.MeshBasicMaterial({color:0x14264d,transparent:true,opacity:.48,depthWrite:false}));nightShade.position.z=2.85;scene.add(nightShade);
  for(let i=0;i<35;i++){const f=new T.Sprite(new T.SpriteMaterial({map:glowTexture(),color:0xffed84,transparent:true,depthWrite:false}));f.scale.setScalar(.15);rescueScene.add(f);fireflies.push(f);}
  // Three illustrated rail-deck sections rise into a real gap.
  cropPiece([812,675,138,280],1.45,12.95,-1.8,2.4);cropPiece([1430,768,73,187],.8,21.1,-1.8,2.4);
  for(let i=0;i<3;i++){const g=grp();g.position.set(13.5+i*2.5,-3,0);art(tex.kit,[950,775,480,120],2.5,1.25,-.6,2,g,.72);g.visible=false;bridge.push(g);}
  // The tunnel is a hollow vault along X: both mouths are perpendicular to the rails.
  tunnelSolid=grp();tunnelSolid.name='hollow-railway-tunnel';
  const tunnelStart=44,tunnelEnd=58,base=-.82,shoulder=1.45,centerZ=3.05,innerRadius=2.65,outerRadius=3.13;
  const sunlight=new T.DirectionalLight(0xffe8c5,2.5);sunlight.position.set(30,25,22);scene.add(sunlight);scene.add(new T.HemisphereLight(0xe2efff,0x8b7791,2));
  const stone=new T.MeshStandardMaterial({color:0xe7d4b7,roughness:.95,side:T.DoubleSide});
  const lining=new T.MeshBasicMaterial({color:0x34404d,side:T.DoubleSide});
  function vaultSurface(radius,material){const vaultStart=44.52,vaultEnd=57.48,verts=[],uv=[];const arc=32;for(let i=0;i<arc;i++){const a=i/arc*Math.PI,b=(i+1)/arc*Math.PI;const p=[vaultStart,shoulder+Math.sin(a)*radius,centerZ+Math.cos(a)*radius],q=[vaultEnd,p[1],p[2]],r=[vaultStart,shoulder+Math.sin(b)*radius,centerZ+Math.cos(b)*radius],t=[vaultEnd,r[1],r[2]];verts.push(...p,...q,...r,...q,...t,...r);uv.push(0,i/arc,1,i/arc,0,(i+1)/arc,1,i/arc,1,(i+1)/arc,0,(i+1)/arc);}for(const sign of [-1,1]){const z=centerZ+sign*radius;verts.push(vaultStart,base,z,vaultEnd,base,z,vaultStart,shoulder,z,vaultEnd,base,z,vaultEnd,shoulder,z,vaultStart,shoulder,z);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.computeVertexNormals();const o=new T.Mesh(g,material);o.name=radius===innerRadius?'tunnel-inner-vault':'tunnel-outer-vault';tunnelSolid.add(o);}
  vaultSurface(outerRadius,stone);vaultSurface(innerRadius,lining);
  const floor=new T.Mesh(new T.BoxGeometry(14,.12,innerRadius*2),new T.MeshStandardMaterial({color:0x6f7072,roughness:1}));floor.position.set(51,base-.06,centerZ);tunnelSolid.add(floor);
  // Individual masonry blocks frame open holes in the YZ plane, never across the screen.
  for(const x of [tunnelStart-.22,tunnelEnd-.48]){
   const portal=grp(tunnelSolid);portal.position.set(x,0,centerZ);portal.name=x<50?'tunnel-entrance':'tunnel-exit';
   for(let i=0;i<15;i++){const a=i*Math.PI/15+.008,b=(i+1)*Math.PI/15-.008,shape=new T.Shape();shape.moveTo(Math.cos(a)*innerRadius,shoulder+Math.sin(a)*innerRadius);shape.lineTo(Math.cos(a)*outerRadius,shoulder+Math.sin(a)*outerRadius);shape.absarc(0,shoulder,outerRadius,a,b,false);shape.lineTo(Math.cos(b)*innerRadius,shoulder+Math.sin(b)*innerRadius);shape.absarc(0,shoulder,innerRadius,b,a,true);shape.closePath();const block=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.7,bevelEnabled:true,bevelThickness:.035,bevelSize:.012,bevelSegments:2,steps:1,curveSegments:4}),stone);block.rotation.y=Math.PI/2;portal.add(block);}
   for(const side of [-1,1])for(let i=0;i<4;i++){const block=new T.Mesh(new T.BoxGeometry(.72,(shoulder-base)/4-.035,outerRadius-innerRadius),stone);block.position.set(.34,base+(i+.5)*(shoulder-base)/4,side*(innerRadius+outerRadius)/2);portal.add(block);}
  }
  // The solid vault carries the painted cloud-and-stone exterior, clear of both mouth planes.
  for(const x of [47.8,51,54.2]){const facade=art(tex.cloud,[773,450,753,550],6,x,-.9,6.22,scene,6.15);facade.material.clippingPlanes=[new T.Plane(new T.Vector3(1,0,0),-45.15),new T.Plane(new T.Vector3(-1,0,0),56.85)];}
  // Illustrated clouds sit on the roof; they do not cover either mouth.
  for(const x of [48,51.5,55])art(tex.cloud,[23,21,1500,384],7,x,3.7,2,scene,2.2);
  for(let i=0;i<2;i++){const rect=i===0?[1258,713,195,106]:[1264,830,220,105],stone=art(tex.story,rect,1.95,113.1+i*1.5,-2.5,3,scene,.67);pathStones.push(stone);stoneRings.push(ring(113.1+i*1.5,-.08,3.1,.65));}
  legacyScene=grp();legacyScene.name='original-route';for(const child of [...scene.children])if(child!==legacyScene&&!child.isLight)legacyScene.add(child);
  coupling=art(tex.kit,[955,827,400,16],1,0,0,3.04,scene,.09);train=grp();art(tex.kit,ATLAS.engine,5.8,0,-.13,3,train);wagon=grp();normalWagon=art(tex.kit,ATLAS.wagon,5.3,0,-.2,3,wagon);
  // The door image, clickable target and glow move with the wagon itself.
  doorGroup=grp(wagon);doorGroup.position.set(1.84,1.08,3.13);door=art(tex.story,[240,242,111,196],.56,0,0,0,doorGroup,1.2);door.position.x=-.28;
  doorTarget=new T.Mesh(new T.PlaneGeometry(2.6,2.5),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));doorTarget.position.set(1.57,1.68,3.2);doorTarget.userData.action='door';wagon.add(doorTarget);
  doorHalo=new T.Mesh(new T.RingGeometry(.68,.73,40),new T.MeshBasicMaterial({color:0xffd169,transparent:true,opacity:.95,depthWrite:false}));doorHalo.position.copy(doorTarget.position);doorHalo.position.z=3.22;wagon.add(doorHalo);
  noor=art(tex.animals,[88,511,342,494],1.1,21.7,0,4);seated=art(tex.animals,[100,535,305,265],.88,-1.34,1.45,3.08,wagon,.75);seated.visible=false;
  fox=art(tex.animals,[1055,490,420,520],1.28,21.7,0,4);foxSeat=art(tex.animals,[1120,505,300,285],.88,-1.34,1.45,3.08,wagon,.75);
  basket=art(tex.story,[805,599,430,377],.83,0,0,4.5);basketStage=art(tex.story,[805,599,430,377],1.45,77.5,1.65,2);basket.visible=false;
  const glow=glowTexture();for(let i=0;i<9;i++){const o=new T.Sprite(new T.SpriteMaterial({map:glow,transparent:true,depthWrite:false,opacity:.55}));o.scale.setScalar(.45);scene.add(o);steam.push(o);}
  for(const o of [noor,fox,basketStage,giftStage]){o.material.transparent=true;o.material.depthWrite=false;}
  fogVeil=new T.Mesh(new T.PlaneGeometry(80,150),new T.MeshBasicMaterial({color:0xe7f0f8,transparent:true,depthWrite:false,depthTest:false}));fogVeil.renderOrder=99;scene.add(fogVeil);
  for(let i=0;i<7;i++){const c=art(tex.cloud,[23,21,1500,384],35,0,0,12,scene,18);c.material.transparent=true;c.material.depthWrite=false;c.material.depthTest=false;c.renderOrder=100;journeyClouds.push(c);}
  postWorld=createPostWorld({T,scene,art,tex,grp,wagon,height,ribbon});gardenWorld=createGardenWorld({T,scene,art,tex,grp,wagon,height,ribbon});starWorld=createStarWorld({T,scene,art,tex,grp,wagon,height,ribbon,glowTexture});
  loaded=true;
 });
 function setVehicle(o,x,route){const a=height(x-1.6,route),b=height(x+1.6,route);o.position.set(x,(a+b)/2,0);o.rotation.z=Math.atan2(b-a,3.2);o.updateMatrixWorld(true);}
 function update(m,dt,preview=false){if(!loaded)return;const bounds=canvas.getBoundingClientRect(),viewWidth=Math.max(1,bounds.width),viewHeight=Math.max(1,bounds.height);if(w!==viewWidth||h!==viewHeight){w=viewWidth;h=viewHeight;renderer.setSize(w,h,false);}const stars=m.level===6,garden=m.level===5,post=m.level===4,special=post||garden||stars,party=m.level===2,rescue=m.level===3;legacyScene.visible=!special;normalWagon.visible=!special;rescueScene.visible=rescue;nightShade.visible=rescue;partyScene.visible=party;homeArt.visible=!party&&!rescue;marketArt.visible=!party&&!rescue;gate.visible=party;gateArm.rotation.z=T.MathUtils.lerp(gateArm.rotation.z,-Math.min(3,Math.max(0,m.done-2))*Math.PI/6,Math.min(1,dt*3));for(let i=0;i<3;i++){partyDecor[i].visible=m.done>5+i;partyDecor[i].rotation.z=Math.sin(m.time*1.5+i)*.04;}for(let i=0;i<partyGuests.length;i++)partyGuests[i].position.y=.77+(['celebrating','complete'].includes(m.phase)?Math.abs(Math.sin(m.time*4+i))*.18:0);giftStage.visible=party&&m.done<2;giftStage.material.opacity=m.done===0?.35:1;giftBow.visible=false;const route=m.route||'high';setVehicle(train,m.x,route);let wagonX=m.x,length=0;while(length<5.45){const next=wagonX-.04;length+=Math.hypot(.04,height(wagonX,route)-height(next,route));wagonX=next;}setVehicle(wagon,wagonX,route);const a=new T.Vector3(-2.81,.76,3.04),b=new T.Vector3(2.64,.66,3.04);train.localToWorld(a);wagon.localToWorld(b);coupling.position.copy(a).add(b).multiplyScalar(.5);coupling.scale.x=a.distanceTo(b);coupling.rotation.z=Math.atan2(b.y-a.y,b.x-a.x);
  const waiting=['boarding','arrived'].includes(m.phase),open=['entering','leaving','celebrating','complete'].includes(m.phase);doorGroup.rotation.y=T.MathUtils.lerp(doorGroup.rotation.y,open?-1.45:0,Math.min(1,dt*5));doorHalo.visible=waiting;doorHalo.scale.setScalar(1+Math.sin(m.time*4)*.05);doorTarget.visible=waiting;
  const seatedNow=m.onboard&&!['leaving','celebrating','complete'].includes(m.phase);seated.visible=seatedNow;noor.visible=!seatedNow;noor.material.opacity=1;let foot={x:21.7,y:.12},characterScale=1;const doorX=wagon.position.x+1.57;
  if(m.phase==='entering'){const t=1-Math.max(0,m.timer)/3;if(t<.55){const k=t/.55;foot.x=T.MathUtils.lerp(21.7,doorX-.38,k);foot.y=.12+Math.sin(k*Math.PI*4)**2*.035;}else{const k=Math.min(1,(t-.55)/.3);foot.x=T.MathUtils.lerp(doorX-.38,doorX+.03,k);foot.y=T.MathUtils.lerp(.12,1.08,k);characterScale=T.MathUtils.lerp(1,.78,k);}noor.material.opacity=t>.87?(1-t)/.13:1;}
  else if(m.phase==='leaving'){const t=m.delivery;if(t<.23){const k=t/.23;foot.x=T.MathUtils.lerp(doorX+.03,doorX-.38,k);foot.y=T.MathUtils.lerp(1.08,.12,k);characterScale=T.MathUtils.lerp(.78,1,k);noor.material.opacity=Math.min(1,k*4);}else if(t<.58){const k=(t-.23)/.35;foot.x=T.MathUtils.lerp(doorX-.38,112,k);foot.y=.12+Math.sin(k*Math.PI*4)**2*.035;}else{const k=Math.min(.999999,(t-.58)/.42)*3,j=Math.floor(k),u=k-j,points=[112,113.1,114.6,house.doorX];foot.x=T.MathUtils.lerp(points[j],points[j+1],u);foot.y=.12+Math.sin(u*Math.PI)*.22;}}
  else if(m.phase==='arrived')foot={x:doorX,y:1.08};else if(m.delivered||['celebrating','complete'].includes(m.phase))foot={x:house.doorX,y:.12};
  noor.scale.setScalar(characterScale);noor.position.set(foot.x,foot.y+.795*characterScale,4);noor.rotation.z=['entering','leaving'].includes(m.phase)?Math.sin(m.time*14)*.02:0;if(m.phase==='arrived')noor.visible=false;
  const carrying=m.delivered||['leaving','celebrating','complete'].includes(m.phase);basket.visible=!party&&!rescue&&m.done>=6;basketStage.visible=!party&&!rescue&&m.done<6;basketStage.material.opacity=m.done<4?.6:m.done===4?.76:1;
  if(carrying){basket.scale.setScalar(characterScale);basket.rotation.z=0;basket.position.set(foot.x+.58*characterScale,foot.y+.48*characterScale,4.2);}else{basket.scale.setScalar(.78);basket.rotation.z=wagon.rotation.z;const bp=new T.Vector3(.22,1.63,3.15);wagon.localToWorld(bp);basket.position.copy(bp);}
  gift.visible=party&&m.done>=2;gift.position.copy(basket.position);gift.rotation.copy(basket.rotation);gift.scale.copy(basket.scale);if(party&&m.done===2&&m.x<19){const t=Math.max(0,(m.x-10)/9);gift.position.lerp(new T.Vector3(15.8,1.4,4.3),1-t);gift.scale.setScalar(T.MathUtils.lerp(2.5,.78,t));}
  for(let i=0;i<3;i++){bridge[i].visible=party||rescue||m.done>i;if(!bridge[i].visible)bridge[i].position.y=-.7;else bridge[i].position.y=T.MathUtils.lerp(bridge[i].position.y,0,Math.min(1,dt*4));}for(let i=0;i<2;i++){pathStones[i].position.y=T.MathUtils.lerp(pathStones[i].position.y,party||rescue||m.done>i+6?-.18:-2.5,Math.min(1,dt*3));stoneRings[i].visible=!party&&!rescue&&m.x>97&&m.done<=i+6;stoneRings[i].scale.setScalar(1+Math.sin(m.time*4)*.07);}
  for(let i=0;i<steam.length;i++){const age=(m.time*.6+i/steam.length)%1,o=steam[i];o.visible=['driving','outbound'].includes(m.phase)||m.repairPulse>0;const p=new T.Vector3(1.33,3.8,3.4);train.localToWorld(p);if(route==='low'&&p.x>44&&p.x<58)o.visible=false;o.position.set(p.x-age*2,p.y+age*1.5,p.z);o.material.opacity=(1-age)*.5;o.scale.setScalar((m.repairPulse>0?1.4:1)*(.3+age*.65));}
  fox.visible=rescue&&noor.visible&&(m.done>=3||m.picked);fox.position.copy(noor.position);fox.scale.copy(noor.scale);fox.rotation.copy(noor.rotation);fox.material.opacity=noor.material.opacity;foxSeat.visible=rescue&&seatedNow;if(rescue){noor.visible=false;seated.visible=false;}
  for(let i=0;i<3;i++){searchGlows[i].visible=m.done>i;windows[i].material.color.set(m.done>7+i?0xffffff:0x182b38);}
  lantern.material.color.set(m.done===10?0xffffff:0x22313b);beacon.visible=m.done===10;beacon.scale.x=3+Math.abs(Math.sin(m.time*.7))*13;
  for(let i=0;i<fireflies.length;i++){fireflies[i].position.set((i*3.73+m.time*.12)%130,1.5+Math.sin(m.time*.8+i)*.7+(i%4)*.7,3);fireflies[i].material.opacity=.35+Math.sin(m.time*2+i)*.3;}
  for(let i=0;i<4;i++){const removed=m.done>3+i;logLift[i]=T.MathUtils.lerp(logLift[i],removed?1:0,Math.min(1,dt*3.5));const k=logLift[i],j=3-i;logs[i].position.set(79.9+(k>.65?(k-.65)/.35*6:0),.4+j*.34+Math.sin(Math.min(k/.65,1)*Math.PI/2)*2.2,3.25);logs[i].visible=k<.98;clearedLogs[i].visible=k>=.98;}
  if(m.task===1&&m.phase==='building'&&rescue){const i=Math.min(3,Math.max(0,m.done-4));hook.position.set(logs[i].position.x,logs[i].position.y+.9,3.3);}else hook.position.set(80,2.2,3.3);
  const rp=rope.geometry.attributes.position;rp.setXYZ(1,hook.position.x,hook.position.y+.6,3.3);rp.needsUpdate=true;
  if(special){noor.visible=false;fox.visible=false;seated.visible=false;foxSeat.visible=false;basket.visible=false;basketStage.visible=false;doorGroup.visible=false;}else doorGroup.visible=true;postWorld.update(m,dt);gardenWorld.update(m,dt);starWorld.update(m,dt);
  const homeView=!special&&m.x>=101&&!['outbound','nextLevel'].includes(m.phase),question=m.phase==='question'||m.phase==='building';let targetX=preview?2:m.x+3.3,targetY=3.0+train.position.y*.73;if(stars){targetX=m.task===0?13:m.task===1?46:m.task===2?79:m.task===3?120:126.5;targetY=m.task>=3?4.4:3.4;}else if(garden){targetX=m.task===0?5:m.task===4?122:m.x-5;targetY=m.task===0?3.8:3;}else if(post){targetX=m.task===0?4:m.x+(m.task>0&&m.task<5?-4.5:2);targetY=3.3+train.position.y*.8;}else if(m.phase==='boarding'){targetX=25;targetY=2.5;}else if(homeView){targetX=111.6;targetY=rescue?3.8:2.8;}else if(question){targetX=m.task===0?15.3:(party||rescue?79:76);targetY=2.8;}
  if(m.phase==='outbound')targetX=m.x+3.3;if(stars&&!['celebrating','complete'].includes(m.phase)){targetX=m.x+3.3;targetY=3.4+train.position.y*.45;}
  camX=T.MathUtils.lerp(camX,targetX,Math.min(1,dt*2.4));camY=T.MathUtils.lerp(camY,targetY,Math.min(1,dt*2));const aspect=w/h,halfWidth=aspect<1.1?(stars?11:['boarding','arrived','leaving','celebrating'].includes(m.phase)?8.6:11):13,halfHeight=Math.max(6,halfWidth/aspect);camera.left=-halfHeight*aspect;camera.right=halfHeight*aspect;camera.top=halfHeight;camera.bottom=-halfHeight;const inTunnelRoute=route==='low'&&m.x>34&&m.x<72;let view=0;if(inTunnelRoute){const fade=Math.min(1,(m.x-34)/6,(72-m.x)/6),side=T.MathUtils.smoothstep(m.x,49,55)*2-1;view=side*15*fade;}tunnelView=T.MathUtils.lerp(tunnelView,view,Math.min(1,dt*2));camera.position.set(camX+tunnelView,camY+Math.abs(tunnelView)*.08,35);camera.lookAt(camX,camY,3);camera.updateProjectionMatrix();
  const backdrop=stars?tex.nightSky:tex.sky;scene.background=backdrop;const bgAspect=backdrop.image.width/backdrop.image.height,horizontal=Math.min(1,aspect/bgAspect),vertical=Math.min(1,bgAspect/aspect);backdrop.repeat.set(horizontal,vertical);backdrop.offset.set((1-horizontal)*(.2+Math.min(1,m.x/120)*.6),(1-vertical)*.45);const fog=m.phase==='outbound'?Math.max(0,Math.min(1,(m.x-(m.level===4?173:126))/12)):m.journeyEntry?Math.max(0,Math.min(1,-m.x/8)):0;
  for(let i=0;i<journeyClouds.length;i++){const c=journeyClouds[i];c.visible=fog>0;c.material.opacity=Math.min(1,fog*1.4);c.position.set(camX+Math.sin(i*2)*3+(1-fog)*15,camY+(i-3)*12,12);}
  fogVeil.visible=fog>0;fogVeil.material.opacity=fog;fogVeil.position.set(camX,camY,11);nightShade.position.x=camX;nightShade.position.y=camY;renderer.render(scene,camera);
 }
 function hit(e){if(!loaded)return;const target=starWorld.target||gardenWorld.target|| (postWorld.target.visible?postWorld.target:doorTarget.visible?doorTarget:null);if(!target)return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObject(target,false).length?target.userData.action:undefined;}
 return {get starWorld(){return starWorld},get gardenWorld(){return gardenWorld},get postWorld(){return postWorld},get tunnelSolid(){return tunnelSolid}, rebase(distance){camX-=distance;},ready,update,hit,scene,renderer,get train(){return train},get wagon(){return wagon},bridge,pathStones,get doorMesh(){return doorTarget}};
}
