'use strict';
(() => {
const D=TaalData,G=TaalGenerator,$=id=>document.getElementById(id),storage='zisa-taalsystematiek-v1';
const defaults={title:'Mijn taalbundel',font:'arial',fontSize:14,lineType:'type3',lineHeight:'klein',hints:true,symbols:true,newPage:false};let state={settings:{...defaults},items:[]},level='basic',selected=new Set(['article-word']),renderToken=0,renderPromise=Promise.resolve(),busy=false;
const limit=type=>({ 'tell-recognize':12,'tell-complete':8,'tell-words':8,'tell-picture':12,'rhyme-match':12,'rhyme-color':12,'rhyme-find':8,'rhyme-fill':8,'rhyme-write':12,'punct-find':18,'punct-fill':18,'punct-complete':18,'punct-write':12,'article-text':6,'scene':10,'write':4,'capital-choice':8,'noun-pictures':TaalData.nouns.filter(n=>n.image).length,'article-find':12,'noun-find':12,'capital-find':12,'capital-fix':12,'noun-sort':9}[type]||24);
const fonts={nunito:'Nunito',arial:'Arial',comic:'"Comic Sans MS"',georgia:'Georgia'};
function validate(v){if(!v||!Array.isArray(v.items)||v.items.length>60)throw Error('Dit is geen geldige taalbundel (maximaal 60 opdrachten).');const s=v.settings||{};return{settings:{title:String(s.title||defaults.title).slice(0,70),font:Object.hasOwn(fonts,s.font)?s.font:'arial',fontSize:[14,16,18,20,22].includes(+s.fontSize)?+s.fontSize:14,lineType:/^type[1-7]$/.test(s.lineType)?s.lineType:'type3',lineHeight:s.lineHeight==='middel'?'middel':'klein',hints:s.hints!==false,symbols:s.symbols!==false,newPage:s.newPage===true},items:v.items.map((x,i)=>{if(!D.types.some(t=>t.id===x.type)||!Object.hasOwn(D.levels,x.level))throw Error('Onbekende opdracht in dit bestand.');return{id:'item-'+i+'-'+Date.now(),type:x.type,level:x.level,count:x.type==='scene'&&!x.sceneMode?6:Math.max(1,Math.min(limit(x.type),Math.floor(+x.count)||6)),sceneId:D.scenes.some(scene=>scene.id===x.sceneId)?x.sceneId:'schooltuin',sceneMode:['words','both','sentences'].includes(x.sceneMode)?x.sceneMode:x.level==='challenge'?'sentences':'words',removed:Array.isArray(x.removed)?x.removed.filter(k=>typeof k==='string'&&/^(row-\d+|word-[a-z]+)$/.test(k)).slice(0,100):[],seed:Number.isInteger(x.seed)?x.seed>>>0:12345+i}})}}
function persist(){try{localStorage.setItem(storage,JSON.stringify(state))}catch{$('message').textContent='Automatisch bewaren lukt niet. Gebruik Bewaar samenstelling.'}}
function fillSettings(){for(const key of ['title','font','fontSize','lineHeight'])$(key).value=state.settings[key];$('hints').checked=state.settings.hints;$('symbols').checked=state.settings.symbols;$('newPage').checked=state.settings.newPage;renderLines()}
function renderLines(){const labels=['Klassieke hulplijnen','Vier lijnen','Kleurlijnen','Grijs-blauw','Sterke kleuren','Enkele lijn','Dubbele lijn'];$('lineTypes').replaceChildren();labels.forEach((label,i)=>{const b=document.createElement('button');b.className='line-choice';b.setAttribute('aria-pressed',state.settings.lineType==='type'+(i+1));b.innerHTML=`<canvas width="180" height="66" aria-hidden="true"></canvas>${label}`;SpellingSchrijflijnen.tekenCanvas(b.firstChild,'type'+(i+1),'klein');b.onclick=()=>{state.settings.lineType='type'+(i+1);renderLines();changed()};$('lineTypes').append(b)})}
function catalog(){let topic='';$('catalog').replaceChildren();for(const t of D.types){if($('topic').value!=='Alle onderwerpen'&&t.topic!==$('topic').value)continue;if(t.topic!==topic){topic=t.topic;const h=document.createElement('h3');h.className='topic-label';h.textContent=topic;$('catalog').append(h)}const label=document.createElement('label');label.className='choice';const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(t.id);check.onchange=()=>{check.checked?selected.add(t.id):selected.delete(t.id);$('add').textContent=`＋ Voeg ${selected.size||''} opdracht${selected.size===1?'':'en'} toe`;updateSceneOptions()};const text=document.createElement('span');text.innerHTML=`${G.esc(t.name)}<small>${G.esc(t.description)}</small>`;label.append(check,text);$('catalog').append(label)}updateSceneOptions()}
function updateSceneOptions(){$('sceneOptions').hidden=!selected.has('scene');const scene=D.scenes.find(x=>x.id===$('sceneSelect').value)||D.scenes[0];$('sceneThumb').src=scene.image;$('sceneThumb').alt=scene.name}
for(const scene of D.scenes){const option=document.createElement('option');option.value=scene.id;option.textContent=scene.name;$('sceneSelect').append(option)}$('sceneSelect').onchange=updateSceneOptions;
for(const [id,data]of Object.entries(D.levels)){const label=document.createElement('label');label.className='check';label.innerHTML=`<input type="radio" name="level" value="${id}" ${id===level?'checked':''}> ${data.symbol} ${data.name}`;label.firstChild.onchange=()=>{level=id;$('levelHelp').textContent=data.help};$('levels').append(label)}$('levelHelp').textContent=D.levels[level].help;
function bundle(){const root=$('bundle');root.replaceChildren();state.items.forEach((item,i)=>{const t=D.types.find(t=>t.id===item.type),l=D.levels[item.level],row=document.createElement('div');row.className='bundle-item';row.innerHTML=`<span class="badge">${i+1}</span><div class="item-text"><b>${G.esc(t.name)}</b><small>${l.symbol} ${l.name} · ${item.count} ${item.type==='noun-sort'?'woorden':'vragen'}${item.removed?.length?' · '+item.removed.length+' verwijderd':''}</small></div>`;for(const [label,title,action,disabled]of [['↑','Verplaats omhoog',()=>move(i,-1),i===0],['↓','Verplaats omlaag',()=>move(i,1),i===state.items.length-1],['+','Voeg een vraag toe',()=>addQuestion(item),false],['↻','Andere woorden',()=>{item.seed=seed();item.removed=[];changed()},false],['×','Verwijder opdracht',()=>{state.items.splice(i,1);changed()},false]]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',title+' '+(i+1));b.title=title;b.disabled=disabled;b.onclick=action;row.append(b)}if(item.type==='scene'){const options=document.createElement('div');options.className='bundle-scene-options';for(const field of ['sceneId','sceneMode']){const label=document.createElement('label');label.textContent=field==='sceneId'?'Zoekprent':'Opdracht';const select=document.createElement('select');const choices=field==='sceneId'?D.scenes.map(x=>[x.id,x.name]):[['words','Woorden met lidwoord'],['both','Woorden + één uitdagingszin'],['sentences','Zinnen schrijven']];for(const [value,text]of choices){const option=document.createElement('option');option.value=value;option.textContent=text;select.append(option)}select.value=item[field]||choices[0][0];select.onchange=()=>{item[field]=select.value;item.removed=[];changed()};label.append(select);options.append(label)}row.append(options)}root.append(row)});$('summary').textContent=state.items.length?`${state.items.length} opdracht${state.items.length===1?'':'en'} in jouw bundel.`:'Nog geen opdrachten toegevoegd.';for(const id of ['pdf','answerPdf','print','save','clear'])$(id).disabled=!state.items.length||busy}
function addQuestion(item){if(item.removed?.length)item.removed.pop();else if(item.count<limit(item.type))item.count++;else{$('message').textContent='Alle beschikbare vragen voor deze opdracht staan al in de bundel. Voeg eventueel een nieuwe opdracht toe.';return}changed()}
function seed(){return crypto.getRandomValues(new Uint32Array(1))[0]}
function move(i,d){[state.items[i],state.items[i+d]]=[state.items[i+d],state.items[i]];changed()}
function changed(){persist();bundle();renderPromise=renderPreview()}
async function waitImages(root){await Promise.all([...root.querySelectorAll('img')].map(img=>img.complete?(img.naturalWidth?Promise.resolve():Promise.reject(Error('Een afbeelding ontbreekt: '+img.getAttribute('src')))):new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(Error('Een afbeelding ontbreekt: '+img.getAttribute('src')))})))}
function selectedItems(){return state.items.filter(x=>$('filter').value==='all'||x.level===$('filter').value)}
async function pages(host,items,solutions,settings){
await document.fonts.ready;const s={...settings};host.style.setProperty('--worksheet-font',fonts[s.font]);host.style.setProperty('--worksheet-size',s.fontSize+'pt');let pageNo=0,page,body;const all=[];
function newPage(){page=document.createElement('article');page.className='page';page.innerHTML='<header><span class="sheet-brand">JUF ZISA · TAALSYSTEMATIEK · 2DE LEERJAAR'+(solutions?' · OPLOSSINGEN':'')+'</span><h2>'+G.esc(s.title)+'</h2>'+(solutions?'':'<div class="identity"><span>Naam: __________________________</span><span>Datum: ______________</span></div>')+'</header><div class="page-body"></div><footer><span>Taalsystematiek'+(solutions?' · Antwoorden en beoordelingshulp':'')+'</span><span>Blad '+(++pageNo)+'</span></footer>';host.append(page);all.push(page);body=page.querySelector('.page-body')}
for(const item of items){const type=D.types.find(t=>t.id===item.type),m=G.model(item,s,solutions);if(!m.blocks.length)continue;const intro=continuation=>{const el=document.createElement('div');el.className='exercise-intro';el.innerHTML='<p class="exercise-heading">'+(s.symbols?'<span class="level-mark">'+D.levels[item.level].symbol+'</span>':'')+(state.items.indexOf(item)+1)+'. '+G.esc(type.name)+(continuation?' · vervolg':'')+'</p><p class="instruction">'+G.esc(m.instruction)+'</p>'+(!continuation&&s.hints&&m.hint?'<div class="hint">Onthoud: '+G.esc(m.hint)+'</div>':'')+(!continuation&&m.example?'<div class="example">'+G.esc(m.example)+'</div>':'');return el};
if(!body||s.newPage)newPage();let heading=intro(false);heading.dataset.itemId=item.id;body.append(heading);let first=true;
for(const html of m.blocks){const holder=document.createElement('div');holder.innerHTML=html;const block=holder.firstElementChild;block.dataset.itemId=item.id;body.append(block);await waitImages(block);if(block.getBoundingClientRect().bottom>body.getBoundingClientRect().bottom-4){block.remove();if(first)heading.remove();newPage();heading=intro(!first);heading.dataset.itemId=item.id;body.append(heading,block);if(block.getBoundingClientRect().bottom>body.getBoundingClientRect().bottom-4)throw Error('Deze opdracht past niet. Kies een kleinere letter of minder schrijfruimte.')}SpellingSchrijflijnen.tekenAlle(block);first=false}
}return all}
function addPreviewControls(preview){for(const head of preview.querySelectorAll('.exercise-intro')){const item=state.items.find(x=>x.id===head.dataset.itemId);if(!item)continue;const b=document.createElement('button');b.className='question-add no-print';b.textContent='＋';b.title='Voeg één vraag toe aan deze opdracht';b.setAttribute('aria-label',b.title);b.onclick=()=>addQuestion(item);head.append(b)}for(const unit of preview.querySelectorAll('[data-question-key]')){if(unit.querySelector('[data-question-key]'))continue;const item=state.items.find(x=>x.id===unit.closest('[data-item-id]').dataset.itemId);if(!item)continue;const b=document.createElement('button');b.className='question-remove no-print';b.textContent='−';b.title='Verwijder deze vraag';b.setAttribute('aria-label',b.title);b.onclick=()=>{item.removed||=[];item.removed.push(unit.dataset.questionKey);changed()};unit.append(b)}}
async function renderPreview(){const token=++renderToken,host=document.createElement('div');host.className='export-host';document.body.append(host);$('exportStatus').textContent='Voorbeeld wordt opgebouwd…';try{const items=selectedItems();await pages(host,items,$('answers').checked,state.settings);if(token!==renderToken)return;const preview=$('preview');preview.replaceChildren();preview.style.setProperty('--worksheet-font',fonts[state.settings.font]);preview.style.setProperty('--worksheet-size',state.settings.fontSize+'pt');if(!items.length)preview.innerHTML='<div class="empty">Nog geen opdrachten voor deze selectie. Voeg links opdrachten toe.</div>';else while(host.firstChild)preview.append(host.firstChild);addPreviewControls(preview);$('exportStatus').textContent=items.length?`${preview.querySelectorAll('.page').length} pagina’s in dit voorbeeld.`:''}catch(e){if(token===renderToken)$('exportStatus').textContent=e.message}finally{host.remove()}}
async function pdf(solutions){if(busy)return;await renderPromise;const items=selectedItems();if(!items.length){$('exportStatus').textContent='Kies eerst een selectie met opdrachten.';return}busy=true;bundle();document.querySelector('.builder').inert=true;const host=document.createElement('div');host.className='export-host';document.body.append(host);try{const list=await pages(host,items,solutions,state.settings);const doc=new jspdf.jsPDF({unit:'mm',format:'a4',orientation:'portrait'});for(let i=0;i<list.length;i++){$('exportStatus').textContent=`PDF maken: blad ${i+1} van ${list.length}…`;const canvas=await html2canvas(list[i],{scale:2,backgroundColor:'#fff',logging:false});if(i)doc.addPage();doc.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,210,297)}doc.save('taalsystematiek-'+(solutions?'oplossingen':'werkbladen')+'.pdf');$('exportStatus').textContent=`${list.length} pagina’s gedownload.`}catch(e){$('exportStatus').textContent='Download mislukt. '+e.message}finally{host.remove();busy=false;document.querySelector('.builder').inert=false;bundle()}}
$('add').onclick=()=>{if(!selected.size){$('message').textContent='Kies eerst minstens één opdracht.';return}if(state.items.length+selected.size>60){$('message').textContent='Een bundel kan maximaal 60 opdrachten bevatten.';return}for(const type of selected)state.items.push({id:crypto.randomUUID(),type,level,count:Math.min(limit(type),+$('count').value),sceneId:$('sceneSelect').value,sceneMode:$('sceneMode').value,removed:[],seed:seed()});$('message').textContent=`${selected.size} opdracht${selected.size===1?'':'en'} toegevoegd.`;changed()};const tabs=[...document.querySelectorAll('[role="tab"]')];function chooseTab(tab){$('topic').value=tab.dataset.topic;selected.clear();const first=D.types.find(t=>t.topic===tab.dataset.topic);if(first)selected.add(first.id);tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',active);t.tabIndex=active?0:-1});$('catalog').setAttribute('aria-labelledby',tab.id);const strip=tab.parentElement;const left=tab.offsetLeft-strip.offsetLeft;if(left<strip.scrollLeft)strip.scrollLeft=left;else if(left+tab.offsetWidth>strip.scrollLeft+strip.clientWidth)strip.scrollLeft=left+tab.offsetWidth-strip.clientWidth;catalog();$('add').textContent='＋ Voeg toe aan mijn bundel'}for(const [i,tab]of tabs.entries()){tab.onclick=()=>chooseTab(tab);tab.onkeydown=e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();chooseTab(tabs[next]);tabs[next].focus()}}for(const id of ['title','font','fontSize','lineHeight','hints','symbols','newPage'])$(id).onchange=()=>{state.settings[id]=['hints','symbols','newPage'].includes(id)?$(id).checked:id==='fontSize'?+$(id).value:$(id).value;changed()};$('answers').onchange=$('filter').onchange=()=>{renderPromise=renderPreview()};$('clear').onclick=()=>{if(confirm('Alle opdrachten uit deze bundel verwijderen?')){state.items=[];changed()}};$('pdf').onclick=()=>pdf(false);$('answerPdf').onclick=()=>pdf(true);$('print').onclick=async()=>{await renderPromise;if(selectedItems().length)window.print()};$('save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,...state},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='taalbundel-samenstelling.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('load').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>200000)throw Error('Dit bestand is te groot.');const incoming=validate(JSON.parse(await file.text()));if(state.items.length&&!confirm('De huidige samenstelling vervangen door dit bestand?'))return;state=incoming;fillSettings();changed();$('message').textContent='Samenstelling geopend.'}catch(err){$('message').textContent='Openen lukt niet. '+err.message}finally{e.target.value=''}};
try{const saved=localStorage.getItem(storage);if(saved)state=validate(JSON.parse(saved))}catch{$('message').textContent='De vorige samenstelling kon niet worden geopend.'}try{if(localStorage.getItem(storage+'-layout')!=='3'){state.settings.fontSize=14;state.settings.font='arial';localStorage.setItem(storage+'-layout','3');persist()}}catch{}catalog();fillSettings();bundle();renderPromise=renderPreview();window.TaalApp={getState:()=>structuredClone(state),validate,ready:()=>renderPromise,load:v=>{state=validate(v);fillSettings();changed();return renderPromise},pages};
})();

