(() => {
const D=window.TaalData,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const phrase=n=>n.article+' '+n.word;
const line=(s,n=1)=>Array.from({length:n},()=>`<div class="write-line">${SpellingSchrijflijnen.htmlCanvas(s.lineType,s.lineHeight,640)}</div>`).join('');
const answer=(text,s,solutions,n=1)=>solutions?`<div class="answer">${text}</div>`:line(s,n);
function markWords(text,words,solutions){return text.split(/(\s+|[.,!?])/).map(w=>solutions&&words.includes(w.toLowerCase())?`<strong class="marked">${esc(w)}</strong>`:esc(w)).join('')}
function model(item,s,solutions){if(/^(tell|rhyme)-/.test(item.type))return TaalLanguageExtra.model(item,s,solutions);if(item.type.startsWith('punct-'))return TaalPunctuation.model(item,s,solutions);const r=rng(item.seed),support=item.level==='support',hard=item.level==='challenge',count=item.count;let words=shuffle(D.nouns,r).slice(0,count),sentences=shuffle(D.sentences,r).slice(0,count),caps=shuffle(D.capitals,r).slice(0,count);let blocks=[],instruction='',hint='',example='',questionIndex=0;const removed=new Set(item.removed||[]);const row=(html,removable=true)=>{const key='row-'+questionIndex++;if(!removable||!removed.has(key))blocks.push(`<div class="question-block"${removable?' data-question-key="'+key+'"':''}>${html}</div>`)};const write=(prompt,a,n=1)=>row(`<p>${prompt}</p>${answer(a,s,solutions,n)}`);
if(item.type.startsWith('article')){hint='De, het en een zijn lidwoorden. Ze staan bij een zelfstandig naamwoord.';if(item.type==='article-word'){instruction='Schrijf de of het op de korte lijn vóór elk woord.';hint='Kies de of het. Bijvoorbeeld: de bal en het boek.';example=support?'Zeg het woord zachtjes met de en met het. Wat klinkt juist?':'';words=words.filter(n=>!removed.has('word-'+n.word));for(let i=0;i<words.length;i+=3)row('<div class="article-grid">'+words.slice(i,i+3).filter(n=>!removed.has('word-'+n.word)).map(n=>'<div class="article-cell" data-question-key="word-'+n.word+'"><span class="article-gap">'+(solutions?'<b class="article-answer">'+esc(n.article)+'</b>':line(s))+'</span><span>'+esc(n.word)+'</span></div>').join('')+'</div>',false);if(hard){row('<p class="extra-task">Kies drie woorden van hierboven. Maak er meer van en schrijf het lidwoord erbij.</p>');for(let i=0;i<3;i++)row(answer(i===0?'Mogelijke antwoorden: '+words.map(n=>'de '+esc(n.plural)).join(' · '):'Andere juiste keuze uit de woorden hierboven.',s,solutions))}}
if(item.type==='article-text'){instruction='Vul de, het of een in. Soms past meer dan één lidwoord.';hint='Gebruik een als je iets voor het eerst noemt. Met de of het kun je er daarna naar verwijzen.';example=support?'Lees eerst het hele tekstje. Bij elke lege plaats staan twee lidwoorden om uit te kiezen.':'';const texts=[['In de tuin loopt {} kat. {} kat zit naast {} boom.',[['een','de'],['De','Een'],['een','de']]],['Noor vindt {} boek. Ze legt {} boek op {} tafel.',[['een','het'],['het','een'],['de','een']]],['Sam koopt {} appel. Hij stopt {} appel in {} tas.',[['een','de'],['de','een'],['een','de']]],['In het gras ligt {} bal. {} hond duwt tegen {} bal.',[['een','de'],['Een','De'],['de','een']]],['Op de bank zit {} kind. {} kind tekent {} bloem.',[['een','het'],['Het','Een'],['een','de']]],['Lina ziet {} konijn. {} konijn eet {} wortel.',[['een','het'],['Het','Een'],['een','de']]]];shuffle(texts,r).slice(0,Math.min(count,6)).forEach(([t,opts])=>{let i=0;const text=esc(t).replace(/\{\}/g,()=>{const options=opts[i++];return solutions?'<b class="text-answer">'+options.map(esc).join(' / ')+'</b>':'<span class="inline-gap">'+line(s)+'</span>'+(support?'<small class="support-note">('+shuffle(options,r).map(esc).join(' / ')+')</small>':'')});row('<p class="text-exercise">'+text+'</p>')});if(hard)write('Schrijf zelf twee zinnen. Gebruik eerst een en daarna de of het.','Bijvoorbeeld: Ik zie een hond. De hond rent naar mij.',2)}

if(item.type==='article-change'){instruction='Vervang een door de of het. Schrijf de hele woordgroep op de lijn ernaast.';hint='Je schrijft bijvoorbeeld een jas opnieuw als de jas.';example=support?'Kies telkens de of het. Schrijf ook het woord erachter.':'';const active=words.filter(n=>!removed.has('word-'+n.word));for(let i=0;i<active.length;i+=2)row('<div class="rewrite-grid">'+active.slice(i,i+2).map(n=>'<div class="rewrite-cell" data-question-key="word-'+n.word+'"><span class="given-word">een '+esc(n.word)+'</span><div class="rewrite-space">'+answer(esc(phrase(n)),s,solutions)+'</div></div>').join('')+'</div>',false);if(hard){write('Kies twee woordgroepen van hierboven. Schrijf met elke woordgroep een zin.','Eigen zinnen. Controleer het juiste lidwoord, een hoofdletter en een punt.',2)}}

if(item.type==='article-singular'){instruction=hard?'Maak er één van. Schrijf daarna ook het verkleinwoord met het juiste lidwoord.':'Maak er één van. Schrijf de of het erbij.';example=support?'Voorbeeld: de boeken → het boek.':'';const dimin={bal:'balletje',kat:'katje',tas:'tasje',pen:'pennetje',kip:'kipje',vis:'visje',boek:'boekje',huis:'huisje',muis:'muisje',deur:'deurtje',stoel:'stoeltje',bloem:'bloemetje',raam:'raampje',schaap:'schaapje',paard:'paardje',konijn:'konijntje',kind:'kindje',juf:'jufje',bakker:'bakkertje',meester:'meestertje',jongen:'jongetje',meisje:'meisje',tafel:'tafeltje',bord:'bordje',bed:'bedje',appel:'appeltje',fiets:'fietsje',hond:'hondje',boom:'boompje',bank:'bankje',rugzak:'rugzakje'};const active=words.filter(n=>!removed.has('word-'+n.word));for(let i=0;i<active.length;i+=2)row('<div class="rewrite-grid">'+active.slice(i,i+2).map(n=>'<div class="rewrite-cell" data-question-key="word-'+n.word+'"><span class="given-word">de '+esc(n.plural)+(support?'<small class="support-note">één '+esc(n.word)+'</small>':'')+'</span><div class="rewrite-space">'+answer(esc(phrase(n)),s,solutions)+'</div></div>').join('')+'</div>',false);if(hard){instruction='Maak er één van. Schrijf de of het erbij. Kies daarna twee woorden en maak er verkleinwoorden van.';write('Schrijf twee verkleinwoorden met het juiste lidwoord.','Mogelijk: '+active.map(n=>'het '+esc(dimin[n.word])).join(' · '),2)}}

if(item.type==='article-find'){instruction=hard?'Omkring de lidwoorden. Schrijf bij elk lidwoord het zelfstandig naamwoord.':'Omkring de lidwoorden in elke zin.';example=support?'Zoek de, het en een. Ook De, Het en Een tellen mee.':'';sentences.forEach(n=>{row(`<p>${markWords(n.t,['de','het','een'],solutions)}</p>${hard?answer(esc(n.t.match(/\b(?:de|het|een)\s+\w+/gi).join(' · ')),s,solutions):''}`)})}}
if(item.type==='noun-pictures'){
instruction=hard?'Schrijf bij elke prent een zin. Omkring het zelfstandig naamwoord bij de prent.':'Schrijf bij elke prent het woord met de of het.';
hint='Een zelfstandig naamwoord geeft een naam aan een persoon, een dier of een ding.';
words=shuffle(D.nouns.filter(n=>n.image),r).slice(0,count).filter(n=>!removed.has('word-'+n.word));
if(support)example='Woorden om te kiezen: '+shuffle(words,r).map(phrase).join(' · ');
if(hard){words.forEach(n=>row('<div class="picture-sentence" data-question-key="word-'+n.word+'"><img src="'+esc(n.image)+'" alt="'+esc(n.word)+'"><div class="sentence-space">'+answer('Eigen zin met <b>'+esc(phrase(n))+'</b>.',s,solutions,2)+'</div></div>',false))}
else for(let i=0;i<words.length;i+=2)row('<div class="picture-pair">'+words.slice(i,i+2).map(n=>'<div class="picture-card" data-question-key="word-'+n.word+'"><img src="'+esc(n.image)+'" alt="'+esc(n.word)+'"><div>'+answer(esc(phrase(n)),s,solutions)+'</div></div>').join('')+'</div>',false)
}

if(item.type==='noun-find'){
hint='Een zelfstandig naamwoord noemt een persoon, dier of ding. Je kunt er meestal de, het of een voor zetten.';
instruction=(support?'Omkring in elke rij de twee zelfstandige naamwoorden.':'Omkring alle zelfstandige naamwoorden in elke zin.')+' Schrijf de gevonden woorden in de juiste kolom, met de of het erbij. Schrijf elk woord één keer.'+(hard?' Bedenk zelf nog een extra woord voor elke kolom.':'');
const found=[];
if(support){const pool=shuffle(D.nouns,r),distractors=['mooi','snel','blauw','klein','vrolijk','lief','zacht','groen'];for(let i=0;i<count;i++){const ns=pool.slice(i*2,i*2+2);if(!removed.has('row-'+questionIndex))found.push(...ns);row('<p class="word-row">'+shuffle([...ns.map(n=>n.word),distractors[i%distractors.length]],r).map(w=>solutions&&ns.some(n=>n.word===w)?'<b class="marked">'+esc(w)+'</b>':esc(w)).join(' · ')+'</p>')}}
else sentences.forEach(n=>{if(!removed.has('row-'+questionIndex))found.push(...n.n.map(w=>D.nouns.find(x=>x.word===w)));row('<p>'+markWords(n.t,n.n,solutions)+'</p>')});
const unique=[...new Map(found.filter(Boolean).map(n=>[n.word,n])).values()],groups=['dier','persoon','ding'];
if(unique.length){const columns=groups.map(g=>unique.filter(n=>n.group===g));const total=Math.max(...columns.map(c=>c.length))+(hard?1:0);for(let start=0;start<total;start+=3){const amount=Math.min(3,total-start);row('<div class="classification"><p class="sort-instruction">'+(start?'Schrijf verder in de juiste kolom.':'Schrijf de omcirkelde woorden met de of het in de juiste kolom.')+'</p><div class="sort-grid">'+groups.map((g,j)=>'<section><h3>'+g+'</h3>'+Array.from({length:amount},(_,offset)=>{const index=start+offset,n=columns[j][index];return answer(n?esc(phrase(n)):hard&&index===total-1?'Eigen passend woord met lidwoord.':'',s,solutions)}).join('')+'</section>').join('')+'</div></div>',false)}}}

if(item.type==='noun-sort'){instruction=hard?'Sorteer de woorden. Schrijf het lidwoord erbij. Voeg zelf een nieuw woord toe aan elke groep.':'Sorteer de woorden. Schrijf de of het erbij.';hint='Persoon: iemand. Dier: een dier. Ding: iets, zoals een boek of een bloem.';const groups=['persoon','dier','ding'],pools=groups.map(g=>shuffle(D.nouns.filter(n=>n.group===g),r));words=Array.from({length:count},(_,i)=>pools[i%3][Math.floor(i/3)]).filter(n=>n&&!removed.has('word-'+n.word));if(words.length){row('<p class="word-bank">'+shuffle(words,r).map(n=>'<span class="sort-word" data-question-key="word-'+n.word+'">'+esc(support?phrase(n):n.word)+'</span>').join(' · ')+'</p>',false);row('<div class="sort-grid">'+groups.map(g=>'<section><h3>'+g+'</h3>'+(support?'<p class="support-note">'+({persoon:'Bijvoorbeeld: de oma',dier:'Bijvoorbeeld: de egel',ding:'Bijvoorbeeld: het glas'}[g])+'</p>':'')+answer(words.filter(n=>n.group===g).map(n=>esc(phrase(n))).join('<br>')+(hard?'<br>+ eigen passend woord':''),s,solutions,Math.max(1,words.filter(n=>n.group===g).length)+(hard?1:0))+'</section>').join('')+'</div>',false)}}

if(item.type==='scene'){
const scene=D.scenes.find(x=>x.id===item.sceneId)||D.scenes[0],mode=item.sceneMode||(hard?'sentences':'words');
const keys=Array.from({length:count},(_,i)=>'row-'+i).filter(key=>!removed.has(key));
const sceneWords=shuffle(scene.words,r);const number=keys.length===6?'zes':String(keys.length);
instruction=mode==='sentences'?'Schrijf '+number+' '+(keys.length===1?'zin':'zinnen')+' bij de prent. Gebruik in elke zin een zelfstandig naamwoord met een lidwoord.':'Schrijf '+number+' woorden die je ziet. Schrijf er het juiste lidwoord bij.'+(mode==='both'?' Schrijf daarna één zin bij de prent.':'');
hint=mode==='sentences'?'Begin elke zin met een hoofdletter en eindig met een punt.':'Kijk goed naar de personen, dieren en dingen.';
if(support)example='Woorden om te kiezen: '+sceneWords.slice(0,Math.min(count,sceneWords.length)).map(n=>esc(n.word)).join(' · ');
if(keys.length){row('<img class="scene" src="'+esc(scene.image)+'" alt="'+esc(scene.name)+'. '+esc(scene.words.map(n=>n.word).join(', '))+'">',false);
if(mode==='sentences'){for(const key of keys)blocks.push('<div class="question-block scene-sentence" data-question-key="'+key+'">'+answer('Eigen zin bij de prent. Controleer de betekenis, het lidwoord, de hoofdletter en het leesteken.',s,solutions,2)+'</div>')}
else for(let i=0;i<keys.length;i+=2)row('<div class="scene-word-grid">'+keys.slice(i,i+2).map(key=>'<div class="scene-word" data-question-key="'+key+'">'+answer('Bijvoorbeeld: '+esc(phrase(sceneWords[Number(key.slice(4))%sceneWords.length])),s,solutions)+'</div>').join('')+'</div>',false);if(mode==='both'&&!removed.has('row-100'))blocks.push('<div class="question-block scene-sentence" data-question-key="row-100">'+answer('Eigen zin bij de prent. Controleer het lidwoord, de hoofdletter en de punt.',s,solutions,2)+'</div>')}
}

if(item.type.startsWith('capital')){hint='Een zin begint met een hoofdletter. Namen van mensen, dieren en plaatsen krijgen ook een hoofdletter. Dagen schrijf je met een kleine letter.';if(item.type==='capital-find'){instruction=hard?'Omkring de hoofdletters. Leg uit waarom elk woord een hoofdletter krijgt.':'Omkring de hoofdletters.';if(support)example='Voorbeeld: de L in Lina en de B in Brugge.';caps.forEach(t=>row(`<p>${solutions?esc(t).replace(/[A-Z]/g,c=>`<b class="marked">${c}</b>`):esc(t)}</p>${hard?answer(esc(t.split(' ').filter(w=>/^[A-Z]/.test(w)).map((w,i)=>w.replace('.','')+(i===0?(['Lina','Milan','Yara','Omar','Fien'].includes(w)?' (begin van de zin en naam)':' (begin van de zin)'):' (naam)')).join(' · ')),s,solutions):''}`))}
if(item.type==='capital-fix'){instruction=hard?'Schrijf de zinnen correct over. Onderstreep de namen.':'Schrijf de zin over met de juiste hoofdletters.';if(support)example='Begin met een hoofdletter. Kijk ook naar namen van mensen en plaatsen.';caps.forEach(t=>write(esc(t.toLowerCase())+(support?'<br><span class="support-note">Woorden met een hoofdletter: '+esc(t.split(' ').filter(w=>/^[A-Z]/.test(w)).join(' '))+'</span>':''),hard?markWords(t,['lina','brugge','milan','noor','sam','bas','gent','yara','leuven','omar','emma','belgië','fien','rayan','lotte','minoes','jules'],true).replaceAll('class="marked"','class="underlined"'):esc(t),s.fontSize>=20?2:1))}
if(item.type==='capital-choice'){instruction=hard?'Kies de juiste schrijfwijze. Leg uit waarom.':'Omkring de juiste schrijfwijze.';const choices=[['We gaan op','maandag','Maandag','naar school.','Een dag krijgt geen hoofdletter.'],['Mijn vriendin heet','Noor','noor','.','Een naam krijgt een hoofdletter.'],['Oma woont in','Gent','gent','.','Een plaatsnaam krijgt een hoofdletter.'],['','Vandaag','vandaag','schijnt de zon.','Het eerste woord van een zin krijgt een hoofdletter.'],['De hond heet','Max','max','.','Een dierennaam krijgt een hoofdletter.'],['Ik speel op','zaterdag','Zaterdag','buiten.','Een dag krijgt geen hoofdletter.'],['','Morgen','morgen','gaan we zwemmen.','Het eerste woord van een zin krijgt een hoofdletter.'],['Mijn neef woont in','België','belgië','.','Een landsnaam krijgt een hoofdletter.']];shuffle(choices,r).slice(0,count).forEach(([start,a,b,end,why])=>row(`<p>${esc(start)} ${shuffle([a,b],r).map(w=>solutions&&w===a?`<b class="marked">${esc(w)}</b>`:esc(w)).join(' / ')}${end==='.'?'':' '}${esc(end)}</p>${hard?answer(esc(why),s,solutions):''}`))}}
if(item.type==='write'){instruction=hard?'Bedenk een kort verhaal. Gebruik alle woorden en geef iemand een naam.':support?'Maak de zinnen af. Gebruik het woord tussen haakjes.':'Bedenk bij elke woordgroep een zin.';hint='Controleer: hoofdletter, lidwoord, zelfstandig naamwoord en punt.';words=words.slice(0,Math.min(count,4));if(hard){row('<p class="word-bank">'+words.map(n=>esc(n.word)).join(' · ')+'</p>');for(let i=0;i<Math.min(count,4);i++)write(`Zin ${i+1}`,i===0?'Eigen verhaal. Controleer alle opgegeven woorden, een naam met hoofdletter, passende lidwoorden en volledige zinnen.':'Eigen vervolgzin.',2)}else words.forEach(n=>write(support?`Ik zie … (${esc(phrase(n))})`:esc(phrase(n)),support?'Bijvoorbeeld: Ik zie '+esc(phrase(n))+'.':'Eigen zin met '+esc(phrase(n))+'.',2))}
blocks=blocks.filter(b=>!b.includes('class="article-grid"></div>')&&!b.includes('class="picture-pair"></div>'));return{instruction,hint,example,blocks};}
window.TaalGenerator={model,esc,shuffle,rng};
})();
