(() => {
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
  const backgroundFiles=['assets/rekenkern-vallei.png','assets/level2-tafelrivier.png','assets/level3-draairuines.png','assets/level4-kristalberg.png','assets/level5-rekenkern.png'];
  const backgrounds=backgroundFiles.map(src=>{const image=new Image();image.src=src;return image});
  const lanaBody=new Image();lanaBody.src='assets/lana-full.png';
  const levelNames=['Energiebos','Tafelrivier','Draairuïnes','Kristalberg','De Rekenkern'];
  const levels=[
    [q('6 × 7',42,[36,42,48],'Denk aan 6 groepjes van 7.'),q('8 × 4',32,[28,32,36],'Verdubbel 4 × 4.'),q('7 × 8',56,[54,56,63],'7 × 4 is 28; verdubbel dat.'),q('9 × 6',54,[48,54,56],'10 × 6 is 60; neem er 6 af.'),q('8 × 7',56,[49,56,64],'Dit is dezelfde uitkomst als 7 × 8.')],
    [q('42 : 6',7,[6,7,8],'Welke tafel van 6 geeft 42?'),q('56 : 8',7,[6,7,9],'Welke tafel van 8 geeft 56?'),q('36 : 4',9,[8,9,10],'4 × hoeveel is 36?'),q('63 : 7',9,[7,8,9],'7 × hoeveel is 63?'),q('48 : 6',8,[7,8,9],'6 × hoeveel is 48?')],
    [q('7 × ? = 49',7,[6,7,8],'Zoek 49 in de tafel van 7.'),q('? × 8 = 64',8,[7,8,9],'Welke twee gelijke factoren geven 64?'),q('6 × ? = 54',9,[7,8,9],'Zoek 54 in de tafel van 6.'),q('? × 4 = 28',7,[6,7,8],'28 gedeeld door 4.'),q('9 × ? = 72',8,[7,8,9],'Zoek 72 in de tafel van 9.')],
    [q('7 × 40',280,[240,280,320],'Bereken eerst 7 × 4 en voeg een nul toe.'),q('8 × 60',480,[420,480,540],'Bereken eerst 8 × 6.'),q('540 : 9',60,[50,60,70],'54 : 9 is 6; hier is alles tienmaal groter.'),q('6 × 70',420,[360,420,490],'Bereken eerst 6 × 7.'),q('320 : 8',40,[30,40,50],'32 : 8 is 4; hier is alles tienmaal groter.')],
    [q('8 × 9',72,[63,72,81],'Denk aan 10 × 8 min 8.'),q('560 : 7',80,[70,80,90],'56 : 7 is 8.'),q('? × 6 = 48',8,[7,8,9],'Zoek 48 in de tafel van 6.'),q('9 × 70',630,[560,630,720],'Bereken eerst 9 × 7.'),q('72 : 8',9,[7,8,9],'8 × hoeveel is 72?')]
  ];
  function q(text,correct,answers,hint){return{text,correct,answers,hint}}
  const QUESTIONS_PER_LEVEL=10;
  const LEVEL_TIME=[12,10,8,7,6];
  const game={level:0,round:0,shields:3,energy:0,state:'intro',time:0,scroll:0,nextAt:2.3,jumpT:0,wrong:0,timeLeft:12,lanaX:0,jumpStartX:0,coreX:0,mode:'mixed',question:null,portalT:0};
  function makeQuestion(){
    const a=2+Math.floor(Math.random()*9),b=2+Math.floor(Math.random()*9),product=a*b;
    const divide=game.mode==='divide'||(game.mode==='mixed'&&game.round%2===1);
    const correct=divide?b:product,text=divide?`${product} : ${a}`:`${a} × ${b}`;
    const values=new Set([correct]);
    while(values.size<3){const offset=(1+Math.floor(Math.random()*3))*(Math.random()<.5?-1:1);values.add(Math.max(1,correct+offset))}
    return q(text,correct,[...values],divide?`Welke tafel van ${a} geeft ${product}?`:`Denk aan ${a} groepjes van ${b}.`)
  }
  let last=0,W=innerWidth,H=innerHeight,ground=H*.82;

  function resize(){const d=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;ground=H*.82;canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);ctx.setTransform(d,0,0,d,0,0)}
  addEventListener('resize',resize);resize();
  function buildMap(){const map=document.getElementById('levelMap');map.replaceChildren();levelNames.forEach((_,i)=>{const d=document.createElement('span');d.className='level-dot'+(i<game.level?' done':i===game.level?' current':'');d.textContent=i+1;map.append(d)})}
  function updateHud(){document.getElementById('levelName').textContent=`${game.level+1} · ${levelNames[game.level]}`;document.getElementById('scoreIcon').textContent=game.level===1?'💧':'⚡';document.getElementById('scoreText').textContent=`${game.energy} / ${QUESTIONS_PER_LEVEL}`;const s=document.getElementById('shields');s.textContent='◆ '.repeat(game.shields).trim()||'geen';s.classList.toggle('danger',game.shields===1);buildMap()}
  function startLevel(){game.round=0;game.energy=0;game.shields=3;game.wrong=0;game.state='running';game.lanaX=Math.max(105,W*.16);game.nextAt=game.time+2.4;document.getElementById('levelComplete').hidden=true;document.getElementById('levelFailed').hidden=true;document.getElementById('challenge').hidden=true;document.getElementById('runnerMessage').hidden=false;document.getElementById('runnerMessage').textContent=game.level===1?'De eerste antwoorddruppels komen eraan…':'Lana loopt naar de volgende tafelkern…';updateHud()}
  function showChallenge(){game.state='question';game.wrong=0;game.timeLeft=LEVEL_TIME[game.level];game.question=makeQuestion();const stepGap=Math.min(145,Math.max(100,W*.056+45));game.coreX=Math.min(W*.76,(game.lanaX||W*.16)+stepGap);const item=game.question;document.getElementById('question').textContent=item.text+' = ?';const answerBox=document.getElementById('answers');answerBox.replaceChildren();[...item.answers].sort(()=>Math.random()-.5).forEach(value=>{const b=document.createElement('button');b.className='answer-core';b.textContent=value;b.onclick=()=>answer(value,b);answerBox.append(b)});document.getElementById('timeBar').style.transform='scaleX(1)';document.getElementById('feedback').className='';document.getElementById('feedback').textContent='Tik op het juiste antwoord voordat de energiebalk leeg is.';document.getElementById('runnerMessage').hidden=true;document.getElementById('challenge').hidden=false}
  function miss(reason,button){if(game.state!=='question')return;game.state='feedback';game.shields=Math.max(0,game.shields-1);document.querySelectorAll('.answer-core').forEach(b=>{b.disabled=true;if(Number(b.textContent)===game.question.correct)b.classList.add('correct')});if(button)button.classList.add('wrong');updateHud();document.getElementById('feedback').className='hint';document.getElementById('feedback').textContent=`${reason} Het juiste antwoord was ${game.question.correct}.`;setTimeout(()=>{document.getElementById('challenge').hidden=true;if(game.shields===0){game.state='failed';document.getElementById('levelFailed').hidden=false}else{game.state='running';game.nextAt=game.time+1.2}},1200)}
  function answer(value,button){if(game.state!=='question')return;const item=game.question;if(value===item.correct){button.classList.add('correct');document.querySelectorAll('.answer-core').forEach(b=>b.disabled=true);document.getElementById('feedback').className='';if(game.level===1){document.getElementById('feedback').textContent='Juist! Je ving de goede regendruppel.';game.state='feedback';setTimeout(()=>{document.getElementById('challenge').hidden=true;finishJump()},420)}else{document.getElementById('feedback').textContent='Juist! Lana wandelt naar de energiekern.';game.state='jump';game.jumpT=0;game.jumpStartX=game.lanaX;setTimeout(()=>{document.getElementById('challenge').hidden=true},420)}}else miss('Dat antwoord is fout.',button)}
  function finishJump(){game.energy++;game.round++;updateHud();if(game.energy>=QUESTIONS_PER_LEVEL){game.state='portal';game.portalT=0;document.getElementById('runnerMessage').hidden=false;document.getElementById('runnerMessage').textContent=game.level===4?'De laatste Rekenkern is hersteld!':'De magische poort naar het volgende gebied opent!'}else{game.state='running';game.nextAt=game.time+1.4;document.getElementById('runnerMessage').hidden=false;document.getElementById('runnerMessage').textContent=game.level===1?`Druppel ${game.energy} van ${QUESTIONS_PER_LEVEL} juist · de volgende komt eraan!`:`Kern ${game.energy} van ${QUESTIONS_PER_LEVEL} gevangen · op naar de volgende tafel!`}}
  function showLevelComplete(){document.getElementById('completeTitle').textContent=`${levelNames[game.level]} voltooid!`;document.getElementById('completeText').textContent=game.level===1?'Je klikte tien juiste antwoorddruppels aan.':`Je loste ${QUESTIONS_PER_LEVEL} tafels op en verzamelde ${QUESTIONS_PER_LEVEL} energiekernen.`;const btn=document.getElementById('nextButton');if(game.level===4){document.getElementById('gameOver').hidden=false}else{btn.textContent=`Naar level ${game.level+2} →`;document.getElementById('levelComplete').hidden=false}}
  function update(dt){game.time+=dt;if(game.state==='running'){if(game.time>=game.nextAt)showChallenge()}else if(game.state==='question'){game.timeLeft=Math.max(0,game.timeLeft-dt);document.getElementById('timeBar').style.transform=`scaleX(${game.timeLeft/LEVEL_TIME[game.level]})`;if(game.timeLeft<=0)miss('De tijd is op.')}else if(game.state==='jump'){game.jumpT+=dt;const target=game.coreX-45;game.lanaX=Math.min(target,game.lanaX+82*dt);if(game.lanaX>=target)finishJump()}else if(game.state==='portal'){game.portalT+=dt;game.lanaX+=(W*.72-game.lanaX)*Math.min(1,dt*2);if(game.portalT>2.3){if(game.level===4){game.state='done';document.getElementById('gameOver').hidden=false}else{game.level++;startLevel()}}}}

  function rr(x,y,w,h,r,color){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=color;ctx.fill()}
  function drawLana(){const x=game.lanaX||Math.max(105,W*.16),base=ground;const sourceX=226,sourceY=123,sourceW=556,sourceH=1233,dh=250,dw=dh*sourceW/sourceH;ctx.save();ctx.translate(x,base);ctx.drawImage(lanaBody,sourceX,sourceY,sourceW,sourceH,-dw/2,-dh,dw,dh);ctx.restore()}
  function drawEnergy(){if(game.level!==0)return;if(game.state!=='question'&&game.state!=='jump')return;if(game.state==='jump'&&game.coreX-game.lanaX<52)return;const x=game.coreX||((game.lanaX||W*.2)+145);const y=ground-125+Math.sin(game.time*3)*5;ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.shadowColor='#ffe94f';ctx.shadowBlur=35;rr(-22,-22,44,44,8,'#ffcc27');ctx.restore()}
  function drawPortal(){if(game.state!=='portal')return;const x=W*.78,y=ground-125,pulse=1+Math.sin(game.time*5)*.04;ctx.save();ctx.translate(x,y);ctx.scale(pulse,pulse);ctx.shadowColor='#8dfcff';ctx.shadowBlur=45;ctx.strokeStyle='#bafcff';ctx.lineWidth=13;ctx.beginPath();ctx.ellipse(0,0,54,105,0,0,Math.PI*2);ctx.stroke();const glow=ctx.createRadialGradient(0,0,5,0,0,52);glow.addColorStop(0,'#ffffffee');glow.addColorStop(.35,'#71e9ffbb');glow.addColorStop(1,'#6838cf22');ctx.fillStyle=glow;ctx.fill();ctx.restore()}
  function drawGround(){const palettes=[['#82c957','#2e733d','#173f2e'],['#a8d86b','#397c52','#173e43'],['#c89963','#684431','#30251f'],['#eaf8ff','#87b9d4','#315782'],['#287360','#123f46','#071f31']];const colors=palettes[game.level];const g=ctx.createLinearGradient(0,ground-10,0,H);g.addColorStop(0,colors[0]);g.addColorStop(.18,colors[1]);g.addColorStop(1,colors[2]);ctx.fillStyle=g;ctx.fillRect(0,ground-10,W,H-ground+10);ctx.fillStyle=game.level===3?'#ffffff':colors[0];ctx.fillRect(0,ground-10,W,10);ctx.globalAlpha=.22;ctx.fillStyle='#ffffff';for(let x=-80;x<W+100;x+=170){ctx.beginPath();ctx.ellipse(x,ground+35,62,9,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
  function draw(){ctx.clearRect(0,0,W,H);const bg=backgrounds[game.level];if(bg&&bg.complete){const scale=Math.max(W/bg.width,H/bg.height);const bw=bg.width*scale,bh=bg.height*scale;ctx.drawImage(bg,(W-bw)/2,(H-bh)/2,bw,bh)}drawGround();drawPortal();drawEnergy();drawLana();if(game.state==='portal'&&game.portalT>1.75){ctx.fillStyle=`rgba(255,255,255,${Math.min(1,(game.portalT-1.75)/.55)})`;ctx.fillRect(0,0,W,H)}}
  function loop(now){const dt=Math.min((now-last)/1000||0,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);

  const showChallengeBase=showChallenge;
  showChallenge=()=>{showChallengeBase();const challenge=document.getElementById('challenge');const falling=game.level===1;challenge.classList.toggle('falling-mode',falling);document.querySelector('.challenge-label').textContent=falling?'KIES DE JUISTE ANTWOORDDRUPPEL':'KIES DE JUISTE ENERGIEKERN';if(falling){challenge.style.setProperty('--fall-time',`${LEVEL_TIME[game.level]}s`);challenge.style.setProperty('--fall-start',`${Math.ceil(challenge.getBoundingClientRect().bottom+10)}px`);document.getElementById('feedback').textContent='Tik de juiste regendruppel aan vóór hij de grond raakt.'}}

  document.getElementById('startButton').onclick=()=>{game.mode=document.querySelector('input[name="mode"]:checked').value;document.getElementById('intro').hidden=true;game.level=0;startLevel()};
  document.getElementById('nextButton').onclick=()=>{game.level++;startLevel()};
  document.getElementById('againButton').onclick=()=>{document.getElementById('gameOver').hidden=true;game.level=0;startLevel()};
  document.getElementById('retryButton').onclick=startLevel;
  updateHud();
})();
