(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const menu = $('menuPanel'), game = $('gamePanel'), finish = $('finishPanel'), activity = $('activity'), feedback = $('feedback');
  const modeNames = { article:'De lidwoordmachine', sort:'De woordsoortensorteerder', sentence:'De zinnenbouwer', adjective:'De woordenkast', color:'Kleur de zin' };
  const colors = { 'lidwoord':'#ffd34e', 'zelfstandig naamwoord':'#72bceb', 'werkwoord':'#f18479', 'bijvoeglijk naamwoord':'#6bd2a2' };
  const roleColors = { wie:'#f4d94e', doet:'#ef6b67', waar:'#a985d6', wat:'#9a6b45', hoe:'#67c98f', wanneer:'#f3a04b' };
  const data = {
    article: [
      ['bank','de','bank'],['bankje','het','bank','Een verkleinwoord krijgt altijd het.'],
      ['huis','het','huis'],['huizen','de','huis','Een meervoud krijgt altijd de.'],
      ['boek','het','boek'],['boeken','de','boek','Een meervoud krijgt altijd de.'],
      ['hond','de','hond'],['hondje','het','hond','Een verkleinwoord krijgt altijd het.'],
      ['bloem','de','bloem'],['bloemetje','het','bloem','Een verkleinwoord krijgt altijd het.'],
      ['tafel','de','tafel'],['tafeltje','het','tafel','Een verkleinwoord krijgt altijd het.'],
      ['stoel','de','stoel'],['stoeltje','het','stoel','Een verkleinwoord krijgt altijd het.'],
      ['kind','het','kind'],['kinderen','de','kind','Een meervoud krijgt altijd de.'],
      ['jas','de','jas'],['jasje','het','jas','Een verkleinwoord krijgt altijd het.'],
      ['fiets','de','fiets'],['fietsje','het','fiets','Een verkleinwoord krijgt altijd het.'],
      ['bed','het','bed'],['bedden','de','bed','Een meervoud krijgt altijd de.'],
      ['boom','de','boom'],['boompje','het','boom','Een verkleinwoord krijgt altijd het.'],
      ['ei','het','ei'],['eieren','de','ei','Een meervoud krijgt altijd de.'],
      ['deur','de','deur'],['deurtje','het','deur','Een verkleinwoord krijgt altijd het.'],
      ['kat','de','kat'],['katje','het','kat','Een verkleinwoord krijgt altijd het.'],
      ['spel','het','spel'],['spellen','de','spel','Een meervoud krijgt altijd de.'],
      ['schoen','de','schoen'],['schoentje','het','schoen','Een verkleinwoord krijgt altijd het.'],
      ['tuin','de','tuin'],['tuintje','het','tuin','Een verkleinwoord krijgt altijd het.'],
      ['raam','het','raam'],['ramen','de','raam','Een meervoud krijgt altijd de.'],
      ['paard','het','paard'],['paarden','de','paard','Een meervoud krijgt altijd de.'],
      ['appel','de','appel'],['appeltje','het','appel','Een verkleinwoord krijgt altijd het.'],
      ['school','de','school'],['schooltje','het','school','Een verkleinwoord krijgt altijd het.']
    ].map(([word,answer,family,rule='']) => ({word,answer,family,rule})),
    sort: [
      ['fiets','zelfstandig naamwoord','een naam voor een ding','Lina rijdt met haar fiets naar school.','assets/word-types/fiets.png'],
      ['rennen','werkwoord','het zegt wat iemand doet','De kinderen rennen snel naar buiten.','assets/word-types/rennen.png'],
      ['vrolijk','bijvoeglijk naamwoord','het vertelt hoe iemand of iets is','Het vrolijke kind danst op de speelplaats.','assets/word-types/vrolijk.png'],
      ['meester','zelfstandig naamwoord','een naam voor een persoon','De meester schrijft op het bord.','assets/word-types/meester.png'],
      ['schrijft','werkwoord','het zegt wat iemand doet','Noor schrijft een mooie brief.','assets/word-types/schrijft.png'],
      ['zachte','bijvoeglijk naamwoord','het vertelt meer over een zelfstandig naamwoord','De zachte kat ligt in haar mand.','assets/word-types/zachte.png'],
      ['tuin','zelfstandig naamwoord','een naam voor een plaats','In de tuin groeien mooie bloemen.','assets/word-types/tuin.png'],
      ['slaapt','werkwoord','het zegt wat iemand doet','De poes slaapt rustig op het bed.','assets/word-types/slaapt.png'],
      ['grote','bijvoeglijk naamwoord','het vertelt hoe iemand of iets is','De grote hond bewaakt het huis.','assets/word-types/grote.png']
    ].map(([word,answer,explain,sentence,image]) => ({word,answer,explain,sentence,image})),
    sentence: [
      {type:'Mededelende zin',instruction:'Vertel wat Noor doet. Begin met Noor.',words:['Noor','speelt','buiten'],roles:['wie','doet','waar'],answers:['Noor speelt buiten .']},
      {type:'Mededelende zin',instruction:'Vertel eerst waar het gebeurt. Begin met Buiten.',words:['Noor','speelt','Buiten'],roles:['wie','doet','waar'],answers:['Buiten speelt Noor .']},
      {type:'Vraagzin',instruction:'Vraag of Noor buiten speelt.',words:['Noor','buiten','Speelt'],roles:['wie','waar','doet'],answers:['Speelt Noor buiten ?']},
      {type:'Mededelende zin',instruction:'Vertel wat de hond doet. Begin met De hond.',words:['blaft','De hond','luid'],roles:['doet','wie','hoe'],answers:['De hond blaft luid .']},
      {type:'Vraagzin',instruction:'Vraag of de hond luid blaft.',words:['de hond','Blaft','luid'],roles:['wie','doet','hoe'],answers:['Blaft de hond luid ?']},
      {type:'Mededelende zin',instruction:'Vertel waar Mila leest.',words:['leest','Mila','in bed'],roles:['doet','wie','waar'],answers:['In bed leest Mila .','Mila leest in bed .']},
      {type:'Mededelende zin',instruction:'Vertel wat Amir eet.',words:['Amir','een appel','eet'],roles:['wie','wat','doet'],answers:['Amir eet een appel .']},
      {type:'Vraagzin',instruction:'Vraag of Amir een appel eet.',words:['Amir','een appel','Eet'],roles:['wie','wat','doet'],answers:['Eet Amir een appel ?']},
      {type:'Roepzin',instruction:'Roep dat de hond heel snel loopt!',words:['De hond','loopt','heel snel'],roles:['wie','doet','hoe'],answers:['De hond loopt heel snel !']}
    ],
    adjective: [
      {sentence:'De ___ poes ligt rustig in haar mand.',choices:['lieve','speelse','bange'],answer:'lieve',explain:'Lieve vertelt hoe de poes is.',image:'assets/adjectives/zachte-poes.png',alt:'Een lieve poes die wordt geaaid'},
      {sentence:'De ___ hond let goed op het huis.',choices:['waakse','speelse','slaperige'],answer:'waakse',explain:'Waakse vertelt hoe de hond oplet.',image:'assets/adjectives/waakse-hond.png',alt:'Een waakse hond'},
      {sentence:'Lina draagt een ___ jas in de sneeuw.',choices:['warme','dunne','natte'],answer:'warme',explain:'Warme vertelt wat voor jas Lina draagt.',image:'assets/adjectives/warme-jas.png',alt:'Lina draagt een warme jas'},
      {sentence:'We eten een ___ appel.',choices:['sappige','zure','onrijpe'],answer:'sappige',explain:'Sappige vertelt meer over de appel.',image:'assets/adjectives/sappige-appel.png',alt:'Een sappige appel'},
      {sentence:'Het ___ huis staat al honderd jaar in de straat.',choices:['oude','nieuwe','kleine'],answer:'oude',explain:'Oude vertelt hoe lang het huis er al staat.',image:'assets/adjectives/oude-huis.png',alt:'Een oud huis'},
      {sentence:'De ___ vrachtwagen kan veel dozen dragen.',choices:['grote','snelle','zware'],answer:'grote',explain:'Grote vertelt hoe de vrachtwagen is.',image:'assets/adjectives/grote-vrachtwagen.png',alt:'Een grote vrachtwagen'},
      {sentence:'Lina ruikt aan de ___ bloem.',choices:['geurige','kleurrijke','verwelkte'],answer:'geurige',explain:'Geurige vertelt dat de bloem lekker ruikt.',image:'assets/adjectives/geurige-bloem.png',alt:'Een geurige bloem'},
      {sentence:'De ___ clown laat iedereen lachen.',choices:['grappige','verdrietige','onhandige'],answer:'grappige',explain:'Grappige vertelt hoe de clown is.',image:'assets/adjectives/grappige-clown.png',alt:'Een grappige clown'},
      {sentence:'De ___ muis zit naast de appel.',choices:['kleine','snelle','dikke'],answer:'kleine',explain:'Kleine vertelt hoe groot de muis is.',image:'assets/adjectives/kleine-muis.png',alt:'Een heel kleine muis naast een appel'},
      {sentence:'De ___ auto rijdt over de weg.',choices:['snelle','trage','stilstaande'],answer:'snelle',explain:'Snelle vertelt hoe vlug de auto rijdt.',image:'assets/adjectives/snelle-auto.png',alt:'Een snelle auto'},
      {sentence:'De ___ toren steekt boven de boom uit.',choices:['hoge','lage','brede'],answer:'hoge',explain:'Hoge vertelt hoe groot de toren is.',image:'assets/adjectives/hoge-toren.png',alt:'Een hoge toren naast een kleine boom'},
      {sentence:'De ___ mand zit boordevol appels.',choices:['volle','lege','lichte'],answer:'volle',explain:'Volle vertelt dat er veel appels in de mand zitten.',image:'assets/adjectives/volle-mand.png',alt:'Een volle mand met appels'},
      {sentence:'De ___ doos bevat geen speelgoed.',choices:['lege','volle','zware'],answer:'lege',explain:'Lege vertelt dat er niets in de doos zit.',image:'assets/adjectives/lege-doos.png',alt:'Een lege speelgoeddoos'},
      {sentence:'De ___ hond komt net uit bad.',choices:['natte','droge','modderige'],answer:'natte',explain:'Natte vertelt dat er water op de hond zit.',image:'assets/adjectives/natte-hond.png',alt:'Een natte hond'},
      {sentence:'De ___ leeuw kijkt erg kwaad.',choices:['boze','blije','slaperige'],answer:'boze',explain:'Boze vertelt hoe de leeuw zich voelt.',image:'assets/adjectives/boze-leeuw.png',alt:'Een boze maar kindvriendelijke leeuw'},
      {sentence:'De ___ vlinder heeft veel kleuren.',choices:['kleurrijke','grijze','witte'],answer:'kleurrijke',explain:'Kleurrijke vertelt dat de vlinder veel kleuren heeft.',image:'assets/adjectives/kleurrijke-vlinder.png',alt:'Een kleurrijke vlinder'}
    ],
    color: [
      {parts:[['Noor','wie'],['speelt','doet'],['buiten','waar']]},
      {parts:[['De hond','wie'],['eet','doet'],['een bot','wat']]},
      {parts:[['Morgen','wanneer'],['fietst','doet'],['Lina','wie'],['naar school','waar']]},
      {parts:[['Papa','wie'],['kookt','doet'],['vanavond','wanneer'],['soep','wat']]},
      {parts:[['De poes','wie'],['slaapt','doet'],['rustig','hoe'],['in haar mand','waar']]},
      {parts:[['Na school','wanneer'],['leest','doet'],['Mila','wie'],['een boek','wat']]},
      {parts:[['Omar','wie'],['loopt','doet'],['snel','hoe'],['naar huis','waar']]},
      {parts:[['In de tuin','waar'],['bouwt','doet'],['Sem','wie'],['een hut','wat']]}
    ]
  };
  let mode = '', round = 0, order = [], attempts = 0, soundOn = true, locked = false, exerciseCount = 10, answerOffset = 0;
  const discoverDemo = new URLSearchParams(location.search).get('ontdek') === '1';
  const shuffle = list => [...list].sort(() => Math.random() - .5);
  function speak(text){if(!soundOn||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-NL';u.rate=.95;const voices=speechSynthesis.getVoices();u.voice=voices.find(voice=>voice.lang.toLowerCase().startsWith('nl'))||null;speechSynthesis.speak(u)}
  function setFeedback(text,kind='',spokenText=''){feedback.textContent=text;feedback.className=`feedback ${kind}`;if(text)speak(spokenText||(kind==='good'?'Juist!':text))}
  function showMenu(){menu.hidden=false;game.hidden=true;finish.hidden=true;round=0;window.scrollTo({top:0,behavior:'smooth'})}
  function start(nextMode){mode=nextMode;round=0;answerOffset=Math.floor(Math.random()*3);const pools={article:()=>shuffle(data.article).slice(0,exerciseCount),sort:()=>shuffle(sortPool()).slice(0,exerciseCount),sentence:()=>shuffle(sentencePool()).slice(0,exerciseCount),adjective:adjectiveRound,color:()=>shuffle(colorPool()).slice(0,exerciseCount)};order=pools[mode]();menu.hidden=true;finish.hidden=true;game.hidden=false;$('modeLabel').textContent=modeNames[mode];render()}
  function sortPool(){const scenes=[
    ['assets/word-types/fiets.png','Lina rijdt met haar nieuwe fiets naar school.',[['fiets','zelfstandig naamwoord'],['rijdt','werkwoord'],['nieuwe','bijvoeglijk naamwoord']]],
    ['assets/word-types/rennen.png','De snelle kinderen rennen naar buiten.',[['kinderen','zelfstandig naamwoord'],['rennen','werkwoord'],['snelle','bijvoeglijk naamwoord']]],
    ['assets/word-types/vrolijk.png','Het vrolijke kind danst op de speelplaats.',[['kind','zelfstandig naamwoord'],['danst','werkwoord'],['vrolijke','bijvoeglijk naamwoord']]],
    ['assets/word-types/meester.png','De vriendelijke meester wijst naar het bord.',[['meester','zelfstandig naamwoord'],['wijst','werkwoord'],['vriendelijke','bijvoeglijk naamwoord']]],
    ['assets/word-types/schrijft.png','Noor schrijft een mooie brief.',[['brief','zelfstandig naamwoord'],['schrijft','werkwoord'],['mooie','bijvoeglijk naamwoord']]],
    ['assets/word-types/zachte.png','De lieve kat ligt op het kussen.',[['kat','zelfstandig naamwoord'],['ligt','werkwoord'],['lieve','bijvoeglijk naamwoord']]],
    ['assets/word-types/tuin.png','In de kleurrijke tuin groeien bloemen.',[['tuin','zelfstandig naamwoord'],['groeien','werkwoord'],['kleurrijke','bijvoeglijk naamwoord']]],
    ['assets/word-types/slaapt.png','De rustige poes slaapt op het bed.',[['bed','zelfstandig naamwoord'],['slaapt','werkwoord'],['rustige','bijvoeglijk naamwoord']]],
    ['assets/word-types/grote.png','De grote vrachtwagen draagt veel dozen.',[['vrachtwagen','zelfstandig naamwoord'],['draagt','werkwoord'],['grote','bijvoeglijk naamwoord']]],
    ['assets/word-types/fiets.png','De blauwe fiets staat bij de school.',[['school','zelfstandig naamwoord'],['staat','werkwoord'],['blauwe','bijvoeglijk naamwoord']]]
  ];const explain={['zelfstandig naamwoord']:'een naam voor een persoon, dier, plaats of ding',werkwoord:'het zegt wat iemand of iets doet',['bijvoeglijk naamwoord']:'het vertelt hoe iemand of iets is'};return scenes.flatMap(([image,sentence,items])=>items.map(([word,answer])=>({word,answer,explain:explain[answer],sentence,image})))}
  function sentencePool(){const scenes=[
    ['Noor','speelt',[['vandaag','wanneer'],['rustig','hoe'],['buiten','waar']]],
    ['de hond','eet',[['een groot bot','wat'],['in de tuin','waar']]],
    ['Mila','leest',[['vanavond','wanneer'],['een spannend boek','wat'],['in bed','waar']]],
    ['Amir','eet',[['langzaam','hoe'],['een rode appel','wat'],['aan tafel','waar']]],
    ['Lina','fietst',[['morgen','wanneer'],['snel','hoe'],['naar school','waar']]],
    ['papa','kookt',[['vanavond','wanneer'],['lekkere soep','wat'],['in de keuken','waar']]],
    ['de poes','slaapt',[['vandaag','wanneer'],['rustig','hoe'],['in haar mand','waar']]],
    ['Sem','bouwt',[['morgen','wanneer'],['een grote hut','wat'],['in de tuin','waar']]],
    ['Omar','loopt',[['na school','wanneer'],['snel','hoe'],['naar huis','waar']]],
    ['de juf','vertelt',[['in de voormiddag','wanneer'],['een spannend verhaal','wat'],['in de klas','waar']]]
  ];const calls=[
    {instruction:'Roep dat iemand snel naar binnen moet rennen.',words:['Ren','snel','naar binnen'],roles:['doet','hoe','waar'],answer:'Ren snel naar binnen !'},
    {instruction:'Roep dat iemand morgen naar school moet komen.',words:['Kom','morgen','naar school'],roles:['doet','wanneer','waar'],answer:'Kom morgen naar school !'},
    {instruction:'Roep dat iemand de doos buiten moet zetten.',words:['Zet','de zware doos','buiten'],roles:['doet','wat','waar'],answer:'Zet de zware doos buiten !'},
    {instruction:'Roep dat iemand vandaag de appel moet eten.',words:['Eet','vandaag','de lekkere appel'],roles:['doet','wanneer','wat'],answer:'Eet vandaag de lekkere appel !'},
    {instruction:'Roep dat iemand het boek luidop moet lezen.',words:['Lees','het spannende boek','luidop'],roles:['doet','wat','hoe'],answer:'Lees het spannende boek luidop !'},
    {instruction:'Roep dat iemand straks de fiets naar binnen moet brengen.',words:['Breng','straks','de fiets','naar binnen'],roles:['doet','wanneer','wat','waar'],answer:'Breng straks de fiets naar binnen !'},
    {instruction:'Roep dat iemand vandaag de warme jas moet dragen.',words:['Draag','vandaag','de warme jas'],roles:['doet','wanneer','wat'],answer:'Draag vandaag de warme jas !'},
    {instruction:'Roep dat iemand nu een mooie brief moet schrijven.',words:['Schrijf','nu','een mooie brief'],roles:['doet','wanneer','wat'],answer:'Schrijf nu een mooie brief !'},
    {instruction:'Roep dat iemand morgen een grote hut moet bouwen.',words:['Bouw','morgen','een grote hut'],roles:['doet','wanneer','wat'],answer:'Bouw morgen een grote hut !'},
    {instruction:'Roep dat iemand rustig in de tuin moet spelen.',words:['Speel','rustig','in de tuin'],roles:['doet','hoe','waar'],answer:'Speel rustig in de tuin !'}
  ];return scenes.flatMap(([who,does,extras],index)=>{const capDoes=does[0].toUpperCase()+does.slice(1),call=calls[index],extraWords=extras.map(part=>part[0]),questionContent=[who,...extraWords,does].join(' '),natural=naturalSentenceAnswers(who,does,extras);return [{type:'Mededelende zin',instruction:`Vertel de volledige zin over ${who}.`,words:[who,does,...extraWords],roles:['wie','doet',...extras.map(part=>part[1])],answers:natural.statements},{type:'Vraagzin',instruction:`Vraag of ${questionContent}.`,words:[who,capDoes,...extraWords],roles:['wie','doet',...extras.map(part=>part[1])],answers:natural.questions},{type:'Roepzin',instruction:call.instruction,words:call.words,roles:call.roles,answers:[call.answer]}]})}
  function naturalSentenceAnswers(who,does,extras){const cap=text=>text[0].toUpperCase()+text.slice(1),words=extras.map(part=>part[0]),roles=extras.map(part=>part[1]),capDoes=cap(does),statements=[`${cap(who)} ${does} ${words.join(' ')} .`],questions=[`${capDoes} ${who} ${words.join(' ')} ?`],add=(list,value)=>{if(!list.some(item=>normaliseSentence(item)===normaliseSentence(value)))list.push(value)},when=roles.indexOf('wanneer'),what=roles.indexOf('wat'),where=roles.indexOf('waar');if(when>=0){const rest=words.filter((_,i)=>i!==when);add(statements,`${cap(words[when])} ${does} ${who} ${rest.join(' ')} .`);add(statements,`${cap(who)} ${does} ${rest.join(' ')} ${words[when]} .`);add(questions,`${capDoes} ${who} ${rest.join(' ')} ${words[when]} ?`)}if(what>=0&&where>=0){const placeBeforeThing=[...words];[placeBeforeThing[what],placeBeforeThing[where]]=[placeBeforeThing[where],placeBeforeThing[what]];add(statements,`${cap(who)} ${does} ${placeBeforeThing.join(' ')} .`);add(questions,`${capDoes} ${who} ${placeBeforeThing.join(' ')} ?`)}return {statements,questions}}
  function adjectivePool(){const variants=[
    ['lieve',['De ___ poes ligt in haar mand.','Noor aait de ___ poes.','De ___ poes rust op een kussen.','Wij verzorgen de ___ poes.']],
    ['waakse',['De ___ hond let op het huis.','Een ___ hond houdt de poort in het oog.','De ___ hond spitst zijn oren.','Wij zien een ___ hond bij het hek.']],
    ['warme',['Lina draagt een ___ jas in de sneeuw.','De ___ jas beschermt Lina tegen de kou.','Lina trekt haar ___ jas aan.','Aan de kapstok hangt een ___ jas.']],
    ['sappige',['We eten een ___ appel.','Lina bijt in de ___ appel.','Er ligt een ___ appel op het bord.','Het sap druipt uit de ___ appel.']],
    ['oude',['Het ___ huis staat al lang in de straat.','Klimop groeit langs het ___ huis.','Het ___ huis heeft verweerde stenen.','We bekijken een ___ huis.']],
    ['grote',['De ___ vrachtwagen draagt veel dozen.','Een ___ vrachtwagen rijdt voorbij.','De ___ vrachtwagen is veel groter dan de kegels.','Wij laden de ___ vrachtwagen.']],
    ['geurige',['Lina ruikt aan de ___ bloem.','De ___ bloem ruikt heerlijk.','Een ___ bloem staat in de vaas.','De bij vliegt naar de ___ bloem.']],
    ['grappige',['De ___ clown laat iedereen lachen.','Wij lachen om de ___ clown.','De ___ clown jongleert met ballen.','Iedereen kijkt naar de ___ clown.']],
    ['kleine',['De ___ muis zit naast de appel.','Wij zien een ___ muis bij de appel.','De ___ muis lijkt piepklein.','Een ___ muis kijkt naar de appel.']],
    ['snelle',['De ___ auto rijdt over de weg.','Wij zien een ___ auto voorbijrijden.','De ___ auto zoeft door de bocht.','Een ___ auto rijdt vlug vooruit.']],
    ['hoge',['De ___ toren steekt boven de boom uit.','Wij kijken omhoog naar de ___ toren.','De ___ toren is veel groter dan de boom.','Naast de boom staat een ___ toren.']],
    ['volle',['De ___ mand zit boordevol appels.','De appels vallen bijna uit de ___ mand.','Wij dragen een ___ mand met appels.','Op de grond staat een ___ mand.']],
    ['lege',['De ___ doos bevat geen speelgoed.','Er zit niets in de ___ doos.','Wij kijken in een ___ doos.','Al het speelgoed ligt naast de ___ doos.']],
    ['natte',['De ___ hond komt net uit bad.','Water drupt uit de vacht van de ___ hond.','Wij drogen de ___ hond af.','De ___ hond staat naast een handdoek.']],
    ['boze',['De ___ leeuw kijkt erg kwaad.','De ___ leeuw fronst zijn wenkbrauwen.','Wij zien een ___ leeuw.','De poten van de ___ leeuw zijn gekruist.']],
    ['kleurrijke',['De ___ vlinder heeft veel kleuren.','Wij bewonderen de ___ vlinder.','De ___ vlinder spreidt zijn bonte vleugels.','Op de bloem zit een ___ vlinder.']]
  ];return variants.flatMap(([answer,sentences])=>{const base=data.adjective.find(item=>item.answer===answer);return sentences.map(sentence=>answer==='oude'&&sentence.includes('een ___ huis')?{...base,sentence,answer:'oud',choices:['oud','nieuw','klein'],explain:'Oud vertelt hoe lang het huis er al staat. Na “een” schrijven we hier oud zonder e.'}:{...base,sentence})})}
  function adjectiveRound(){const groups=Object.values(adjectivePool().reduce((all,item)=>{(all[item.image]??=[]).push(item);return all},{})),result=[];for(let cycle=0;result.length<exerciseCount;cycle++){let cycleGroups=shuffle(groups);if(result.length&&cycleGroups[0][0].image===result.at(-1).image)cycleGroups=[...cycleGroups.slice(1),cycleGroups[0]];cycleGroups.forEach(group=>{if(result.length<exerciseCount)result.push(group[cycle%group.length])})}return result}
  function colorPool(){const scenes=[['Noor','speelt','buiten','waar'],['de hond','eet','een bot','wat'],['Lina','fietst','naar school','waar'],['papa','kookt','soep','wat'],['de poes','slaapt','rustig','hoe'],['Mila','leest','een boek','wat'],['Omar','loopt','snel','hoe'],['Sem','bouwt','een hut','wat'],['de juf','vertelt','een verhaal','wat'],['Amir','tekent','in de klas','waar']];return scenes.flatMap(([who,does,extra,role],index)=>{const firstWho=who[0].toUpperCase()+who.slice(1);return [{parts:[[firstWho,'wie'],[does,'doet'],[extra,role]]},{parts:[[index%2?'Morgen':'Vandaag','wanneer'],[does,'doet'],[who,'wie'],[extra,role]]},{parts:[[index%2?'Na school':'In de voormiddag','wanneer'],[does,'doet'],[who,'wie'],[extra,role]]}]})}
  function render(){if('speechSynthesis'in window)speechSynthesis.cancel();locked=false;attempts=0;setFeedback('');$('checkButton').hidden=true;$('checkButton').textContent='Controleer mijn zin';$('roundLabel').textContent=`${round+1} / ${exerciseCount}`;$('progressBar').style.width=`${round/exerciseCount*100}%`;const q=order[round];activity.className='activity';activity.replaceChildren();if(mode==='article')renderArticle(q);if(mode==='sort')renderSort(q);if(mode==='sentence')renderSentence(q);if(mode==='adjective')renderAdjective(q);if(mode==='color')renderColor(q)}
  function button(label,onClick){const b=document.createElement('button');b.type='button';b.className='choice';b.textContent=label;b.onclick=()=>!locked&&onClick(b);return b}
  function choiceResult(buttonEl,correct,success,hint,spokenSuccess='Juist!',spokenHint=''){if(correct){locked=true;buttonEl.classList.add('correct');setFeedback(success,'good',spokenSuccess);setTimeout(next,1400)}else{attempts++;buttonEl.classList.add('wrong');setTimeout(()=>buttonEl.classList.remove('wrong'),450);const visibleHint=attempts===1?hint:'Kijk naar de gekleurde tip. Probeer nog eens.';setFeedback(visibleHint,'bad',spokenHint||visibleHint)}}
  function next(){if('speechSynthesis'in window)speechSynthesis.cancel();round++;if(round>=exerciseCount){game.hidden=true;finish.hidden=false;$('finishText').textContent=`Je oefende ${exerciseCount} opdrachten in ${modeNames[mode].toLowerCase()}.`;return}render()}
  function renderArticle(q){$('taskKind').textContent='DE OF HET?';$('taskKind').style.background=colors.lidwoord;$('prompt').textContent=`Is “${q.word}” een de-woord of een het-woord?`;$('support').textContent='Zeg beide mogelijkheden zachtjes: de … of het …';['de','het'].forEach(answer=>activity.append(button(`${answer} ${q.word}`,b=>choiceResult(b,answer===q.answer,`Juist: ${q.answer} ${q.word}. ${q.rule||`“${q.word}” is een ${q.answer}-woord.`}`,q.rule||`Luister nog eens: zeggen we de ${q.word} of het ${q.word}?`,'Juist!','Denk goed na en probeer opnieuw.'))))}
  function renderSort(q){$('taskKind').textContent='WOORDSOORT';$('taskKind').style.background=colors[q.answer];$('prompt').textContent=`Wat voor woord is “${q.word}”?`;$('support').textContent='Bekijk de prent en lees hoe het woord in de zin wordt gebruikt.';activity.classList.add('sort-activity');const context=document.createElement('div');context.className='sort-context';const picture=document.createElement('img');picture.className='sort-picture';picture.src=q.image;picture.alt='Prent bij de voorbeeldzin';const example=document.createElement('p');example.className='sort-example';const start=q.sentence.toLowerCase().indexOf(q.word.toLowerCase());example.append(q.sentence.slice(0,start));const highlighted=document.createElement('mark');highlighted.textContent=q.sentence.slice(start,start+q.word.length);example.append(highlighted,q.sentence.slice(start+q.word.length));context.append(picture,example);const choices=document.createElement('div');choices.className='sort-choices';['zelfstandig naamwoord','werkwoord','bijvoeglijk naamwoord'].forEach(answer=>{const b=button(answer,el=>choiceResult(el,answer===q.answer,`Juist! ${q.word} is een ${q.answer}: ${q.explain}.`,answer==='werkwoord'?'Een werkwoord zegt wat iemand doet. Past dat hier?':answer==='zelfstandig naamwoord'?'Kun je er de, het of een voor zetten?':'Vertelt dit woord hoe iemand of iets is?'));b.style.borderColor=colors[answer];choices.append(b)});activity.append(context,choices)}
  function renderAdjective(q){$('taskKind').textContent='BIJVOEGLIJK NAAMWOORD';$('taskKind').style.background=colors['bijvoeglijk naamwoord'];$('prompt').textContent=q.sentence;$('support').textContent='Kijk naar de prent. Welk woord past het best?';activity.classList.add('adjective-activity');const picture=document.createElement('img');picture.className='adjective-picture';picture.src=q.image;picture.alt=q.alt;activity.append(picture);const choices=document.createElement('div');choices.className='adjective-choices';activity.append(choices);const distractors=shuffle(q.choices.filter(answer=>answer!==q.answer)),answerOrder=[...distractors];answerOrder.splice((round+answerOffset)%3,0,q.answer);answerOrder.forEach(answer=>choices.append(button(answer,b=>choiceResult(b,answer===q.answer,`Mooi gekozen! ${q.explain}`,'Kijk nog eens goed naar de prent en lees de hele zin.'))))}
  function renderSentence(q){$('taskKind').textContent=q.type.toUpperCase();$('taskKind').style.background=q.type==='Vraagzin'?'#ffe59a':q.type==='Roepzin'?'#ffd3a6':'#dff3ff';$('prompt').textContent=`Maak een ${q.type.toLowerCase()}.`;$('support').textContent='Bouw de zin en kies zelf het juiste leesteken.';activity.classList.add('sentence-builder');const bankLabel=document.createElement('b');bankLabel.className='builder-label';bankLabel.textContent='Losse zinsdelen';const bank=document.createElement('div');bank.className='word-bank';const markLabel=document.createElement('b');markLabel.className='builder-label mark-label';markLabel.textContent='Kies een leesteken';const marks=document.createElement('div');marks.className='punctuation-bank';['.','?','!'].forEach(mark=>{const card=document.createElement('button');card.type='button';card.className='word-card punctuation';card.textContent=mark;card.draggable=true;marks.append(card)});const lineLabel=document.createElement('b');lineLabel.className='builder-label answer-label';lineLabel.textContent='Bouw je zin';const line=document.createElement('div');line.className='sentence-line answer-drop';line.dataset.placeholder='Sleep je zin hier';const listen=document.createElement('button');listen.type='button';listen.className='listen-sentence';listen.innerHTML='<span aria-hidden="true">🔊</span> Luister naar mijn zin';listen.onclick=()=>{const sentence=sentenceText(line);if(!sentence){feedback.textContent='Bouw eerst een stukje van je zin.';feedback.className='feedback';return}speak(sentence)};activity.append(bankLabel,bank,markLabel,marks,lineLabel,line,listen);let shuffled=q.words.map((word,index)=>({word,role:q.roles[index]}));const expectedMark=q.type==='Vraagzin'?'?':q.type==='Roepzin'?'!':'.',alreadyCorrect=items=>validSentenceArrangement(q,items,expectedMark);for(let tries=0;tries<12&&shuffled.length>1&&alreadyCorrect(shuffled);tries++)shuffled=shuffle(shuffled);if(shuffled.length>1&&alreadyCorrect(shuffled))shuffled=[...shuffled.slice(1),shuffled[0]];shuffled.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='word-card';b.textContent=item.word;b.draggable=true;if(item.role){b.dataset.role=item.role;b.style.setProperty('--role-color',roleColors[item.role])}bank.append(b)});enableSentenceBuilder(bank,line,marks);$('checkButton').hidden=false;$('checkButton').onclick=()=>checkSentence(q,line,bank)}
  function sentenceText(line){const text=[...line.children].map(card=>card.textContent).join(' ').replace(/\s+([.?!])/g,'$1');return text?text[0].toUpperCase()+text.slice(1):''}
  function normaliseSentence(text){return text.trim().replace(/\s+/g,' ').toLocaleLowerCase('nl-BE')}
  function validSentenceArrangement(q,items,mark){const expected=q.type==='Vraagzin'?'?':q.type==='Roepzin'?'!':'.';if(mark!==expected)return false;const value=items.map(item=>item.textContent||item.word).join(' ');return q.answers.some(answer=>normaliseSentence(answer.replace(/[.?!]\s*$/,''))===normaliseSentence(value))}
  function showPartsToMove(q,cards){cards.forEach(card=>card.classList.remove('needs-move'));const orders=q.answers.map(answer=>q.words.map(word=>({word,position:normaliseSentence(answer).indexOf(normaliseSentence(word))})).sort((a,b)=>a.position-b.position).map(item=>normaliseSentence(item.word))),current=cards.map(card=>normaliseSentence(card.textContent)),closest=orders.sort((a,b)=>b.filter((word,index)=>word===current[index]).length-a.filter((word,index)=>word===current[index]).length)[0];cards.forEach((card,index)=>card.classList.toggle('needs-move',current[index]!==closest[index]))}
  function renderColor(q){$('taskKind').textContent='ZIEN IS SNAPPEN';$('taskKind').style.background='#fff';$('prompt').textContent=q.parts.map(part=>part[0]).join(' ')+'.';$('support').textContent='Kies een kleur. Tik daarna op het juiste stukje van de zin.';activity.classList.add('color-activity');let chosenRole='';const palette=document.createElement('div');palette.className='role-palette';const paletteTitle=document.createElement('b');paletteTitle.className='palette-title';paletteTitle.textContent='1. Kies een kleur';Object.entries(roleColors).forEach(([role,color])=>{const pick=document.createElement('button');pick.type='button';pick.textContent=role;pick.style.background=color;pick.onclick=()=>{chosenRole=role;palette.querySelectorAll('button').forEach(button=>button.classList.remove('active'));pick.classList.add('active');setFeedback(`Je koos ${role}. Tik nu op het juiste stukje.`,'','')};palette.append(pick)});const sentenceTitle=document.createElement('b');sentenceTitle.className='sentence-title';sentenceTitle.textContent='2. Tik het passende stukje aan';const sentence=document.createElement('div');sentence.className='color-sentence';q.parts.forEach(([text,role])=>{const word=document.createElement('button');word.type='button';word.className='color-part';word.textContent=text;word.dataset.answer=role;word.onclick=()=>{if(!chosenRole){setFeedback('Kies eerst bovenaan een kleur.','bad','Kies eerst een kleur.');palette.classList.add('attention');setTimeout(()=>palette.classList.remove('attention'),600);return}word.dataset.chosen=chosenRole;word.style.background=roleColors[chosenRole];word.classList.add('painted');setFeedback(`${text} kreeg de kleur ${chosenRole}.`,'','')};sentence.append(word)});const punctuation=document.createElement('span');punctuation.className='sentence-punctuation';punctuation.textContent='.';punctuation.setAttribute('aria-label','punt');sentence.append(punctuation);activity.append(paletteTitle,palette,sentenceTitle,sentence);$('checkButton').hidden=false;$('checkButton').textContent='Klaar? Controleer!';$('checkButton').onclick=()=>checkColors(sentence)}
  function checkColors(sentence){const parts=[...sentence.querySelectorAll('.color-part')];if(parts.some(part=>!part.dataset.chosen)){setFeedback('Geef eerst ieder zinsdeel een kleur.','bad');return}const wrong=parts.filter(part=>part.dataset.chosen!==part.dataset.answer);if(!wrong.length){locked=true;setFeedback('Juist! Je ziet nu hoe de zin is opgebouwd.','good','Juist!');setTimeout(next,1500);return}attempts++;wrong.forEach(part=>{part.classList.add('wrong');setTimeout(()=>part.classList.remove('wrong'),500)});setFeedback(attempts===1?'Kijk naar de omlijnde zinsdelen. Welke vraag stel je erbij?':'Denk zo: wie doet wat, waar, hoe of wanneer?','bad')}
  function enableSentenceBuilder(bank,line,marks){let dragged=null;const clearHints=()=>line.querySelectorAll('.needs-move').forEach(card=>card.classList.remove('needs-move')),moveCard=(card,target)=>{clearHints();if(target===line&&card.classList.contains('punctuation')){const oldMark=line.querySelector('.punctuation');if(oldMark&&oldMark!==card)marks.append(oldMark)}target.append(card)};[bank,line,marks].forEach(container=>{container.addEventListener('dragstart',event=>{clearHints();dragged=event.target.closest('.word-card');if(dragged)dragged.classList.add('dragging')});container.addEventListener('dragend',()=>{dragged?.classList.remove('dragging');dragged=null});container.addEventListener('dragover',event=>{event.preventDefault();if(!dragged)return;const target=event.target.closest('.word-card');if(target&&target!==dragged)container.insertBefore(dragged,target.getBoundingClientRect().left+target.offsetWidth/2<event.clientX?target.nextSibling:target)});container.addEventListener('drop',event=>{event.preventDefault();if(!dragged||event.target.closest('.word-card'))return;moveCard(dragged,container)});container.addEventListener('click',event=>{const card=event.target.closest('.word-card');if(!card||dragged)return;if(card.parentElement===line)moveCard(card,card.classList.contains('punctuation')?marks:bank);else moveCard(card,line)})})}
  function checkSentence(q,line,bank){if(bank.children.length){setFeedback('Er liggen nog zinsdelen bovenaan. Zet ze eerst allemaal in je zin.','bad','Zet eerst alle zinsdelen in je zin.');return}const cards=[...line.querySelectorAll('.word-card:not(.punctuation)')],punctuation=line.querySelector('.punctuation'),mark=punctuation?.textContent||'',value=sentenceText(line),expected=q.type==='Vraagzin'?'?':q.type==='Roepzin'?'!':'.',markAtEnd=punctuation===line.lastElementChild;line.querySelectorAll('.needs-move').forEach(card=>card.classList.remove('needs-move'));if(markAtEnd&&validSentenceArrangement(q,cards,mark)){locked=true;setFeedback(`Juist! ${value}`,'good','Juist!');setTimeout(next,1400);return}attempts++;let hint='Verplaats de oranje omlijnde zinsdelen.';if(mark!==expected){punctuation?.classList.add('needs-move');hint=`Deze ${q.type.toLowerCase()} heeft een ${expected==='?'?'vraagteken':expected==='!'?'uitroepteken':'punt'} nodig.`}else if(!markAtEnd){punctuation?.classList.add('needs-move');hint='Zet het leesteken helemaal achteraan.'}else showPartsToMove(q,cards);if(attempts>1&&mark===expected&&markAtEnd)hint='Bekijk de oranje zinsdelen, verplaats ze en luister opnieuw.';setFeedback(hint,'bad');line.classList.remove('wrong');void line.offsetWidth;line.classList.add('wrong');setTimeout(()=>line.classList.remove('wrong'),450)}
  document.querySelectorAll('[data-count]').forEach(button=>button.onclick=()=>{exerciseCount=Number(button.dataset.count);document.querySelectorAll('[data-count]').forEach(choice=>choice.classList.toggle('active',choice===button))});
  if(discoverDemo){
    document.querySelectorAll('[data-count="20"],[data-count="30"]').forEach(button=>{
      button.classList.add('pro-count');
      button.setAttribute('aria-label',`${button.dataset.count} opdrachten, beschikbaar in PRO`);
      button.innerHTML=`${button.dataset.count} <small>PRO</small>`;
      button.onclick=()=>{if(confirm('20 en 30 opdrachten horen bij Zisa Spelen PRO. Wil je de mogelijkheden van PRO bekijken?'))window.open('https://demo.jufzisa.be/#zg-prijzen','_blank','noopener')};
    });
    const note=document.createElement('p');
    note.className='discover-note';
    note.innerHTML='<b>Ontdek:</b> kies 10 opdrachten. Met PRO kies je ook 20 of 30.';
    document.querySelector('.round-choice').append(note);
  }
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('backButton').onclick=showMenu;$('otherButton').onclick=showMenu;$('againButton').onclick=()=>start(mode);$('soundButton').onclick=()=>{soundOn=!soundOn;$('soundButton').textContent=soundOn?'🔊':'🔇';$('soundButton').setAttribute('aria-pressed',soundOn)};
})();
