const Q=(prompt,answers,correct,goals,explain,age='')=>({type:'choice',prompt,answers,correct,goals,explain,age});
const V=(prompt,answers,correct,goals,explain,visual)=>({type:'choice',prompt,answers,correct,goals,explain,visual});
const T=(prompt,answer,goals,explain)=>({type:'typing',prompt,answer,goals,explain});
const R=(prompt,cols,rows,start,finish,solution,goals,rocks=[])=>({type:'route',prompt,cols,rows,start,finish,solution,goals,rocks});
const M=(prompt,sequence,goals,success)=>({type:'media',prompt,sequence,goals,success});
const X=(prompt,tool,url,term,answer,goals,note,age='')=>({type:'external-search',prompt,tool,url,term,answer,goals,note,age});
const D=(prompt,goals)=>({type:'drawing',prompt,goals});
const speakerIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9v6h4l5 4V5L8 9H4Z"/><path d="M16 8.2a5 5 0 0 1 0 7.6M18.7 5.5a9 9 0 0 1 0 13"/></svg>';

const missions=[
 {id:'systemen',image:'assets/slimme-systemen.png',title:'Slimme systemen',text:'Van tik en beeld tot internet en opslag.',goals:['IT.002','IT.003','IT.004','IT.014'],tasks:[
  Q('Je zwaait tijdens een videogesprek. Wat krijgt de tablet als invoer?',['Jouw beweging via de camera','De andere klas op het scherm','De internetkabel','De batterij'],0,['IT.002','IT.003'],'De camera vangt jouw beweging op. Dat is invoer.'),
  Q('Wat zorgt ervoor dat twee klassen op afstand kunnen videobellen?',['Het internet','Een rekenmachine','Een printer','Een zaklamp'],0,['IT.002'],'Via het internet worden beeld en geluid doorgestuurd.'),
  Q('Je typt 8 + 4. Wat is de verwerking?',['De rekenmachine rekent','Je vingers typen','Het antwoord 12','Het scherm licht op'],0,['IT.003'],'Wat het toestel met jouw invoer doet, heet verwerking.'),
  Q('Een tablet toont de gemaakte foto. Wat is de uitvoer?',['De foto op het scherm','De tik op de knop','Het opladen','De cameraknop'],0,['IT.003'],'Wat het systeem teruggeeft, is de uitvoer.'),
  Q('Je wilt weten of het buiten regent. Wat is de eenvoudigste keuze?',['Even door het raam kijken','Een presentatie maken','Een filmpje opnemen','Een printer starten'],0,['IT.004'],'Niet elke taak heeft een digitaal systeem nodig.'),
  Q('Je wilt een foto naar oma sturen. Welke keuze helpt daarbij?',['Een telefoon of tablet','Een papieren gum','Een liniaal','Een drinkbus'],0,['IT.004','IT.014'],'Een digitaal toestel kan de foto maken, verwerken, bewaren en versturen.'),
  Q('Welke volgorde klopt bij een digitale foto?',['Tik → verwerken → foto verschijnt','Foto → tik → verwerken','Verwerken → foto → tik','Tik → foto → invoer'],0,['IT.002','IT.003','IT.014'],'Eerst komt invoer, daarna verwerking en dan uitvoer.'),
  Q('Jules typt in een presentatie en bewaart die. Wat gebruikt hij samen?',['Toetsenbord, app en opslag','Alleen een luidspreker','Alleen het internet','Schaar en lijm'],0,['IT.004','IT.014'],'Hij combineert hardware, software en opslag voor zijn taak.')
 ]},
 {id:'robot',image:'assets/robot-zisa.png',title:'Robotroute',text:'Herken patronen en bouw een stappenplan.',goals:['IT.015','IT.019'],tasks:[
  R('Laat de robot zelf naar de ster stappen. Tik eerst de pijlen in de juiste volgorde en druk daarna op “Laat de robot stappen”.',3,2,[0,0],[2,1],['→','→','↓'],['IT.015','IT.019']),
  V('De rots blokkeert de rechte weg. Welke pijlen brengen de robot veilig naar de ster?',['↑ → → → ↓','→ → →','↑ → ↓ → →','↓ → → →'],0,['IT.015'],'Deze reeks gaat eerst naar boven, rijdt boven de rots voorbij en gaat dan omlaag naar de ster.','choose-route'),
  V('Bekijk de stappen. Wat merk je aan het plan van de robot?',['Dezelfde drie stappen komen terug','Elke stap is helemaal anders','De robot heeft geen plan','De kleuren bepalen de route'],0,['IT.015'],'Je herkent dat dezelfde reeks stappen terugkomt.','repeat'),
  R('Breng de robot stap voor stap naar de ster.',4,3,[0,0],[3,2],['→','→','→','↓','↓'],['IT.015','IT.019']),
  R('Ontwerp een route rond de rots.',4,3,[0,1],[3,1],['↑','→','→','→','↓'],['IT.015','IT.019'],[[1,1]]),
  R('Maak zelf het volledige stappenplan naar de batterijster.',3,4,[0,0],[2,3],['↓','↓','↓','→','→'],['IT.015','IT.019'],[[1,1]]),
  R('Zoek een veilige weg langs twee hindernissen.',5,4,[0,3],[4,0],['↑','↑','↑','→','→','→','→'],['IT.015','IT.019'],[[1,3],[1,2],[3,1]]),
  R('Programmeer de robot van rechtsonder naar linksboven.',4,4,[3,3],[0,0],['↑','↑','↑','←','←','←'],['IT.015','IT.019'],[[2,3],[2,2]])
 ]},
 {id:'bedienen',image:'assets/toesteltraining.png',title:'Toesteltraining',text:'Bedien apps, geluid, batterij en bestanden.',goals:['IT.027','IT.030','IT.035'],tasks:[
  M('In het filmpje verschijnt een vlinder. Start de video, zet hem op pauze om de vleugels na te tekenen, speel daarna verder en stop wanneer je klaar bent.',['play','pause','play','stop'],['IT.027','IT.035'],'Je zette het beeld stil om rustig te kunnen tekenen en ging daarna verder.'),
  M('Je juf vraagt iets terwijl je naar een filmpje kijkt. Start het filmpje, pauzeer om te luisteren en stop het daarna omdat de les begint.',['play','pause','stop'],['IT.027','IT.035'],'Je gebruikte pauze om te luisteren en stop om het filmpje netjes af te sluiten.'),
  M('Het verhaal speelt, maar je hoort het te stil. Start het fragment, zet het geluid één stap luider zonder te stoppen, pauzeer bij het moeilijke woord, speel verder en stop aan het einde.',['play','volumeUp','pause','play','stop'],['IT.027','IT.035'],'Je paste het geluid tijdens het afspelen aan en gebruikte pauze op een nuttig moment.'),
  M('Je koptelefoon klinkt plots te luid. Start het fragment, zet het geluid zachter, pauzeer om te controleren en stop daarna.',['play','volumeDown','pause','stop'],['IT.027','IT.035'],'Je beschermde je oren door het volume zachter te zetten en controleerde bewust.'),
  Q('Je wilt straks verder luisteren vanaf dezelfde plaats. Welke knop kies je?',['Pauze','Stop','Geluid luider','Verwijderen'],0,['IT.027','IT.035'],'Pauze onderbreekt even zonder alles af te sluiten.'),
  Q('De batterij toont bijna leeg. Wat doe je?',['Het toestel veilig opladen','Nog luider spelen','Het scherm natmaken','De app verwijderen'],0,['IT.027','IT.035'],'Het batterijpictogram vertelt wanneer opladen nodig is.'),
  Q('Hoe open je meestal een app op een tablet?',['Tik één keer op het pictogram','Draai de tablet om','Hou volume vast','Blaas op het scherm'],0,['IT.027','IT.035'],'Je opent een app door het pictogram aan te tikken.'),
  Q('Je hoort niets door de koptelefoon. Wat controleer je eerst?',['Stekker en volume','Achtergrondkleur','Datum','Cameraflens'],0,['IT.027','IT.035'],'Controleer de verbinding en een veilig volume.'),
  Q('Je bent klaar in een app. Wat hoort daarbij?',['De app correct sluiten','De tablet laten vallen','Alles wissen','De kabel lostrekken'],0,['IT.027','IT.035'],'Apps openen én sluiten horen bij functioneel gebruik.'),
  Q('Welke bestandsnaam is duidelijk voor een herfstboomtekening?',['herfstboom-tekening','nieuw1','ding','aaaa'],0,['IT.030'],'Een herkenbare naam vertelt wat in het bestand zit.','7-8'),
  Q('Je wilt morgen verder aan je tekst. Wat doe je vóór je afsluit?',['Opslaan','Verwijderen','Volume verhogen','Een foto maken'],0,['IT.030','IT.035'],'Opslaan, sluiten en later openen vormen samen één bruikbare werkwijze.','7-8'),
  Q('Een fout bestand mag echt weg. Welke handeling kies je?',['Verwijderen','Openen','Afspelen','Vergroten'],0,['IT.030'],'Verwijderen gebruik je alleen wanneer het bestand weg mag.','7-8')
 ]},
 {id:'bestanden',image:'assets/bestandenhuis.png',title:'Bestandenhuis',text:'Open iets en ontdek welk type bestand het is.',minAge:'7-8',goals:['IT.028','IT.029','IT.030'],tasks:[
  Q('Welke omschrijving past bij een bestand?',['Digitale informatie die je kunt openen, opslaan of bewerken','Een knop op het toetsenbord','Een kabel','Een papieren map'],0,['IT.028'],'Een bestand bevat digitale informatie.'),
  Q('Je opent iets en ziet een geschreven verhaal. Wat is het?',['Tekstbestand','Geluidsbestand','Videobestand','Programma'],0,['IT.028','IT.029'],'Geschreven woorden wijzen op tekst.'),
  Q('Je opent iets en hoort alleen een verhaal. Wat is het?',['Geluidsbestand','Beeldbestand','Tekstbestand','Programma'],0,['IT.028','IT.029'],'Wat je alleen hoort, is geluid.'),
  Q('Je opent iets en ziet bewegend beeld met geluid. Wat is het?',['Videobestand','Tekstbestand','Beeldbestand','Rekenprogramma'],0,['IT.028','IT.029'],'Bewegend beeld met geluid is video.'),
  Q('Je ziet één stilstaande foto. Welk type is dat?',['Beeld','Video','Geluid','Tekst'],0,['IT.029'],'Een foto is een beeldbestand.'),
  Q('Je bewerkt een foto en wilt later verder. Welke reeks klopt?',['Openen → bewerken → duidelijk benoemen → opslaan → sluiten','Verwijderen → sluiten → openen','Afspelen → luider → printen','Sluiten → verwijderen → bewerken'],0,['IT.028','IT.029','IT.030'],'Hier combineer je bestand herkennen, type begrijpen en ermee werken.')
 ]},
 {id:'toetsenbord',image:'assets/toetsenbordtuin.png',title:'Toetsenbordtuin',text:'Typ, kies apparaten en werk er zorgzaam mee.',goals:['IT.037','IT.042','IT.044'],tasks:[
  T('Typ de zin precies na:','Zisa leest.',['IT.037','IT.042'],'Een gewone zin eindigt met een punt.'),
  T('Typ de vraag precies na:','Waar is mijn boek?',['IT.037','IT.042'],'Een vraag eindigt met een vraagteken.'),
  T('Typ de uitroep precies na:','Pas op!',['IT.037','IT.042'],'Een uitroep eindigt met een uitroepteken.'),
  T('Typ de code met letters en cijfers:','Zisa7',['IT.037','IT.042'],'Je gebruikte letters en een cijfer.'),
  Q('Hoe draag je een tablet het veiligst?',['Met twee handen','Aan één hoek','Aan de kabel','Terwijl je rent'],0,['IT.044'],'Met twee handen houd je het toestel stevig vast.'),
  Q('Wat doe je met een koptelefoon na gebruik?',['Rustig neerleggen of ophangen','Aan de kabel trekken','Op de grond laten vallen','Heel strak oprollen'],0,['IT.044'],'Zorgzaam omgaan voorkomt schade.'),
  Q('Je schrijft een zin, neemt je stem op en luistert terug. Wat gebruik je?',['Toetsenbord, microfoon en luidspreker','Alleen een scherm','Alleen een printer','Camera en rekenmachine'],0,['IT.037','IT.042','IT.044'],'Je combineert meerdere apparaten en behandelt ze zorgzaam.'),
  Q('Je neemt muziek op. Welk apparaat geeft de invoer?',['Microfoon','Luidspreker','Beamer','Scherm'],0,['IT.042'],'Een microfoon vangt geluid op als invoer.')
 ]},
 {id:'zoeken',image:'assets/zoekexpeditie.png',title:'Zoekexpeditie',text:'Zoek gericht, vergelijk en kies bruikbare bronnen.',goals:['IT.045','IT.046','IT.055','IT.058'],tasks:[
  Q('Je zoekt een korte tekst die speciaal voor kinderen is geschreven. Waar begin je het best?',['WikiKids','Gewone YouTube','TikTok','Een webwinkel'],0,['IT.045','IT.055'],'WikiKids is een Nederlandstalige internetencyclopedie voor en door kinderen.','6-7'),
  Q('Je zoekt voor school een duidelijk filmpje over dieren. Waar begin je het best?',['Schooltv','Gewone YouTube','Een reclamesite','Een willekeurig spel'],0,['IT.045','IT.055'],'Schooltv verzamelt onderwijsfilmpjes en is een goede startplek voor een schoolvraag.','6-7'),
  Q('Je wilt thuis zelf naar kinderfilmpjes zoeken. Welke keuze is het meest geschikt?',['YouTube Kids met een kinderprofiel dat een volwassene instelde','Gewone YouTube zonder begeleiding','Om het even welke videosite','Een link van een onbekende persoon'],0,['IT.045','IT.055','IT.058'],'YouTube Kids heeft kinderinstellingen, maar een volwassene blijft nodig omdat geen enkel filtersysteem perfect is.'),
  X('Ga echt zoeken op WikiKids. Zoek met de woorden “poten spin”. Hoeveel poten heeft een spin?','WikiKids','https://wikikids.nl/','poten spin',['8','acht'],['IT.046','IT.055'],'Kinderencyclopedie met begrijpelijke Nederlandstalige informatie.'),
  X('Ga echt zoeken op Schooltv. Gebruik de woorden “bijen honing”. Welk zoet voedsel maken bijen?','Schooltv','https://schooltv.nl/','bijen honing',['honing'],['IT.046','IT.055','IT.058'],'Onderwijsfilmpjes van de publieke omroep.'),
  X('Open YouTube Kids en zoek met de woorden “hoe groeit een vlinder”. Doe dit alleen wanneer je juf, meester of ouder het kinderprofiel heeft ingesteld.','YouTube Kids','https://www.youtubekids.com/','hoe groeit een vlinder',null,['IT.046','IT.055','IT.058'],'Kinderomgeving met ouderinstellingen. Zoekresultaten zijn niet allemaal vooraf door mensen bekeken.'),
  Q('Je krijgt de zoektermen “poten spin”. Wat typ je in?',['poten spin','leuk dier','ik wil iets weten','website'],0,['IT.046'],'Je gebruikt de aangereikte zoektermen gericht.'),
  Q('Welke zoekopdracht helpt om te weten wat een egel eet?',['eten egel','egel','dieren leuk','eten'],0,['IT.046'],'Twee gerichte woorden geven betere resultaten.'),
  Q('Je zoekt wanneer het zwembad open is. Welke bron past het best?',['De website van het zwembad','Een filmpje over zwemmen','Een oude foto','Een spelletje'],0,['IT.055','IT.058'],'De officiële website past bij de vraag.'),
  Q('Je zoekt feiten over bijen. Welke bron lijkt bruikbaar?',['Een natuurmuseum','Een snoepadvertentie','Een anonieme grap','Een spel zonder uitleg'],0,['IT.055','IT.058'],'Kijk of de maker kennis heeft over het onderwerp.'),
  Q('Je zoekt met “eten egel” en vindt twee verschillende antwoorden. Wat doe je?',['Vergelijk met een derde betrouwbare bron','Kies het leukste antwoord','Stop meteen','Verzin zelf iets'],0,['IT.046','IT.055','IT.058'],'Hier combineer je zoeken, herkennen en evalueren.'),
  Q('Een pagina heeft geen maker en wil meteen iets verkopen. Wat doe je?',['Zoek een andere bron','Geloof alles','Betaal meteen','Deel de link'],0,['IT.055','IT.058'],'Maker en doel zeggen iets over bruikbaarheid.')
 ]},
 {id:'mediafit',image:'assets/mediafit.png',title:'Mediafit',text:'Voel wat media doen en maak gezonde keuzes.',goals:['IT.061','IT.064'],tasks:[
  Q('Je ogen voelen moe na lang kijken. Wat helpt?',['Bewegen en in de verte kijken','Scherm dichter zetten','Licht uitdoen','Sneller klikken'],0,['IT.061','IT.064'],'Een kijk- en beweegpauze geeft rust.'),
  Q('Een spel maakt je boos en onrustig. Wat kun je doen?',['Stoppen en erover praten','Blijven spelen','Geluid luider zetten','Geheimhouden'],0,['IT.061','IT.064'],'Merk gevoelens op en vraag hulp.'),
  Q('Welke houding is het gezondst?',['Rechtop en op een fijne afstand','Scherm vlak voor je ogen','Gebogen zonder pauze','Rennen met de tablet'],0,['IT.061','IT.064'],'Een ontspannen houding en afstand zijn beter.'),
  Q('Een klasgenoot wil niet gefilmd worden. Wat doe je?',['Niet filmen en respecteren','Toch filmen','Stiekem delen','Boos worden'],0,['IT.061','IT.064'],'Gezond gebruik houdt rekening met anderen.'),
  Q('Welke afspraak helpt bij een rustige avond?',['Op tijd stoppen met schermen','In bed gamen','Alle meldingen aan','Scherm heel fel'],0,['IT.061','IT.064'],'Een vaste stopafspraak helpt je tot rust komen.'),
  Q('Je vriend krijgt nare berichten en slaapt er slecht van. Wat doe je samen?',['Stoppen, bewijs bewaren en hulp vragen','Alles doorsturen','Terugschelden','Blijven kijken'],0,['IT.061','IT.064'],'Je herkent de impact en kiest gezond en sociaal handelen.')
 ]},
 {id:'creatie',image:'assets/creatiestudio.png',title:'Creatiestudio',text:'Ken de mogelijkheden en kies slim gereedschap.',goals:['IT.092','IT.093'],tasks:[
  Q('Wat kun je met een tekenprogramma?',['Tekenen en kleuren','Een boterham snijden','Schoenen strikken','Een plant water geven'],0,['IT.092'],'Een tekenprogramma maakt digitale beelden.'),
  Q('Wat kun je met een opname-app?',['Stem of muziek opnemen','Een som gummen','Een boek kaften','Een stoel meten'],0,['IT.092'],'Een opname-app bewaart geluid.'),
  Q('Je wilt opa’s stem bewaren. Welke tool kies je?',['Een opname-app','Een tekenprogramma','Een kalender','Een rekenmachine'],0,['IT.093'],'Voor geluid kies je een opname-app.'),
  Q('Je wilt drie groepjes potloden tekenen en mooi inkleuren. Welke tool past?',['Een tekenprogramma','Een camera','Een muziekspeler','Een routeplanner'],0,['IT.092','IT.093'],'Met een tekenprogramma kun je lijnen tekenen en kleuren kiezen.'),
  D('Maak nu zelf een digitale tekening van een boom, de zon en gras. Teken echt en gebruik minstens twee kleuren.',['IT.092','IT.093','IT.042']),
  Q('Je maakt een uitnodiging met tekst, foto en ingesproken boodschap. Wat heb je nodig?',['Ontwerptool, toetsenbord, camera en microfoon','Alleen een rekenmachine','Alleen een luidspreker','Een zoektool zonder invoer'],0,['IT.092','IT.093','IT.042'],'Deze opdracht combineert toolkeuze met functioneel gebruik.'),
  Q('Je wilt een klasfoto op het grote bord tonen. Welke combinatie past?',['Fotobestand en smartboard','Microfoon en rekenmachine','Koptelefoon en papier','Wekker en toetsenbord'],0,['IT.092','IT.093','IT.042'],'Je kiest een beeldtool en geschikte uitvoer.')
 ]}
];

const goalDescriptions={'IT.002':'Globale werking van digitale systemen herkennen','IT.003':'Invoer, verwerking en uitvoer herkennen','IT.004':'Bepalen wanneer een digitaal systeem nuttig is','IT.014':'Kennis over informatieverwerking tonen','IT.015':'De opbouw van een lineair algoritme herkennen','IT.019':'Een lineair algoritme ontwerpen','IT.027':'Eenvoudige digitale handelingen illustreren','IT.028':'Een bestand herkennen','IT.029':'Het bestandstype bepalen','IT.030':'Bestanden openen, opslaan, sluiten, verwijderen en benoemen','IT.035':'Eenvoudige digitale handelingen gebruiken','IT.037':'Letters, cijfers en leestekens gebruiken','IT.042':'Invoer- en uitvoerapparaten functioneel gebruiken','IT.044':'Apparaten zorgzaam hanteren','IT.045':'De functie van een zoektool begrijpen','IT.046':'Met aangereikte zoektermen informatie verzamelen','IT.055':'Bruikbare digitale bronnen herkennen','IT.058':'Digitale bronnen evalueren','IT.061':'Gezond mediagebruik en impact illustreren','IT.064':'Digitale media gezond en sociaal gebruiken','IT.092':'Mogelijkheden van digitale tools beschrijven','IT.093':'Het juiste type tool voor een taak gebruiken'};
const goalAges={'IT.002':['6-7'],'IT.028':['7-8'],'IT.029':['7-8'],'IT.030':['7-8'],'IT.045':['6-7']};
const practicalGoals=new Set(['IT.019','IT.030','IT.035','IT.042','IT.044','IT.046','IT.064','IT.093']);
const readJson=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const state={age:localStorage.getItem('zisa-age')||'',done:readJson('zisa-done',[]),observed:readJson('zisa-observed',[]),hits:readJson('zisa-goal-hits',{})};
let session=null;
const $=s=>document.querySelector(s),welcome=$('#welcome'),dashboard=$('#dashboard'),grid=$('#missionGrid'),dialog=$('#missionDialog'),body=$('#missionBody');

document.querySelectorAll('.age-button').forEach(b=>b.addEventListener('click',()=>selectAge(b.dataset.age)));
$('#changeAge').addEventListener('click',()=>{dashboard.hidden=true;welcome.hidden=false});
$('.brand').addEventListener('click',e=>{e.preventDefault();if(state.age){welcome.hidden=true;dashboard.hidden=false;render()}});
$('#closeMission').addEventListener('click',()=>dialog.close());$('#teacherBtn').addEventListener('click',openTeacher);$('#closeTeacher').addEventListener('click',()=>$('#teacherDialog').close());
$('#resetProgress').addEventListener('click',()=>{if(confirm('Wil je alle missiesterren, oefenresultaten en observaties op dit toestel wissen?')){state.done=[];state.observed=[];state.hits={};save();render();openTeacher();toast('De voortgang is gewist.')}});

function selectAge(age){state.age=age;localStorage.setItem('zisa-age',age);welcome.hidden=true;dashboard.hidden=false;render()}
function goalForAge(goal){return !goalAges[goal]||goalAges[goal].includes(state.age)}function requiredGoals(m){return m.goals.filter(goalForAge)}function available(m){return !m.minAge||m.minAge===state.age}function tasksFor(m){return m.tasks.filter(t=>!t.age||t.age===state.age)}
function render(){const list=missions.filter(available);grid.innerHTML=list.map((m,i)=>{const total=tasksFor(m).length,done=state.done.includes(m.id);return `<button class="mission-card ${done?'done':''}" data-id="${m.id}"><span class="status">${done?'★ Behaald':total+' opdrachten'}</span><img class="mission-art" src="${m.image}" alt=""><h2>${m.title}</h2><p>${m.text}</p><span class="card-foot">Missie ${i+1} · ${requiredGoals(m).length} doelen</span></button>`}).join('');grid.querySelectorAll('.mission-card').forEach(c=>c.addEventListener('click',()=>startMission(c.dataset.id)));const done=list.filter(m=>state.done.includes(m.id)).length;$('#starCount').textContent=`${done} / ${list.length}`;$('#progressFill').style.width=`${done/list.length*100}%`}
function startMission(id){const mission=missions.find(m=>m.id===id);session={mission,tasks:tasksFor(mission),index:0,correct:0,answered:false};$('#missionNumber').textContent=requiredGoals(mission).join(' · ');$('#missionTitle').textContent=mission.title;renderTask();dialog.showModal()}
function speak(text){if(!('speechSynthesis'in window))return toast('Voorlezen wordt niet ondersteund op dit toestel.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.88;speechSynthesis.speak(u)}
function renderTask(){clearInterval(window.zisaMediaTimer);const{tasks,index,mission}=session;if(index>=tasks.length)return finishMission();const task=tasks[index];session.answered=false;body.innerHTML=`<div class="round-head"><span>Opdracht ${index+1} van ${tasks.length}</span><div class="round-track"><i style="width:${index/tasks.length*100}%"></i></div></div><div class="mission-scene scene-${mission.id}"><img class="scene-art" src="${mission.image}" alt=""><div><small>ZISA’S OPDRACHT</small><p>${task.prompt}</p><button class="speak-button" aria-label="Lees de opdracht voor" title="Lees de opdracht voor" data-speak="${task.prompt.replaceAll('"','&quot;')}">${speakerIcon}</button></div></div><div id="taskArea"></div><div class="feedback" hidden></div>`;body.querySelector('[data-speak]').addEventListener('click',e=>speak(e.currentTarget.dataset.speak));if(task.type==='choice')renderChoice(task);else if(task.type==='typing')renderTyping(task);else if(task.type==='media')renderMedia(task);else if(task.type==='external-search')renderExternalSearch(task);else if(task.type==='drawing')renderDrawing(task);else renderRoute(task)}
function orderedAnswers(task){const items=task.answers.map((text,original)=>({text,original})),right=items.splice(task.correct,1)[0],slot=(session.index+missions.indexOf(session.mission))%4;items.unshift(items.pop());items.splice(slot,0,right);return items}
function robotExample(kind){if(!kind)return'';if(kind==='repeat')return `<div class="robot-example repeat-example"><img src="assets/robot-zisa.png" alt="robot"><div><strong>Eerste stukje</strong><span>↑</span><span>↑</span><span>←</span></div><div><strong>Nog een keer</strong><span>↑</span><span>↑</span><span>←</span></div></div>`;const cells=kind==='choose-route'?['empty','empty','empty','empty','robot','rock','empty','star','empty','empty','empty','empty']:['robot','arrow','arrow','turn','star'];const token=x=>x==='robot'?'<span class="example-cell"><img src="assets/robot-zisa.png" alt="robot bij de start"></span>':x==='star'?'<span class="example-cell example-star">★</span>':x==='rock'?'<span class="example-cell"><i class="example-rock"></i></span>':x==='arrow'?'<span class="example-cell example-arrow">→</span>':x==='turn'?'<span class="example-cell example-arrow">↓</span>':'<span class="example-cell"></span>';return `<div class="robot-example board-example ${kind}">${cells.map(token).join('')}</div>`}
function renderChoice(task){const area=$('#taskArea'),answers=orderedAnswers(task);area.innerHTML=`${robotExample(task.visual)}<div class="answer-grid">${answers.map((a,i)=>`<div class="answer-row"><button class="answer" data-original="${a.original}"><span>${['A','B','C','D'][i]}</span>${a.text}</button><button class="speak-answer" data-read="${a.text.replaceAll('"','&quot;')}" aria-label="Lees antwoord ${['A','B','C','D'][i]} voor" title="Lees antwoord voor">${speakerIcon}</button></div>`).join('')}</div>`;area.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>checkChoice(task,Number(b.dataset.original))));area.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',e=>speak(e.currentTarget.dataset.read)))}
function checkChoice(task,original){if(session.answered)return;session.answered=true;const buttons=[...body.querySelectorAll('.answer')],ok=original===task.correct;buttons.forEach(b=>{b.disabled=true;if(Number(b.dataset.original)===task.correct)b.classList.add('correct');if(Number(b.dataset.original)===original&&!ok)b.classList.add('wrong')});showFeedback(ok,ok?task.explain:`Bijna. ${task.explain}`,task.goals)}
function renderTyping(task){const area=$('#taskArea');area.innerHTML=`<div class="copy-card"><strong>${task.answer}</strong><button class="speak-answer" data-read="${task.answer}" aria-label="Lees de voorbeeldzin voor" title="Lees voor">${speakerIcon}</button></div><label class="type-label">Typ hier<input class="typing-box" autocomplete="off" autocapitalize="sentences" spellcheck="false"></label><button class="primary-button" data-check>Controleer</button>`;area.querySelector('[data-read]').addEventListener('click',e=>speak(e.currentTarget.dataset.read));const input=area.querySelector('input');area.querySelector('[data-check]').addEventListener('click',()=>{if(session.answered)return;session.answered=true;const clean=s=>s.trim().replace(/\s+/g,' ').toLocaleLowerCase('nl'),ok=clean(input.value)===clean(task.answer);input.classList.add(ok?'input-correct':'input-wrong');showFeedback(ok,ok?task.explain:`Kijk naar hoofdletters, spaties en leesteken. Typ: ${task.answer}`,task.goals)});setTimeout(()=>input.focus(),80)}
function renderExternalSearch(task){const area=$('#taskArea'),host=new URL(task.url).hostname.replace('www.','');area.innerHTML=`<div class="safe-tool-card"><div class="tool-badge">${task.tool.slice(0,2).toUpperCase()}</div><div><strong>${task.tool}</strong><span>${host}</span><p>${task.note}</p></div></div><div class="search-steps"><span><b>1</b>Open de website.</span><span><b>2</b>Typ precies: <mark>${task.term}</mark></span><span><b>3</b>Bekijk een passend resultaat en kom terug.</span></div><a class="external-tool-button" href="${task.url}" target="_blank" rel="noopener noreferrer">Open ${task.tool} in een nieuw tabblad</a>${task.answer?`<label class="type-label search-answer">Wat heb je gevonden?<input class="typing-box" autocomplete="off" spellcheck="false"></label><button class="primary-button" data-check>Controleer mijn antwoord</button>`:`<button class="primary-button" data-done>Ik heb gezocht en ben terug</button>`}`;if(task.answer){const input=area.querySelector('input');area.querySelector('[data-check]').addEventListener('click',()=>{if(session.answered)return;session.answered=true;const value=input.value.trim().toLocaleLowerCase('nl'),ok=task.answer.includes(value);input.classList.add(ok?'input-correct':'input-wrong');showFeedback(ok,ok?`Goed gezocht met “${task.term}” op ${task.tool}.`:`Zoek nog eens met precies “${task.term}” en lees het resultaat aandachtig.`,task.goals)})}else area.querySelector('[data-done]').addEventListener('click',()=>{if(session.answered)return;session.answered=true;showFeedback(true,`Je gebruikte de opgegeven zoekwoorden in ${task.tool}. Vertel aan een volwassene wanneer je iets vreemds of vervelends ziet.`,task.goals)})}
function renderDrawing(task){const area=$('#taskArea');area.innerHTML=`<div class="drawing-studio"><div class="drawing-tools"><strong>Kies een kleur</strong>${['#173f5f','#168aad','#39a96b','#f4b942','#ef6f61','#8f63b8'].map((c,i)=>`<button class="color-swatch ${i===0?'active':''}" data-color="${c}" style="--swatch:${c}" aria-label="Kies kleur ${i+1}"></button>`).join('')}<button class="clear-drawing">Opnieuw</button></div><canvas width="680" height="340" aria-label="Tekenblad"></canvas><div class="drawing-status" aria-live="polite">Begin te tekenen. Gebruik minstens twee kleuren.</div><button class="primary-button" data-finish disabled>Mijn tekening is klaar</button></div>`;const canvas=area.querySelector('canvas'),ctx=canvas.getContext('2d'),colors=new Set();let color='#173f5f',drawing=false,moves=0;ctx.lineWidth=9;ctx.lineCap='round';ctx.lineJoin='round';const point=e=>{const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height]},update=()=>{const ready=moves>=8&&colors.size>=2;area.querySelector('[data-finish]').disabled=!ready;area.querySelector('.drawing-status').textContent=ready?'Mooi! Je gebruikte de tekentool en meerdere kleuren.':'Teken verder en gebruik minstens twee kleuren.'};canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);const[x,y]=point(e);ctx.beginPath();ctx.moveTo(x,y);colors.add(color);update()});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const[x,y]=point(e);ctx.strokeStyle=color;ctx.lineTo(x,y);ctx.stroke();moves++;update()});canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false);area.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{color=b.dataset.color;area.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x===b))}));area.querySelector('.clear-drawing').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);moves=0;colors.clear();update()});area.querySelector('[data-finish]').addEventListener('click',()=>{if(session.answered)return;session.answered=true;showFeedback(true,'Je koos zelf kleuren en gebruikte een echte digitale tekentool om iets te maken.',task.goals)})}
function mediaIcon(action){const shapes={play:'<path d="M9 6.8v10.4L18 12 9 6.8Z" fill="currentColor"/>',pause:'<rect x="7" y="6" width="4" height="12" rx="1" fill="currentColor"/><rect x="13" y="6" width="4" height="12" rx="1" fill="currentColor"/>',stop:'<rect x="7" y="7" width="10" height="10" rx="1.5" fill="currentColor"/>',volumeDown:'<path d="M4 10v4h4l5 4V6l-5 4H4Z" fill="currentColor"/><path d="M16 12h5" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round"/>',volumeUp:'<path d="M3 10v4h4l5 4V6l-5 4H3Z" fill="currentColor"/><path d="M15 12h6M18 9v6" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">${shapes[action]}</svg>`}
function renderMedia(task){
 const area=$('#taskArea'),labels={play:'Afspelen',pause:'Pauze',stop:'Stop',volumeUp:'Luider',volumeDown:'Zachter'};
 const clips=[
  {src:'assets/video-vlinderweide.png',title:'Vlinders in de bloemenweide'},
  {src:'assets/video-eekhoornbos.png',title:'De eekhoorn in het herfstbos'},
  {src:'assets/video-zeeschildpad.png',title:'Op reis met de zeeschildpad'},
  {src:'assets/video-eekhoornbos.png',title:'Geluiden van het herfstbos'}
 ],clip=clips[session.index%clips.length];
 let progress=0,volume=2,actions=[];
 area.innerHTML=`<div class="media-player"><div class="media-screen stopped"><img class="video-image" src="${clip.src}" alt="${clip.title}"><span class="video-label">${clip.title}</span><span class="video-state">Klaar</span><span class="sound-meter" aria-live="polite">Geluid: <i></i><i></i><i></i><i></i></span></div><div class="media-timeline"><div class="media-progress"><i></i></div><output class="time-code">0:00 / 0:45</output></div><div class="media-controls">${['play','pause','stop','volumeDown','volumeUp'].map(action=>`<button data-action="${action}" aria-label="${labels[action]}" title="${labels[action]}">${mediaIcon(action)}<span class="visually-hidden">${labels[action]}</span></button>`).join('')}</div><div class="action-plan"><strong>Jouw plan</strong>${task.sequence.map((x,i)=>`<span><b>${i+1}</b>${mediaIcon(x)}${labels[x]}</span>`).join('')}</div><div class="action-log" aria-live="polite">De video staat klaar.</div></div>`;
 const screen=area.querySelector('.media-screen'),stateLabel=area.querySelector('.video-state');
 const update=()=>{area.querySelector('.media-progress i').style.width=progress+'%';area.querySelector('.time-code').textContent=`0:${String(Math.round(progress*.45)).padStart(2,'0')} / 0:45`;area.querySelectorAll('.sound-meter i').forEach((bar,i)=>bar.classList.toggle('on',i<volume))};
 update();
 area.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{if(session.answered)return;const action=b.dataset.action;actions.push(action);if(action==='play'){clearInterval(window.zisaMediaTimer);screen.classList.remove('stopped');screen.classList.add('playing');stateLabel.textContent='Speelt';window.zisaMediaTimer=setInterval(()=>{progress=Math.min(100,progress+1);update();if(progress>=100){clearInterval(window.zisaMediaTimer);screen.classList.remove('playing');stateLabel.textContent='Einde'}},100)}if(action==='pause'){clearInterval(window.zisaMediaTimer);screen.classList.remove('playing');stateLabel.textContent='Gepauzeerd'}if(action==='stop'){clearInterval(window.zisaMediaTimer);screen.classList.remove('playing');screen.classList.add('stopped');stateLabel.textContent='Gestopt';progress=0}if(action==='volumeUp')volume=Math.min(4,volume+1);if(action==='volumeDown')volume=Math.max(1,volume-1);update();area.querySelector('.action-log').textContent=actions.map(x=>labels[x]).join(' → ');const expected=task.sequence.slice(0,actions.length);if(actions.some((x,i)=>x!==expected[i])){actions=[];area.querySelector('.action-log').textContent='Die knop past nu niet bij de situatie. Lees de opdracht en probeer de reeks opnieuw.';return}if(actions.length===task.sequence.length){session.answered=true;showFeedback(true,task.success||'Je hebt de mediaknoppen in een echte situatie gebruikt.',task.goals)}}))
}
function renderRoute(task){const area=$('#taskArea'),cells=[];for(let r=0;r<task.rows;r++)for(let c=0;c<task.cols;c++){const start=c===task.start[0]&&r===task.start[1],finish=c===task.finish[0]&&r===task.finish[1],blocked=task.rocks.some(([x,y])=>x===c&&y===r);cells.push(`<div class="route-cell ${blocked?'blocked':''}" data-x="${c}" data-y="${r}">${finish?'<span class="goal-star">★</span>':''}${blocked?'<span class="rock-shape"></span>':''}${start?'<img class="robot-token" src="assets/robot-zisa.png" alt="robot">':''}</div>`)}area.innerHTML=`<div class="route-board" style="--route-cols:${task.cols};grid-template-columns:repeat(${task.cols},58px)">${cells.join('')}</div><div class="route-code" aria-live="polite"></div><div class="arrow-pad"><button data-arrow="↑">↑<small>boven</small></button><button data-arrow="→">→<small>rechts</small></button><button data-arrow="↓">↓<small>onder</small></button><button data-arrow="←">←<small>links</small></button><button data-undo>↶<small>terug</small></button></div><button class="primary-button" data-check>Laat de robot stappen</button>`;const entered=[],draw=()=>area.querySelector('.route-code').innerHTML=entered.length?entered.map(x=>`<b>${x}</b>`).join(''):'<span>Tik je pijlen…</span>';draw();area.querySelectorAll('[data-arrow]').forEach(b=>b.addEventListener('click',()=>{if(!session.answered&&entered.length<16){entered.push(b.dataset.arrow);draw()}}));area.querySelector('[data-undo]').addEventListener('click',()=>{if(!session.answered){entered.pop();draw()}});area.querySelector('[data-check]').addEventListener('click',()=>walkRobot(task,entered,area))}
async function walkRobot(task,entered,area){if(session.answered||!entered.length)return;session.answered=true;area.querySelectorAll('.arrow-pad button,[data-check]').forEach(b=>b.disabled=true);let[x,y]=task.start;const robot=area.querySelector('.robot-token'),moveTo=()=>area.querySelector(`[data-x="${x}"][data-y="${y}"]`).appendChild(robot);let crashed=false;for(const arrow of entered){await new Promise(resolve=>setTimeout(resolve,420));if(!area.isConnected||!dialog.open)return;if(arrow==='↑')y--;if(arrow==='↓')y++;if(arrow==='←')x--;if(arrow==='→')x++;if(x<0||y<0||x>=task.cols||y>=task.rows||task.rocks.some(([rx,ry])=>rx===x&&ry===y)){crashed=true;robot.classList.add('bumped');break}moveTo()}const ok=!crashed&&x===task.finish[0]&&y===task.finish[1];showFeedback(ok,ok?'De robot heeft jouw programma uitgevoerd en bereikte de ster!':crashed?'De robot botste tegen een hindernis of de rand. Bouw een nieuwe route.':'De robot voerde alle stappen uit, maar staat nog niet bij de ster.',task.goals)}
function showFeedback(ok,message,goals){const f=body.querySelector('.feedback');f.hidden=false;f.className=`feedback ${ok?'success':'try-again'}`;f.innerHTML=`<strong>${ok?'Goed gedaan!':'Nog eens kijken'}</strong><span>${message}</span>`;if(ok){session.correct++;goals.forEach(addHit)}const next=document.createElement('button');next.className='primary-button';next.textContent=ok?'Volgende opdracht →':'Opnieuw proberen';next.addEventListener('click',()=>{if(ok)session.index++;renderTask()});body.appendChild(next);save()}
function addHit(goal){if(goalForAge(goal))state.hits[goal]=Math.min(2,(state.hits[goal]||0)+1)}
function finishMission(){const passed=session.correct===session.tasks.length;if(passed&&!state.done.includes(session.mission.id))state.done.push(session.mission.id);save();render();body.innerHTML=`<div class="mission-finish"><div class="finish-stars">${passed?'★★★':'★★☆'}</div><h3>${passed?'Missie volbracht!':'Sterk geoefend!'}</h3><p>${passed?'Je maakte alle opdrachten juist en verdiende een missiester.':'Probeer later opnieuw voor de volle missiester.'}</p><div class="score-orb"><strong>${session.correct}/${session.tasks.length}</strong><span>juist</span></div><button class="primary-button" data-close>Terug naar de missies</button></div>`;body.querySelector('[data-close]').addEventListener('click',()=>dialog.close());if(passed)toast('Missiester verdiend! ★')}
function save(){localStorage.setItem('zisa-done',JSON.stringify(state.done));localStorage.setItem('zisa-observed',JSON.stringify(state.observed));localStorage.setItem('zisa-goal-hits',JSON.stringify(state.hits))}function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openTeacher(){const t=$('#teacherDialog');if(t.open)t.close();const goals=[...new Set(missions.filter(available).flatMap(requiredGoals))];const reached=goals.filter(g=>(state.hits[g]||0)>=2&&(!practicalGoals.has(g)||state.observed.includes(g))).length;$('#teacherSummary').textContent=`${reached} van ${goals.length} doelen bereikt · leeftijd ${state.age||'nog niet gekozen'}. Elk doel vraagt minstens 2 geslaagde oefenmomenten.`;$('#teacherGoals').innerHTML=goals.map(g=>{const hits=state.hits[g]||0,practical=practicalGoals.has(g),observed=state.observed.includes(g),mastered=hits>=2&&(!practical||observed);return `<div class="goal-row ${mastered?'mastered':''}"><strong>${g}</strong><span>${goalDescriptions[g]}<small>${hits}/2 digitale oefenmomenten</small></span>${practical?`<button class="observe-button ${observed?'checked':''}" data-goal="${g}">${observed?'✓ Praktijk gezien':'Praktijk afvinken'}</button>`:`<em>${mastered?'✓ Bereikt':hits+'/2 geoefend'}</em>`}</div>`}).join('');$('#teacherGoals').querySelectorAll('[data-goal]').forEach(b=>b.addEventListener('click',()=>{const goal=b.dataset.goal,index=state.observed.indexOf(goal);if(index>=0)state.observed.splice(index,1);else state.observed.push(goal);save();openTeacher()}));t.showModal()}
if(state.age){welcome.hidden=true;dashboard.hidden=false;render()}
