import {inboxClient} from './inlever-api.js';
const el=id=>document.getElementById(id),status=message=>{el('connection').textContent=message};let api,selected;
el('closePreview').onclick=()=>el('preview').close();el('print').onclick=()=>window.print();
function button(label,action){const b=document.createElement('button');b.textContent=label;b.onclick=action;return b}
async function showRound(box){
 selected=box;el('works').replaceChildren();status('Werk ophalen…');
 try{const result=await api.call('readMissionInbox',{inboxId:box.id});const title=document.createElement('h2');title.textContent=box.label;el('works').append(title);
  const actions=document.createElement('div');actions.className='actions';
  if(box.open)actions.append(button('Inleveren sluiten',async()=>{try{await api.call('manageMissionInbox',{action:'close',inboxId:box.id});await loadRounds();status('De ronde is gesloten. Je kunt het werk nog bekijken.')}catch(e){status(e.message)}}));
  actions.append(button('Ronde en werk verwijderen',async()=>{if(!confirm('Alle werkstukken uit '+box.label+' definitief verwijderen? Download eerst wat je wilt bewaren.'))return;try{await api.call('manageMissionInbox',{action:'delete',inboxId:box.id});el('works').replaceChildren();selected=null;await loadRounds();status('De ronde en haar werkstukken zijn verwijderd.')}catch(e){status(e.message)}}));el('works').append(actions);
  if(!result.works.length){const p=document.createElement('p');p.textContent='Nog geen werk ingeleverd. Klik op Vernieuwen nadat kinderen hebben ingeleverd.';el('works').append(p)}
  result.works.forEach(work=>{const row=document.createElement('article'),p=document.createElement('p');p.textContent=work.author+' — '+work.task+' · '+new Date(work.createdAt).toLocaleString('nl-BE');row.append(p,button('Open werk',async()=>{try{status('Afbeelding ophalen…');const data=await api.call('readMissionInbox',{inboxId:box.id,workId:work.id});el('workImage').src=data.png;el('workTitle').textContent=work.author+' — '+work.task;el('download').href=data.png;el('download').download=(work.author+'-'+work.task).replace(/[^a-z0-9À-ÿ_-]/gi,'-')+'.png';el('preview').showModal();status('Werk geopend.')}catch(e){status(e.message)}}));el('works').append(row)});status('Overzicht bijgewerkt.');
 }catch(e){status(e.message)}
}
async function loadRounds(){const result=await api.call('manageMissionInbox',{action:'list'});el('rounds').replaceChildren();if(!result.boxes.length)el('rounds').textContent='Nog geen inleverrondes.';result.boxes.forEach(box=>el('rounds').append(button(box.label+' · '+box.count+' werkjes · '+(box.open?'open':'gesloten'),()=>showRound(box))))}
el('createRound').onsubmit=async e=>{e.preventDefault();if(!api)return;el('create').disabled=true;try{const box=await api.call('manageMissionInbox',{action:'create',label:el('className').value});const link=new URL('./',location.href);link.hash=new URLSearchParams({klas:box.id,sleutel:box.token}).toString();el('classLink').value=link.href;el('newLink').hidden=false;await loadRounds();status('Je ronde is open. Bewaar de klaslink: de geheime sleutel wordt maar één keer getoond.')}catch(e){status(e.message)}finally{el('create').disabled=false}};
el('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(el('classLink').value);el('linkStatus').textContent='Gekopieerd. Deel deze link alleen met je klas.'}catch{el('classLink').select();el('linkStatus').textContent='Selecteer en kopieer de link.'}};
el('refresh').onclick=async()=>{try{await loadRounds();if(selected)await showRound(selected)}catch(e){status(e.message)}};
if(!window.ZISA_INLEVER_CONFIG?.enabled){status('Nog niet online geactiveerd. Dit is de voorbereide inleverplek; er wordt geen leerlingwerk verstuurd.');el('rounds').textContent='Hier verschijnen de echte inzendingen na activering. Er zijn geen voorbeeldinzendingen.'}
else{try{api=await inboxClient();if(!api.auth.currentUser){status('Log eerst op deze website in met je bestaande Zisa-leerkrachtaccount.');const a=document.createElement('a');a.href='../pro/';a.textContent='Naar de leerkrachtlogin';el('connection').append(' ',a);api=null}else{await loadRounds();el('create').disabled=false;el('refresh').disabled=false;status('Aangemeld. Je ziet alleen je eigen klassenwerk.')}}catch(e){status(e.message)}}
