/* Practical curriculum revision. All pupil work stays on this device. */
const practiceTask=(type,prompt,goals,extra={})=>({type,prompt,goals,...extra});
const mediaGoals=['IT.027','IT.035'];
const fileGoals=['IT.028','IT.029'];
const mediaTasks=[
 practiceTask('media','Doe alle stappen van de kijkopdracht. Start het filmpje en kijk wat er met de bloem gebeurt. Volg daarna steeds de stap die oplicht.',mediaGoals,{age:'6-7',clip:'flower',watchUntil:10,question:'Wat verandert er aan de bloem tijdens het filmpje?',answers:['De bloem gaat dicht','De bloem gaat open','De bloem valt van de plant'],answer:'De bloem gaat open'}),
 practiceTask('media','Je hoort het konijnenfilmpje niet goed. Start het en zet het geluid een stap luider. Luister even. Druk daarna op stop en op Klaar.',mediaGoals,{age:'6-7',adjust:'volumeUp',clip:'rabbit'}),
 practiceTask('media','Het vlinderfilmpje klinkt te luid. Start het en zet het geluid een stap zachter. Luister even. Druk daarna op stop en op Klaar.',mediaGoals,{age:'6-7',adjust:'volumeDown',clip:'monarch'}),
 practiceTask('media','Je wilt even stoppen met kijken. Start het beekfilmpje, druk op pauze en speel weer verder. Druk daarna op stop en op Klaar.',mediaGoals,{age:'6-7',clip:'stream',pausePractice:true}),
 practiceTask('media','Bekijk hoe de eend eten zoekt. Pauzeer het filmpje en beantwoord de Kijkvraag. Speel daarna verder en druk op stop.',mediaGoals,{age:'7-8',clip:'duck',question:'Waar zoekt de eend eten in dit filmpje?',answers:['Op de oever','Onder water','In de lucht'],answer:'Onder water'}),
 practiceTask('media','Je maatje wil rustig werken. Start de waterval en zet het geluid zachter. Pauzeer even voor je maatje. Speel daarna verder en druk op stop.',mediaGoals,{age:'7-8',clip:'waterfall',adjust:'volumeDown',pausePractice:true}),
 practiceTask('media','Je hoort de uitleg over de vis niet goed. Start het filmpje en zet het geluid luider. Pauzeer en beantwoord de Kijkvraag. Speel verder en druk op stop.',mediaGoals,{age:'7-8',clip:'fish',adjust:'volumeUp',question:'Wat beweegt de vis om te zwemmen?',answers:['Zijn vinnen','Zijn mond','Zijn ogen'],answer:'Zijn vinnen'}),
 practiceTask('media','Bekijk de bijzondere vleugels van deze vlinder. Pauzeer en beantwoord de Kijkvraag. Speel daarna verder en druk op stop.',mediaGoals,{age:'7-8',clip:'glasswing',question:'Wat is bijzonder aan de grote vlakken van de vleugels?',answers:['Ze zijn helemaal zwart','Je kunt erdoorheen kijken','Ze zijn helemaal geel'],answer:'Je kunt erdoorheen kijken'})
];
const mediaClips={
 flower:{title:'Een bloem gaat open',file:'flower-v3.mp4',credit:'MDN, CC0. Vertraagd; nieuwe Nederlandse vertelstem.'},
 rabbit:{title:'Het konijn en de vlinder',file:'konijn.mp4',credit:'Big Buck Bunny — Blender Foundation, CC BY 3.0. Kort fragment via W3Schools.'},
 monarch:{title:'Een vlinder op een plant',file:'monarch-v3.mp4',credit:'Truem, Monarch butterfly 1, CC0.',source:'Monarch_butterfly_1.webm'},
 stream:{title:'Water over de stenen',file:'stream-v3.mp4',credit:'leeroy / LIFEOFVIDS, Tiny Water Fall-HD, CC BY 3.0.',source:'Tiny_Water_Fall-HD.ogv'},
 duck:{title:'Een eend zoekt eten',file:'duck-v3.mp4',credit:'Whpq, Canvas back duck diving, CC BY-SA 4.0. Vertraagd; bewerking onder dezelfde licentie.',source:'Canvas_back_duck_diving.webm'},
 waterfall:{title:'Bij de waterval',file:'waterfall-v3.mp4',credit:'Kbmotswagole, Mma Legage Waterfall video, CC0.',source:'Mma_Legage_Waterfall_video.webm'},
 fish:{title:'Een vis tussen de rotsen',file:'fish-v3.mp4',credit:'Uusijani, Boxfish at Artis, CC0.',source:'Boxfish_at_Artis.ogv'},
 glasswing:{title:'Een vlinder met doorzichtige vleugels',file:'glasswing-v3.mp4',credit:'Brandon, Glasswinged butterfly, CC BY 2.0.',source:'Glasswinged_butterfly.webm'}
};
const observeTask=(prompt,goals,criteria)=>practiceTask('observe',prompt,goals,{criteria});
const files=[
 {name:'bloemenfoto',kind:'Beeld',src:'assets/video-vlinderweide.png'},
 {name:'bericht-van-zisa',kind:'Tekst',text:'Dag klas! Vandaag kijken we naar bloemen. Breng je kleurpotloden mee.'},
 {name:'bloemenfilmpje',kind:'Video',src:'assets/bloemen-kijken.mp4'},
 {name:'luisterbericht',kind:'Geluid',src:'assets/bloemen-stem.wav'},
 {name:'kleurenmenger',kind:'Programma'}
];
missions.find(m=>m.id==='systemen').tasks=[
 practiceTask('system-photo','Maak een foto van een voorwerp voor de gevonden-voorwerpentafel. Vergroot een detail en bewaar je foto.',['IT.003','IT.014'],{subject:'Leg een voorwerp op tafel. Zorg dat er geen mensen op de foto staan.',name:'gevonden-voorwerp'}),
 practiceTask('system-sound','Maak een dierenraadsel voor je maatje. Neem een dierengeluid op en luister het terug.',['IT.003','IT.014'],{message:'Bedenk een dier. Doe het geluid na. Je maatje mag straks raden.'}),
 practiceTask('system-photo','Maak een detailfoto van je bouwwerk of tekening. Vergroot het stukje dat je aan je maatje wilt tonen.',['IT.003','IT.014'],{subject:'Leg een bouwwerk of tekening klaar. Zet het belangrijke stukje midden in de foto.',name:'mijn-detailfoto'}),
 practiceTask('system-sound','Spreek een opruimtip in voor de klas. Luister of je boodschap goed te horen is.',['IT.003','IT.014'],{message:'Vertel waar iets hoort. Bijvoorbeeld: de blokken horen in de doos.'}),
 observeTask('Je maatje zit naast je. Toon je echte voorwerp. Toon daarna je detailfoto. Wanneer helpt de foto? Probeer beide manieren.',['IT.004','IT.014'],'Laat het kind beide manieren echt gebruiken en uitleggen waarom rechtstreeks tonen of vergroten nuttig is. Laat het bij de eigen foto aanwijzen: camera levert beeld, app vergroot, scherm toont resultaat.'),
 observeTask('Je wilt je werk tonen aan iemand die niet in de klas is. Bekijk met je leerkracht hoe een foto via jullie klasapp gedeeld kan worden. Vergelijk dit met tonen op je eigen scherm.',['IT.002','IT.004'],'Geen nepverzending: bekijk een echte, door de school toegelaten deelroute met de leerkracht. Verstuur alleen met diens toestemming. Alleen lokaal tonen bereikt de andere persoon niet.'),
 observeTask('Neem samen een bericht op in de gewone opname-app van het toestel. Luister terug en wijs aan: waar ging je stem naar binnen en waar komt het geluid uit?',['IT.003','IT.014'], 'Controleer transfer naar een andere app en of het kind microfoon, opname/verwerking en luidspreker aan de eigen handeling kan koppelen.')
];
missions.find(m=>m.id==='systemen').tasks[6].age='7-8';
const robotMission=missions.find(m=>m.id==='robot');
robotMission.tasks[1]=R('De rots blokkeert de weg. Bouw zelf een route eromheen. Elke pijl is één vakje.',4,3,[0,1],[3,1],['↑','→','→','→','↓'],['IT.015','IT.019'],[[1,1]]);
robotMission.tasks[2]=R('Maak twee keer hetzelfde stukje: rechts, omlaag. Voer je plan uit en kijk waar de robot komt.',3,3,[0,0],[2,2],['→','↓','→','↓'],['IT.015','IT.019']);
robotMission.tasks[6].age='7-8';robotMission.tasks[7].age='7-8';
missions.find(m=>m.id==='bedienen').tasks=[...mediaTasks,
 practiceTask('launcher','Open de tekenapp. Teken iets met twee kleuren. Sluit daarna de app met het kruisje.',mediaGoals,{app:'tekenen'}),
 practiceTask('launcher','Open de schrijfapp. Typ Dag Zisa! en sluit daarna de app.',mediaGoals,{app:'schrijven'}),
 observeTask('Bekijk het echte batterijpictogram van jouw toestel met je leerkracht. Toon waar je ziet of opladen nodig is.',mediaGoals,'Herkenning van het batterijpictogram; passende actie met begeleiding. Niet zelfstandig kabels of stopcontacten laten bedienen.')
];
missions.find(m=>m.id==='bestanden').tasks=[...files.map(file=>practiceTask('file-open',`Open ${file.name}. Onderzoek wat er verschijnt. Kies daarna welk soort bestand dit is.`,fileGoals,{file})),
 practiceTask('file-edit','Maak een bericht voor de klas. Bewaar het als bloemenbericht, sluit het en open je bewaarde bericht opnieuw.',['IT.028','IT.030','IT.035'],{name:'bloemenbericht',text:'Breng je kleurpotloden mee.'}),
 practiceTask('file-edit','Bewaar een tweede bericht met de naam klasuitstap. Sluit het en open het opnieuw om te controleren.',['IT.028','IT.030','IT.035'],{name:'klasuitstap',text:'We gaan naar het park!'}),
 practiceTask('file-delete','Ruim de oefenmap op. Verwijder alleen proefklad. Bewaar de uitnodiging.',['IT.028','IT.030'],{})
];
const keyboard=missions.find(m=>m.id==='toetsenbord');
keyboard.tasks=keyboard.tasks.slice(0,4).concat([
 T('Verbeter deze zin: voeg de ontbrekende spatie en het punt toe.','Zisa leest.',['IT.037','IT.042'],'Je verbeterde de tekst.',),
 practiceTask('record','Neem de boodschap Dag Zisa! op. Stop de opname en luister jouw stem terug.',['IT.042','IT.093'],{sentence:'Dag Zisa!'}),
 observeTask('Leg je toestel en koptelefoon rustig klaar. Toon hoe je ze na het werk veilig opbergt.',['IT.044'],'Ziet de leerkracht zorgvuldig dragen, neerleggen en omgaan met kabels tijdens echt gebruik?'),
 observeTask('Werk samen: laat je maatje luisteren en geef de koptelefoon rustig door.',['IT.044','IT.064'],'Observeer materiaalzorg en rekening houden met de ander tijdens een echte gezamenlijke opdracht.')
]);
keyboard.tasks[4].prefill='Zisaleest';
const searchMission=missions.find(m=>m.id==='zoeken');
searchMission.tasks=[
 practiceTask('search-lab','Zoek met poten spin. Open een resultaat dat jouw vraag beantwoordt: hoeveel poten heeft een spin?',['IT.045','IT.046','IT.055','IT.058'],{term:'poten spin',answer:'8',topic:'spin'}),
 practiceTask('search-lab','Zoek met bijen honing. Open een bruikbare bron. Wat maken bijen?',['IT.045','IT.046','IT.055','IT.058'],{term:'bijen honing',answer:'honing',topic:'bij'}),
 ...searchMission.tasks.filter(t=>t.type==='external-search'&&t.answer).map(t=>({...t,goals:['IT.046','IT.055'],requiresObservation:true})),
 observeTask('Zoek nog eens op Schooltv met bijen honing. Toon je leerkracht waarom jouw gekozen filmpje bij de vraag past.',['IT.046','IT.055','IT.058'],'Kind voert de aangereikte woorden in, opent een resultaat en legt uit welke informatie bruikbaar is. Een juist feit alleen bewijst het zoeken niet.')
];
missions.find(m=>m.id==='mediafit').tasks=[
 practiceTask('break','Onderbreek je schermwerk. Kies een korte pauze en voer die uit. Vertel daarna hoe je je voelt.',['IT.061','IT.064']),
 observeTask('Vertel over een keer dat een scherm je blij, boos of onrustig maakte. Luister ook naar je maatje. Bedenk samen één helpende afspraak.',['IT.061','IT.064'],'Kind verbindt een echte ervaring met een gevoel en formuleert een bruikbare afspraak; observeer toepassing later opnieuw.'),
 practiceTask('break','Neem opnieuw een pauze. Kies deze keer iets anders en kijk na afloop hoe je lichaam voelt.',['IT.061','IT.064']),
 observeTask('Test jullie afspraak tijdens een echt werkmoment: stop wanneer de afgesproken tijd voorbij is en berg rustig op.',['IT.044','IT.064'],'Observeer daadwerkelijk stoppen, lichaamshouding en zorgvuldig opbergen; een klik geldt niet als bewijs.')
];
missions.find(m=>m.id==='creatie').tasks=[
 practiceTask('create','Maak een bloemenkaart voor de kijktafel in de klas. Voeg een afbeelding van bloemen in. Schrijf erbij wat je ziet. Bewaar je kaart en toon ze aan je maatje.',['IT.092','IT.093','IT.037'],{name:'mijn-bloemenkaart',topic:'flowers'}),
 practiceTask('create','Maak een dierenkaart om aan je maatje te tonen. Voeg een afbeelding van een dier in. Schrijf er een eigen zin bij over dat dier. Bewaar je kaart.',['IT.092','IT.093','IT.042'],{name:'mijn-dierenkaart',topic:'animals'}),
 D('Kies kleuren en teken een boom, de zon en gras. Laat daarna aan je leerkracht zien welke tekentools je gebruikte.',['IT.092','IT.093','IT.042']),
 D('Maak een tweede tekening: bloemen voor de klas. Gebruik minstens twee kleuren en toon je werk.',['IT.092','IT.093','IT.042']),
 practiceTask('record','Kies de opnametool om een uitnodiging in te spreken: Kom je tekenen? Neem op en luister terug.',['IT.092','IT.093','IT.042'],{sentence:'Kom je tekenen?'}),
 practiceTask('record','Maak nog een luisterbericht voor je maatje: Veel plezier! Neem op, stop en luister terug.',['IT.092','IT.093','IT.042'],{sentence:'Veel plezier!'})
];
missions.forEach(m=>{m.goals=[...new Set(m.tasks.flatMap(t=>t.goals))];m.tasks.forEach((t,i)=>t.id=m.id+'-'+i)});
missions.find(m=>m.id==='systemen').tasks.forEach((t,i)=>t.id='systemen-praktijk-v3-'+i);
mediaTasks.forEach(t=>t.id='bedienen-media-v3-'+t.age+'-'+t.clip);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cleanupPractice=()=>{};
const originalRenderTask=renderTask;
renderTask=function(){cleanupPractice();cleanupPractice=()=>{};document.querySelectorAll('video,audio').forEach(el=>el.pause());window.speechSynthesis?.cancel();const task=session.tasks[session.index];if(!task)return finishMission();
 if(['choice','typing','route','drawing','external-search'].includes(task.type)){originalRenderTask();if(task.prefill)$('#taskArea input').value=task.prefill;return}
 session.answered=false;body.innerHTML=`<div class="round-head">Opdracht ${session.index+1} van ${session.tasks.length} · ${state.age} jaar</div><div class="mission-scene scene-${session.mission.id}"><img class="scene-art" src="${session.mission.image}" alt=""><div><small>ZISA’S DOE-OPDRACHT</small><p>${escapeHtml(task.prompt)}</p><button class="speak-answer" aria-label="Lees de opdracht voor">${speakerIcon}</button></div></div><div id="taskArea" class="practice-area"></div><div class="feedback" hidden></div>`;body.querySelector('.speak-answer').onclick=()=>speak(task.prompt);
 const handlers={'system-photo':renderSystemPhoto,'system-sound':renderSystemSound,'media':renderRealMedia,'file-open':renderFileOpen,'file-edit':renderFileEdit,'file-delete':renderFileDelete,'create':renderCreate,'record':renderRecorder,'launcher':renderLauncher,'transform':renderTransform,'calculator':renderCalculator,'observe':renderObservation,'break':renderBreak,'search-lab':renderSearchLab};handlers[task.type](task);
};
dialog.addEventListener('close',()=>{cleanupPractice();cleanupPractice=()=>{};document.querySelectorAll('video,audio').forEach(el=>el.pause());window.speechSynthesis?.cancel()});
function completePractice(task,message){if(session.answered)return;session.answered=true;showFeedback(true,message,task.goals)}
function note(text){const el=$('#taskArea .practice-note');if(el)el.textContent=text}
function sayButton(text){return `<button class="read-small" type="button" data-say="${escapeHtml(text)}" aria-label="Lees voor">${speakerIcon}</button>`}
function wireRead(){document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say))}
function mediaRequirements(task, progress){
 const checks=[['Gestart',progress.started]];
 if(task.adjust)checks.push([task.adjust==='volumeUp'?'Geluid luider gezet':'Geluid stiller gezet',progress.adjusted]);
 if(task.question||task.pausePractice)checks.push(['Zelf gepauzeerd',progress.paused]);
 if(task.question)checks.push(['Kijkvraag beantwoord',progress.answered]);
 if(task.question||task.pausePractice)checks.push(['Verder afgespeeld',progress.resumed]);
 checks.push(['Op stop gedrukt',progress.stopped]);return checks;
}
function renderRealMedia(task){
 const area=$('#taskArea'),progress={started:false,adjusted:false,paused:false,answered:false,resumed:false,stopped:false};
 const clip=mediaClips[task.clip],label=task.clip==='flower'?'Kijk wat er verandert':task.question&&task.clip==='glasswing'?'Een bijzondere vlinder':clip.title;
 let busy=false,resumeAt=null;
 const title={play:'Afspelen',pause:'Pauze',stop:'Stop',volumeDown:'Stiller',volumeUp:'Luider'};
 area.innerHTML=`<div class="work-panel media-exercise"><h3>${label}</h3><video class="real-video" playsinline preload="metadata" src="assets/${clip.file}"></video><div class="media-timeline"><progress max="1" value="0" aria-label="Voortgang filmpje"></progress><output class="clock">0:00</output></div><div class="media-controls">${['play','pause','stop','volumeDown','volumeUp'].map(a=>`<button data-action="${a}" aria-label="${title[a]}" title="${title[a]}">${mediaIcon(a)}</button>`).join('')}</div><p class="volume-status"></p><p class="practice-note" role="status">${task.question?'Bekijk eerst de Kijkvraag. Start daarna het filmpje.':'Start het filmpje met de driehoek.'}</p><section class="pause-question" ${task.question?'':'hidden'} aria-label="Kijkvraag">${task.question?`<strong>Kijkvraag</strong><h3 tabindex="-1">${task.question}</h3>${sayButton('Kijkvraag. '+task.question+' Start het filmpje en pauzeer om te antwoorden.')}<p class="question-hint">Pauzeer het filmpje om te antwoorden.</p>${task.answers.map(a=>`<button class="tool-choice" disabled data-answer="${a}">${a}</button>${sayButton(a)}`).join('')}`:''}</section><ul class="media-checks" aria-label="Jouw oefenstappen"></ul><div class="media-ready-bar"><button class="primary-button" data-ready>Klaar – volgende opdracht →</button><small data-next></small></div><details><summary>Hulp bij de knoppen</summary><p>Driehoek: afspelen. Twee streepjes: pauze. Vierkant: stoppen en terug naar het begin. Luidspreker − / +: stiller / luider.</p></details><small>${clip.credit} ${clip.source?`Ingekort en voorzien van Nederlandse vertelstem. <a href="https://commons.wikimedia.org/wiki/File:${clip.source}" target="_blank" rel="noopener">Bron en licentie</a>`:''}</small></div>`;
 const video=area.querySelector('video'),ready=area.querySelector('[data-ready]');
 area.querySelector('.media-exercise').classList.add('media-guided');
 let guideKey='',guideWords='',alive=true,voiceVersion=0;
 const cancelGuide=()=>{voiceVersion++;window.speechSynthesis?.cancel();video.muted=false;};
 const readGuide=(words=guideWords)=>{
  cancelGuide();
  if(!window.speechSynthesis||typeof SpeechSynthesisUtterance==='undefined')return;
  const version=voiceVersion,utterance=new SpeechSynthesisUtterance(words);
  utterance.lang='nl-BE';utterance.rate=.85;
  // Keep the film narration from competing with the instruction.
  video.muted=true;
  const restore=()=>{if(alive&&version===voiceVersion)video.muted=false;};
  utterance.onend=restore;utterance.onerror=restore;
  speechSynthesis.speak(utterance);
 };
 function guideStep(){
  let key,words,icon='play';
  if(!progress.started){key='start';words='Tik op de driehoek. Dan begint het filmpje.';}
  else if(progress.stopped&&mediaRequirements(task,progress).every(([,done])=>done)){key='done';words='Goed gedaan! Tik op Klaar voor het volgende filmpje.';icon='done';}
  else if(video.paused&&(!progress.paused||progress.stopped)){key='restart';words='Tik op de driehoek om verder te kijken.';}
  else if(task.adjust&&!progress.adjusted){key=task.adjust;icon=key;words=key==='volumeUp'?'Tik op de luidspreker met het plusje. Dan klinkt het luider.':'Tik op de luidspreker met het minnetje. Dan klinkt het zachter.';}
  else if(!watchedEnough()){key='watch';words='Kijk goed. Wat verandert er? Ik zeg wanneer je mag pauzeren.';icon='watch';}
  else if((task.question||task.pausePractice)&&!progress.paused){key='pause';icon='pause';words='Tik nu op de twee streepjes. Dan staat het beeld stil.';}
  else if(task.question&&!progress.answered){key='answer';icon='answer';words='Beantwoord nu de vraag. '+task.question+' '+task.answers.map((a,i)=>(i+1)+': '+a).join('. ')+'. Tik op jouw antwoord. Je kunt elk antwoord ook beluisteren.';}
  else if((task.question||task.pausePractice)&&!progress.resumed){key='resume';words='Tik weer op de driehoek. Dan speelt het filmpje verder.';}
  else {key='stop';icon='stop';words='Tik op het vierkant. Daarmee stop je het filmpje.';}
  const short={start:'Start het filmpje',restart:'Speel verder',volumeUp:'Zet het geluid luider',volumeDown:'Zet het geluid zachter',watch:'Kijk wat er verandert',pause:'Zet het beeld stil',answer:task.question,resume:'Speel verder',stop:'Stop het filmpje',done:'Klaar!'};
  const answerNow=key==='answer';
  area.querySelector('.pause-question').hidden=!answerNow;
  const control={start:'play',restart:'play',resume:'play',pause:'pause',stop:'stop',volumeUp:'volumeUp',volumeDown:'volumeDown'}[key];
  area.querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('next-control',b.dataset.action===control));
  const changed=key!==guideKey;
  guideKey=key;guideWords=words;
  const symbol=['watch','answer','done'].includes(icon)?speakerIcon:mediaIcon(icon);
  const guide=area.querySelector('.practice-note');
  guide.innerHTML=`<span class="guide-symbol" aria-hidden="true">${symbol}</span><strong>${escapeHtml(short[key])}</strong><button type="button" class="guide-repeat" aria-label="Luister nog eens">${speakerIcon}</button>`;
  guide.querySelector('.guide-repeat').onclick=()=>readGuide();
  if(changed)readGuide();
 }
 video.poster='assets/video-start.svg';
 let watchedUntil=0;
 const watchedEnough=()=>watchedUntil>=(task.watchUntil||0);
 video.volume=task.adjust==='volumeUp'?.2:task.adjust==='volumeDown'?.6:.4;
 const update=()=>{area.querySelector('progress').value=video.duration?video.currentTime/video.duration:0;area.querySelector('.clock').textContent='0:'+String(Math.floor(video.currentTime)).padStart(2,'0');area.querySelector('.volume-status').textContent='Geluid: '+Math.round(video.volume*100)+'%';const checks=mediaRequirements(task,progress),next=checks.findIndex(([,done])=>!done),all=next===-1;const actions=['play',...(task.adjust?[task.adjust]:[]),...(task.question||task.pausePractice?['pause']:[]),...(task.question?['answer']:[]),...(task.question||task.pausePractice?['resume']:[]),'stop'];const labels={play:'Druk op afspelen',volumeUp:'Zet het geluid luider',volumeDown:'Zet het geluid stiller',pause:watchedEnough()?'Druk op pauze':'Kijk nog even wat er verandert',answer:'Beantwoord de Kijkvraag',resume:'Speel weer verder',stop:'Druk op stop'};area.querySelector('.media-checks').innerHTML=`<li class="steps-title">Doe alle ${checks.length} stappen</li>`+checks.map(([text,done],i)=>`<li class="${done?'done':i===next?'current-step':''}" ${i===next?'aria-current="step"':''}>${done?'✓':i+1+'.'} ${done?text:labels[actions[i]]}${i===next?' — nu jij':''}</li>`).join('');area.querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('next-control',!all&&(actions[next]==='resume'?'play':actions[next])===b.dataset.action&&(actions[next]!=='pause'||watchedEnough())));ready.classList.toggle('ready',all);ready.disabled=!all;area.querySelector('[data-next]').textContent=all?'Deze oefening is klaar. Klik om door te gaan.':'Doe eerst alle stappen hierboven.';syncQuestion();};
 const missingHelp=()=>{if(!progress.started)return 'Druk op afspelen om te beginnen.';if(task.adjust&&!progress.adjusted)return 'Speel het filmpje af en druk op de luidspreker met '+(task.adjust==='volumeUp'?'+ om het luider te zetten.':'− om het stiller te zetten.');if(!watchedEnough())return 'Kijk wat er verandert. Druk op pauze wanneer die stap oplicht.';if((task.question||task.pausePractice)&&!progress.paused)return 'Druk tijdens het kijken op pauze.';if(task.question&&!progress.answered)return 'Beantwoord de vraag in het vak Kijkvraag. Pauzeer eerst als het filmpje nog speelt.';if((task.question||task.pausePractice)&&!progress.resumed)return 'Druk op afspelen om verder te kijken.';if(!progress.stopped)return 'Druk op het vierkant om te stoppen. Daarna kun je op Klaar klikken.';return 'Goed gedaan. Klik op Klaar – volgende opdracht.';};
 const syncQuestion=()=>{area.querySelectorAll('[data-answer]').forEach(b=>b.disabled=!progress.paused||!video.paused||progress.stopped||progress.answered);if(task.question){area.querySelector('.pause-question').classList.toggle('question-active',progress.paused&&video.paused&&!progress.stopped&&!progress.answered);area.querySelector('.question-hint').textContent=progress.answered?'Kijkvraag klaar.':'Tik op je antwoord. De luidspreker leest het voor.';}guideStep();};
 video.ontimeupdate=()=>{if(!video.paused)watchedUntil=Math.max(watchedUntil,video.currentTime);if(resumeAt!==null&&!video.paused&&video.currentTime>resumeAt+.2)progress.resumed=true;update()};
 video.onended=()=>{if(resumeAt!==null&&video.currentTime>resumeAt)progress.resumed=true;note('Het filmpje is afgelopen. '+missingHelp());update()};
 video.onerror=()=>note('Het filmpje kon niet laden. Heropen de opdracht of vraag hulp. Je krijgt geen oefenbewijs voor een filmpje dat niet afspeelt.');
 area.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(!video.paused||!progress.paused||progress.stopped||progress.answered)return;if(b.dataset.answer!==task.answer){readGuide('Dat klopt nog niet. Kijk nog eens goed. '+task.question);return}progress.answered=true;b.classList.add('selected');update()});
 area.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{
  if(session.answered||busy)return;cancelGuide();const action=b.dataset.action;
  if(action==='play'){if(!video.paused)return;window.speechSynthesis?.cancel();busy=true;try{if(video.ended)video.currentTime=0;const from=video.currentTime;await video.play();if(!area.isConnected){video.pause();return}progress.started=true;progress.stopped=false;if(progress.answered||(task.pausePractice&&progress.paused))resumeAt=from;note('Het filmpje speelt. '+(resumeAt!==null?'Kijk nog even verder en druk daarna op stop.':missingHelp()))}catch{note('Afspelen lukt niet. Probeer opnieuw.')}finally{busy=false}}
  if(action==='pause'){if(!progress.started||video.paused)return note(video.ended?'Het filmpje is afgelopen. Speel het opnieuw af en pauzeer tijdens het kijken.':'Start eerst het filmpje.');video.pause();if(!watchedEnough()){update();return}progress.paused=true;}
  if(action==='volumeUp'||action==='volumeDown'){const before=video.volume;video.volume=Math.max(0,Math.min(.8,before+(action==='volumeUp'?.2:-.2)));if(action===task.adjust&&progress.started&&!video.paused&&video.volume!==before)progress.adjusted=true;note(progress.adjusted?'Je hebt het geluid aangepast. '+missingHelp():!progress.started||video.paused?'Speel het filmpje af om het verschil in geluid te horen.':'Het geluid is aangepast.')}
  if(action==='stop'){if(resumeAt!==null&&video.currentTime>resumeAt+.2)progress.resumed=true;video.pause();video.currentTime=0;progress.stopped=progress.started;resumeAt=null;note('Gestopt. '+missingHelp())}
  syncQuestion();update();
 });
 ready.onclick=()=>{if(session.answered)return;if(!mediaRequirements(task,progress).every(([,done])=>done)){note(missingHelp());area.querySelector('.practice-note').scrollIntoView({block:'nearest',behavior:'smooth'});return}video.pause();session.answered=true;session.correct++;task.goals.forEach(addHit);save();session.index++;renderTask();body.scrollTop=0;dialog.scrollTop=0;};
 const help=area.querySelector("details");help.querySelector("summary").textContent="Hulp en videobron";help.appendChild(area.querySelector(".media-exercise>small"));
 wireRead();update();cleanupPractice=()=>{alive=false;cancelGuide();video.pause();};
}
function fileContent(file){if(file.kind==='Beeld')return `<img class="file-picture" src="${file.src}" alt="Vlinder in een bloemenweide">`;if(file.kind==='Tekst')return `<article class="paper">${file.text}</article>`;if(file.kind==='Video')return `<video class="real-video" controls playsinline src="${file.src}"></video>`;if(file.kind==='Geluid')return `<audio controls src="${file.src}"></audio>`;return '<label>Kies de kleur van je scherm <input type="color" value="#e4f3fb"></label><div class="color-output">Jouw kleur verschijnt hier.</div>'}
function renderFileOpen(task){
 const a=$('#taskArea');let inspected=false;
 a.innerHTML=`<div class="work-panel"><button class="file-tile" data-open>Open ${task.file.name}</button><div class="file-window" hidden></div><div class="file-kinds" hidden><p>Wat heb je geopend?</p>${['Tekst','Beeld','Geluid','Video','Programma'].map(k=>`<button class="tool-choice" data-kind="${k}">${k}</button>${sayButton(k)}`).join('')}</div><p class="practice-note" role="status">Open het bestand om de inhoud te onderzoeken.</p></div>`;
 a.querySelector('[data-open]').onclick=()=>{
  const w=a.querySelector('.file-window');w.hidden=false;w.innerHTML=fileContent(task.file);a.querySelector('.file-kinds').hidden=false;
  inspected=['Tekst','Beeld'].includes(task.file.kind);
  if(task.file.kind==='Programma'){w.querySelector('input').oninput=e=>{w.querySelector('.color-output').style.background=e.target.value;inspected=true};note('Probeer de kleurknop. Wat doet dit bestand?')}
  else if(['Video','Geluid'].includes(task.file.kind)){const media=w.querySelector('video,audio');media.ontimeupdate=()=>{if(media.currentTime>=1)inspected=true};media.onerror=()=>note('Dit bestand kon niet laden. Vraag hulp; er wordt geen oefenbewijs toegekend.');note('Druk op afspelen en onderzoek de inhoud.')}
  else note('Bekijk of lees de inhoud. Kies daarna het bestandstype.');
 };
 a.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{if(!inspected)return note('Open het bestand en speel het af, of probeer het programma eerst.');if(b.dataset.kind===task.file.kind)completePractice(task,'Je opende het bestand en herkende het type aan de inhoud.');else note('Onderzoek opnieuw: lees je tekst, zie je een stil beeld, hoor je geluid, zie je video of gebruik je een programma?')});wireRead();
}
function workKey(){return 'zisa-work-'+state.age}
function readWork(){return readJson(workKey(),{})}
function saveWork(name,value){const work=readWork();work[name]=value;localStorage.setItem(workKey(),JSON.stringify(work))}
function renderFileEdit(task){const a=$('#taskArea');let stage=0;a.innerHTML=`<div class="work-panel"><p>Maak dit bericht: <strong>${task.text}</strong>${sayButton(task.text)}</p><div class="editor"><label>Bestandsnaam<input class="typing-box" data-name autocomplete="off"></label><label>Jouw bericht<textarea class="typing-box" data-text></textarea></label><div class="tool-row"><button data-save>Opslaan</button><button data-close>Sluiten</button></div></div><div class="saved-file" hidden><button data-reopen>Open ${task.name}</button></div><p class="practice-note" role="status">Typ het bericht en geef het de naam ${task.name}.</p></div>`;wireRead();a.querySelector('[data-save]').onclick=()=>{const name=a.querySelector('[data-name]').value.trim(),text=a.querySelector('[data-text]').value.trim();if(name!==task.name||text!==task.text)return note('Controleer de herkenbare bestandsnaam en typ de voorbeeldzin precies na.');try{saveWork(name,{kind:'text',text});stage=1;note('Bewaard op dit toestel. Sluit nu het bericht.')}catch{note('Bewaren lukt niet op dit toestel. Vraag je leerkracht om hulp.')}};a.querySelector('[data-close]').onclick=()=>{if(stage!==1)return note('Bewaar je bericht eerst.');if(a.querySelector('[data-text]').value.trim()!==readWork()[task.name].text)return note('Je veranderde de tekst. Bewaar eerst opnieuw.');a.querySelector('.editor').hidden=true;a.querySelector('.saved-file').hidden=false;stage=2;note('Gesloten. Open je bestand opnieuw.')};a.querySelector('[data-reopen]').onclick=()=>{if(stage!==2)return;const saved=readWork()[task.name];a.querySelector('.saved-file').innerHTML=`<h3>${escapeHtml(task.name)}</h3><article class="paper">${escapeHtml(saved.text)}</article>`;note('Je bewaarde bericht is opnieuw geopend.');completePractice(task,'Je gaf je bestand een naam, bewaarde het, sloot het en haalde de bewaarde inhoud weer op.')}}
function renderFileDelete(task){const a=$('#taskArea');let selected='';a.innerHTML='<div class="work-panel"><p>Oefenmap — alleen deze twee oefenbestanden</p><button class="file-tile" data-file="uitnodiging">uitnodiging</button><button class="file-tile" data-file="proefklad">proefklad</button><div class="paper" hidden></div><button data-delete>Verwijderen</button><p class="practice-note" role="status">Open eerst het bestand dat weg mag.</p></div>';a.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{selected=b.dataset.file;a.querySelector('.paper').hidden=false;a.querySelector('.paper').textContent=selected==='proefklad'?'Dit is een leeg proefbericht. Het mag weg.':'Kom je tekenen? Deze uitnodiging bewaren we.'});a.querySelector('[data-delete]').onclick=()=>{if(selected!=='proefklad')return note('Alleen proefklad mag weg. De uitnodiging hebben we nog nodig.');a.querySelector('[data-file="proefklad"]').remove();a.querySelector('.paper').hidden=true;completePractice(task,'Je controleerde de inhoud en verwijderde alleen het juiste oefenbestand.')}}
function renderCreate(task){
 const a=$('#taskArea'),flowers=task.topic==='flowers';
 const pictures=flowers?[['assets/bloem-foto.png','Een rode bloem'],['assets/video-vlinderweide.png','Bloemen in de wei']]:[['assets/video-zeeschildpad.png','Een zeeschildpad'],['assets/video-eekhoornbos.png','Een eekhoorn']];
 let selected=null;
 a.innerHTML=`<div class="work-panel card-editor"><div class="editor-toolbar" role="toolbar" aria-label="Kaart bewerken"><strong>Mijn kaart</strong><button data-insert aria-expanded="false">Afbeelding invoegen</button><button data-save>Opslaan als afbeelding</button></div><div class="editor-pictures" hidden><p>Voeg een afbeelding in.</p><button data-upload>Afbeelding van dit toestel…</button><input data-image-file type="file" accept="image/png,image/jpeg,image/webp" hidden><p>Of kies een schoolafbeelding:</p><div class="picture-picks">${pictures.map(([src,label],i)=>`<button data-picture="${i}"><img src="${src}" alt="${label}"><span>${label}</span></button>`).join('')}</div><button data-cancel>Sluiten</button></div><div class="card-paper"><div class="card-image-placeholder">Voeg hier een afbeelding in met de knop hierboven.</div><img class="card-image" hidden alt=""><label>Schrijf bij je afbeelding<textarea rows="2" maxlength="180" placeholder="${flowers?'Wat zie je aan de bloem?':'Wat doet het dier?'}"></textarea></label></div><p class="practice-note" role="status">Maak een kaart met een afbeelding en je eigen zin.</p></div>`;
 const picker=a.querySelector('.editor-pictures'),insert=a.querySelector('[data-insert]'),input=a.querySelector('textarea');
 insert.onclick=()=>{picker.hidden=!picker.hidden;insert.setAttribute('aria-expanded',String(!picker.hidden))};
 a.querySelector('[data-cancel]').onclick=()=>{picker.hidden=true;insert.setAttribute('aria-expanded','false')};
 a.querySelectorAll('[data-picture]').forEach(b=>b.onclick=()=>{selected=pictures[Number(b.dataset.picture)];const img=a.querySelector('.card-image');img.src=selected[0];img.alt=selected[1];img.hidden=false;a.querySelector('.card-image-placeholder').hidden=true;picker.hidden=true;insert.setAttribute('aria-expanded','false');insert.textContent='Afbeelding vervangen';note('Schrijf iets over wat je op deze afbeelding ziet.');input.focus()});
 a.querySelector('[data-upload]').onclick=()=>a.querySelector('[data-image-file]').click();
 a.querySelector('[data-image-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>5000000)return note('Kies een afbeelding kleiner dan 5 MB.');try{const bitmap=await createImageBitmap(file);const c=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();selected=[c.toDataURL('image/png'),file.name];const image=a.querySelector('.card-image');image.src=selected[0];image.alt=file.name;image.hidden=false;a.querySelector('.card-image-placeholder').hidden=true;picker.hidden=true;insert.setAttribute('aria-expanded','false');insert.textContent='Afbeelding vervangen';note('Je afbeelding staat op je kaart. Schrijf er een zin bij.')}catch{note('Deze afbeelding kon niet worden geopend. Kies een PNG, JPG of WebP.')}};
 a.querySelector('[data-save]').textContent='Kaart bewaren';
 a.querySelector('[data-save]').onclick=()=>{if(session.answered)return;const text=input.value.trim();if(!selected)return note('Voeg eerst een afbeelding in.');if(!/[a-zA-ZÀ-ÿ]{2}/.test(text)||text.split(/\s+/).length<2)return note('Schrijf een korte zin bij de afbeelding. Je leerkracht kan helpen.');try{saveWork(task.name,{kind:'card',text,src:selected[0]});input.readOnly=true;insert.disabled=true;a.querySelector('[data-save]').disabled=true;note('Je kaart is bewaard. Je kunt ze nu downloaden, delen of afdrukken.');completePractice(task,'Je maakte een kaart met tekst en beeld. Toon ze aan je maatje: past jouw zin bij de afbeelding? Je leerkracht kijkt mee.')}catch{note('Bewaren lukt niet. Vraag je leerkracht om hulp.')}}
}
function renderRecorder(task){const a=$('#taskArea');let stream,recorder,chunks=[],url,start=0,heard=false,recorded=false;a.innerHTML=`<div class="work-panel"><p>Zeg: <strong>${task.sentence}</strong>${sayButton(task.sentence)}</p><p>Je stem blijft in deze opdracht op dit toestel. Er wordt niets verstuurd.</p><button data-record>Opname-app openen en opnemen</button><button data-stop disabled>${mediaIcon('stop')} Stop opname</button><audio controls hidden></audio><button data-ready disabled>Ik heb mijn stem teruggeluisterd</button><p class="practice-note" role="status">Vraag je leerkracht om hulp als de browser microfoontoegang vraagt.</p><button class="text-button" data-help>Geen microfoon? Doe dit met de leerkracht</button></div>`;wireRead();const audio=a.querySelector('audio');a.querySelector('[data-record]').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return note('Opnemen is hier niet beschikbaar. Gebruik de opdracht met de leerkracht.');try{stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!a.isConnected||!a.querySelector('[data-record]')){stream.getTracks().forEach(t=>t.stop());return}chunks=[];heard=false;recorded=false;a.querySelector('[data-ready]').disabled=true;recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());if(!a.isConnected||!a.querySelector('[data-record]'))return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));audio.src=url;audio.hidden=false;recorded=Date.now()-start>=1500;note(recorded?'Luister je opname terug met de afspeelknop.':'Dat was erg kort. Neem je hele boodschap opnieuw op.');a.querySelector('[data-record]').disabled=false};recorder.start();start=Date.now();a.querySelector('[data-record]').disabled=true;a.querySelector('[data-stop]').disabled=false;note('De microfoon neemt nu op. Spreek je boodschap uit.')}catch{note('De microfoon is niet beschikbaar of niet toegestaan. Je kunt opnieuw proberen of samen met de leerkracht oefenen.')}};a.querySelector('[data-stop]').onclick=()=>{if(recorder?.state==='recording')recorder.stop();a.querySelector('[data-stop]').disabled=true};audio.onended=()=>{if(recorded){heard=true;a.querySelector('[data-ready]').disabled=false}};a.querySelector('[data-ready]').onclick=()=>{if(heard)completePractice(task,'Je nam echt geluid op met de microfoon en beluisterde je opname. Laat je leerkracht ook naar de boodschap luisteren.')};a.querySelector('[data-help]').onclick=()=>{cleanupPractice();renderObservation({...task,requiresObservation:true,criteria:'Kind neemt de gevraagde boodschap op in een beschikbare opname-app en luistert terug. Niet automatisch als digitaal voltooid tellen.'})};cleanupPractice=()=>{if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());if(url)URL.revokeObjectURL(url);audio.pause()}}
function renderLauncher(task){const a=$('#taskArea');let used=false;a.innerHTML='<div class="work-panel"><p>Jouw oefentablet</p><div class="tool-row"><button data-app="tekenen">Tekenapp</button><button data-app="schrijven">Schrijfapp</button></div><div class="mini-app" hidden><button data-close aria-label="App sluiten">×</button><div class="mini-content"></div></div><p class="practice-note" role="status">Open de app die in de opdracht staat.</p></div>';a.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>{if(b.dataset.app!==task.app)return note('Kijk nog eens welke app je nodig hebt.');a.querySelector('.mini-app').hidden=false;const c=a.querySelector('.mini-content');if(task.app==='schrijven'){c.innerHTML='<label>Typ Dag Zisa!<input class="typing-box"></label>';c.querySelector('input').oninput=e=>used=e.target.value==='Dag Zisa!'}else{c.innerHTML='<label>Kleur <input type="color" value="#147da0"></label><canvas width="600" height="220"></canvas>';const canvas=c.querySelector('canvas'),ctx=canvas.getContext('2d'),colors=new Set();let drawing=false,lines=0;const pt=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*600/r.width,(e.clientY-r.top)*220/r.height]};canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...pt(e))};canvas.onpointermove=e=>{if(!drawing)return;ctx.strokeStyle=c.querySelector('input').value;ctx.lineWidth=7;ctx.lineCap='round';ctx.lineTo(...pt(e));ctx.stroke();colors.add(ctx.strokeStyle);used=++lines>6&&colors.size>=2};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false}note('Gebruik de app en sluit ze daarna met het kruisje.')});a.querySelector('[data-close]').onclick=()=>{if(!used)return note(task.app==='tekenen'?'Teken eerst met twee kleuren.':'Typ eerst Dag Zisa!');a.querySelector('.mini-app').hidden=true;completePractice(task,'Je opende de juiste app, gebruikte die en sloot de app weer.')}}
function renderTransform(task){const a=$('#taskArea');a.innerHTML=`<div class="work-panel"><label>Invoer: typ ${task.word}<input class="typing-box"></label><button data-process>Maak grote letters</button><div class="paper" hidden></div><p class="practice-note" role="status">Jij geeft letters aan de computer.</p><div class="explain-steps" hidden><p>Invoer: jouw letters. Verwerking: de computer maakt hoofdletters. Uitvoer: de woordkaart op het scherm.</p><button data-finish>Toon mijn woordkaart</button></div></div>`;a.querySelector('[data-process]').onclick=()=>{const val=a.querySelector('input').value.trim();if(val!==task.word)return note('Typ eerst '+task.word+'.');a.querySelector('.paper').hidden=false;a.querySelector('.paper').textContent=val.toUpperCase();a.querySelector('.explain-steps').hidden=false;note('Je ziet het resultaat van de verwerking.')};a.querySelector('[data-finish]').onclick=()=>completePractice(task,'Je gebruikte invoer, verwerking en uitvoer om een woordkaart te maken.')}
function renderCalculator(task){const a=$('#taskArea');let expression='';a.innerHTML=`<div class="work-panel"><p>Voer ${task.a} + ${task.b} in.</p><output class="calc-display">0</output><div class="calc-keys">${['7','8','9','4','5','6','1','2','3','0','+','C'].map(k=>`<button data-key="${k}">${k}</button>`).join('')}<button data-equals>=</button></div><p class="practice-note" role="status">Gebruik de cijfertoetsen en de plustoets.</p></div>`;a.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{expression=b.dataset.key==='C'?'':(expression+b.dataset.key).slice(0,12);a.querySelector('output').textContent=expression||'0'});a.querySelector('[data-equals]').onclick=()=>{if(expression!==`${task.a}+${task.b}`)return note('Voer eerst precies de gevraagde som in. Met C begin je opnieuw.');a.querySelector('output').textContent=task.a+task.b;completePractice(task,`Jouw invoer was ${expression}. De rekenmachine verwerkte die som. De uitvoer is ${task.a+task.b}.`)}}
function renderObservation(task){const a=$('#taskArea');task.requiresObservation=true;a.innerHTML=`<div class="work-panel"><h3>Samen met je leerkracht</h3><p>${escapeHtml(task.prompt)}</p>${sayButton(task.prompt)}<p>Voer dit echt uit. Je leerkracht kijkt mee.</p><details><summary>Waar kijkt de leerkracht naar?</summary><p>${escapeHtml(task.criteria||'Observeer of het kind de gevraagde handelingen daadwerkelijk uitvoert.')}</p></details><button data-later>Verder — leerkracht kijkt dit nog na</button><p class="practice-note">Dit wordt geen automatisch behaald doel.</p></div>`;wireRead();a.querySelector('[data-later]').onclick=()=>{session.answered=true;session.correct++;const next=document.createElement('button');next.className='primary-button';next.textContent='Volgende opdracht';next.onclick=()=>{session.index++;renderTask()};a.appendChild(next);a.querySelector('[data-later]').disabled=true;note('Genoteerd als praktijkopdracht om nog te observeren.')};}
function renderBreak(task){const a=$('#taskArea');let start=0,chosen='';a.innerHTML='<div class="work-panel"><h3>Even weg van het scherm</h3><div class="tool-row"><button data-break="Ver weg kijken">Ver weg kijken</button><button data-break="Rustig rechtstaan en rekken">Rustig rechtstaan en rekken</button></div><p class="practice-note" role="status">Kies een pauze van 20 seconden.</p><button data-return disabled>Ik ben terug</button><div class="reflection" hidden><p>Hoe voel je je nu?</p><button data-feel>Rustiger</button><button data-feel>Hetzelfde</button><button data-feel>Nog moe of onrustig</button></div></div>';a.querySelectorAll('[data-break]').forEach(b=>b.onclick=()=>{chosen=b.dataset.break;start=Date.now();note(chosen+'. Kijk nu weg van het scherm.');a.querySelector('[data-return]').disabled=true;cleanupPractice();const timer=setTimeout(()=>{if(a.isConnected)a.querySelector('[data-return]').disabled=false},20000);cleanupPractice=()=>clearTimeout(timer)});a.querySelector('[data-return]').onclick=()=>{if(Date.now()-start>=20000)a.querySelector('.reflection').hidden=false};a.querySelectorAll('[data-feel]').forEach(b=>b.onclick=()=>{task.requiresObservation=true;completePractice(task,'Je nam tijd voor een pauze en dacht na over je gevoel. De leerkracht kijkt mee of de pauze ook echt uitgevoerd werd.')})}
function renderSearchLab(task){const a=$('#taskArea');let opened=false;const isSpider=task.topic==='spin';const cards=isSpider?[['Spinnen — dierenkaart','Een spin heeft acht poten. Dat zijn 8 poten.','Zisa’s oefenbibliotheek',true],['Spinnen knutselen','Maak een spin van papier en draad.','Knutselhoek',false],['Spinnenverhaal','Een verzonnen spin reist naar de maan.','Verhalenhoek',false]]:[['Bijen — dierenkaart','Bijen maken honing van nectar uit bloemen.','Zisa’s oefenbibliotheek',true],['Honingkoekjes bakken','Een recept met honing en bloem.','Receptenhoek',false],['Bij in de klas','Een fantasieverhaal over een bij die leert lezen.','Verhalenhoek',false]];
 a.innerHTML=`<div class="work-panel"><h3>Zisa’s oefenzoeker</h3><p>Een kleine oefenbibliotheek. Daarna zoek je op echte websites.</p><form><label>Zoekwoorden<input class="typing-box" type="search" autocomplete="off"></label><button>Zoeken</button></form><div class="search-results"></div><div class="opened-source" hidden></div><div class="found-answer" hidden><label>Jouw gevonden antwoord<input class="typing-box" data-answer></label><button data-check>Gebruik dit antwoord</button></div><p class="practice-note" role="status">Typ de opgegeven zoekwoorden.</p></div>`;a.querySelector('form').onsubmit=e=>{e.preventDefault();if(a.querySelector('[type="search"]').value.trim().toLowerCase().replace(/\s+/g,' ')!==task.term)return note('Gebruik precies deze woorden: '+task.term);a.querySelector('.search-results').innerHTML=cards.map((c,i)=>`<button class="source-result" data-source="${i}"><strong>${c[0]}</strong><span>${c[2]}</span></button>`).join('');a.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{const c=cards[Number(b.dataset.source)],src=a.querySelector('.opened-source');src.hidden=false;src.innerHTML=`<h3>${c[0]}</h3><p>${c[1]}</p>${sayButton(c[1])}<button data-use>Deze bron beantwoordt mijn vraag</button>`;wireRead();src.querySelector('[data-use]').onclick=()=>{if(!c[3])return note('Deze bron gaat over hetzelfde onderwerp, maar beantwoordt jouw vraag niet. Open een ander resultaat.');opened=true;a.querySelector('.found-answer').hidden=false;note('Haal het antwoord uit de bron.')};});note('Open een resultaat en kijk of het bruikbaar is.')};a.querySelector('[data-check]').onclick=()=>{if(!opened)return;const answer=a.querySelector('[data-answer]').value.trim().toLowerCase();if(answer!==task.answer&&!(task.answer==='8'&&answer==='acht'))return note('Lees de bron opnieuw.');completePractice(task,'Je zocht met de opgegeven woorden, opende bronnen en gebruikte de bron die jouw vraag beantwoordt.')};}

// Evidence is age-specific and counts distinct activities, never repeat clicks.
let evidence=readJson('zisa-practice-v2-'+state.age,{tasks:{},observed:[],done:[]});
function loadPracticeProgress(){evidence=readJson('zisa-practice-v2-'+state.age,{tasks:{},observed:[],done:[]});state.done=evidence.done;state.observed=evidence.observed;state.hits={};Object.values(evidence.tasks).forEach(gs=>gs.forEach(g=>state.hits[g]=(state.hits[g]||0)+1))}
loadPracticeProgress();
selectAge=function(age){state.age=age;localStorage.setItem('zisa-age',age);loadPracticeProgress();welcome.hidden=true;dashboard.hidden=false;render()};
save=function(){evidence.done=state.done;evidence.observed=state.observed;localStorage.setItem('zisa-practice-v2-'+state.age,JSON.stringify(evidence))};
addHit=function(goal){const task=session.tasks[session.index];if(!goalForAge(goal)||task.requiresObservation||task.type==='observe')return;const seen=evidence.tasks[task.id]||(evidence.tasks[task.id]=[]);if(!seen.includes(goal)){seen.push(goal);state.hits[goal]=(state.hits[goal]||0)+1}};
requiredGoals=function(m){return [...new Set(tasksFor(m).flatMap(t=>t.goals))].filter(goalForAge)};
openTeacher=function(){const t=$('#teacherDialog');if(t.open)t.close();const goals=[...new Set(missions.filter(available).flatMap(requiredGoals))];$('#teacherSummary').textContent=`Leeftijd ${state.age||'nog niet gekozen'} — oefenbewijs, geen automatische uitspraak dat een doel beheerst is. Herhaal op andere dagen en observeer zelfstandig gebruik. Vorige quizscores blijven bewaard maar tellen niet als nieuw praktijkbewijs.`;$('#teacherGoals').innerHTML=goals.map(g=>{const tasks=missions.filter(available).flatMap(tasksFor).filter(t=>t.goals.includes(g)),done=state.hits[g]||0;return `<div class="goal-row"><strong>${g}</strong><span>${goalDescriptions[g]}<small>${done} verschillende digitale oefenbewijzen · ${tasks.length} oefenkansen</small><details><summary>Opdrachten en observatie</summary>${tasks.map(t=>`<p>${escapeHtml(t.prompt)}${t.criteria?'<br><em>'+escapeHtml(t.criteria)+'</em>':''}<button data-practice="${t.id}">Deze opdracht oefenen</button></p>`).join('')}</details></span><button data-goal="${g}">${state.observed.includes(g)?'Praktijk geobserveerd':'Observatie noteren'}</button></div>`}).join('');$('#teacherGoals').querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{const g=b.dataset.goal;if(state.observed.includes(g))state.observed=state.observed.filter(x=>x!==g);else state.observed.push(g);save();openTeacher()});$('#teacherGoals').querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>{const mission=missions.find(m=>m.tasks.some(task=>task.id===b.dataset.practice));const tasks=tasksFor(mission),index=tasks.findIndex(task=>task.id===b.dataset.practice);t.close();session={mission,tasks,index,correct:0,answered:false};$('#missionNumber').textContent=requiredGoals(mission).join(' · ');$('#missionTitle').textContent=mission.title;renderTask();dialog.showModal()});t.showModal()};
const teacherButton=$('#teacherBtn'),newTeacherButton=teacherButton.cloneNode(true);teacherButton.replaceWith(newTeacherButton);newTeacherButton.onclick=openTeacher;
const resetButton=$('#resetProgress'),newResetButton=resetButton.cloneNode(true);resetButton.replaceWith(newResetButton);newResetButton.onclick=()=>{if(!confirm('Wis de nieuwe oefenvoortgang voor deze leeftijd? Bewaarde werkstukken blijven behouden.'))return;evidence={tasks:{},observed:[],done:[]};state.done=[];state.observed=[];state.hits={};save();render();openTeacher()};
const oldTyping=renderTyping;
renderTyping=function(task){oldTyping(task);const old=$('#taskArea [data-check]'),button=old.cloneNode(true);old.replaceWith(button);button.onclick=()=>{if(session.answered)return;const input=$('#taskArea input'),ok=input.value.trim()===task.answer;if(!ok){input.classList.add('input-wrong');toast('Kijk naar hoofdletters, spaties en het leesteken. Probeer opnieuw.');return}input.classList.remove('input-wrong');input.classList.add('input-correct');completePractice(task,task.explain)};};
const oldSearch=renderExternalSearch;
renderExternalSearch=function(task){oldSearch(task);const link=$('#taskArea a'),input=$('#taskArea input'),old=$('#taskArea [data-check]'),check=old.cloneNode(true);old.replaceWith(check);let visited=false;link.addEventListener('click',()=>visited=true);check.onclick=()=>{if(!visited)return toast('Open eerst de website en zoek met de opgegeven woorden.');if(!task.answer.includes(input.value.trim().toLowerCase()))return toast('Zoek nog eens en bekijk je resultaat.');completePractice(task,'Je antwoord klopt. Toon je leerkracht ook hoe je de zoekwoorden invoerde en welke bron je opende. De zoekhandeling buiten deze site wordt niet automatisch beoordeeld.')}};
const originalFinish=finishMission;
finishMission=function(){originalFinish();body.querySelector('.mission-finish h3').textContent='Missie doorlopen!';body.querySelector('.score-orb span').textContent='afgerond';const p=body.querySelector('.mission-finish p');p.textContent='Je werkte de missie door. Oefen later opnieuw in een andere situatie. De leerkracht bekijkt welke handelingen je zelfstandig kunt uitvoeren.'};
renderDrawing=function(task){
 const a=$('#taskArea');let color='#147da0',drawing=false,segments=0;const used=new Set();
 a.innerHTML=`<div class="work-panel"><p>Teken met minstens twee kleuren.</p><div class="tool-row">${['#147da0','#e7b23a','#278653','#d64745','#8055ac'].map((c,i)=>`<button data-color="${c}" style="background:${c};color:white" aria-label="${['Blauw','Geel','Groen','Rood','Paars'][i]}">${['Blauw','Geel','Groen','Rood','Paars'][i]}</button>`).join('')}</div><canvas class="real-drawing" width="680" height="340" aria-label="Tekenblad"></canvas><div class="tool-row"><button data-clear>Tekening opnieuw</button><button data-save disabled>Tekening bewaren</button></div><p class="practice-note" role="status">Teken je idee op het witte blad.</p></div>`;
 const canvas=a.querySelector('canvas'),ctx=canvas.getContext('2d');ctx.lineWidth=8;ctx.lineCap='round';ctx.lineJoin='round';
 const point=e=>{const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*680/r.width,(e.clientY-r.top)*340/r.height]};
 a.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{color=b.dataset.color;a.querySelectorAll('[data-color]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
 canvas.onpointerdown=e=>{if(session.answered)return;drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e))};
 canvas.onpointermove=e=>{if(!drawing)return;ctx.strokeStyle=color;ctx.lineTo(...point(e));ctx.stroke();used.add(color);segments++;a.querySelector('[data-save]').disabled=segments<8||used.size<2};
 canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;
 a.querySelector('[data-clear]').onclick=()=>{ctx.clearRect(0,0,680,340);segments=0;used.clear();a.querySelector('[data-save]').disabled=true};
 a.querySelector('[data-save]').onclick=()=>{if(segments<8||used.size<2)return;try{saveWork(task.id,{kind:'drawing',image:canvas.toDataURL('image/png')});completePractice(task,'Je tekening is bewaard. Laat je leerkracht bekijken of je de opdracht uitvoerde en vertel welke tools je gebruikte.')}catch{note('Je tekening kon niet bewaard worden. Vraag je leerkracht om hulp.')}};
};
$('#viewWork').onclick=()=>{cleanupPractice();$('#missionTitle').textContent='Mijn bewaarde werk';$('#missionNumber').textContent=state.age+' jaar';const work=readWork();body.innerHTML='<p>Dit werk is bewaard in deze browser op dit toestel.</p><div class="saved-gallery"></div>';const gallery=body.querySelector('.saved-gallery');if(!Object.keys(work).length)gallery.innerHTML='<p>Hier verschijnen je bewaarde kaarten, berichten en tekeningen.</p>';Object.entries(work).forEach(([name,item])=>{const article=document.createElement('article');article.className='paper';const h=document.createElement('h3');h.textContent=name;article.appendChild(h);if(item.text){const p=document.createElement('p');p.textContent=item.text;article.appendChild(p)}const source=item.image||item.src;if(source){const img=document.createElement('img');img.src=source;img.alt='Bewaard werk '+name;img.className='file-picture';article.appendChild(img)}gallery.appendChild(article)});dialog.showModal()};
if(state.age)render();
