/* Real external searches. No simulated results and no automatic assessment. */
const childSearchTools=[
 {name:'Schooltv',url:'https://schooltv.nl/onderwijsvorm/primair-onderwijs',icon:'▶',description:'Ik wil een uitlegfilmpje bekijken en beluisteren.',help:'Zoek samen een filmpje voor jonge kinderen. De Nederlandse groepen 3 en 4 komen ongeveer overeen met 6–8 jaar. Laat de leerkracht helpen met de leeftijdskeuze.'},
 {name:'Jeugdbieb',url:'https://www.jeugdbieb.nl/',icon:'⌕',description:'Ik wil informatie en filmpjes uit verschillende kinderbronnen zoeken.',help:'Jeugdbieb verwijst naar andere websites. Kies met je leerkracht een bron die je kunt begrijpen. Laat tekst zo nodig voorlezen.'}
];
searchMission.tasks=[
 {age:'6-7',topic:'honing',question:'Hoe maken bijen honing?',term:'honing'},
 {age:'6-7',topic:'spin',question:'Hoeveel poten heeft een spin?',term:'spin'},
 {age:'7-8',topic:'egel',question:'Wat eet een egel?',term:'egel'},
 {age:'7-8',topic:'kikker',question:'Hoe verandert een kikkervisje in een kikker?',term:'kikker'}
].map(t=>({...t,type:'external-search',id:'echt-zoeken-v1-'+t.age+'-'+t.topic,prompt:t.question+' Kies een zoekomgeving voor kinderen. Zoek daar zelf met '+t.term+'.',goals:['IT.045','IT.046','IT.055','IT.058'],requiresObservation:true,criteria:'Observeer de echte zoekhandeling: kind kiest een passende zoekomgeving, voert de aangereikte zoekwoorden in, opent twee resultaten, bekijkt of beluistert de inhoud en wijst aan welke bron de vraag beantwoordt. Help met lezen en leeftijdsfilters; een klik of juist feit is geen bewijs.'}));
searchMission.text='Zoek op echte kinderwebsites en kies een bruikbare bron.';
searchMission.goals=['IT.045','IT.046','IT.055','IT.058'];
renderExternalSearch=function(task){
 const a=$('#taskArea');
 a.innerHTML=`<section class="work-panel real-search"><span class="eyebrow">ECHT ZOEKEN OP INTERNET</span><h3>${escapeHtml(task.question)}</h3><div class="search-word"><span>Deze zoekwoorden krijg je:</span><strong>${escapeHtml(task.term)}</strong>${sayButton(task.term)}</div><h4>Waar wil jij zoeken?</h4><p>Vertel je maatje waarom je deze zoekomgeving kiest. Er kan meer dan één goede keuze zijn.</p><div class="child-search-tools">${childSearchTools.map((tool,i)=>`<article><h4>${tool.icon} ${tool.name}</h4><p>${tool.description}</p>${sayButton(tool.description)}<a class="primary-button" data-real-search="${i}" href="${tool.url}" target="_blank" rel="noopener noreferrer">Open ${tool.name}</a><small>${tool.help}</small></article>`).join('')}</div><details open><summary>Dit doe je op de echte website</summary><ol><li>Zoek het zoekvak. Typ <strong>${escapeHtml(task.term)}</strong> en start het zoeken.</li><li>Open een resultaat. Kijk, luister of laat de tekst voorlezen.</li><li>Ga terug naar de resultaten en open ook een ander resultaat.</li><li>Kies wat jouw vraag beantwoordt. Toon het stukje dat helpt.</li></ol>${sayButton('Typ '+task.term+' in het zoekvak. Open en bekijk twee resultaten. Kies welke bron jouw vraag beantwoordt. Toon het stukje dat helpt.')}</details><p>Kom daarna terug naar het tabblad van Zisa. Je opdracht blijft hier staan.</p><details><summary>Voor de leerkracht</summary><p>${escapeHtml(task.criteria)}</p><p>6–7: zoek samen, lees titels voor en laat het kind zelf typen en openen. 7–8: laat het kind ook uitleggen waarom de andere bron minder helpt. Controleer vooraf de resultaten en leeftijdsaanduidingen. Deze sites bedienen meerdere leeftijden; niet elk resultaat is geschikt voor 6–8 jaar.</p><p>Geen resultaten of een te moeilijke tekst? Geef een ander zoekwoord of help een leesbaar resultaat vinden. Beoordeel de zoekhandeling, niet de leesvaardigheid.</p></details><button data-search-return>Ik ben terug: ik toon mijn gekozen bron</button><div class="search-reflect" hidden><h4>Vertel en toon aan je leerkracht</h4><p>Ik koos deze zoekomgeving omdat…<br>Deze bron helpt, want hier zie of hoor ik…<br>De andere bron helpt minder, omdat…</p><p>Je mag dit vertellen terwijl je de echte bron op je iPad laat zien. Je leerkracht kruist de beoordeling aan op papier.</p><button data-search-finish>Verder na het bespreken</button></div><p class="practice-note" role="status">Je leerkracht kijkt mee. De website beoordeelt je zoekwerk niet automatisch.</p></section>`;
 wireRead();
 a.querySelector('[data-search-return]').onclick=()=>{a.querySelector('.search-reflect').hidden=false;speak('Toon jouw gekozen bron aan je leerkracht. Vertel waarom die helpt.')};
 a.querySelector('[data-search-finish]').onclick=()=>{if(session.answered)return;session.answered=true;session.correct++;session.index++;renderTask();body.scrollTop=0;dialog.scrollTop=0};
};
// Every entry, including a teacher task link or QR round, uses the external route.
if(state.age)render();
