'use client';
import {useState} from 'react';
import {Search,BookOpen,Play,Music,Users,House,ArrowRight,ExternalLink,Check,ChevronLeft,ChevronRight,PawPrint,Leaf,MessageCircle,Map,Type} from 'lucide-react';
import Listen from '@/components/listen';
import {Checkbox} from '@/components/ui/checkbox';
const symbols={book:BookOpen,film:Play,music:Music,adult:Users,animal:PawPrint,leaf:Leaf,word:Type,map:Map,chat:MessageCircle,search:Search};
type Symbol=keyof typeof symbols;
type Choice={label:string;icon:Symbol;why:string};
type Task={title:string;story:string;icon:Symbol;choices:Choice[];good:number[];tryIt?:{label:string;url:string;instruction:string}};
const tasks:Task[]=[
 {title:'Wat eet een egel?',story:'Je wilt weten wat een egel eet. Waar kun je dit opzoeken?',icon:'animal',good:[0,2],choices:[{label:'In een dierenboek.',icon:'book',why:'Een informatief dierenboek kan vertellen wat een egel eet. Zoek met hulp bij de egel.'},{label:'In een liedjeslijst.',icon:'music',why:'Een liedjeslijst is bedoeld om muziek te vinden. Voor dierenweetjes kies je een informatiebron.'},{label:'In een dierenfilmpje van Schooltv.',icon:'film',why:'Een uitlegfilmpje over egels kan ook helpen. Er kan meer dan één geschikt zoekmiddel zijn.'}],tryIt:{label:'Naar Schooltv',url:'https://schooltv.nl/',instruction:'Zoek samen op Schooltv naar: egel. Kies een filmpje dat past bij jouw vraag.'}},
 {title:'Een moeilijk woord',story:'In je boek staat “winterslaap”. Je begrijpt dat woord niet. Wat helpt?',icon:'word',good:[1],choices:[{label:'Een kaart met landen.',icon:'map',why:'Een kaart helpt je plaatsen vinden. Ze legt dit woord niet uit.'},{label:'Een kinderwoordenboek.',icon:'book',why:'In een kinderwoordenboek zoek je wat een woord betekent. Je kunt ook hulp vragen bij het lezen.'},{label:'Een dansfilmpje.',icon:'music',why:'Een dansfilmpje toont bewegingen. Kies voor een woordbetekenis een woordenboek.'}]},
 {title:'Een dansje leren',story:'Je wilt zien hoe je de bewegingen van een dansje doet. Wat kies je?',icon:'music',good:[2],choices:[{label:'Een woordenboek.',icon:'book',why:'Een woordenboek legt woorden uit, maar laat het dansje niet bewegen.'},{label:'Een foto van een podium.',icon:'map',why:'Op één foto zie je de bewegingen na elkaar niet.'},{label:'Een dansfilmpje voor kinderen.',icon:'film',why:'In een filmpje kun je bewegingen bekijken, pauzeren en nadoen.'}],tryIt:{label:'Naar Zappelin',url:'https://www.zappelin.nl/programmas/zin-in-zappelin',instruction:'Zoek samen een dansje bij Zin in Zappelin. Kijk eerst. Doe dan mee.'}},
 {title:'Leren over paddenstoelen',story:'Je wilt leren over giftige paddenstoelen. Welke bron past het best?',icon:'leaf',good:[0],choices:[{label:'Een natuurboek met uitleg van een volwassene.',icon:'book',why:'Een natuurboek is een passende informatiebron om samen over paddenstoelen te leren. Eet nooit een gevonden paddenstoel op basis van een boek, foto of zoekresultaat. Een deskundige moet beoordelen wat het is.'},{label:'Een onbekende in een spel.',icon:'chat',why:'Je weet niet of die persoon er echt iets van weet. Kies een betrouwbare informatiebron en vraag hulp.'},{label:'Een filmpje met een grappig dansje.',icon:'music',why:'Een dansfilmpje geeft geen betrouwbare uitleg over paddenstoelen.'}],tryIt:{label:'Het bos op Schooltv',url:'https://schooltv.nl/thema/het-bos',instruction:'Bekijk met je leerkracht informatie over het bos. Paddenstoelen laat je staan en eet je niet.'}},
 {title:'Kies goede zoekwoorden',story:'Je wilt weten wat een egel eet. Welke zoekwoorden passen het best?',icon:'search',good:[1],choices:[{label:'leuk filmpje',icon:'film',why:'Dat is erg breed. Noem het dier én wat je wilt weten.'},{label:'egel eten',icon:'animal',why:'Deze twee woorden noemen het dier en jouw vraag. Zo maak je de zoekopdracht gericht.'},{label:'dansje oefenen',icon:'music',why:'Die woorden zoeken naar dansen, niet naar het eten van een egel.'}],tryIt:{label:'Probeer op Schooltv',url:'https://schooltv.nl/',instruction:'Typ in het zoekvak: egel eten. Lees of beluister samen welke resultaten echt bij je vraag passen.'}},
 {title:'Nog meer dierenweetjes',story:'Je wilt samen met de juf informatie over een dier lezen. Welke website past?',icon:'animal',good:[2],choices:[{label:'Een pagina om schoenen te kopen.',icon:'map',why:'Een winkelpagina helpt je schoenen kiezen. Ze is niet bedoeld voor dierenweetjes.'},{label:'Een muziekspeler.',icon:'music',why:'Een muziekspeler is vooral bedoeld om muziek te beluisteren.'},{label:'WikiKids, samen met de juf.',icon:'book',why:'WikiKids is een encyclopedie voor kinderen. Veel teksten zijn nog moeilijk op zeven jaar: lees ze samen en vraag uitleg.'}],tryIt:{label:'Naar WikiKids',url:'https://wikikids.nl/',instruction:'Zoek samen een dier op. Zoek één weetje. Vertel het daarna in je eigen woorden.'}},
 {title:'Mag ik deze eten?',story:'Je vindt een paddenstoel buiten. Een foto op internet lijkt erop. Mag je hem daarom eten?',icon:'leaf',good:[1],choices:[{label:'Ja, want de foto lijkt erop.',icon:'film',why:'Een foto kan misleiden. Paddenstoelen die op elkaar lijken, kunnen heel verschillend zijn.'},{label:'Nee. Ik laat hem staan en vraag hulp.',icon:'adult',why:'Eet geen gevonden paddenstoel. Een volwassene kan een deskundige raadplegen. Een zoekresultaat is geen bewijs dat iets veilig is.'},{label:'Ja, als een vriend het zegt.',icon:'chat',why:'Een vriend kan zich ook vergissen. Je proeft geen paddenstoelen die je vindt.'}]},
 {title:'Weet ik het nu zeker?',story:'Je vindt twee verschillende antwoorden op je vraag. Wat doe je?',icon:'search',good:[0],choices:[{label:'Ik vergelijk ze met hulp van de juf.',icon:'adult',why:'Goed zoeken is ook controleren. Kijk samen wie de informatie maakte en vergelijk met een andere betrouwbare bron.'},{label:'Ik kies de mooiste foto.',icon:'film',why:'Een mooie foto zegt niet of de uitleg klopt.'},{label:'Ik geloof altijd het eerste resultaat.',icon:'search',why:'Bovenaan staan betekent niet vanzelf dat het antwoord juist of geschikt is.'}]},
];
export default function SearchMission(){
 const [index,setIndex]=useState(0),[selected,setSelected]=useState<number[]>([]),[checked,setChecked]=useState(false);
 const task=tasks[index];const Icon=symbols[task.icon];const multiple=task.good.length>1;
 const good=checked&&selected.length===task.good.length&&task.good.every(i=>selected.includes(i));
 const wrong=selected.filter(i=>!task.good.includes(i));
 const feedback=good?task.good.map(i=>task.choices[i].why).join(' '):wrong.length?wrong.map(i=>task.choices[i].why).join(' '):'Je hebt al een juist antwoord. Er past nog een antwoord bij. Kijk nog eens en vink ook dat aan.';
 const instruction=multiple?'Duid alles aan wat past. Er zijn meerdere juiste antwoorden. Druk daarna op Controleer.':'Kies één antwoord. Druk daarna op Controleer.';
 function silence(){if('speechSynthesis'in window){window.dispatchEvent(new Event('zisa-speech'));window.speechSynthesis.cancel();}}
 function choose(i:number){silence();setChecked(false);setSelected(previous=>multiple?(previous.includes(i)?previous.filter(n=>n!==i):[...previous,i]):[i]);}
 function move(n:number){silence();setIndex(n);setSelected([]);setChecked(false);}
 return <div className="safe-app search-app"><header className="safe-header"><a className="safe-brand" href="/"><Search size={33}/><div><strong>Slim zoeken</strong><small>Zisa’s digitale missies</small></div></a><a className="safe-home" href="/"><House size={23}/> Missies</a></header><main className="safe-main"><div className="safe-nav"><button aria-label="Vorige zoekopdracht" disabled={index===0} onClick={()=>move(index-1)}><ChevronLeft/></button><span>Opdracht {index+1} van {tasks.length}</span><button aria-label="Volgende zoekopdracht" disabled={index===tasks.length-1} onClick={()=>move(index+1)}><ChevronRight/></button></div>
 <section className="safe-story"><div className="safe-scene" aria-hidden="true"><Icon size={76}/></div><div><h1>{task.title}</h1><p>{task.story}</p></div><Listen text={task.title+'. '+task.story+' '+instruction} label="Luister naar de opdracht"/></section><div className="safe-choice-heading"><h2>{multiple?'Duid alles aan wat past':'Kies één antwoord'}</h2><Listen text={instruction} label="Luister hoe je antwoorden kiest"/></div>
 <div className="safe-choices">{task.choices.map((choice,i)=>{const ChoiceIcon=symbols[choice.icon];const chosen=selected.includes(i);return <div className={'safe-choice '+(chosen?(checked?(task.good.includes(i)?'chosen-right':'chosen-try'):'chosen-pending'):'')} key={index+'-'+i}>
 {multiple?<div className="search-multi-answer"><label htmlFor={'search-choice-'+i}><ChoiceIcon size={46}/><span>{choice.label}</span></label><Checkbox id={'search-choice-'+i} checked={chosen} onCheckedChange={()=>choose(i)} className="search-checkbox"/></div>:<button className="safe-answer" aria-pressed={chosen} onClick={()=>choose(i)}><ChoiceIcon size={46}/><span>{choice.label}</span>{chosen&&<Check size={22}/>}</button>}
 <div className="safe-answer-audio"><Listen text={choice.label} label={`Luister naar antwoord ${i+1}: ${choice.label}`}/></div></div>;})}</div>
 <div className="search-check-row"><button className="safe-next" onClick={()=>{silence();setChecked(true);}} disabled={!selected.length}><Check size={23}/> Controleer</button><Listen text="Controleer mijn antwoorden" label="Luister: Controleer"/></div>
 {checked&&<section className={'safe-feedback '+(good?'safe-positive':'')} aria-live="polite"><div><h2>{good?'Helemaal juist!':wrong.length?'Kijk nog eens.':'Nog niet helemaal klaar.'}</h2><p>{feedback}</p></div><Listen text={feedback} label="Luister naar de uitleg"/></section>}

 {good&&task.tryIt&&<div className="search-try"><p>{task.tryIt.instruction}</p><Listen text={task.tryIt.instruction} label="Luister naar de zoekopdracht"/><a href={task.tryIt.url} target="_blank" rel="noopener noreferrer">{task.tryIt.label}<ExternalLink size={19}/></a></div>}
 {good&&index<tasks.length-1&&<button className="safe-next" onClick={()=>move(index+1)}>Volgende opdracht <ArrowRight size={23}/></button>}{good&&index===tasks.length-1&&<p className="search-done">Goed geoefend! Ga naar Zelf opzoeken om verder te zoeken.</p>}

 <a className="search-open-library" href="/opzoeken"><BookOpen size={24}/> Zelf opzoeken <ArrowRight size={21}/></a>
 </main></div>;
}
