import {getTeacherUser} from '@/lib/teacher-auth';
export {database,bucket} from '@/lib/local-storage';
export class AppError extends Error {constructor(public status:number,message:string){super(message);}}
export async function teacher(){const user=await getTeacherUser();if(!user)throw new AppError(401,'Meld je aan als leerkracht.');return user;}
export function clean(value:unknown,max:number){return typeof value==='string'?value.trim().replace(/[\u0000-\u001f]/g,' ').slice(0,max):'';}
export function json(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new AppError(403,'Open het tekenatelier opnieuw en probeer nog eens.');}
export function newCode(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const b=crypto.getRandomValues(new Uint8Array(8));return [...b].map(x=>alphabet[x%alphabet.length]).join('');}
export async function readLimited(req:Request,max:number){const len=Number(req.headers.get('content-length'));if(len>max)throw new AppError(413,'Deze tekening is te groot. Bewaar ze als afbeelding.');const reader=req.body?.getReader();if(!reader)throw new AppError(400,'De tekening ontbreekt.');const parts:Uint8Array[]=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>max){await reader.cancel();throw new AppError(413,'Deze tekening is te groot. Bewaar ze als afbeelding.');}parts.push(value);}}finally{reader.releaseLock();}const all=new Uint8Array(total);let offset=0;for(const p of parts){all.set(p,offset);offset+=p.length;}return all;}
export function validatePng(bytes:Uint8Array){const signature=[137,80,78,71,13,10,26,10];if(bytes.length<33||!signature.every((v,i)=>bytes[i]===v)||String.fromCharCode(...bytes.slice(12,16))!=='IHDR')throw new AppError(400,'Stuur een tekening uit het tekenatelier.');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(view.getUint32(16)!==1200||view.getUint32(20)!==800)throw new AppError(400,'Het formaat van de tekening klopt niet.');}
