const {chromium}=require(require.resolve('playwright',{paths:['C:/Users/isabe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules']}));const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
if(process.argv.includes('--demo')){
 await page.goto('http://127.0.0.1:8765/spelen/games/spellingeiland/index.html?spel=workshop&proef=bouw');
 await page.locator('[data-vehicle="1"]').click();await page.locator('#world-action').waitFor();assert.equal(await page.locator('#world-action').textContent(),'Verdien een onderdeel');
 for(let i=1;i<=2;i++){await page.locator('#world-action').click();await page.locator('#build-reward').waitFor();assert.equal(await page.locator('#world-parts').textContent(),i+' / 20');await page.locator('#world-action').waitFor({state:'visible'});}
 await page.locator('#demo-race').click();await page.locator('[data-drive="gas"]').waitFor();assert(await page.locator('.build-demo').isHidden());assert.deepEqual(errors,[]);await browser.close();console.log('PASS: directe bouwproef, grote knop tweemaal, terugkeer na animatie en directe race.');return;
}
await page.goto('http://127.0.0.1:8765/spelen/games/spellingeiland/?spel=workshop');
await page.evaluate(()=>localStorage.setItem('zisa-spelling-settings-v1',JSON.stringify({mode:'workshop',count:10,categories:['mmkm']})));await page.reload();
await page.evaluate(()=>{const A=SpellingWorkshop;window.SpellingWorkshop=class extends A{constructor(o){super(o);window.shop=this;}};const make=SpellingEngine.makeExercise;SpellingEngine.makeExercise=(...a)=>(window.ex=make(...a));speechSynthesis.speak=u=>setTimeout(()=>u.onend?.(),10);});
while(await page.locator('#setup-next').count())await page.locator('#setup-next').click();await page.locator('#start').click();await page.getByRole('button',{name:'Op avontuur!',exact:true}).click();await page.waitForFunction(()=>Object.values(shop.images).every(i=>i.complete&&i.naturalWidth));
assert(await page.locator('#vehicle-choice').isVisible());await page.screenshot({path:__dirname+'/build-three-choices.png'});await page.locator('[data-vehicle="1"]').click();assert(await page.locator('#vehicle-choice').isHidden());assert.equal(await page.locator('#garage-store').count(),0);
if(!process.argv.includes('--visual')){
for(let n=1;n<=10;n++){await page.waitForFunction(()=>document.body.dataset.view==='play');const ex=await page.evaluate(()=>window.ex);for(const ch of ex.answer)await page.locator('[data-token]:not(:disabled)').filter({hasText:new RegExp('^'+ch+'$')}).first().click();await page.locator('#check').click();await page.waitForFunction(n=>shop.done===n,n);assert.equal(await page.evaluate(()=>shop.installed.size),n*2);if(n===1){await page.waitForTimeout(2200);await page.screenshot({path:__dirname+'/build-first.png'});}if(n===5){await page.locator('#build-color').waitFor();await page.locator('[data-paint="125"]').click();await page.locator('#keep-paint').click();}}
await page.waitForFunction(()=>shop.phase==='ready');assert.equal(await page.evaluate(()=>shop.colorChosen),true);await page.screenshot({path:__dirname+'/build-finished.png'});
await page.locator('#world-action').click();await page.waitForTimeout(3200);assert.equal(await page.evaluate(()=>shop.carState.speed),0);await page.keyboard.down('ArrowUp');await page.waitForTimeout(600);await page.keyboard.down('ArrowRight');await page.waitForTimeout(400);await page.keyboard.up('ArrowUp');await page.keyboard.up('ArrowRight');assert(await page.evaluate(()=>shop.carState.speed)>0);
}
for(const vehicle of [0,1,2])for(const count of [10,15,20]){const result=await page.evaluate(({count,vehicle})=>{shop.destroy();document.body.dataset.view='world';window.shop=new SpellingWorkshop({count,onChallenge:()=>{},onStop:()=>{},onFinish:()=>{}});shop.buildPreview=true;shop.choose(vehicle);let paint=0;for(let n=1;n<=count;n++){shop.phase='question';shop.solve('woord');shop.finishReward();if(shop.phase==='paint-choice'){paint++;shop.colorChosen=true;shop.nextBuild();}}return {phase:shop.phase,size:shop.installed.size,paint};},{count,vehicle});assert.deepEqual(result,{phase:'ready',size:20,paint:1});await page.waitForFunction(()=>shop.images.sideCars.complete&&shop.images.sideCars.naturalWidth);if(count===20){await page.screenshot({path:__dirname+'/build-car-'+vehicle+'.png'});await page.evaluate(()=>shop.startRace());await page.waitForTimeout(100);await page.screenshot({path:__dirname+'/race-car-'+vehicle+'.png'});}}
await page.waitForFunction(()=>shop.images.sideCars.complete&&shop.images.sideCars.naturalWidth);await page.screenshot({path:__dirname+'/build-complete.png'});
for(const n of [1,5,10,15,19]){await page.evaluate(n=>{shop.installed=new Set(Array.from({length:n},(_,i)=>i));shop.done=n;shop.rewardParts=[n-1];shop.phase='reward';shop.rewardTime=2.8;shop.renderControls();shop.drawReward();shop.draw();},n);await page.screenshot({path:__dirname+'/build-stage-'+n+'.png'});}
for(const size of [{width:768,height:1024},{width:390,height:844}]){await page.setViewportSize(size);await page.evaluate(()=>{shop.phase='paint-choice';shop.renderControls();});const r=await page.locator('#build-color').boundingBox();assert(r.y>=0&&r.y+r.height<=size.height);await page.screenshot({path:__dirname+'/build-'+size.width+'.png'});}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: onderdelen, 10/15/20 compleet, één kleurkeuze, geen winkel, race en schermmaten.');})().catch(e=>{console.error(e);process.exit(1)});
