const {chromium}=require(require.resolve('playwright',{paths:['C:/Users/isabe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules']}));const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/spelen/games/spellingeiland/?spel=workshop');await page.evaluate(()=>{document.body.dataset.view='world';window.race=new SpellingWorkshop({count:10,onChallenge:()=>{},onFinish:()=>{},onStop:()=>{}});race.buildPreview=true;race.startRace();});await page.waitForFunction(()=>Object.values(race.images).every(im=>im.complete&&im.naturalWidth));await page.waitForTimeout(3100);
if(process.argv.includes('--steering')){
 const cases=await page.evaluate(()=>{
  const results=[];
  for(const direction of [-1,1])for(const gap of [120,180,255]){
   race.startRace();race.raceTime=4;race.obstacles=[];race.pads=[];race.carState.progress=1000;race.carState.speed=180;race.rivals[0].progress=1000+gap;race.rivals[0].lane=direction*.62;race.rivals[0].home=direction*.62;race.rivals[0].velocity=180;race.rivals[1].progress=5000;race.held.add(direction<0?'left':'right');
   let backwards=false;for(let i=0;i<100;i++){const before=race.carState.progress;race.updateRace(.016);backwards ||=race.carState.progress<before;}results.push({direction,gap,offset:race.carState.offset,backwards});
  }
  for(const direction of [-1,1]){race.startRace();race.raceTime=4;race.obstacles=[];race.pads=[];race.rivals.forEach(r=>r.progress=5000);race.held.add(direction<0?'left':'right');for(let i=0;i<160;i++)race.updateRace(.016);results.push({direction,stopped:true,offset:race.carState.offset});}
  return results;
 });for(const r of cases){assert(Math.abs(r.offset-r.direction*.8)<.001,JSON.stringify(r));assert(!r.backwards);}assert.deepEqual(errors,[]);await browser.close();console.log('PASS steering reaches both edges behind nearby cars and at low speed',cases);return;
}
if(process.argv.includes('--pads')){
 const result=await page.evaluate(()=>{
  race.startRace();race.raceTime=4;race.rivals.forEach(r=>r.progress=5000);race.obstacles=[];race.pads=[{distance:1100,lane:0,used:false}];race.carState.progress=1099;race.carState.offset=0;race.carState.speed=235;race.updateRace(.016);const immediate={speed:race.carState.speed,boost:race.boost,used:race.pads[0].used};
  const before=race.carState.progress;for(let i=0;i<60;i++)race.updateRace(1/60);const travelled=race.carState.progress-before;
  race.held.add('brake');race.updateRace(.016);const braking={speed:race.carState.speed,boost:race.boost};race.held.clear();
  race.boost=2;race.carState.speed=310;race.obstacles=[{distance:race.carState.progress+1,lane:0,hit:false}];race.updateRace(.016);const obstacle={boost:race.boost,speed:race.carState.speed};
  return{immediate,travelled,braking,obstacle,uses:race.turbosUsed};
 });assert.equal(result.immediate.speed,310);assert(result.immediate.used);assert(result.travelled>300);assert.equal(result.braking.boost,0);assert(result.braking.speed<=235);assert.equal(result.obstacle.boost,0);assert(result.obstacle.speed<100);assert.equal(result.uses,1);assert.deepEqual(errors,[]);await browser.close();console.log('PASS immediate pad boost, faster travel without button, braking and obstacle cancel boost',result);return;
}
if(process.argv.includes('--collisions')){
 const result=await page.evaluate(()=>{
  const results=[];
  for(const scenario of [{a:0,b:.49,gap:0},{a:0,b:-.49,gap:40},{a:.8,b:.32,gap:-40},{a:-.8,b:-.32,gap:20}]){
   race.startRace();race.raceTime=4;race.obstacles=[];race.pads=[];race.carState.progress=1000;race.carState.offset=scenario.a;race.carState.speed=200;race.rivals[0].progress=1000+scenario.gap;race.rivals[0].lane=scenario.b;race.rivals[0].home=scenario.b;race.rivals[0].velocity=200;race.rivals[1].progress=4000;
   const before=[race.carState.progress,race.rivals[0].progress];race.updateRace(.016);results.push({deltas:[race.carState.progress-before[0],race.rivals[0].progress-before[1]],lanes:[race.carState.offset,race.rivals[0].lane],speeds:[race.carState.speed,race.rivals[0].velocity]});
  }
  race.startRace();race.raceTime=4;race.carState.progress=0;race.rivals[0].progress=1000;race.rivals[1].progress=1020;race.rivals[0].lane=-.2;race.rivals[1].lane=.2;race.rivals.forEach(r=>r.velocity=200);race.resolveCarContacts([0,1000,1020],[0,-.2,.2]);const ai={positions:race.rivals.map(r=>r.progress),lanes:race.rivals.map(r=>r.lane)};
  return{results,ai};
 });
 for(const r of result.results){assert(r.deltas.every(n=>n>=0&&n<4),'no forward or backward jump');assert(Math.abs(r.lanes[1]-r.lanes[0])>=.5);assert(r.lanes.every(n=>Math.abs(n)<=.8));assert(r.speeds.every(n=>n<200));}assert.deepEqual(result.ai.positions,[1000,1020]);assert(Math.abs(result.ai.lanes[1]-result.ai.lanes[0])>=.5);assert.deepEqual(errors,[]);await browser.close();console.log('PASS side contacts left/right/road edges/AI: separate sideways, slow down, no longitudinal teleport');return;
}
if(process.argv.includes('--lanes')){
 for(const offset of [-.65,.65]){await page.evaluate(offset=>{race.carState.offset=offset;race.carState.angle=.12;race.drawRace();},offset);await page.screenshot({path:__dirname+'/lane-'+(offset<0?'left':'right')+'.png'});}
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS both side lanes render');return;
}
if(process.argv.includes('--drivers')){
 for(const vehicle of [0,1,2]){await page.evaluate(vehicle=>{race.vehicle=vehicle;race.color=125;race.startRace();race.raceTime=4;race.carState.progress=1600;race.distance=1600;race.rivals[0].progress=2100;race.rivals[1].progress=2400;race.drawRace();},vehicle);await page.screenshot({path:__dirname+'/driver-race-'+vehicle+'.png'});
 const protectedColor=await page.evaluate(vehicle=>{const im=race.driverCars[vehicle],paint=race.carPaint(im,125,vehicle,true);const cv=document.createElement('canvas');cv.width=im.naturalWidth;cv.height=im.naturalHeight;const c=cv.getContext('2d');c.drawImage(im,0,0);const point=[[.48,.12],[.36,.23],[.38,.22]][vehicle],x=Math.floor(point[0]*cv.width),y=Math.floor(point[1]*cv.height);const before=[...c.getImageData(x,y,1,1).data],after=[...paint.getContext('2d').getImageData(x,y,1,1).data];return{before,after};},vehicle);assert.deepEqual(protectedColor.before,protectedColor.after);}
 await page.setViewportSize({width:1024,height:768});await page.locator('#island-menu-button').click();assert(await page.locator('#island-menu').isVisible());await page.locator('#island-menu .continue').click();await page.keyboard.down('ArrowUp');await page.waitForTimeout(400);await page.keyboard.up('ArrowUp');assert(await page.evaluate(()=>race.carState.speed)>0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 3 driver sprites, helmet colour protected, same return menu, race controls');return;
}
if(process.argv.includes('--traffic')){
 const result=await page.evaluate(()=>{race.startRace();race.raceTime=4;race.pads=[];race.obstacles=[{distance:1300,lane:.62,hit:false}];race.carState.progress=1000;race.carState.offset=0;race.carState.speed=0;race.rivals[0].progress=1000;race.rivals[0].lane=.62;race.rivals[0].home=.62;race.rivals[0].velocity=190;race.rivals[1].progress=1000;race.rivals[1].lane=-.62;race.rivals[1].home=-.62;race.rivals[1].finished=4;
 for(let i=0;i<250;i++)race.updateRace(.02);const stopped={progress:race.rivals[0].progress,speed:race.rivals[0].velocity};race.carState.progress=2100;race.rivals[1].progress=0;let crossedSafely=true;for(let i=0;i<350;i++){const prev=race.rivals[0].progress;race.updateRace(.02);if(prev<1300&&race.rivals[0].progress>=1300&&Math.abs(race.rivals[0].lane-.62)<.48)crossedSafely=false;}const resumed=race.rivals[0].progress>1300;
 race.startRace();race.raceTime=4;race.obstacles=[];race.pads=[];race.carState.progress=2000;race.carState.speed=235;race.rivals[0].progress=1000;race.rivals[0].velocity=185;race.rivals[1].progress=500;race.held.add('gas');for(let i=0;i<1000;i++)race.updateRace(.02);return{stopped,resumed,crossedSafely,gap:race.carState.progress-race.rivals[0].progress};});assert(result.stopped.progress<=1190);assert.equal(result.stopped.speed,0);assert(result.resumed);assert(result.crossedSafely);assert(result.gap<800);assert.deepEqual(errors,[]);await browser.close();console.log('PASS blocked rival brakes, waits, safely resumes, and catches up on open road',result);return;
}
if(process.argv.includes('--passing')){
 const result=await page.evaluate(()=>{race.startRace();window.obstacleLanes=race.obstacles.map(o=>o.lane);const grid=race.rivals.map(r=>r.progress).concat(race.carState.progress);race.updateRace(1);const countdown=race.rivals.map(r=>r.progress).concat(race.carState.progress);race.raceTime=3;race.held.add('gas');for(let i=0;i<500;i++)race.updateRace(.02);const natural=race.rank;
 race.startRace();race.raceTime=3;race.obstacles=[];race.pads=[];race.carState.progress=1000;race.carState.offset=-.62;race.carState.speed=235;race.rivals[0].progress=1280;race.rivals[0].velocity=185;race.rivals[1].progress=3000;race.rivals[1].velocity=195;race.held.add('gas');for(let i=0;i<60;i++)race.updateRace(.02);const behind=race.carState.progress<race.rivals[0].progress;race.held.add('right');for(let i=0;i<35;i++)race.updateRace(.02);race.held.delete('right');for(let i=0;i<700;i++)race.updateRace(.02);return{grid,countdown,natural,behind,passed:race.carState.progress>race.rivals[0].progress,offset:race.carState.offset};});
 assert.deepEqual((await page.evaluate(()=>[...new Set(obstacleLanes)])).sort((a,b)=>a-b),[-.55,0,.55]);assert.deepEqual(result.grid,[0,0,0]);assert.deepEqual(result.countdown,[0,0,0]);assert.equal(result.natural,1);assert(result.behind);assert(result.passed);await page.evaluate(()=>{race.startRace();race.drawRace();});await page.screenshot({path:__dirname+'/race-equal-start.png'});assert.deepEqual(errors,[]);await browser.close();console.log('PASS equal starting grid, countdown, acceleration and moving aside to overtake',result);return;
}
if(process.argv.includes('--fun')){
 const result=await page.evaluate(()=>{race.raceTime=4;race.pads=[];race.obstacles=[];race.carState.progress=1000;race.distance=1000;race.carState.speed=310;race.carState.offset=0;race.rivals[0].progress=1280;race.rivals[0].lane=0;race.rivals[1].progress=2200;race.held.add('gas');race.useTurbo();let min=Infinity;for(let i=0;i<100;i++){race.updateRace(.02);min=Math.min(min,race.rivals[0].progress-race.carState.progress);}race.held.clear();return{gap:min,charges:race.turboCharges,used:race.turbosUsed};});assert(result.gap>=259);assert.equal(result.charges,0);assert.equal(result.used,1);
 const obstacle=await page.evaluate(()=>{race.startRace();race.raceTime=4;race.rivals.forEach(r=>r.progress=4000);race.pads=[];race.obstacles=[{distance:1100,lane:.55,hit:false}];race.carState.progress=1099;race.carState.offset=.55;race.carState.speed=235;race.held.add('gas');race.updateRace(.02);return{hit:race.obstacles[0].hit,speed:race.carState.speed};});assert(obstacle.hit);assert(obstacle.speed<100);
 await page.evaluate(()=>{race.startRace();race.raceTime=4;race.carState.progress=650;race.distance=650;race.drawRace();});await page.screenshot({path:__dirname+'/race-obstacle.png'});
 await page.evaluate(()=>{race.carState.progress=race.totalDistance-1;race.carState.speed=200;race.rivals.forEach(r=>{r.progress=race.totalDistance-800;});race.held.add('gas');race.updateRace(.02);});await page.locator('#race-podium').waitFor();await page.screenshot({path:__dirname+'/race-new-podium.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:__dirname+'/race-new-podium-phone.png'});for(const id of ['#race-again','#race-done']){const b=await page.locator(id).boundingBox();assert(b.y+b.height<844);}
 await page.locator('#race-again').click();assert(await page.locator('#race-podium').isHidden());assert.equal(await page.evaluate(()=>race.carState.progress),0);assert.equal(await page.evaluate(()=>race.turboCharges),1);assert.deepEqual(errors,[]);await browser.close();console.log('PASS collision separation, manual turbo, podium, replay and mobile buttons',result);return;
}
assert.equal(await page.evaluate(()=>race.carState.speed),0);await page.keyboard.down('ArrowUp');await page.waitForTimeout(800);await page.keyboard.down('ArrowRight');await page.waitForTimeout(1700);await page.keyboard.up('ArrowRight');assert(await page.evaluate(()=>race.carState.offset)<=.8);assert(await page.evaluate(()=>race.carState.speed)>0);await page.keyboard.up('ArrowUp');await page.keyboard.down('ArrowDown');await page.waitForTimeout(800);await page.keyboard.up('ArrowDown');assert.equal(await page.evaluate(()=>race.carState.speed),0);
const stats=await page.evaluate(()=>{race.startRace();race.raceTime=4;race.held.add('gas');let maxOffset=0;for(let i=0;i<4000&&race.phase==='race';i++){const target=race.pads.find(p=>!p.used&&p.distance>race.distance);const diff=(target?.lane||0)-race.carState.offset;race.held.delete('left');race.held.delete('right');if(Math.abs(diff)>.04)race.held.add(diff>0?'right':'left');race.updateRace(.02);maxOffset=Math.max(maxOffset,Math.abs(race.carState.offset));}return{phase:race.phase,rank:race.rank,pads:race.pads.filter(p=>p.used).length,maxOffset,progress:race.distance,total:race.totalDistance};});assert.equal(stats.phase,'podium');assert(stats.pads>3);assert(stats.maxOffset<=.8);assert(stats.progress>=stats.total);
await page.evaluate(()=>{race.startRace();race.raceTime=5;race.carState.progress=2100;race.distance=2100;race.carState.speed=220;race.rivals[0].progress=2450;race.rivals[1].progress=2700;race.drawRace();});await page.screenshot({path:__dirname+'/race-chase.png'});
for(const size of [{width:768,height:1024},{width:390,height:844}]){await page.setViewportSize(size);await page.waitForTimeout(150);for(const name of ['left','right','gas','brake']){const b=await page.locator('[data-drive="'+name+'"]').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=size.width&&b.y+b.height<=size.height);}await page.screenshot({path:__dirname+'/race-chase-'+size.width+'.png'});}
await page.goto('http://127.0.0.1:8765/spelen/games/spellingeiland/index.html?spel=workshop&proef=race');await page.locator('[data-drive="gas"]').waitFor();assert(await page.locator('.build-demo').isHidden());assert.deepEqual(errors,[]);await browser.close();console.log('PASS:',stats,'keyboard, controls in viewport, direct race URL');})().catch(e=>{console.error(e);process.exit(1)});
