(()=>{
const $=id=>document.getElementById(id),stage=()=>$('stage'),menu=()=>$('menu');
const gcd=(a,b)=>b?gcd(b,a%b):a,lcm=(a,b)=>a*b/gcd(a,b),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const types={
 addSame:{icon:'➕',name:'Gelijknamig optellen',desc:'Bouw beide breuken en voeg de gelijke stukken samen.'},
 addUnlike:{icon:'🔄',name:'Ongelijknamig optellen',desc:'Kies eerst de kleinste gemeenschappelijke noemer.'},
 subSame:{icon:'➖',name:'Gelijknamig aftrekken',desc:'Neem de gevraagde stukken één voor één zichtbaar weg.'},
 subUnlike:{icon:'🧠',name:'Ongelijknamig aftrekken',desc:'Maak gelijknamig en neem daarna passende stukken weg.'}
};
const banks={
 addSame:[[1,4,2,4],[2,5,1,5],[1,6,3,6],[2,8,3,8],[1,3,1,3],[3,8,2,8],[2,6,3,6],[1,5,3,5],[2,4,1,4],[1,8,5,8]],
 addUnlike:[[1,2,1,4],[1,3,1,6],[1,2,1,3],[1,4,1,8],[2,3,1,6],[1,3,1,4],[1,4,1,6],[1,2,1,6],[2,5,1,10],[1,6,1,4]],
 subSame:[[5,8,3,8],[4,6,2,6],[3,4,1,4],[4,5,3,5],[5,6,2,6],[7,8,4,8],[2,3,1,3],[3,5,2,5],[6,8,1,8],[5,8,2,8]],
 subUnlike:[[3,4,1,2],[5,6,1,3],[7,8,1,4],[5,6,1,2],[4,6,1,3],[7,10,1,5],[5,8,1,2],[3,6,1,3],[9,12,1,4],[6,8,1,4]]
};
let type='',round=0,rounds=[],s={};
function open(){showPicker()}
function showPicker(){stage().innerHTML='';let o=$('calcPicker');if(!o){o=document.createElement('section');o.id='calcPicker';o.className='overlay';document.body.append(o)}o.innerHTML=`<article><span class="badge">BREUKEN REKENEN</span><h2>Wat wil je oefenen?</h2><p>Kies hoe je vandaag met breuken wilt rekenen.</p><div class="calc-picker">${Object.entries(types).map(([id,t])=>`<button data-calc="${id}"><span class="calc-icon">${t.icon}</span><span><b>${t.name}</b><small>${t.desc}</small></span><i>→</i></button>`).join('')}</div><div class="demo-actions"><button class="secondary" id="calcClose">Terug naar alle oefenvormen</button></div></article>`;o.hidden=false;o.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>begin(b.dataset.calc));$('calcClose').onclick=()=>{o.hidden=true;menu().hidden=false}}
function begin(id){type=id;round=0;rounds=shuffle(banks[id]).slice(0,8);$('calcPicker').hidden=true;showIntro()}
function subtractionDemo(unlike){const den=unlike?4:8,built=unlike?3:5,take=unlike?2:3,original=unlike?'3/4 − 1/2':'5/8 − 3/8',converted=unlike?'<div class="calc-convert-note">Eerst: 1/2 = 2/4</div>':'';return `<div class="calc-sub-demo">${converted}<b>${original}</b><small>Gebouwd</small><div class="calc-take-source">${Array.from({length:den},(_,i)=>`<i class="${i<built?'filled':''}${i>=built-take&&i<built?` take take${i-(built-take)+1}`:''}">1/${den}</i>`).join('')}</div><span class="calc-take-arrow">↓ neem elk stuk één voor één weg ↓</span><small>Weggenomen</small><div class="calc-take-tray">${Array.from({length:take},(_,i)=>`<i class="arrive arrive${i+1}">1/${den}</i>`).join('')}</div><strong>${Array.from({length:take},()=>`1/${den}`).join(' + ')} = ${take}/${den} weggenomen</strong><span class="calc-sub-hand">👆🏼</span></div>`}
function showIntro(){let o=$('calcIntro');if(!o){o=document.createElement('section');o.id='calcIntro';o.className='overlay';document.body.append(o)}const sub=type.startsWith('sub'),unlike=type.endsWith('Unlike'),visual=sub?subtractionDemo(unlike):`<div class="calc-demo-scene"><div class="calc-demo-bar"><i></i><i></i><i></i><i></i></div><b>+</b><div class="calc-demo-bar"><i></i><i></i></div><span class="calc-demo-hand">👆🏼</span></div>`;o.innerHTML=`<article class="demo-card"><span class="badge">KIJK EERST EVEN</span><h2>${types[type].name}</h2><p>${sub?'Kijk: ieder stuk wordt echt uit de eerste breuk gehaald en blijft daarna zichtbaar in de wegneembak.':'Bouw beide breuken apart en voeg ze pas samen wanneer de stukken dezelfde noemer hebben.'}</p><div class="calc-demo">${visual}<b>${unlike?'Maak eerst gelijknamig. Neem daarna de passende stukken één voor één weg.':sub?'Tel onderaan mee hoeveel er samen weggenomen is.':'De noemer blijft gelijk omdat alle stukken even groot zijn.'}</b></div><div class="demo-actions"><button class="secondary" id="calcSkip">Demo overslaan</button><button id="calcStart">Naar het spel →</button></div></article>`;o.hidden=false;$('calcSkip').onclick=$('calcStart').onclick=()=>{o.hidden=true;show()}}
function frac(n,d){return `${n}/${d}`}
function simplified(n,d){const g=gcd(n,d);return g>1?`${frac(n,d)} = ${frac(n/g,d/g)}`:frac(n,d)}
function show(){s={selected:null,left:[],right:[],removed:[],phase:'build',errors:{}};const q=rounds[round],sub=type.startsWith('sub'),unlike=type.endsWith('Unlike'),[a,d,b,e]=q;stage().innerHTML=`<article class="calc-shell"><button class="calc-back" id="calcBack">← Rekenvormen</button><div class="calc-head"><div class="eyebrow">OPDRACHT ${round+1} VAN ${rounds.length}</div><h2>${frac(a,d)} ${sub?'−':'+'} ${frac(b,e)}</h2><p>${sub?'Bouw eerst de eerste breuk. Neem daarna precies de gevraagde hoeveelheid weg.':'Bouw beide breuken eerst apart.'}</p></div><div class="calc-work"><aside class="calc-palette">${[2,3,4,5,6,8,10,12].map(x=>`<button data-pick="${x}">stuk 1/${x}</button>`).join('')}</aside><div class="calc-main"><div class="calc-builds"><section class="calc-zone"><h3>Bouw ${frac(a,d)}</h3><div class="calc-bar" id="calcLeft"></div><button class="calc-addpiece" data-add="left">＋ Leg gekozen stuk</button><button class="calc-undo" data-undo="left">↶ Laatste terug</button></section>${sub?`<section class="calc-zone"><h3>Dit moet weg: ${frac(b,e)}</h3><div class="calc-removed" id="calcRemoved"><span>Nog niets weggenomen</span></div><div class="calc-equation" id="removedEq">0/${e} weggenomen</div></section>`:`<section class="calc-zone"><h3>Bouw ${frac(b,e)}</h3><div class="calc-bar" id="calcRight"></div><button class="calc-addpiece" data-add="right">＋ Leg gekozen stuk</button><button class="calc-undo" data-undo="right">↶ Laatste terug</button></section>`}</div><div class="calc-phase" id="calcPhase"><b>Stap 1: bouw ${sub?'de eerste breuk':'beide breuken'}.</b></div></div></div><div class="calc-actions"><button class="secondary" id="calcReset">Opnieuw</button><button id="calcReady">Klaar met bouwen</button></div><div class="calc-feedback" id="calcFeedback"></div><div class="calc-progress">${types[type].name}</div></article>`;wireBuild(a,d,b,e,sub,unlike);$('calcBack').onclick=showPicker}
const denominatorColors={2:'#ef7eae',3:'#f2a65a',4:'#ffd34f',5:'#80cf8f',6:'#55bad8',8:'#b58ae2',10:'#5fc7bd',12:'#86a9e8'};
function pieceHtml(den,i,removable=false,removed=false){return `<button class="calc-piece${removable?' removable':''}${removed?' removed':''}" style="--den:${den};--piece:${denominatorColors[den]||'#55bad8'}" data-piece="${i}" aria-label="${removable&&!removed?'Sleep ':''}stuk 1/${den}${removable&&!removed?' naar de wegneembak':''}"><span>1/${den}</span>${removable&&!removed?'<b class="remove-mark">↘</b>':''}</button>`}
function modelBar(n,d,label){return `<div class="calc-old-model"><b>${label}</b><div class="calc-bar">${Array.from({length:n},(_,i)=>pieceHtml(d,i)).join('')}</div></div>`}
function renderBars(){ $('calcLeft').innerHTML=s.left.map((d,i)=>pieceHtml(d,i,s.phase==='remove',s.removed.includes(i))).join('');if($('calcRight'))$('calcRight').innerHTML=s.right.map((d,i)=>pieceHtml(d,i)).join('');if(s.phase==='remove')document.querySelectorAll('#calcLeft .calc-piece.removable:not(.removed)').forEach(b=>enablePieceDrag(b,+b.dataset.piece))}
function wireBuild(a,d,b,e,sub,unlike){if(sub){$('calcReady').hidden=true;$('calcPhase').innerHTML=`<b>Bouw ${frac(a,d)}.</b><p>Zodra de breuk juist gebouwd is, kun je meteen stukken wegslepen.</p>`}document.querySelectorAll('[data-pick]').forEach(x=>x.onclick=()=>{s.selected=+x.dataset.pick;document.querySelectorAll('[data-pick]').forEach(y=>y.classList.toggle('selected',y===x))});document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>{if(!s.selected)return bad('Kies eerst links welk soort breukstuk je wilt leggen.');s[x.dataset.add].push(s.selected);renderBars();clearFeedback();if(sub&&exact(s.left,a,d)){lockBuild();setTimeout(()=>unlike?chooseRemovalAmount(a,d,b,e):startRemoval(a,d,b,e,d,b),250)}});document.querySelectorAll('[data-undo]').forEach(x=>x.onclick=()=>{s[x.dataset.undo].pop();renderBars()});$('calcReset').onclick=show;$('calcReady').onclick=()=>checkBuild(a,d,b,e,sub,unlike);renderBars()}
function exact(arr,n,d){return arr.length===n&&arr.every(x=>x===d)}
function err(k){return s.errors[k]=(s.errors[k]||0)+1}
function bad(t){const f=$('calcFeedback');f.className='calc-feedback bad';f.textContent=t}
function good(t){const f=$('calcFeedback');f.className='calc-feedback good';f.textContent=t}
function clearFeedback(){const f=$('calcFeedback');f.className='calc-feedback';f.textContent=''}
function lockBuild(){document.querySelector('.calc-palette').hidden=true;document.querySelector('.calc-work').classList.add('calc-locked');document.querySelectorAll('[data-add],[data-undo]').forEach(x=>x.hidden=true)}
function checkBuild(a,d,b,e,sub,unlike){const ok=exact(s.left,a,d)&& (sub||exact(s.right,b,e));if(!ok){const n=err('build');if(n===1)bad(sub?`Bouw ${a} stukken van 1/${d}.`:`Links heb je ${a} × 1/${d} nodig en rechts ${b} × 1/${e}.`);else if(n===2){document.querySelector(`[data-pick="${d}"]`)?.classList.add('learning-highlight');if(!sub)document.querySelector(`[data-pick="${e}"]`)?.classList.add('learning-highlight');bad('De passende soorten stukken lichten op. Bouw de breuken nog zelf.')}else{document.querySelector(`[data-pick="${d}"]`)?.classList.add('learning-solution');if(!sub)document.querySelector(`[data-pick="${e}"]`)?.classList.add('learning-solution');bad('Groen toont het juiste materiaal. Let op de teller voor het aantal stukken.')}return}lockBuild();clearFeedback();if(unlike)chooseDenominator(a,d,b,e,sub);else if(sub)startRemoval(a,d,b,e,d,b);else finishAddition(a,d,b,e,d,a+b)}
function candidates(d,e){const m=lcm(d,e),list=[m,m*2,m*3].filter(x=>x<=24);return shuffle([...new Set([d,e,...list,Math.max(d,e)+1])]).slice(0,5).sort((a,b)=>a-b)}
function chooseDenominator(a,d,b,e,sub){s.phase='denom';const min=lcm(d,e),box=$('calcPhase');box.innerHTML=`<b>Stap 2: kies de kleinste noemer die voor beide breuken werkt.</b><div class="calc-denoms">${candidates(d,e).map(x=>`<button data-common="${x}">${x}</button>`).join('')}</div><div id="commonHelp"></div>`;$('calcReady').hidden=true;box.querySelectorAll('[data-common]').forEach(x=>x.onclick=()=>{const chosen=+x.dataset.common;if(chosen%d||chosen%e){const n=err('commonInvalid');if(n===1)bad(`Noemer ${chosen} werkt niet: je kunt niet beide soorten stukken er precies in verdelen.`);else if(n===2){$('commonHelp').textContent=`Zoek een getal in zowel de tafel van ${d} als de tafel van ${e}.`;bad(`Tel de sprongen: ${d}, ${d*2}, ${d*3} … en ${e}, ${e*2}, ${e*3} …`)}else{box.querySelector(`[data-common="${min}"]`)?.classList.add('learning-solution');bad('De kleinste passende noemer licht groen op. Tik hem zelf aan.')}return}if(chosen!==min){const n=err('commonLarge');if(n===1)bad(`${chosen} kan, maar het kan eenvoudiger. Zoek de kleinste noemer die voor beide breuken past.`);else{box.querySelector(`[data-common="${min}"]`)?.classList.add(n>2?'learning-solution':'learning-highlight');bad(`Zoek de eerste gemeenschappelijke sprong van ${d} en ${e}.`)}return}convert(a,d,b,e,sub,min)})}
function convert(a,d,b,e,sub,common){const leftN=a*common/d,rightN=b*common/e,builds=document.querySelector('.calc-builds');let history=document.createElement('div');history.className='calc-conversion-history';history.innerHTML=`<span>ZO HEB JE HET EERST GEBOUWD</span>${modelBar(a,d,frac(a,d))}${sub?'':modelBar(b,e,frac(b,e))}<strong>↓ verdeel dezelfde hoeveelheid in kleinere, gelijke stukken ↓</strong>`;builds.parentElement.insertBefore(history,builds);s.left=Array(leftN).fill(common);s.right=Array(rightN).fill(common);clearFeedback();renderBars();document.querySelectorAll('.calc-bar').forEach(x=>x.classList.add('calc-split'));builds.querySelector('.calc-zone:first-child h3').textContent=`Gelijknamig: ${frac(a,d)} = ${frac(leftN,common)}`;if(!sub)builds.querySelector('.calc-zone:nth-child(2) h3').textContent=`Gelijknamig: ${frac(b,e)} = ${frac(rightN,common)}`;$('calcPhase').innerHTML=`<div class="calc-equation">${frac(a,d)} = ${frac(leftN,common)} &nbsp; en &nbsp; ${frac(b,e)} = ${frac(rightN,common)}</div><p>De hoeveelheid blijft hetzelfde; alleen de verdeling en de naam van de stukken veranderen.</p>`;if(sub)startRemoval(a,d,b,e,common,rightN);else finishAddition(a,d,b,e,common,leftN+rightN)}
function finishAddition(a,d,b,e,common,total){s.phase='answer';$('calcReady').hidden=true;const box=$('calcPhase'),leftN=a*common/d,rightN=b*common/e;box.innerHTML+=`<div class="calc-equation">${s.left.map(()=>`1/${common}`).join(' + ')} + ${s.right.map(()=>`1/${common}`).join(' + ')}</div><button class="calc-addpiece" id="mergeCalc">Voeg alle stukken samen ↓</button><div class="calc-bar" id="calcResult"></div><div class="calc-final-equation" id="calcFinalEq" hidden></div>`;$('mergeCalc').onclick=()=>{const chain=d===e?`${frac(a,d)} + ${frac(b,e)} = ${simplified(total,common)}`:`${frac(a,d)} + ${frac(b,e)} = ${frac(leftN,common)} + ${frac(rightN,common)} = ${simplified(total,common)}`;$('calcResult').innerHTML=Array(total).fill(common).map((den,i)=>pieceHtml(den,i)).join('');$('calcFinalEq').textContent=chain;$('calcFinalEq').hidden=false;good('Mooi: je ziet nu elke stap van de bewerking onder de samengevoegde strook.');showNext()}}
function chooseRemovalAmount(a,d,b,e){const needed=b*d/e,options=shuffle([...new Set([Math.max(1,needed-1),needed,needed+1,Math.min(d,needed+2)])]);$('calcPhase').innerHTML=`<b>Maak eerst de breuk die weg moet gelijknamig</b><div class="calc-equation">${frac(b,e)} = ?/${d}</div><p>Hoeveel stukken van 1/${d} zijn evenveel als ${frac(b,e)}?</p><div class="calc-denoms">${options.map(n=>`<button data-remove-count="${n}">${frac(n,d)}</button>`).join('')}</div>`;document.querySelectorAll('[data-remove-count]').forEach(x=>x.onclick=()=>{if(+x.dataset.removeCount!==needed){const n=err('removeEquivalent');if(n===1)bad(`Vergelijk ${frac(b,e)} met de gebouwde stukken van 1/${d}. Hoeveel passen daarin?`);else{document.querySelector(`[data-remove-count="${needed}"]`)?.classList.add(n>2?'learning-solution':'learning-highlight');bad('De gelijkwaardige hoeveelheid licht op. Kies ze zelf.')}return}s.equalizedText=`${frac(b,e)} = ${frac(needed,d)}`;clearFeedback();startRemoval(a,d,b,e,d,needed)})}
function startRemoval(a,d,b,e,common,removeCount){s.phase='remove';s.removed=[];$('calcReady').hidden=true;$('calcPhase').innerHTML=`${s.equalizedText?`<div class="calc-equalized-banner">Gelijknamig gemaakt: ${s.equalizedText}</div>`:''}<b>Sleep ${removeCount} stuk${removeCount===1?'':'ken'} van 1/${common} naar de wegneembak.</b><p>De stukken blijven rechts liggen, zodat je ziet hoeveel je samen hebt weggenomen.</p>`;s.removeData={a,d,b,e,common,removeCount};const zone=$('calcLeft').closest('.calc-zone');zone.querySelector('h3').textContent=`Sleep weg uit ${frac(a,d)}`;let hint=document.createElement('div');hint.className='calc-remove-hint';hint.innerHTML=`<span>↓</span><b>Sleep een gekleurd stuk naar de wegneembak rechts</b>`;zone.append(hint);renderBars();updateRemoved()}
function enablePieceDrag(button,index){button.onpointerdown=event=>{event.preventDefault();button.setPointerCapture(event.pointerId);const ghost=button.cloneNode(true);ghost.className='calc-piece drag-ghost';document.body.append(ghost);const move=e=>{ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`};move(event);button.onpointermove=move;button.onpointerup=e=>{button.onpointermove=null;button.onpointerup=null;ghost.remove();const r=$('calcRemoved').getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)removePiece(index);else bad('Sleep het stuk helemaal tot in de wegneembak rechts.')}}}
function removePiece(i){if(s.removed.includes(i))return;if(s.removed.length>=s.removeData.removeCount){bad(`Je hebt al ${frac(s.removeData.removeCount,s.removeData.common)} weggenomen.`);return}s.removed.push(i);renderBars();updateRemoved();if(s.removed.length===s.removeData.removeCount){const x=s.removeData,left=s.left.length-x.removeCount,leftStart=x.a*x.common/x.d,chain=x.d===x.e?`${frac(x.a,x.d)} − ${frac(x.b,x.e)} = ${simplified(left,x.common)}`:`${frac(x.a,x.d)} − ${frac(x.b,x.e)} = ${frac(leftStart,x.common)} − ${frac(x.removeCount,x.common)} = ${simplified(left,x.common)}`;let final=document.createElement('div');final.className='calc-final-equation';final.textContent=chain;$('calcPhase').append(final);good('Juist: alle weggenomen stukken en de volledige rekenketting blijven zichtbaar.');showNext()}}
function updateRemoved(){const x=s.removeData;if(!x)return;const count=s.removed.length;$('calcRemoved').innerHTML=count?s.removed.map(i=>pieceHtml(x.common,i)).join(''):'<span>Nog niets weggenomen</span>';$('removedEq').textContent=count?`${Array(count).fill(`1/${x.common}`).join(' + ')} = ${count}/${x.common} weggenomen`:`0/${x.common} weggenomen`}
function showNext(){if($('calcNext'))return;const wrap=document.querySelector('.calc-actions'),b=document.createElement('button');b.id='calcNext';b.textContent=round===rounds.length-1?'Ronde afronden':'Volgende opdracht →';b.onclick=()=>{round++;if(round>=rounds.length)finishRound();else show()};wrap.append(b)}
function finishRound(){let o=$('calcFinish');if(!o){o=document.createElement('section');o.id='calcFinish';o.className='overlay';document.body.append(o)}o.innerHTML=`<article><div class="stars">★ ★ ★</div><h2>Mooi gerekend!</h2><p>Je bouwde, maakte gelijknamig en rekende zelf met breuken.</p><div class="end"><button id="calcAgain">Nog een ronde</button><button id="calcOther">Andere rekenvorm</button><button id="calcAll">Alle oefenvormen</button></div></article>`;o.hidden=false;$('calcAgain').onclick=()=>{o.hidden=true;begin(type)};$('calcOther').onclick=()=>{o.hidden=true;showPicker()};$('calcAll').onclick=()=>{o.hidden=true;menu().hidden=false}}
window.BreukenRekenen={open};
})();
