(()=>{
const $=id=>document.getElementById(id),stage=()=>$('stage'),menu=()=>$('menu');
const gcd=(a,b)=>b?gcd(b,a%b):a,lcm=(a,b)=>a*b/gcd(a,b),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const types={
 addSame:{icon:'➕',name:'Gelijknamig optellen',desc:'Bouw beide breuken en voeg de gelijke stukken samen.'},
 addUnlike:{icon:'🔄',name:'Ongelijknamig optellen',desc:'Kies eerst de kleinste gemeenschappelijke noemer.'},
 subSame:{icon:'➖',name:'Gelijknamig aftrekken',desc:'Neem de gevraagde stukken één voor één zichtbaar weg.'},
 subUnlike:{icon:'🧠',name:'Ongelijknamig aftrekken',desc:'Maak gelijknamig en neem daarna passende stukken weg.'}
};
const banks={
 addSame:[[1,4,2,4],[2,5,1,5],[1,6,3,6],[2,8,3,8],[1,3,1,3],[3,8,2,8],[2,6,3,6],[1,5,3,5],[2,4,1,4],[1,8,5,8]],
 addUnlike:[[1,2,1,4],[1,3,1,6],[1,2,1,3],[1,4,1,8],[2,3,1,6],[1,3,1,4],[1,4,1,6],[1,2,1,6],[2,5,1,10],[1,6,1,4]],
 subSame:[[5,8,3,8],[4,6,2,6],[3,4,1,4],[4,5,3,5],[5,6,2,6],[7,8,4,8],[2,3,1,3],[3,5,2,5],[6,8,1,8],[5,8,2,8]],
 subUnlike:[[3,4,1,2],[5,6,1,3],[2,3,1,6],[7,8,1,4],[3,4,1,8],[5,6,1,2],[4,5,1,10],[2,3,1,3],[7,8,1,2],[3,4,1,4]]
};
let type='',round=0,rounds=[],s={};
function open(){showPicker()}
function showPicker(){stage().innerHTML='';let o=$('calcPicker');if(!o){o=document.createElement('section');o.id='calcPicker';o.className='overlay';document.body.append(o)}o.innerHTML=`<article><span class="badge">BREUKEN REKENEN</span><h2>Wat wil je oefenen?</h2><p>Kies hoe je vandaag met breuken wilt rekenen.</p><div class="calc-picker">${Object.entries(types).map(([id,t])=>`<button data-calc="${id}"><span class="calc-icon">${t.icon}</span><span><b>${t.name}</b><small>${t.desc}</small></span><i>→</i></button>`).join('')}</div><div class="demo-actions"><button class="secondary" id="calcClose">Terug naar alle oefenvormen</button></div></article>`;o.hidden=false;o.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>begin(b.dataset.calc));$('calcClose').onclick=()=>{o.hidden=true;menu().hidden=false}}
function begin(id){type=id;round=0;rounds=shuffle(banks[id]).slice(0,8);$('calcPicker').hidden=true;showIntro()}
function showIntro(){let o=$('calcIntro');if(!o){o=document.createElement('section');o.id='calcIntro';o.className='overlay';document.body.append(o)}const sub=type.startsWith('sub'),unlike=type.endsWith('Unlike');o.innerHTML=`<article class="demo-card"><span class="badge">KIJK EERST EVEN</span><h2>${types[type].name}</h2><p>${sub?'Bouw de eerste breuk. Neem daarna elk gevraagd stukje één voor één weg; de weggenomen stukken blijven zichtbaar.':'Bouw beide breuken apart en voeg ze pas samen wanneer de stukken dezelfde noemer hebben.'}</p><div class="calc-demo"><div class="calc-demo-scene"><div class="calc-demo-bar"><i></i><i></i><i></i><i></i></div><b>${sub?'−':'+'}</b><div class="calc-demo-bar"><i></i><i></i></div><span class="calc-demo-hand">👆🏼</span></div><b>${unlike?'Kies zelf de kleinste noemer die voor beide breuken werkt.':'De noemer blijft gelijk omdat alle stukken even groot zijn.'}</b></div><div class="demo-actions"><button class="secondary" id="calcSkip">Demo overslaan</button><button id="calcStart">Naar het spel →</button></div></article>`;o.hidden=false;$('calcSkip').onclick=$('calcStart').onclick=()=>{o.hidden=true;show()}}
function frac(n,d){return `${n}/${d}`}
function simplified(n,d){const g=gcd(n,d);return g>1?`${frac(n,d)} = ${frac(n/g,d/g)}`:frac(n,d)}
function show(){s={selected:null,left:[],right:[],removed:[],phase:'build',errors:{}};const q=rounds[round],sub=type.startsWith('sub'),unlike=type.endsWith('Unlike'),[a,d,b,e]=q;stage().innerHTML=`<article class="calc-shell"><button class="calc-back" id="calcBack">← Rekenvormen</button><div class="calc-head"><div class="eyebrow">OPDRACHT ${round+1} VAN ${rounds.length}</div><h2>${frac(a,d)} ${sub?'−':'+'} ${frac(b,e)}</h2><p>${sub?'Bouw eerst de eerste breuk. Neem daarna precies de gevraagde hoeveelheid weg.':'Bouw beide breuken eerst apart.'}</p></div><div class="calc-work"><aside class="calc-palette">${[2,3,4,5,6,8,10,12].map(x=>`<button data-pick="${x}">stuk 1/${x}</button>`).join('')}</aside><div class="calc-main"><div class="calc-builds"><section class="calc-zone"><h3>Bouw ${frac(a,d)}</h3><div class="calc-bar" id="calcLeft"></div><button class="calc-addpiece" data-add="left">＋ Leg gekozen stuk</button><button class="calc-undo" data-undo="left">↶ Laatste terug</button></section>${sub?`<section class="calc-zone"><h3>Dit moet weg: ${frac(b,e)}</h3><div class="calc-removed" id="calcRemoved"><span>Nog niets weggenomen</span></div><div class="calc-equation" id="removedEq">0/${e} weggenomen</div></section>`:`<section class="calc-zone"><h3>Bouw ${frac(b,e)}</h3><div class="calc-bar" id="calcRight"></div><button class="calc-addpiece" data-add="right">＋ Leg gekozen stuk</button><button class="calc-undo" data-undo="right">↶ Laatste terug</button></section>`}</div><div class="calc-phase" id="calcPhase"><b>Stap 1: bouw ${sub?'de eerste breuk':'beide breuken'}.</b></div></div></div><div class="calc-actions"><button class="secondary" id="calcReset">Opnieuw</button><button id="calcReady">Klaar met bouwen</button></div><div class="calc-feedback" id="calcFeedback"></div><div class="calc-progress">${types[type].name}</div></article>`;wireBuild(a,d,b,e,sub,unlike);$('calcBack').onclick=showPicker}
function pieceHtml(den,i,removable=false,removed=false){return `<button class="calc-piece${removable?' removable':''}${removed?' removed':''}" style="--den:${den}" data-piece="${i}" aria-label="stuk 1/${den}">1/${den}</button>`}
function renderBars(){ $('calcLeft').innerHTML=s.left.map((d,i)=>pieceHtml(d,i,s.phase==='remove',s.removed.includes(i))).join('');if($('calcRight'))$('calcRight').innerHTML=s.right.map((d,i)=>pieceHtml(d,i)).join('');if(s.phase==='remove')document.querySelectorAll('#calcLeft .calc-piece.removable').forEach(b=>b.onclick=()=>removePiece(+b.dataset.piece))}
function wireBuild(a,d,b,e,sub,unlike){document.querySelectorAll('[data-pick]').forEach(x=>x.onclick=()=>{s.selected=+x.dataset.pick;document.querySelectorAll('[data-pick]').forEach(y=>y.classList.toggle('selected',y===x))});document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>{if(!s.selected)return bad('Kies eerst links welk soort breukstuk je wilt leggen.');s[x.dataset.add].push(s.selected);renderBars();clearFeedback()});document.querySelectorAll('[data-undo]').forEach(x=>x.onclick=()=>{s[x.dataset.undo].pop();renderBars()});$('calcReset').onclick=show;$('calcReady').onclick=()=>checkBuild(a,d,b,e,sub,unlike);renderBars()}
function exact(arr,n,d){return arr.length===n&&arr.every(x=>x===d)}
function err(k){return s.errors[k]=(s.errors[k]||0)+1}
function bad(t){const f=$('calcFeedback');f.className='calc-feedback bad';f.textContent=t}
function good(t){const f=$('calcFeedback');f.className='calc-feedback good';f.textContent=t}
function clearFeedback(){const f=$('calcFeedback');f.className='calc-feedback';f.textContent=''}
function lockBuild(){document.querySelectorAll('[data-pick],[data-add],[data-undo]').forEach(x=>x.disabled=true)}
function checkBuild(a,d,b,e,sub,unlike){const ok=exact(s.left,a,d)&& (sub||exact(s.right,b,e));if(!ok){const n=err('build');if(n===1)bad(sub?`Bouw ${a} stukken van 1/${d}.`:`Links heb je ${a} × 1/${d} nodig en rechts ${b} × 1/${e}.`);else if(n===2){document.querySelector(`[data-pick="${d}"]`)?.classList.add('learning-highlight');if(!sub)document.querySelector(`[data-pick="${e}"]`)?.classList.add('learning-highlight');bad('De passende soorten stukken lichten op. Bouw de breuken nog zelf.')}else{document.querySelector(`[data-pick="${d}"]`)?.classList.add('learning-solution');if(!sub)document.querySelector(`[data-pick="${e}"]`)?.classList.add('learning-solution');bad('Groen toont het juiste materiaal. Let op de teller voor het aantal stukken.')}return}lockBuild();clearFeedback();if(unlike)chooseDenominator(a,d,b,e,sub);else if(sub)startRemoval(a,d,b,e,d,b);else finishAddition(a,d,b,e,d,a+b)}
function candidates(d,e){const m=lcm(d,e),list=[m,m*2,m*3].filter(x=>x<=24);return shuffle([...new Set([d,e,...list,Math.max(d,e)+1])]).slice(0,5).sort((a,b)=>a-b)}
function chooseDenominator(a,d,b,e,sub){s.phase='denom';const min=lcm(d,e),box=$('calcPhase');box.innerHTML=`<b>Stap 2: kies de kleinste noemer die voor beide breuken werkt.</b><div class="calc-denoms">${candidates(d,e).map(x=>`<button data-common="${x}">${x}</button>`).join('')}</div><div id="commonHelp"></div>`;$('calcReady').hidden=true;box.querySelectorAll('[data-common]').forEach(x=>x.onclick=()=>{const chosen=+x.dataset.common;if(chosen%d||chosen%e){const n=err('commonInvalid');if(n===1)bad(`Noemer ${chosen} werkt niet: je kunt niet beide soorten stukken er precies in verdelen.`);else if(n===2){$('commonHelp').textContent=`Zoek een getal in zowel de tafel van ${d} als de tafel van ${e}.`;bad(`Tel de sprongen: ${d}, ${d*2}, ${d*3} … en ${e}, ${e*2}, ${e*3} …`)}else{box.querySelector(`[data-common="${min}"]`)?.classList.add('learning-solution');bad('De kleinste passende noemer licht groen op. Tik hem zelf aan.')}return}if(chosen!==min){const n=err('commonLarge');if(n===1)bad(`${chosen} kan, maar het kan eenvoudiger. Zoek de kleinste noemer die voor beide breuken past.`);else{box.querySelector(`[data-common="${min}"]`)?.classList.add(n>2?'learning-solution':'learning-highlight');bad(`Zoek de eerste gemeenschappelijke sprong van ${d} en ${e}.`)}return}convert(a,d,b,e,sub,min)})}
function convert(a,d,b,e,sub,common){const leftN=a*common/d,rightN=b*common/e;s.left=Array(leftN).fill(common);s.right=Array(rightN).fill(common);clearFeedback();renderBars();document.querySelectorAll('.calc-bar').forEach(x=>x.classList.add('calc-split'));$('calcPhase').innerHTML=`<div class="calc-equation">${frac(a,d)} = ${frac(leftN,common)} &nbsp; en &nbsp; ${frac(b,e)} = ${frac(rightN,common)}</div><p>Nu hebben de stukken dezelfde noemer.</p>`;if(sub)startRemoval(a,d,b,e,common,rightN);else finishAddition(a,d,b,e,common,leftN+rightN)}
function finishAddition(a,d,b,e,common,total){s.phase='answer';$('calcReady').hidden=true;const box=$('calcPhase');box.innerHTML+=`<div class="calc-equation">${s.left.map(()=>`1/${common}`).join(' + ')} + ${s.right.map(()=>`1/${common}`).join(' + ')}</div><button class="calc-addpiece" id="mergeCalc">Voeg alle stukken samen ↓</button><div class="calc-bar" id="calcResult"></div>`;$('mergeCalc').onclick=()=>{$('calcResult').innerHTML=Array(total).fill(common).map((d,i)=>pieceHtml(d,i)).join('');good(`${frac(a,d)} + ${frac(b,e)} = ${simplified(total,common)}.`);showNext()}}
function startRemoval(a,d,b,e,common,removeCount){s.phase='remove';s.removed=[];$('calcReady').hidden=true;$('calcPhase').innerHTML=`<b>Stap ${d===e?'2':'3'}: tik ${removeCount} keer op een stuk van 1/${common}.</b><p>De weggenomen stukken blijven rechts zichtbaar.</p>`;s.removeData={a,d,b,e,common,removeCount};renderBars();updateRemoved()}
function removePiece(i){if(s.removed.includes(i))return;if(s.removed.length>=s.removeData.removeCount){bad(`Je hebt al ${frac(s.removeData.removeCount,s.removeData.common)} weggenomen.`);return}s.removed.push(i);renderBars();updateRemoved();if(s.removed.length===s.removeData.removeCount){const x=s.removeData,left=s.left.length-x.removeCount;good(`${frac(x.a,x.d)} − ${frac(x.b,x.e)} = ${simplified(left,x.common)}.`);showNext()}}
function updateRemoved(){const x=s.removeData;if(!x)return;const count=s.removed.length;$('calcRemoved').innerHTML=count?Array(count).fill(x.common).map((d,i)=>pieceHtml(d,i)).join(''):'<span>Nog niets weggenomen</span>';$('removedEq').textContent=count?`${Array(count).fill(`1/${x.common}`).join(' + ')} = ${count}/${x.common} weggenomen`:`0/${x.common} weggenomen`}
function showNext(){if($('calcNext'))return;const wrap=document.querySelector('.calc-actions'),b=document.createElement('button');b.id='calcNext';b.textContent=round===rounds.length-1?'Ronde afronden':'Volgende opdracht →';b.onclick=()=>{round++;if(round>=rounds.length)finishRound();else show()};wrap.append(b)}
function finishRound(){let o=$('calcFinish');if(!o){o=document.createElement('section');o.id='calcFinish';o.className='overlay';document.body.append(o)}o.innerHTML=`<article><div class="stars">★ ★ ★</div><h2>Mooi gerekend!</h2><p>Je bouwde, maakte gelijknamig en rekende zelf met breuken.</p><div class="end"><button id="calcAgain">Nog een ronde</button><button id="calcOther">Andere rekenvorm</button><button id="calcAll">Alle oefenvormen</button></div></article>`;o.hidden=false;$('calcAgain').onclick=()=>{o.hidden=true;begin(type)};$('calcOther').onclick=()=>{o.hidden=true;showPicker()};$('calcAll').onclick=()=>{o.hidden=true;menu().hidden=false}}
window.BreukenRekenen={open};
})();
