(()=>{
const $=id=>document.getElementById(id),stage=()=>$('stage'),menu=()=>$('menu');
const gcd=(a,b)=>b?gcd(b,a%b):a,lcm=(a,b)=>a*b/gcd(a,b),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const types={
 addSame:{icon:'➕',name:'Gelijknamig optellen',desc:'Bouw beide breuken en voeg de gelijke stukken samen.'},
 addUnlike:{icon:'🔄',name:'Ongelijknamig optellen',desc:'Kies eerst de kleinste gemeenschappelijke noemer.'},
 subSame:{icon:'➖',name:'Gelijknamig aftrekken',desc:'Neem de gevraagde stukken één voor één zichtbaar weg.'},
 subUnlike:{icon:'🧠',name:'Ongelijknamig aftrekken',desc:'Maak gelijknamig en neem daarna passende stukken weg.'}
};
const banks={
 addSame:[[1,4,2,4],[2,5,1,5],[1,6,3,6],[2,8,3,8],[1,3,1,3],[3,8,2,8],[2,6,3,6],[1,5,3,5],[2,4,1,4],[1,8,5,8]],
 addUnlike:[[1,2,1,4],[1,3,1,6],[1,2,1,3],[1,4,1,8],[2,3,1,6],[1,3,1,4],[1,4,1,6],[1,2,1,6],[2,5,1,10],[1,6,1,4]],
 subSame:[[5,8,3,8],[4,6,2,6],[3,4,1,4],[4,5,3,5],[5,6,2,6],[7,8,4,8],[2,3,1,3],[3,5,2,5],[6,8,1,8],[5,8,2,8]],
 subUnlike:[[3,4,1,2],[5,6,1,3],[7,8,1,4],[5,6,1,2],[4,6,1,3],[7,10,1,5],[5,8,1,2],[3,6,1,3],[9,12,1,4],[6,8,1,4]]
};
let type='',round=0,rounds=[],s={};
function open(){showPicker()}
function showPicker(){stage().innerHTML='';let o=$('calcPicker');if(!o){o=document.createElement('section');o.id='calcPicker';o.className='overlay';document.body.append(o)}o.innerHTML=`<article><span class="badge">BREUKEN REKENEN</span><h2>Wat wil je oefenen?</h2><p>Kies hoe je vandaag met breuken wilt rekenen.</p><div class="calc-picker">${Object.entries(types).map(([id,t])=>`<button data-calc="${id}"><span class="calc-icon">${t.icon}</span><span><b>${t.name}</b><small>${t.desc}</small></span><i>→</i></button>`).join('')}</div><div class="demo-actions"><button class="secondary" id="calcClose">Terug naar alle oefenvormen</button></div></article>`;o.hidden=false;o.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>begin(b.dataset.calc));$('calcClose').onclick=()=>{o.hidden=true;menu().hidden=false}}
function begin(id){type=id;round=0;rounds=shuffle(banks[id]).slice(0,8);$('calcPicker').hidden=true;showIntro()}
function subtractionDemo(unlike){const den=unlike?4:8,built=unlike?3:5,take=unlike?2:3,original=unlike?'3/4 − 1/2':'5/8 − 3/8',converted=unlike?'<div class="calc-convert-note">Eerst: 1/2 = 2/4</div>':'';return `<div class="calc-sub-demo">${converted}<b>${original}</b><small>Gebouwd</small><div class="calc-take-source">${Array.from({length:den},(_,i)=>`<i class="${i<built?'filled':''}${i>=built-take&&i<built?` take take${i-(built-take)+1}`:''}">1/${den}</i>`).join('')}</div><span class="calc-take-arrow">↓ neem elk stuk één voor één weg ↓</span><small>Weggenomen</small><div class="calc-take-tray">${Array.from({length:take},(_,i)=>`<i class="arrive arrive${i+1}">1/${den}</i>`).join('')}</div><strong class="calc-take-total calc-take-total-${take}">${Array.from({length:take},()=>`1/${den}`).join(' + ')} = ${take}/${den} weggenomen</strong><span class="calc-sub-hand">👆🏼</span></div>`}
function demoBar(n,d,removed=0){return `<div class="calc-demo-realbar">${Array.from({length:d},(_,i)=>`<i class="${i<n?'filled':''}${i>=n-removed&&i<n?' leaving':''}">1/${d}</i>`).join('')}</div>`}
function demoAnswer(d,value='?'){return `<span class="calc-demo-answer"><b>${value}</b><i></i><strong>${d}</strong></span>`}
function demoSteps(){if(type==='addSame')return[
 {title:'1. Bouw beide breuken',text:'Kies hetzelfde soort stuk en leg het juiste aantal in beide stroken.',body:`<div class="calc-demo-columns"><section><b>Bouw 1/4</b>${demoBar(1,4)}<button class="calc-addpiece demo-active">＋ Leg gekozen stuk</button></section><section><b>Bouw 2/4</b>${demoBar(2,4)}<button class="calc-addpiece">＋ Leg gekozen stuk</button></section></div>`},
 {title:'2. Controleer het bouwen',text:'Als beide stroken klaar zijn, tik je op dezelfde knop als in het spel.',body:`<div class="calc-demo-equation">1/4 + 2/4</div><button class="calc-demo-main demo-active">Klaar met bouwen</button>`},
 {title:'3. Vul de uitkomst in',text:'Tel de stukken. De noemer blijft gelijk. Vul zelf de teller in.',body:`<div class="calc-demo-inline"><strong>1/4 + 2/4 =</strong>${demoAnswer(4)}</div><button class="calc-demo-main demo-active">Controleer mijn antwoord</button>`}
 ];if(type==='addUnlike')return[
 {title:'1. Bouw beide oorspronkelijke breuken',text:'Bouw eerst wat er in de som staat.',body:`<div class="calc-demo-columns"><section><b>Bouw 2/3</b>${demoBar(2,3)}<button class="calc-addpiece">＋ Leg gekozen stuk</button></section><section><b>Bouw 1/6</b>${demoBar(1,6)}<button class="calc-addpiece">＋ Leg gekozen stuk</button></section></div>`},
 {title:'2. Kies een gemeenschappelijke noemer',text:'Kies de kleinste noemer die bij beide breuken past.',body:`<div class="calc-denoms"><button>3</button><button class="demo-active">6</button><button>12</button></div>`},
 {title:'3. Bouw beide breuken opnieuw',text:'Leg zelf stukken van 1/6 onder de oorspronkelijke stroken.',body:`<div class="calc-demo-columns"><section><b>2/3 = 4/6</b>${demoBar(2,3)}<span>↓ dezelfde hoeveelheid ↓</span>${demoBar(4,6)}<button class="calc-addpiece demo-active">＋ Leg 1/6</button></section><section><b>1/6 = 1/6</b>${demoBar(1,6)}<span>↓ dezelfde hoeveelheid ↓</span>${demoBar(1,6)}<button class="calc-addpiece">＋ Leg 1/6</button></section></div>`},
 {title:'4. Vul de eindbreuk in',text:'Tel alle gelijknamige stukken samen en vul zelf de teller in.',body:`<div class="calc-demo-inline"><strong>4/6 + 1/6 =</strong>${demoAnswer(6)}</div><button class="calc-demo-main demo-active">Controleer mijn antwoord</button>`}
 ];if(type==='subSame')return[
 {title:'1. Bouw de eerste breuk',text:'Bouw eerst de breuk waaruit je gaat wegnemen.',body:`<section class="calc-demo-one"><b>Bouw 5/8</b>${demoBar(5,8)}<button class="calc-addpiece demo-active">＋ Leg gekozen stuk</button></section>`},
 {title:'2. Sleep elk gevraagd stuk weg',text:'Sleep drie stukken van 1/8 één voor één naar de bak rechts.',body:`<div class="calc-demo-columns"><section><b>Sleep weg uit 5/8</b>${demoBar(5,8,3)}<span class="calc-demo-drag">→</span></section><section><b>Dit moet weg: 3/8</b>${demoBar(3,8)}<strong>1/8 + 1/8 + 1/8 = 3/8</strong></section></div>`},
 {title:'3. Vul in wat overblijft',text:'Tel de gekleurde stukken die nog links liggen en vul de teller in.',body:`<div class="calc-demo-inline"><strong>5/8 − 3/8 =</strong>${demoAnswer(8)}</div><button class="calc-demo-main demo-active">Controleer mijn antwoord</button>`}
 ];return[
 {title:'1. Bouw de eerste breuk',text:'Bouw eerst de breuk waaruit je gaat wegnemen.',body:`<section class="calc-demo-one"><b>Bouw 5/8</b>${demoBar(5,8)}<button class="calc-addpiece demo-active">＋ Leg gekozen stuk</button></section>`},
 {title:'2. Bouw wat weg moet met achtsten',text:'Leg zelf stukken van 1/8 onder 1/2 tot beide stroken even lang zijn.',body:`<div class="calc-demo-remove-build"><section><b>1/2</b>${demoBar(1,2)}</section><span>↓ dezelfde hoeveelheid ↓</span><section><b>1/2 = 4/8</b>${demoBar(4,8)}<button class="calc-addpiece demo-active">＋ Leg 1/8</button></section></div>`},
 {title:'3. Sleep de vier stukken één voor één weg',text:'Boven de rechterbak blijft staan hoeveel je moet wegnemen.',body:`<div class="calc-demo-columns"><section><b>Sleep weg uit 5/8</b>${demoBar(5,8,4)}<span class="calc-demo-drag">→</span></section><section><b>Dit moet weg: 1/2 = 4/8</b>${demoBar(4,8)}<strong>4/8 weggenomen</strong></section></div>`},
 {title:'4. Vul in wat overblijft',text:'Tel wat links overblijft en voer zelf de teller in.',body:`<div class="calc-demo-inline"><strong>5/8 − 4/8 =</strong>${demoAnswer(8)}</div><button class="calc-demo-main demo-active">Controleer mijn antwoord</button>`}
 ]}
function showIntro(){let o=$('calcIntro');if(!o){o=document.createElement('section');o.id='calcIntro';o.className='overlay';document.body.append(o)}const steps=demoSteps();let current=0;const render=()=>{const step=steps[current];o.innerHTML=`<article class="demo-card calc-walkthrough"><span class="badge">ZO WERKT HET SPEL</span><h2>${types[type].name}</h2><div class="calc-demo-count">Stap ${current+1} van ${steps.length}</div><h3>${step.title}</h3><p>${step.text}</p><div class="calc-walkthrough-stage">${step.body}<span class="calc-walkthrough-hand">👆🏼</span></div><div class="demo-actions"><button class="secondary" id="calcPrev" ${current===0?'disabled':''}>← Vorige stap</button>${current<steps.length-1?'<button id="calcNextDemo">Volgende stap →</button>':'<button id="calcStart">Naar het spel →</button>'}</div><button class="calc-demo-skip" id="calcSkip">Demo overslaan</button></article>`;o.hidden=false;$('calcPrev').onclick=()=>{if(current>0){current--;render()}};if($('calcNextDemo'))$('calcNextDemo').onclick=()=>{current++;render()};if($('calcStart'))$('calcStart').onclick=()=>{o.hidden=true;show()};$('calcSkip').onclick=()=>{o.hidden=true;show()}};render()}
function frac(n,d){return `${n}/${d}`}
function simplified(n,d){const g=gcd(n,d);return g>1?`${frac(n,d)} = ${frac(n/g,d/g)}`:frac(n,d)}
function show(){s={selected:null,left:[],right:[],removed:[],phase:'build',errors:{}};const q=rounds[round],sub=type.startsWith('sub'),unlike=type.endsWith('Unlike'),[a,d,b,e]=q;stage().innerHTML=`<article class="calc-shell"><button class="calc-back" id="calcBack">← Rekenvormen</button><div class="calc-head"><div class="eyebrow">OPDRACHT ${round+1} VAN ${rounds.length}</div><h2>${frac(a,d)} ${sub?'−':'+'} ${frac(b,e)}</h2><p>${sub?'Bouw eerst de eerste breuk. Neem daarna precies de gevraagde hoeveelheid weg.':'Bouw beide breuken eerst apart.'}</p></div><div class="calc-work"><aside class="calc-palette">${[2,3,4,5,6,8,10,12].map(x=>`<button data-pick="${x}">stuk 1/${x}</button>`).join('')}</aside><div class="calc-main"><div class="calc-builds"><section class="calc-zone"><h3>Bouw ${frac(a,d)}</h3><div class="calc-bar" id="calcLeft"></div><button class="calc-addpiece" data-add="left">＋ Leg gekozen stuk</button><button class="calc-undo" data-undo="left">↶ Laatste terug</button></section>${sub?`<section class="calc-zone"><h3>Dit moet weg: ${frac(b,e)}</h3><div class="calc-removed" id="calcRemoved"><span>Nog niets weggenomen</span></div><div class="calc-equation" id="removedEq">0/${e} weggenomen</div></section>`:`<section class="calc-zone"><h3>Bouw ${frac(b,e)}</h3><div class="calc-bar" id="calcRight"></div><button class="calc-addpiece" data-add="right">＋ Leg gekozen stuk</button><button class="calc-undo" data-undo="right">↶ Laatste terug</button></section>`}</div><div class="calc-phase calc-build-instruction" id="calcPhase"><b><span>1</span> Kies links een breukstuk.</b><b><span>2</span> Tik onder de juiste strook op <em>Leg gekozen stuk</em>.</b></div></div></div><div class="calc-actions"><button class="secondary" id="calcReset">Opnieuw</button><button id="calcReady">Klaar met bouwen</button></div><div class="calc-feedback" id="calcFeedback"></div><div class="calc-progress">${types[type].name}</div></article>`;wireBuild(a,d,b,e,sub,unlike);$('calcBack').onclick=showPicker}
const denominatorColors={2:'#ef7eae',3:'#f2a65a',4:'#ffd34f',5:'#80cf8f',6:'#55bad8',8:'#b58ae2',10:'#5fc7bd',12:'#86a9e8'};
function pieceHtml(den,i,removable=false,removed=false){return `<button class="calc-piece${removable?' removable':''}${removed?' removed':''}" style="--den:${den};--piece:${denominatorColors[den]||'#55bad8'}" data-piece="${i}" aria-label="${removable&&!removed?'Sleep ':''}stuk 1/${den}${removable&&!removed?' naar de wegneembak':''}"><span>1/${den}</span>${removable&&!removed?'<b class="remove-mark">↘</b>':''}</button>`}
function modelBar(n,d,label){return `<div class="calc-old-model"><b>${label}</b><div class="calc-bar">${Array.from({length:n},(_,i)=>pieceHtml(d,i)).join('')}</div></div>`}
function renderBars(){ $('calcLeft').innerHTML=s.left.map((d,i)=>pieceHtml(d,i,s.phase==='remove',s.removed.includes(i))).join('');if($('calcRight'))$('calcRight').innerHTML=s.right.map((d,i)=>pieceHtml(d,i)).join('');if(s.phase==='remove')document.querySelectorAll('#calcLeft .calc-piece.removable:not(.removed)').forEach(b=>enablePieceDrag(b,+b.dataset.piece))}
function wireBuild(a,d,b,e,sub,unlike){if(sub)$('calcReady').hidden=true;document.querySelectorAll('[data-pick]').forEach(x=>x.onclick=()=>{s.selected=+x.dataset.pick;document.querySelectorAll('[data-pick]').forEach(y=>y.classList.toggle('selected',y===x))});document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>{if(!s.selected)return bad('Kies eerst links welk soort breukstuk je wilt leggen.');s[x.dataset.add].push(s.selected);renderBars();clearFeedback();if(sub&&exact(s.left,a,d)){lockBuild();setTimeout(()=>unlike?chooseRemovalAmount(a,d,b,e):startRemoval(a,d,b,e,d,b),250)}});document.querySelectorAll('[data-undo]').forEach(x=>x.onclick=()=>{s[x.dataset.undo].pop();renderBars()});$('calcReset').onclick=show;$('calcReady').onclick=()=>checkBuild(a,d,b,e,sub,unlike);renderBars()}
function exact(arr,n,d){return arr.length===n&&arr.every(x=>x===d)}
function err(k){return s.errors[k]=(s.errors[k]||0)+1}
function bad(t){const f=$('calcFeedback');f.className='calc-feedback bad';f.textContent=t}
function good(t){const f=$('calcFeedback');f.className='calc-feedback good';f.textContent=t}
function clearFeedback(){const f=$('calcFeedback');f.className='calc-feedback';f.textContent=''}
function lockBuild(){document.querySelector('.calc-palette').hidden=true;document.querySelector('.calc-work').classList.add('calc-locked');document.querySelectorAll('[data-add],[data-undo]').forEach(x=>x.hidden=true)}
function checkBuild(a,d,b,e,sub,unlike){const ok=exact(s.left,a,d)&& (sub||exact(s.right,b,e));if(!ok){const n=err('build');if(n===1)bad(sub?`Bouw ${a} stukken van 1/${d}.`:`Links heb je ${a} × 1/${d} nodig en rechts ${b} × 1/${e}.`);else if(n===2){document.querySelector(`[data-pick="${d}"]`)?.classList.add('learning-highlight');if(!sub)document.querySelector(`[data-pick="${e}"]`)?.classList.add('learning-highlight');bad('De passende soorten stukken lichten op. Bouw de breuken nog zelf.')}else{document.querySelector(`[data-pick="${d}"]`)?.classList.add('learning-solution');if(!sub)document.querySelector(`[data-pick="${e}"]`)?.classList.add('learning-solution');bad('Groen toont het juiste materiaal. Let op de teller voor het aantal stukken.')}return}lockBuild();clearFeedback();if(unlike)chooseDenominator(a,d,b,e,sub);else if(sub)startRemoval(a,d,b,e,d,b);else finishAddition(a,d,b,e,d,a+b)}
function candidates(d,e){const m=lcm(d,e),list=[m,m*2,m*3].filter(x=>x<=24);return shuffle([...new Set([d,e,...list,Math.max(d,e)+1])]).slice(0,5).sort((a,b)=>a-b)}
function chooseDenominator(a,d,b,e,sub){s.phase='denom';const min=lcm(d,e),box=$('calcPhase');box.innerHTML=`<b>Kies de kleinste noemer die voor beide breuken werkt.</b><div class="calc-denoms">${candidates(d,e).map(x=>`<button data-common="${x}">${x}</button>`).join('')}</div><div id="commonHelp"></div>`;$('calcReady').hidden=true;box.querySelectorAll('[data-common]').forEach(x=>x.onclick=()=>{const chosen=+x.dataset.common;if(chosen%d||chosen%e){const n=err('commonInvalid');if(n===1)bad(`Noemer ${chosen} past niet bij beide breuken.`);else if(n===2){$('commonHelp').textContent=`Zoek een getal in zowel de tafel van ${d} als de tafel van ${e}.`;bad(`Tel de sprongen van ${d} en ${e}. Waar kom je hetzelfde getal tegen?`)}else{box.querySelector(`[data-common="${min}"]`)?.classList.add('learning-solution');bad('De kleinste passende noemer licht groen op. Tik hem zelf aan.')}return}if(chosen!==min){const n=err('commonLarge');if(n===1)bad(`${chosen} kan, maar het kan met een kleinere noemer.`);else{box.querySelector(`[data-common="${min}"]`)?.classList.add(n>2?'learning-solution':'learning-highlight');bad('Zoek de eerste gemeenschappelijke sprong.')}return}beginConversion(a,d,b,e,min)})}
function beginConversion(a,d,b,e,common){const leftN=a*common/d,rightN=b*common/e,builds=document.querySelector('.calc-builds');s.phase='convert';s.convertLeft=[];s.convertRight=[];builds.innerHTML=`<section class="calc-zone calc-convert-card"><h3>Maak ${frac(a,d)} met stukken van 1/${common}</h3>${modelBar(a,d,frac(a,d))}<span class="calc-convert-arrow">↓ dezelfde hoeveelheid ↓</span><div class="calc-bar calc-converted-bar" id="convertedLeft"></div><div><button class="calc-addpiece" data-convert-add="left">＋ Leg 1/${common}</button><button class="calc-undo" data-convert-undo="left">↶ Stuk terug</button></div></section><section class="calc-zone calc-convert-card"><h3>Maak ${frac(b,e)} met stukken van 1/${common}</h3>${modelBar(b,e,frac(b,e))}<span class="calc-convert-arrow">↓ dezelfde hoeveelheid ↓</span><div class="calc-bar calc-converted-bar" id="convertedRight"></div><div><button class="calc-addpiece" data-convert-add="right">＋ Leg 1/${common}</button><button class="calc-undo" data-convert-undo="right">↶ Stuk terug</button></div></section>`;$('calcPhase').innerHTML=`<b>Leg zelf de stukken van 1/${common} onder elke oorspronkelijke breuk.</b><button class="calc-addpiece" id="checkConversions">Klaar met gelijknamig maken</button>`;const draw=()=>{$('convertedLeft').innerHTML=s.convertLeft.map((_,i)=>pieceHtml(common,i)).join('');$('convertedRight').innerHTML=s.convertRight.map((_,i)=>pieceHtml(common,i)).join('')};document.querySelectorAll('[data-convert-add]').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.convertAdd==='left'?'convertLeft':'convertRight';if(s[key].length<common)s[key].push(common);draw();clearFeedback()});document.querySelectorAll('[data-convert-undo]').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.convertUndo==='left'?'convertLeft':'convertRight';s[key].pop();draw();clearFeedback()});$('checkConversions').onclick=()=>{const l=s.convertLeft.length,r=s.convertRight.length;if(l!==leftN||r!==rightN){const n=err('conversion');if(n===1)bad(`De nieuwe stroken moeten even lang zijn als ${frac(a,d)} en ${frac(b,e)} erboven.`);else if(n===2)bad(`Voor ${frac(a,d)}: elk stuk van 1/${d} wordt ${common/d} stukken van 1/${common}.`);else bad(`Tel opnieuw: links heb je ${leftN} stukken nodig en rechts ${rightN}. Leg ze nog zelf.`);return}s.left=[...s.convertLeft];s.right=[...s.convertRight];const headings=builds.querySelectorAll('h3');headings[0].textContent=`${frac(a,d)} = ${frac(leftN,common)}`;headings[1].textContent=`${frac(b,e)} = ${frac(rightN,common)}`;document.querySelectorAll('[data-convert-add],[data-convert-undo]').forEach(x=>x.hidden=true);clearFeedback();good('Juist: de hoeveelheden zijn gelijk gebleven.');askConvertedAdditionAnswer(a,d,b,e,common,leftN,rightN)}}
function askConvertedAdditionAnswer(a,d,b,e,common,leftN,rightN){const total=leftN+rightN,box=$('calcPhase');box.innerHTML=`<div class="calc-add-answer-row"><div><b>Reken nu zelf uit.</b><small>Tel alle gelijknamige stukken.</small></div><div class="calc-inline-sum"><strong>${frac(leftN,common)} + ${frac(rightN,common)} =</strong><div class="calc-answer-fraction"><input id="calcAddNumerator" type="number" min="0" max="${common*2}" inputmode="numeric" aria-label="Teller van de uitkomst"><span></span><strong>${common}</strong></div></div><button class="calc-addpiece" id="checkAddAnswer">Controleer</button><div class="calc-add-local-result" id="convertedFinal"></div></div>`;const input=$('calcAddNumerator'),check=()=>{if(+input.value!==total){const n=err('addAnswer');if(n===1)bad(`Tel de ${leftN} en ${rightN} stukken van 1/${common} samen.`);else if(n===2)bad(`${leftN} + ${rightN} = ? De noemer blijft ${common}.`);else{input.value=total;input.classList.add('learning-solution');bad('De juiste teller staat klaar. Controleer hem met beide stroken.')}return}const whole=total===common?' = 1 geheel':'',canSimplify=total!==common&&gcd(total,common)>1;$('convertedFinal').innerHTML=`<strong>✓ ${frac(a,d)} + ${frac(b,e)} = ${frac(leftN,common)} + ${frac(rightN,common)} = ${frac(total,common)}${whole}</strong>${canSimplify?`<small>Tip: ${frac(total,common)} kan nog vereenvoudigd worden.</small>`:''}`;input.disabled=true;$('checkAddAnswer').disabled=true;clearFeedback();showNext()};$('checkAddAnswer').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}}
function finishAddition(a,d,b,e,common,total){s.phase='answer';$('calcReady').hidden=true;const box=$('calcPhase'),leftN=a*common/d,rightN=b*common/e;box.innerHTML=`<b>Voeg de twee gebouwde stroken samen.</b><button class="calc-addpiece" id="mergeCalc">Voeg samen ↓</button><div class="calc-bar calc-result-bar" id="calcResult"></div><div id="additionAnswer"></div>`;$('mergeCalc').onclick=()=>{$('calcResult').innerHTML=Array(total).fill(common).map((den,i)=>pieceHtml(den,i)).join('');$('mergeCalc').hidden=true;askAdditionAnswer(a,d,b,e,common,total,leftN,rightN)}}
function askAdditionAnswer(a,d,b,e,common,total,leftN,rightN){const box=$('additionAnswer');box.innerHTML=`<div class="calc-add-answer-row"><div><b>Welke breuk heb je nu?</b><small>Tel de gekleurde stukken.</small></div><div class="calc-answer-fraction"><input id="calcAddNumerator" type="number" min="0" max="${common*2}" inputmode="numeric" aria-label="Teller van de uitkomst"><span></span><strong>${common}</strong></div><button class="calc-addpiece" id="checkAddAnswer">Controleer</button><div class="calc-add-local-result" id="addLocalResult"></div></div>`;const input=$('calcAddNumerator'),check=()=>{if(+input.value!==total){const n=err('addAnswer');if(n===1)bad('Tel alle gekleurde stukken in de samengevoegde strook.');else if(n===2)bad(`Je voegde ${leftN} stukken en ${rightN} stukken van 1/${common} samen.`);else{input.value=total;input.classList.add('learning-solution');bad('De juiste teller staat klaar. Controleer hem met de strook.')}return}const whole=total===common?' = 1 geheel':'',canSimplify=total!==common&&gcd(total,common)>1;$('addLocalResult').innerHTML=`<strong>✓ ${frac(a,d)} + ${frac(b,e)} = ${frac(total,common)}${whole}</strong>${canSimplify?`<small>Tip: ${frac(total,common)} kan nog vereenvoudigd worden.</small>`:''}`;input.disabled=true;$('checkAddAnswer').disabled=true;clearFeedback();showNext()};$('checkAddAnswer').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}}
function chooseRemovalAmount(a,d,b,e){const needed=b*d/e,box=$('calcPhase');s.removeBuild=[];box.innerHTML=`<b>Bouw ${frac(b,e)} met stukken van 1/${d}</b><p>Leg stukken tot de onderste strook precies even lang is als ${frac(b,e)}.</p><div class="calc-remove-convert"><section><strong>${frac(b,e)}</strong>${modelBar(b,e,frac(b,e))}</section><span>↓ dezelfde hoeveelheid ↓</span><section><strong id="removeBuildLabel">?/${d}</strong><div class="calc-bar" id="removeBuildBar"></div><div><button class="calc-addpiece" id="addRemovePiece">＋ Leg 1/${d}</button><button class="calc-undo" id="undoRemovePiece">↶ Stuk terug</button></div></section></div><button class="calc-addpiece" id="checkRemoveBuild">Klaar met gelijknamig maken</button>`;const draw=()=>{$('removeBuildBar').innerHTML=s.removeBuild.map((_,i)=>pieceHtml(d,i)).join('');$('removeBuildLabel').textContent=`${s.removeBuild.length}/${d}`};$('addRemovePiece').onclick=()=>{if(s.removeBuild.length<d)s.removeBuild.push(d);draw();clearFeedback()};$('undoRemovePiece').onclick=()=>{s.removeBuild.pop();draw();clearFeedback()};$('checkRemoveBuild').onclick=()=>{if(s.removeBuild.length!==needed){const n=err('removeEquivalent');if(n===1)bad(`De onderste strook moet precies even lang zijn als ${frac(b,e)} erboven.`);else if(n===2)bad(`Elk stuk van 1/${e} wordt ${d/e} kleinere stukken van 1/${d}.`);else bad(`Je hebt ${needed} stukken van 1/${d} nodig. Leg ze nog zelf.`);return}s.equalizedText=`${frac(b,e)} = ${frac(needed,d)}`;clearFeedback();startRemoval(a,d,b,e,d,needed)}}
function startRemoval(a,d,b,e,common,removeCount){s.phase='remove';s.removed=[];$('calcReady').hidden=true;$('calcPhase').innerHTML=`<b>Sleep ${removeCount} stuk${removeCount===1?'':'ken'} van 1/${common} naar de wegneembak.</b><p>De stukken blijven rechts liggen, zodat je ziet hoeveel je samen hebt weggenomen.</p>`;s.removeData={a,d,b,e,common,removeCount};const zones=document.querySelectorAll('.calc-zone');zones[0].querySelector('h3').textContent=`Sleep weg uit ${frac(a,d)}`;zones[1].querySelector('h3').textContent=s.equalizedText?`Dit moet weg: ${s.equalizedText}`:`Dit moet weg: ${frac(b,e)}`;let hint=document.createElement('div');hint.className='calc-remove-hint';hint.innerHTML=`<span>→</span><b>Sleep een gekleurd stuk naar de wegneembak rechts</b>`;zones[0].append(hint);renderBars();updateRemoved()}
function enablePieceDrag(button,index){button.onpointerdown=event=>{event.preventDefault();button.setPointerCapture(event.pointerId);const ghost=button.cloneNode(true);ghost.className='calc-piece drag-ghost';document.body.append(ghost);const move=e=>{ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`};move(event);button.onpointermove=move;button.onpointerup=e=>{button.onpointermove=null;button.onpointerup=null;ghost.remove();const r=$('calcRemoved').getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)removePiece(index);else bad('Sleep het stuk helemaal tot in de wegneembak rechts.')}}}
function removePiece(i){if(s.removed.includes(i))return;if(s.removed.length>=s.removeData.removeCount){bad(`Je hebt al ${frac(s.removeData.removeCount,s.removeData.common)} weggenomen.`);return}s.removed.push(i);renderBars();updateRemoved();if(s.removed.length===s.removeData.removeCount)askSubtractionAnswer()}
function askSubtractionAnswer(){const x=s.removeData,left=s.left.length-x.removeCount,leftStart=x.a*x.common/x.d,box=$('calcPhase'),zone=$('calcLeft').closest('.calc-zone');zone.querySelector('.calc-remove-hint')?.remove();box.hidden=true;let answer=document.createElement('div');answer.className='calc-sub-answer';answer.innerHTML=`<div><b>Wat blijft er over?</b><small>Tel de gekleurde stukken die nog links liggen.</small></div><div class="calc-answer-fraction"><input id="calcAnswerNumerator" type="number" min="0" max="${x.common}" inputmode="numeric" aria-label="Teller van het antwoord"><span></span><strong>${x.common}</strong></div><button class="calc-addpiece" id="checkSubAnswer">Controleer</button><div class="calc-sub-local-result" id="subLocalResult"></div>`;zone.append(answer);const input=$('calcAnswerNumerator');input.focus();const check=()=>{if(+input.value!==left){const n=err('subAnswer');if(n===1)bad('Tel alleen de stukken die nog links liggen. De stukken in de wegneembak zijn eraf.');else if(n===2)bad(`Er waren ${leftStart} stukken van 1/${x.common}. Je nam er ${x.removeCount} weg. Hoeveel blijven er over?`);else{input.value=left;input.classList.add('learning-solution');bad('De juiste teller staat nu klaar. Kijk nog eens naar de strook en controleer hem.')}return}const chain=x.d===x.e?`${frac(x.a,x.d)} − ${frac(x.b,x.e)} = ${frac(left,x.common)}`:`${frac(x.a,x.d)} − ${frac(x.b,x.e)} = ${frac(leftStart,x.common)} − ${frac(x.removeCount,x.common)} = ${frac(left,x.common)}`,canSimplify=left>0&&gcd(left,x.common)>1;$('subLocalResult').innerHTML=`<strong>✓ ${chain}</strong>${canSimplify?`<small>Tip: ${frac(left,x.common)} kan nog vereenvoudigd worden door teller en noemer door hetzelfde getal te delen.</small>`:''}`;input.disabled=true;$('checkSubAnswer').disabled=true;clearFeedback();showNext()};$('checkSubAnswer').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}}
function updateRemoved(){const x=s.removeData;if(!x)return;const count=s.removed.length;$('calcRemoved').innerHTML=count?s.removed.map(i=>pieceHtml(x.common,i)).join(''):'<span>Nog niets weggenomen</span>';$('removedEq').textContent=count?`${Array(count).fill(`1/${x.common}`).join(' + ')} = ${count}/${x.common} weggenomen`:`0/${x.common} weggenomen`}
function showNext(){if($('calcNext'))return;const wrap=document.querySelector('.calc-actions'),b=document.createElement('button');b.id='calcNext';b.textContent=round===rounds.length-1?'Ronde afronden':'Volgende opdracht →';b.onclick=()=>{round++;if(round>=rounds.length)finishRound();else show()};wrap.append(b)}
function finishRound(){let o=$('calcFinish');if(!o){o=document.createElement('section');o.id='calcFinish';o.className='overlay';document.body.append(o)}o.innerHTML=`<article><div class="stars">★ ★ ★</div><h2>Mooi gerekend!</h2><p>Je bouwde, maakte gelijknamig en rekende zelf met breuken.</p><div class="end"><button id="calcAgain">Nog een ronde</button><button id="calcOther">Andere rekenvorm</button><button id="calcAll">Alle oefenvormen</button></div></article>`;o.hidden=false;$('calcAgain').onclick=()=>{o.hidden=true;begin(type)};$('calcOther').onclick=()=>{o.hidden=true;showPicker()};$('calcAll').onclick=()=>{o.hidden=true;menu().hidden=false}}
window.BreukenRekenen={open};
})();
