(()=>{
  const canvas=document.getElementById('foodCanvas'),ctx=canvas.getContext('2d');
  const foods={pizza:load('assets/pizza.png'),taart:load('assets/taart.png'),chocolade:load('assets/chocolade.png')};
  const rounds=[
    {food:'pizza',num:1,den:4},{food:'taart',num:3,den:4},{food:'chocolade',num:5,den:12},{food:'pizza',num:2,den:3},
    {food:'taart',num:5,den:6},{food:'chocolade',num:3,den:4},{food:'pizza',num:3,den:8},{food:'taart',num:2,den:5}
  ];
  let index=0,selected=new Set(),score=0,locked=true,W=600,H=600,foodRect={x:70,y:70,w:460,h:460};
  function load(src){const image=new Image();image.src=src;image.onload=draw;return image}
  function round(){return rounds[index]}
  function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();W=Math.max(360,r.width||600);H=Math.max(360,r.height||600);canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);ctx.setTransform(d,0,0,d,0,0);const size=Math.min(W,H)*.82;foodRect={x:(W-size)/2,y:(H-size)/2,w:size,h:size};draw()}
  addEventListener('resize',resize);setTimeout(resize,0);
  function draw(){ctx.clearRect(0,0,W,H);const r=round(),img=foods[r.food];if(!img.complete)return;if(r.food==='chocolade')drawChocolate(img,r);else drawRoundFood(img,r)}
  function drawRoundFood(img,r){const {x,y,w,h}=foodRect;ctx.save();ctx.beginPath();ctx.arc(x+w/2,y+h/2,w/2,0,Math.PI*2);ctx.clip();ctx.drawImage(img,x,y,w,h);for(const part of selected){ctx.beginPath();ctx.moveTo(x+w/2,y+h/2);ctx.arc(x+w/2,y+h/2,w/2,-Math.PI/2+part*2*Math.PI/r.den,-Math.PI/2+(part+1)*2*Math.PI/r.den);ctx.closePath();ctx.fillStyle='#43d7f070';ctx.fill()}ctx.restore();ctx.strokeStyle='#fff';ctx.lineWidth=5;for(let i=0;i<r.den;i++){const a=-Math.PI/2+i*2*Math.PI/r.den;ctx.beginPath();ctx.moveTo(x+w/2,y+h/2);ctx.lineTo(x+w/2+Math.cos(a)*w/2,y+h/2+Math.sin(a)*h/2);ctx.stroke()}ctx.beginPath();ctx.arc(x+w/2,y+h/2,w/2,0,Math.PI*2);ctx.strokeStyle='#173f6255';ctx.lineWidth=3;ctx.stroke()}
  function chocolateGrid(den){if(den===12)return{cols:4,rows:3};if(den===6)return{cols:3,rows:2};if(den===4)return{cols:2,rows:2};return{cols:3,rows:1}}
  function drawChocolate(img,r){const grid=chocolateGrid(r.den),maxW=W*.86,maxH=H*.62,ratio=img.naturalWidth/img.naturalHeight;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}const x=(W-w)/2,y=(H-h)/2;foodRect={x,y,w,h};ctx.drawImage(img,x,y,w,h);const cw=w/grid.cols,ch=h/grid.rows;for(const part of selected){const col=part%grid.cols,row=Math.floor(part/grid.cols);ctx.fillStyle='#43d7f070';ctx.fillRect(x+col*cw,y+row*ch,cw,ch)}ctx.strokeStyle='#fff';ctx.lineWidth=4;for(let c=0;c<=grid.cols;c++){ctx.beginPath();ctx.moveTo(x+c*cw,y);ctx.lineTo(x+c*cw,y+h);ctx.stroke()}for(let row=0;row<=grid.rows;row++){ctx.beginPath();ctx.moveTo(x,y+row*ch);ctx.lineTo(x+w,y+row*ch);ctx.stroke()}}
  function hitPart(px,py){const r=round(),f=foodRect;if(px<f.x||px>f.x+f.w||py<f.y||py>f.y+f.h)return-1;if(r.food==='chocolade'){const g=chocolateGrid(r.den),col=Math.min(g.cols-1,Math.floor((px-f.x)/(f.w/g.cols))),row=Math.min(g.rows-1,Math.floor((py-f.y)/(f.h/g.rows)));return row*g.cols+col}const dx=px-(f.x+f.w/2),dy=py-(f.y+f.h/2);if(Math.hypot(dx,dy)>f.w/2)return-1;let angle=Math.atan2(dy,dx)+Math.PI/2;if(angle<0)angle+=Math.PI*2;return Math.floor(angle/(Math.PI*2/r.den))}
  canvas.addEventListener('pointerdown',e=>{if(locked)return;const b=canvas.getBoundingClientRect(),part=hitPart((e.clientX-b.left)*W/b.width,(e.clientY-b.top)*H/b.height);if(part<0)return;selected.has(part)?selected.delete(part):selected.add(part);updateSelection();draw()});
  function updateSelection(){document.getElementById('selectionText').textContent=`Je koos ${selected.size} van de ${round().den} delen.`}
  function showRound(){locked=false;selected.clear();const r=round();document.getElementById('roundText').textContent=`Opdracht ${index+1} van ${rounds.length}`;document.getElementById('scoreText').textContent=`★ ${score}`;document.getElementById('foodLabel').textContent=r.food.toUpperCase();document.getElementById('fractionText').textContent=`${r.num}/${r.den}`;document.getElementById('helperText').textContent=`Verdeel het geheel in ${r.den} gelijke delen en kies er ${r.num}.`;document.getElementById('feedback').className='feedback';document.getElementById('feedback').textContent='';updateSelection();draw()}
  document.getElementById('clearButton').onclick=()=>{if(locked)return;selected.clear();updateSelection();draw()};
  document.getElementById('checkButton').onclick=()=>{if(locked)return;const r=round(),feedback=document.getElementById('feedback');if(selected.size!==r.num){feedback.className='feedback bad';feedback.textContent=selected.size<r.num?`Nog niet: je hebt ${selected.size} delen gekozen. Kies er ${r.num}.`:`Dat zijn te veel delen. Voor ${r.num}/${r.den} kies je er ${r.num}.`;return}locked=true;score++;feedback.className='feedback good';feedback.textContent=`Juist! ${r.num} van de ${r.den} gelijke delen is ${r.num}/${r.den}.`;setTimeout(()=>{index++;if(index>=rounds.length){document.getElementById('completeText').textContent=`Je maakte ${score} van de ${rounds.length} bestellingen juist.`;document.getElementById('complete').hidden=false}else showRound()},1000)};
  document.getElementById('startButton').onclick=()=>{document.getElementById('intro').hidden=true;index=0;score=0;showRound()};
  document.getElementById('againButton').onclick=()=>{document.getElementById('complete').hidden=true;index=0;score=0;showRound()};
})();
