(()=>{
const stage=$('stage'),menu=$('menu'),done=$('done'),feedback=()=>$('feedback');
const imgs={pizza:img('assets/pizza.png'),taart:img('assets/taart.png'),chocolade:img('assets/chocolade.png')};
const modes=[
 {id:'build',icon:'🍕',name:'Bouw de breuk',desc:'Leg zelf de juiste stukken en klik daarna op Klaar.'},
 {id:'whole',icon:'🧩',name:'Maak één geheel',desc:'Vul aan tot een volledige pizza, taart of reep.'},
 {id:'add',icon:'➕',name:'Breuken samenvoegen',desc:'Voeg gelijknamige breuken visueel samen.'},
 {id:'equal',icon:'🔎',name:'Gelijkwaardige breuken',desc:'Herken dezelfde hoeveelheid in andere vormen.'},
 {id:'compare',icon:'⚖️',name:'Breuken vergelijken',desc:'Vergelijk stroken en kies <, > of =.'},
 {id:'cup',icon:'🥛',name:'Recepten met 1 liter',desc:'Ontdek hoeveel gelijke breukmaatjes samen een hoeveelheid vormen.'},
 {id:'line',icon:'📍',name:'Breuken op de getallenlijn',desc:'Plaats en lees breuken op getallenlijnen tot 3.'},
 {id:'mixed',icon:'🍕',name:'Gemengde getallen bouwen',desc:'Bouw gehelen en breukdelen en ontdek de onechte breuk.'}
];
let mode='build',round=0,score=0,state={},activeRounds=[],practice=false,demoRun=0;
const rounds={
 build:[[3,4,'pizza'],[2,3,'taart'],[3,5,'pizza'],[5,8,'taart'],[1,2,'pizza'],[4,5,'taart'],[5,6,'pizza'],[3,8,'taart'],[2,5,'pizza'],[7,8,'taart'],[1,3,'pizza'],[4,6,'taart']],
 whole:[[3,4,'pizza'],[4,6,'taart'],[3,5,'pizza'],[5,8,'taart'],[1,2,'pizza'],[2,3,'taart'],[4,5,'pizza'],[3,8,'taart'],[5,6,'pizza'],[1,4,'taart'],[2,5,'pizza'],[7,8,'taart']],
 add:[[1,4,2,4],[2,5,3,5],[1,6,3,6],[1,4,3,4],[2,6,3,6],[1,5,2,5],[3,8,2,8],[1,3,1,3],[2,4,1,4],[4,8,3,8],[2,5,2,5],[1,6,4,6]],
 equal:[[1,2],[2,3],[3,4],[2,5],[1,3],[3,5],[5,6],[3,8],[4,5],[1,4],[2,6],[4,8]],
 compare:[[2,3,3,4],[3,5,1,2],[4,6,2,3],[5,8,3,4],[1,2,2,4],[3,4,4,5],[2,5,3,8],[5,6,7,8],[1,3,2,5],[3,8,1,2],[4,5,5,6],[2,4,3,6]],
 cup:[[1,1,2],[1,1,4],[1,2,4],[1,2,8],[3,4,4],[3,4,8],[1,1,8],[1,2,2],[1,4,4],[1,4,8],[3,4,2],[1,1,2]],
 line:[[3,4,1],[1,2,1],[5,4,2],[3,2,2],[7,4,2],[5,3,2],[9,4,3],[7,3,3],[11,4,3],[5,2,3],[4,3,2],[8,3,3]],
 mixed:[[1,1,2],[1,3,4],[2,1,2],[1,2,3],[2,3,4],[1,4,5],[2,2,3],[1,5,6],[2,1,4],[1,3,5],[2,5,6],[1,7,8]]
};
function $(id){return document.getElementById(id)}function img(src){const i=new Image;i.onload=()=>{if(!menu||menu.hidden)show()};i.src=src;return i}
function menuButtons(){return modes.map(m=>`<button data-mode="${m.id}"><b>${m.icon} ${m.name}</b><span>${m.desc}</span></button>`).join('')}
$('modeGrid').innerHTML=menuButtons();$('quick').innerHTML=modes.map(m=>`<button data-mode="${m.id}">${m.icon} ${m.name}</button>`).join('');
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('studioMenu').onclick=()=>menu.hidden=false;$('other').onclick=()=>{done.hidden=true;menu.hidden=false};$('again').onclick=()=>start(mode);
function shuffled(list){const copy=list.map(x=>[...x]);for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function start(id){mode=id;round=0;score=0;practice=false;activeRounds=shuffled(rounds[id]).slice(0,10);menu.hidden=true;done.hidden=true;showDemo(id)}
const demos={
 build:{title:'Zo bouw je een breuk',text:'Kies links het juiste soort stuk. Tik daarna evenveel keer op + als de teller aangeeft.',visual:'<div class="demo-parts"><span>1/4</span><span>＋</span><span>1/4</span><span>＋</span><span>1/4</span><b>＝ 3/4</b></div>'},
 whole:{title:'Zo maak je één geheel',text:'Kijk wat er al ligt. Kies links stukken die de lege plaats precies opvullen.',visual:'<div class="demo-parts"><span>3/4</span><span>＋</span><span>1/4</span><b>＝ 1 geheel</b></div>'},
 add:{title:'Zo voeg je breuken samen',text:'Bouw eerst de twee breuken in de bovenste vakken. Klik daarna op “Voeg mijn stroken samen”. Alle stukken schuiven naar de somstrook.',visual:'<div class="demo-add"><div><b>Bouw 1/4</b><span class="demo-strip one"></span></div><strong>＋</strong><div><b>Bouw 2/4</b><span class="demo-strip two"></span></div><strong>↓</strong><div><b>Som 3/4</b><span class="demo-strip three"></span></div></div>'},
 equal:{title:'Zo bouw je gelijkwaardige breuken',text:'Bouw links en rechts dezelfde hoeveelheid, maar gebruik stukken met een andere naam.',visual:'<div class="demo-parts"><span>1/2</span><b>＝</b><span>2/4</span></div>'},
 compare:{title:'Zo vergelijk je breuken',text:'Bouw beide torens vanaf dezelfde grondlijn. Kies daarna het teken dat bij de hoogtes past.',visual:'<div class="demo-towers"><i style="height:67%">2/3</i><b>&lt;</b><i style="height:75%">3/4</i></div>'},
 cup:{title:'Zo bouw je een literhoeveelheid',text:'Giet telkens hetzelfde maatje in de maatbeker. Zo ontdek je hoeveel gelijke delen samen de gevraagde hoeveelheid vormen.',visual:'<div class="demo-parts"><span>1/2 L</span><span>＋</span><span>1/2 L</span><b>＝ 1 L</b></div>'},
 line:{title:'Zo plaats je een breuk',text:'Kijk in hoeveel gelijke sprongen ieder geheel verdeeld is. Tik daarna op de juiste plaats op de getallenlijn.',visual:'<div class="demo-parts"><span>0</span><span>1/4</span><span>2/4</span><b>3/4 📍</b><span>1</span></div>'},
 mixed:{title:'Zo bouw je een gemengd getal',text:'Maak eerst het volledige geheel en bouw daarna het overblijvende breukdeel. Zo zie je ook de onechte breuk.',visual:'<div class="demo-parts"><span>4/4</span><span>＋</span><span>3/4</span><b>＝ 1 3/4 ＝ 7/4</b></div>'}
};
function showDemo(id){let overlay=$('modeDemo');if(!overlay){overlay=document.createElement('section');overlay.id='modeDemo';overlay.className='overlay';document.body.append(overlay)}const demo=demos[id];overlay.innerHTML=`<article class="demo-card"><div class="badge">KIJK EERST EVEN MEE</div><h2>${demo.title}</h2><p>${demo.text}</p><div class="real-demo-note"><b>Het spel doet één voorbeeld voor.</b><span>Kijk welk materiaal oplicht en waar het daarna terechtkomt.</span></div><div class="demo-actions"><button class="secondary" id="skipDemo">Overslaan en spelen</button><button id="watchDemo">Demo bekijken</button></div></article>`;overlay.hidden=false;$('skipDemo').onclick=()=>{overlay.hidden=true;show()};$('watchDemo').onclick=()=>{overlay.hidden=true;showAutoDemo(id)}}
function showPractice(id){practice=true;state={};const examples={build:[3,4,'pizza'],whole:[3,4,'pizza'],add:[1,4,2,4],equal:[1,2],compare:[2,3,3,4],cup:[1,1,2],line:[3,4,1],mixed:[1,3,4]};const r=examples[id];if(id==='build')showBuild(r);if(id==='whole')showWhole(r);if(id==='add')showAdd(r);if(id==='equal')showEqual(r);if(id==='compare')showCompare(r);if(id==='cup')showCup(r);if(id==='line')showLine(r);if(id==='mixed')showMixed(r)}
function removeDemoHand(){$('demoHand')?.remove()}
function showAutoDemo(id){const token=++demoRun;document.body.classList.add('demo-running');showPractice(id);const hand=document.createElement('div');hand.id='demoHand';hand.className='demo-hand';hand.textContent='👆🏼';document.body.append(hand);$('skipRunningDemo').onclick=()=>{demoRun++;practice=false;document.body.classList.remove('demo-running');removeDemoHand();round=0;show()};const q=s=>document.querySelector(s),click=s=>()=>q(s)?.click();const steps={build:[click('[data-den="4"]'),click('[data-den="4"]'),click('[data-den="4"]'),click('#ready')],whole:[click('[data-den="4"]'),click('#ready')],add:[click('[data-unit="4"]'),click('.bar-zone[data-zone="left"]'),click('.bar-zone[data-zone="right"]'),click('.bar-zone[data-zone="right"]'),click('#join'),click('#answerChoices [data-n="3"][data-d="4"]')],equal:[click('[data-unit="2"]'),click('.bar-zone[data-zone="left"]'),click('[data-unit="4"]'),click('.bar-zone[data-zone="right"]'),click('.bar-zone[data-zone="right"]'),click('#ready')],compare:[click('[data-unit="3"]'),click('.bar-zone[data-zone="left"]'),click('.bar-zone[data-zone="left"]'),click('[data-unit="4"]'),click('.bar-zone[data-zone="right"]'),click('.bar-zone[data-zone="right"]'),click('.bar-zone[data-zone="right"]'),click('#compareReady'),click('#signs button:first-child')],cup:[click('[data-pour="2"]'),click('[data-pour="2"]'),click('#ready')],line:[click('[data-value="3"]')],mixed:[click('[data-mixed-den="4"]'),click('[data-mixed-den="4"]'),click('[data-mixed-den="4"]'),click('[data-mixed-den="4"]'),click('[data-mixed-den="4"]'),click('[data-mixed-den="4"]'),click('[data-mixed-den="4"]'),click('#mixedReady')]}[id];let i=0;const run=()=>{if(token!==demoRun||i>=steps.length)return;const selectorTarget=demoTarget(id,i),el=selectorTarget?q(selectorTarget):null;if(el){const r=el.getBoundingClientRect();hand.style.left=`${r.left+r.width/2}px`;hand.style.top=`${r.top+r.height/2}px`;hand.classList.add('show');el.classList.add('demo-focus')}setTimeout(()=>{if(token!==demoRun)return;hand.classList.remove('tap');void hand.offsetWidth;hand.classList.add('tap');setTimeout(()=>{if(el)el.classList.remove('demo-focus');steps[i++]();setTimeout(run,450)},260)},520)};setTimeout(run,550)}
function demoTarget(id,i){return({build:['[data-den="4"]','[data-den="4"]','[data-den="4"]','#ready'],whole:['[data-den="4"]','#ready'],add:['[data-unit="4"]','.bar-zone[data-zone="left"]','.bar-zone[data-zone="right"]','.bar-zone[data-zone="right"]','#join','#answerChoices [data-n="3"][data-d="4"]'],equal:['[data-unit="2"]','.bar-zone[data-zone="left"]','[data-unit="4"]','.bar-zone[data-zone="right"]','.bar-zone[data-zone="right"]','#ready'],compare:['[data-unit="3"]','.bar-zone[data-zone="left"]','.bar-zone[data-zone="left"]','[data-unit="4"]','.bar-zone[data-zone="right"]','.bar-zone[data-zone="right"]','.bar-zone[data-zone="right"]','#compareReady','#signs button:first-child'],cup:['[data-pour="2"]','[data-pour="2"]','#ready'],line:['[data-value="3"]'],mixed:['[data-mixed-den="4"]','[data-mixed-den="4"]','[data-mixed-den="4"]','[data-mixed-den="4"]','[data-mixed-den="4"]','[data-mixed-den="4"]','[data-mixed-den="4"]','#mixedReady']})[id][i]}
function shell(title,help,body,buttons=''){stage.innerHTML=`<article class="stage-card">${practice?'<button id="skipRunningDemo" class="skip-running-demo">Ga naar spel →</button>':''}<div class="task"><div class="eyebrow">${practice?'DEMO — KIJK WAT HET SPEL DOET':`OPDRACHT ${round+1} VAN ${activeRounds.length}`}</div><h2>${title}</h2><p>${help}</p></div><div class="workspace">${body}</div><div class="ready">${buttons}</div><div id="feedback" class="feedback"></div></article>`;document.querySelectorAll('#quick button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function show(){const r=activeRounds[round];state={};if(mode==='build')showBuild(r);if(mode==='whole')showWhole(r);if(mode==='add')showAdd(r);if(mode==='equal')showEqual(r);if(mode==='compare')showCompare(r);if(mode==='cup')showCup(r);if(mode==='line')showLine(r);if(mode==='mixed')showMixed(r)}
function next(msg){feedback().className='feedback good';feedback().textContent=practice?`${msg} De echte ronde begint nu.`:msg;if(practice){setTimeout(()=>{demoRun++;practice=false;document.body.classList.remove('demo-running');removeDemoHand();round=0;show()},1500);return}score++;setTimeout(()=>{round++;if(round===activeRounds.length){$('doneText').textContent=`Je voltooide ${activeRounds.length} opdrachten van ${modes.find(m=>m.id===mode).name}.`;done.hidden=false}else show()},850)}
function wrong(msg){feedback().className='feedback bad';feedback().textContent=msg}
function canvas(tag='canvas'){return `<div class="food"><canvas ${tag}></canvas></div>`}
function showBuild([n,d,food]){pieceExercise(`Bouw ${n}/${d}`,'Kies links zelf de juiste stukken.',food,[],d,pieces=>pieces.length===n&&pieces.every(x=>x===d),`Juist: je bouwde ${n}/${d}.`)}
function showWhole([n,d,food]){pieceExercise('Maak één geheel','Vul aan met stukken met dezelfde noemer. Daarna zie je de volledige breukensom.',food,Array(n).fill(d),d,pieces=>pieces.length===d&&pieces.every(x=>x===d),pieces=>`Juist: ${n}/${d} + ${d-n}/${d} = ${d}/${d} = 1 geheel.`)}
function pieceExercise(title,help,food,initial,targetDen,check,success){const choices=pieceChoices(targetDen);state.pieces=[...initial];shell(title,help,`<div class="manip-layout"><aside id="pieceTray" class="piece-tray">${choices.map((d,i)=>`<div class="piece-choice"><canvas id="piece${i}"></canvas><b>1/${d}</b><button data-den="${d}" aria-label="Voeg één ${d}de toe">＋</button></div>`).join('')}</aside><div class="build-board"><canvas id="mainFood"></canvas><p>Tik op een geplaatst stuk om het weer weg te nemen.</p></div></div>`,`<button class="secondary" id="reset">Opnieuw</button><button id="ready">Klaar</button>`);choices.forEach((d,i)=>drawPreview(`piece${i}`,food,d));const render=()=>drawPieces('mainFood',food,state.pieces);render();document.querySelectorAll('[data-den]').forEach(b=>b.onclick=()=>{const den=+b.dataset.den,total=state.pieces.reduce((s,x)=>s+1/x,0);if(total+1/den>1.001){wrong('Dat stuk past niet meer op het bord.');return}state.pieces.push(den);feedback().className='feedback';feedback().textContent='';render()});const board=$('mainFood');let picked=-1;board.onclick=e=>{const index=pieceAt(e,board,state.pieces);if(index>=0){state.pieces.splice(index,1);render()}};board.onpointerdown=e=>{picked=pieceAt(e,board,state.pieces);if(picked>=0){board.setPointerCapture(e.pointerId);board.classList.add('piece-dragging')}};board.onpointerup=e=>{board.classList.remove('piece-dragging');if(picked<0)return;const r=$('pieceTray').getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){state.pieces.splice(picked,1);render()}picked=-1};$('reset').onclick=()=>{state.pieces=[...initial];render()};$('ready').onclick=()=>check(state.pieces)?next(typeof success==='function'?success(state.pieces):success):wrong('Dit is nog niet de gevraagde breuk. Kijk opnieuw naar de stukken links.')}
function pieceChoices(d){const map={3:[3,2,4,6],4:[4,2,6,5],5:[5,2,4,10],6:[6,2,3,4],8:[8,4,6,10],12:[12,6,4,8]};return map[d]||[d,2,4,6]}
function drawPreview(id,food,d){const c=$(id),x=c.getContext('2d');c.width=c.height=100;const im=imgs[food];x.beginPath();x.moveTo(50,50);x.arc(50,50,44,-Math.PI/2,-Math.PI/2+Math.PI*2/d);x.closePath();x.save();x.clip();x.drawImage(im,6,6,88,88);x.restore();x.strokeStyle='#fff';x.lineWidth=2;x.stroke()}
function drawPieces(id,food,pieces){const c=$(id),x=c.getContext('2d');c.width=c.height=360;x.clearRect(0,0,360,360);const im=imgs[food];let a=-Math.PI/2;for(const d of pieces){const b=a+Math.PI*2/d;x.save();x.beginPath();x.moveTo(180,180);x.arc(180,180,155,a,b);x.closePath();x.clip();x.drawImage(im,25,25,310,310);x.restore();x.strokeStyle='#fff';x.lineWidth=4;x.stroke();a=b}x.beginPath();x.arc(180,180,155,0,Math.PI*2);x.strokeStyle='#9ab5c0';x.lineWidth=2;x.stroke()}
function pieceAt(e,c,pieces){const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*360/r.width-180,y=(e.clientY-r.top)*360/r.height-180;if(Math.hypot(x,y)>155)return-1;let a=Math.atan2(y,x)+Math.PI/2;if(a<0)a+=Math.PI*2;let edge=0;for(let i=0;i<pieces.length;i++){edge+=Math.PI*2/pieces[i];if(a<=edge)return i}return-1}
function showAdd([a,d,b]){const dens=pieceChoices(d);state.left=[];state.right=[];state.joined=false;shell(`${a}/${d} + ${b}/${d}`,'Bouw eerst beide termen met breukstroken uit de materiaalbak.',labMarkup(dens,`Bouw ${a}/${d}`,`Bouw ${b}/${d}`,'add-fraction-lab')+`<div class="combine-arrow"><button id="join">Voeg mijn stroken samen ↓</button></div><div class="bar-zone result-zone"><b>Som</b><canvas id="resultBar"></canvas></div><div id="answerChoices" class="answer-choices" hidden></div>`,`<button class="secondary" id="reset">Leegmaken</button>`);setupBarLab(dens,[['left','leftBar'],['right','rightBar']]);drawUnitBar('resultBar',[]);$('reset').onclick=()=>{state.left=[];state.right=[];state.joined=false;$('answerChoices').hidden=true;drawLabBars();drawUnitBar('resultBar',[])};$('join').onclick=()=>{const valid=state.left.length===a&&state.left.every(x=>x===d)&&state.right.length===b&&state.right.every(x=>x===d);if(!valid){wrong(`Bouw eerst ${a}/${d} en ${b}/${d} met stukken van 1/${d}.`);return}state.joined=true;drawUnitBar('resultBar',[...state.left,...state.right]);showSumAnswers(a+b,d)}}
function showSumAnswers(n,d){const box=$('answerChoices'),opts=[[n,d],[Math.max(1,n-1),d],[n,Math.min(12,d+1)]].sort(()=>Math.random()-.5);box.hidden=false;box.innerHTML=`<b>Welke breuk heb je gebouwd?</b>${opts.map(o=>`<button data-n="${o[0]}" data-d="${o[1]}">${o[0]}/${o[1]}</button>`).join('')}`;box.querySelectorAll('button').forEach(b=>b.onclick=()=>+b.dataset.n===n&&+b.dataset.d===d?next(`Juist: samen is dit ${n}/${d}${n===d?' = 1':''}.`):wrong('Kijk opnieuw hoeveel gelijke stukken er samen liggen.'))}
function showEqual([n,d]){const dens=[d,d*2,d===2?4:Math.min(12,d+2),d===2?6:Math.min(12,d*3)].filter((x,i,a)=>x<=12&&a.indexOf(x)===i);state.left=[];state.right=[];shell(`Bouw ${fractionHtml(n,d,true)} op twee verschillende manieren`,'Gebruik bij Manier 1 en Manier 2 bewust stukken met een andere noemer.',labMarkup(dens,'Manier 1','Manier 2')+`<div id="equalEquation" class="equal-equation">Bouw dezelfde hoeveelheid met twee soorten stukken.</div>`,`<button class="secondary" id="reset">Leegmaken</button><button id="ready">Klaar</button>`);setupBarLab(dens,[['left','leftBar'],['right','rightBar']]);$('reset').onclick=()=>{state.left=[];state.right=[];drawLabBars()};$('ready').onclick=()=>{const target=n/d,l=sum(state.left),r=sum(state.right),different=state.left.length&&state.right.length&&state.left[0]!==state.right[0];Math.abs(l-target)<.001&&Math.abs(r-target)<.001&&different?next(`Juist: ${representationLabel(state.left)} = ${representationLabel(state.right)}.`):wrong('Bouw dezelfde hoeveelheid op twee verschillende manieren. Gebruik dus niet tweemaal dezelfde soort stukken.')}}
function showCompare([a,d,b,e]){const dens=[d,e,2,3,4,5,6,8].filter((x,i,z)=>z.indexOf(x)===i).slice(0,6);state.left=[];state.right=[];shell(`Bouw en vergelijk ${fractionHtml(a,d,true)} en ${fractionHtml(b,e,true)}`,'Kies links een stuk en bouw twee torens vanaf dezelfde grondlijn.',labMarkup(dens,`Bouw ${fractionHtml(a,d,true)}`,`Bouw ${fractionHtml(b,e,true)}`,'tower-lab')+`<div id="compareEquation" class="compare-equation" hidden><b>${fractionHtml(a,d,true)}</b><div id="signs" class="signs"><button>&lt;</button><button>=</button><button>&gt;</button></div><b>${fractionHtml(b,e,true)}</b></div>`,`<button class="secondary" id="reset">Leegmaken</button><button id="compareReady">Breuken klaar</button>`);setupBarLab(dens,[['left','leftBar'],['right','rightBar']]);$('reset').onclick=()=>{state.left=[];state.right=[];$('compareEquation').hidden=true;$('compareReady').hidden=false;drawLabBars()};$('compareReady').onclick=()=>{const leftCorrect=state.left.length===a&&state.left.every(x=>x===d),rightCorrect=state.right.length===b&&state.right.every(x=>x===e);if(!leftCorrect||!rightCorrect){wrong(`Bouw ${a}/${d} met ${a} stuk${a===1?'':'ken'} van 1/${d} en ${b}/${e} met ${b} stuk${b===1?'':'ken'} van 1/${e}.`);return}$('compareEquation').hidden=false;$('compareReady').hidden=true};document.querySelectorAll('#signs button').forEach(x=>x.onclick=()=>{const right=a/d>b/e?'>':a/d<b/e?'<':'=';x.textContent===right?next(`Juist: ${a}/${d} ${right} ${b}/${e}.`):wrong('Vergelijk de hoogte van de twee torens opnieuw.')})}
function showCup([n,d,unit]){const target=n/d,dens=[2,4,8],needed=Math.round(target*unit),targetText=fractionLabel(target),unitText=`1/${unit} L`;state.cup=[];shell(`Hoeveel keer ${unitText} vormt ${targetText}?`,'Gebruik telkens hetzelfde maatje en ontdek de vermenigvuldiging.',`<div class="cup-lab"><aside id="cupTray" class="liquid-tray">${dens.map(x=>`<button data-pour="${x}"><span class="mini-cup"><i style="height:${100/x}%"></i></span><b>1/${x} L</b></button>`).join('')}</aside><div class="cup-work"><div class="cup"><i class="cup-mark full-mark">1 L</i><i class="cup-mark half-mark">½ L</i><div class="liquid" id="resultLiquid"></div></div><b>maatbeker van 1 L</b><div class="cup-equation" id="cupEquation">${targetText} = ? × ${unitText}</div></div></div>`,`<button class="secondary" id="emptyCup">Leegmaken</button><button id="ready">Klaar</button>`);const update=()=>{const count=state.cup.length;$('resultLiquid').style.height=`${sum(state.cup)*100}%`;$('cupEquation').textContent=`${targetText} = ${count||'?'} × ${unitText}`};document.querySelectorAll('[data-pour]').forEach(x=>x.onclick=()=>{const den=+x.dataset.pour;if(den!==unit){wrong(`Gebruik voor deze opdracht telkens het maatje van ${unitText}.`);return}if(sum(state.cup)+1/den>1.001){wrong('Die hoeveelheid past niet meer in de maatbeker.');return}state.cup.push(den);update()});$('emptyCup').onclick=()=>{state.cup=[];update()};$('ready').onclick=()=>state.cup.length===needed&&Math.abs(sum(state.cup)-target)<.001?next(`Juist: ${targetText} = ${needed} × ${unitText}.`):wrong(`Kijk naar het vloeistofniveau en tel hoeveel maatjes van ${unitText} je nodig hebt.`)}
function showLine([n,d,max]){const steps=max*d,mixed=n>d?`${Math.floor(n/d)} ${n%d}/${d}`:'';shell(`Plaats ${fractionHtml(n,d,true)} op de getallenlijn`,max===1?`Ieder geheel is verdeeld in ${d} gelijke delen.`:`De lijn loopt tot ${max}. Ieder geheel is verdeeld in ${d} gelijke delen.`,`<div class="number-line" style="--steps:${steps}"><div class="number-track"></div>${Array.from({length:steps+1},(_,i)=>`<button data-value="${i}" style="--pos:${i}" aria-label="Plaats ${i}/${d}"><i></i><span>${i%d===0?i/d:''}</span></button>`).join('')}</div><div class="line-hint">Tel sprongen van <b>1/${d}</b> vanaf 0.</div>`);document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{b.classList.add('chosen');+b.dataset.value===n?next(`Juist: ${n}/${d}${mixed?` = ${mixed}`:''}.`):wrong('Nog niet juist. Tel de gelijke sprongen opnieuw vanaf 0.')})}
function showMixed([whole,n,d]){
 const total=whole*d+n,choices=pieceChoices(d);state.mixed=[];
 shell(`Bouw ${whole} ${fractionHtml(n,d,true)}`,'Maak eerst de volledige pizza’s. Bouw daarna het overblijvende breukdeel.',`<div class="mixed-lab"><aside class="mixed-tray">${choices.map((den,i)=>`<button data-mixed-den="${den}"><canvas id="mixedPiece${i}"></canvas><b>1/${den}</b><span>＋</span></button>`).join('')}</aside><div><div id="mixedBoard" class="mixed-board"></div><div id="mixedEquation" class="mixed-equation">${whole} ${fractionHtml(n,d,true)} = ${fractionHtml('?',d,true)}</div><button type="button" class="take-back" id="mixedBack">↩ Laatste stuk terug</button></div></div>`,`<button class="secondary" id="mixedReset">Leegmaken</button><button id="mixedReady">Klaar</button>`);
 choices.forEach((den,i)=>drawPreview(`mixedPiece${i}`,'pizza',den));
 const render=()=>{const board=$('mixedBoard'),groups=[];for(let start=0;start<state.mixed.length;start+=d)groups.push(state.mixed.slice(start,start+d));board.innerHTML=groups.map((g,i)=>`<div class="mixed-pizza"><canvas id="mixedPizza${i}"></canvas><b>${g.length}/${d}</b></div>`).join('')||'<div class="mixed-empty">Begin met stukken uit de materiaalbak.</div>';groups.forEach((g,i)=>drawPieces(`mixedPizza${i}`,'pizza',g));$('mixedEquation').innerHTML=`${whole} ${fractionHtml(n,d,true)} = ${fractionHtml(state.mixed.length||'?',d,true)}`};
 document.querySelectorAll('[data-mixed-den]').forEach(b=>{b.onclick=()=>{const den=+b.dataset.mixedDen;if(den!==d){wrong(`Gebruik voor deze opdracht stukken van 1/${d}.`);return}if(state.mixed.length>=total){wrong('Je hebt al genoeg stukken gelegd.');return}state.mixed.push(den);render()}});
 $('mixedBack').onclick=()=>{state.mixed.pop();render()};$('mixedReset').onclick=()=>{state.mixed=[];render()};$('mixedReady').onclick=()=>{if(state.mixed.length===total&&state.mixed.every(x=>x===d))next(`Juist: ${whole} ${n}/${d} = ${total}/${d}.`);else wrong(`Bouw ${whole} volledige ${d}/${d} en daarna nog ${n}/${d}.`)};render();
}
function fractionColor(d){return({1:'#ef554f',2:'#ed6fa5',3:'#f29a38',4:'#f4cf45',5:'#65bd69',6:'#52bdd0',8:'#5687d8',10:'#9a65c7',12:'#7d8795'})[d]||'#55bad8'}
function fractionHtml(n,d,stacked=false){return stacked?`<span class="stacked-frac"><span>${n}</span><span>${d}</span></span>`:`${n}/${d}`}
function labMarkup(dens,left,right,extra=''){const stacked=mode==='equal'||mode==='compare',guides=extra.includes('tower')?'<div class="height-guides" aria-hidden="true"><i class="left-guide"></i><i class="right-guide"></i></div>':'';return `<div class="fraction-lab ${extra}"><aside id="fractionTray" class="fraction-tray">${dens.map(d=>`<div class="unit-tile" data-unit="${d}"><span class="unit-model"><i style="width:${100/d}%;background:${fractionColor(d)}"></i></span><b>${fractionHtml(1,d,stacked)}</b><small>kies</small></div>`).join('')}</aside><div class="bar-zones"><div class="bar-zone" data-zone="left"><b>${left}</b><canvas id="leftBar"></canvas><button class="take-back" type="button">↩ Laatste stuk terug</button></div><div class="bar-zone" data-zone="right"><b>${right}</b><canvas id="rightBar"></canvas><button class="take-back" type="button">↩ Laatste stuk terug</button></div>${guides}</div></div>`}
function setupBarLab(dens,zones){let selected=null;drawLabBars();const place=(zone,den)=>{const list=state[zone.dataset.zone];if(sum(list)+1/den<=1.001){list.push(den);drawLabBars()}};document.querySelectorAll('[data-unit]').forEach(tile=>{tile.onclick=()=>{document.querySelectorAll('[data-unit]').forEach(x=>x.classList.remove('selected'));selected=+tile.dataset.unit;tile.classList.add('selected')};tile.onpointerdown=e=>{tile.setPointerCapture(e.pointerId);tile.classList.add('carrying')};tile.onpointerup=e=>{tile.classList.remove('carrying');const zone=[...document.querySelectorAll('.bar-zone[data-zone]')].find(z=>{const r=z.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom});if(zone)place(zone,+tile.dataset.unit)}});document.querySelectorAll('.bar-zone[data-zone]').forEach(zone=>{zone.onclick=e=>{if(!e.target.closest('.take-back')&&selected)place(zone,selected)};zone.querySelector('.take-back').onclick=e=>{e.stopPropagation();state[zone.dataset.zone].pop();drawLabBars()}})}
function drawLabBars(){if($('leftBar'))drawUnitBar('leftBar',state.left||[]);if($('rightBar'))drawUnitBar('rightBar',state.right||[]);updateTowerGuides();const equation=$('equalEquation');if(equation){const l=sum(state.left||[]),r=sum(state.right||[]);equation.innerHTML=state.left?.length&&state.right?.length&&Math.abs(l-r)<.001?`${representationHtml(state.left)} <b>=</b> ${representationHtml(state.right)}`:'Bouw dezelfde hoeveelheid met twee soorten stukken.'}}
function updateTowerGuides(){const zones=document.querySelector('.tower-lab .bar-zones'),left=$('leftBar'),right=$('rightBar');if(!zones||!left||!right)return;const zr=zones.getBoundingClientRect(),lr=left.getBoundingClientRect(),rr=right.getBoundingClientRect(),leftLine=zones.querySelector('.left-guide'),rightLine=zones.querySelector('.right-guide'),l=sum(state.left||[]),r=sum(state.right||[]),towerTop=(rect,value)=>rect.top-zr.top+((345-330*value)/370)*rect.height;leftLine.style.top=`${towerTop(lr,l)}px`;rightLine.style.top=`${towerTop(rr,r)}px`;leftLine.style.borderColor=state.left?.length?fractionColor(state.left[0]):'';rightLine.style.borderColor=state.right?.length?fractionColor(state.right[0]):'';leftLine.hidden=!state.left?.length;rightLine.hidden=!state.right?.length}
function representationLabel(pieces){return pieces.length&&pieces.every(d=>d===pieces[0])?`${pieces.length}/${pieces[0]}`:pieces.map(d=>`1/${d}`).join(' + ')}
function representationHtml(pieces){return pieces.length&&pieces.every(d=>d===pieces[0])?fractionHtml(pieces.length,pieces[0],true):pieces.map(d=>fractionHtml(1,d,true)).join(' + ')}
function drawCanvasFraction(x,cx,cy,d,stacked){x.fillStyle='#173f62';x.textAlign='center';x.textBaseline='middle';if(!stacked){x.font='bold 18px Arial';x.fillText(`1/${d}`,cx,cy);return}x.font='bold 15px Arial';x.fillText('1',cx,cy-11);x.fillRect(cx-12,cy-1,24,2);x.fillText(String(d),cx,cy+12)}
function drawUnitBar(id,pieces){const c=$(id),x=c.getContext('2d'),tower=!!c.closest('.tower-lab'),stacked=mode==='equal'||mode==='compare';if(tower){c.width=240;c.height=370;x.clearRect(0,0,240,370);x.strokeStyle='#173f62';x.lineWidth=4;x.strokeRect(55,15,130,330);let top=345;for(const d of pieces){const h=330/d;top-=h;x.fillStyle=fractionColor(d);x.fillRect(55,top,130,h);x.strokeStyle='#fff';x.lineWidth=3;x.strokeRect(55,top,130,h);drawCanvasFraction(x,120,top+h/2,d,stacked)}x.strokeStyle='#173f62';x.lineWidth=5;x.beginPath();x.moveTo(25,345);x.lineTo(215,345);x.stroke();return}c.width=800;c.height=100;x.clearRect(0,0,800,100);x.strokeStyle='#173f62';x.lineWidth=4;x.strokeRect(10,15,780,70);let pos=10;for(const d of pieces){const w=780/d;x.fillStyle=fractionColor(d);x.fillRect(pos,15,w,70);x.strokeStyle='#fff';x.lineWidth=3;x.strokeRect(pos,15,w,70);drawCanvasFraction(x,pos+w/2,50,d,stacked);pos+=w}}
function sum(list){return list.reduce((s,d)=>s+1/d,0)}function fractionLabel(v){if(Math.abs(v-1)<.001)return'1 L';for(const d of [2,4,8]){const n=Math.round(v*d);if(Math.abs(n/d-v)<.001)return`${n}/${d} L`}return`${v.toFixed(2)} L`}
function draw(id,food,n,d){const c=$(id),x=c.getContext('2d'),s=300;c.width=c.height=s;x.clearRect(0,0,s,s);if(food==='chocolade'){const im=imgs.chocolade;x.drawImage(im,10,55,280,190);const cols=4,rows=3;for(let i=n;i<12;i++){const col=i%cols,row=Math.floor(i/cols);x.fillStyle='#f4fbfd';x.fillRect(10+col*70,55+row*63.4,70,63.4)}return}const im=imgs[food];for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/d,b=-Math.PI/2+(i+1)*Math.PI*2/d;x.save();x.beginPath();x.moveTo(150,150);x.arc(150,150,135,a,b);x.closePath();x.clip();x.drawImage(im,15,15,270,270);x.restore();x.strokeStyle='#fff';x.lineWidth=3;x.stroke()}x.beginPath();x.arc(150,150,135,0,Math.PI*2);x.strokeStyle='#9ab5c0';x.stroke()}
function drawBar(id,n,d,kind){const c=$(id),x=c.getContext('2d');c.width=240;c.height=180;x.clearRect(0,0,240,180);if(kind){const w=190,h=90,X=25,Y=45;for(let i=0;i<d;i++){x.fillStyle=i<n?'#55bad8':'#fff';x.fillRect(X+i*w/d,Y,w/d,h);x.strokeStyle='#173f62';x.strokeRect(X+i*w/d,Y,w/d,h)}}else{for(let i=0;i<n;i++){x.beginPath();x.moveTo(120,90);x.arc(120,90,75,-Math.PI/2+i*2*Math.PI/d,-Math.PI/2+(i+1)*2*Math.PI/d);x.closePath();x.fillStyle='#55bad8';x.fill();x.strokeStyle='#fff';x.stroke()}x.beginPath();x.arc(120,90,75,0,Math.PI*2);x.strokeStyle='#173f62';x.stroke()}}
function bar(n,d){return `<div class="bar">${Array.from({length:d},(_,i)=>`<i class="${i<n?'':'empty'}"></i>`).join('')}</div>`}
})();
