(()=>{
const stage=$('stage'),menu=$('menu'),done=$('done'),feedback=()=>$('feedback');
const imgs={pizza:img('assets/pizza.png'),taart:img('assets/taart.png'),chocolade:img('assets/chocolade.png')};
const modes=[
 {id:'build',icon:'🍕',name:'Bouw de breuk',desc:'Leg zelf de juiste stukken en klik daarna op Klaar.'},
 {id:'whole',icon:'🧩',name:'Maak één geheel',desc:'Vul aan tot een volledige pizza, taart of reep.'},
 {id:'add',icon:'➕',name:'Breuken samenvoegen',desc:'Voeg gelijknamige breuken visueel samen.'},
 {id:'equal',icon:'🔎',name:'Gelijkwaardige breuken',desc:'Herken dezelfde hoeveelheid in andere vormen.'},
 {id:'compare',icon:'⚖️',name:'Breuken vergelijken',desc:'Vergelijk stroken en kies <, > of =.'},
 {id:'cup',icon:'🥛',name:'Recepten met 1 liter',desc:'Giet hoeveelheden samen in een maatbeker van 1 L.'}
];
let mode='build',round=0,score=0,state={};
const rounds={build:[[3,4,'pizza'],[2,3,'taart'],[5,8,'pizza'],[7,12,'chocolade']],whole:[[3,4,'pizza'],[4,6,'taart'],[8,12,'chocolade'],[5,8,'pizza']],add:[[1,4,2,4,'pizza'],[2,5,3,5,'taart'],[3,12,5,12,'chocolade'],[1,4,3,4,'pizza']],equal:[[1,2,[[2,4],[3,4],[1,3]]],[2,3,[[4,6],[3,6],[3,4]]],[3,4,[[6,8],[2,3],[4,5]]],[2,5,[[4,10],[3,5],[1,2]]]],compare:[[2,3,3,4],[3,5,1,2],[4,6,2,3],[5,8,3,4]],cup:[[1,2,1,2],[1,4,1,4],[1,4,3,4],[1,2,1,4]]};
function $(id){return document.getElementById(id)}function img(src){const i=new Image;i.onload=()=>{if(!menu||menu.hidden)show()};i.src=src;return i}
function menuButtons(){return modes.map(m=>`<button data-mode="${m.id}"><b>${m.icon} ${m.name}</b><span>${m.desc}</span></button>`).join('')}
$('modeGrid').innerHTML=menuButtons();$('quick').innerHTML=modes.map(m=>`<button data-mode="${m.id}">${m.icon} ${m.name}</button>`).join('');
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('studioMenu').onclick=()=>menu.hidden=false;$('other').onclick=()=>{done.hidden=true;menu.hidden=false};$('again').onclick=()=>start(mode);
function start(id){mode=id;round=0;score=0;menu.hidden=true;done.hidden=true;show()}
function shell(title,help,body,buttons=''){stage.innerHTML=`<article class="stage-card"><div class="task"><div class="eyebrow">OPDRACHT ${round+1} VAN 4</div><h2>${title}</h2><p>${help}</p></div><div class="workspace">${body}</div><div class="ready">${buttons}</div><div id="feedback" class="feedback"></div></article>`;document.querySelectorAll('#quick button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function show(){const r=rounds[mode][round];state={};if(mode==='build')showBuild(r);if(mode==='whole')showWhole(r);if(mode==='add')showAdd(r);if(mode==='equal')showEqual(r);if(mode==='compare')showCompare(r);if(mode==='cup')showCup(r)}
function next(msg){score++;feedback().className='feedback good';feedback().textContent=msg;setTimeout(()=>{round++;if(round===4){$('doneText').textContent=`Je voltooide alle opdrachten van ${modes.find(m=>m.id===mode).name}.`;done.hidden=false}else show()},850)}
function wrong(msg){feedback().className='feedback bad';feedback().textContent=msg}
function canvas(tag='canvas'){return `<div class="food"><canvas ${tag}></canvas></div>`}
function showBuild([n,d,food]){state.n=0;shell(`Bouw ${n}/${d}`,`Leg ${n} van de ${d} gelijke delen op het bord.`,canvas('id="mainFood"')+`<div class="slice-palette"><button id="minus">− stukje</button><button id="plus">+ stukje</button></div>`,`<button class="secondary" id="reset">Opnieuw</button><button id="ready">Klaar</button>`);draw('mainFood',food,0,d);$('plus').onclick=()=>{state.n=Math.min(d,state.n+1);draw('mainFood',food,state.n,d)};$('minus').onclick=()=>{state.n=Math.max(0,state.n-1);draw('mainFood',food,state.n,d)};$('reset').onclick=()=>{state.n=0;draw('mainFood',food,0,d)};$('ready').onclick=()=>state.n===n?next(`Juist: ${n} van de ${d} delen is ${n}/${d}.`):wrong(`Je legde ${state.n} stukken. Kijk naar de teller en probeer opnieuw.`)}
function showWhole([n,d,food]){state.n=n;shell(`Maak ${n}/${d} volledig`,`Hoeveel gelijke stukken ontbreken tot één geheel?`,canvas('id="mainFood"')+`<div class="slice-palette"><button id="addPiece">Voeg één ${d}de toe</button></div>`,`<button id="ready">Klaar</button>`);draw('mainFood',food,n,d);$('addPiece').onclick=()=>{state.n=Math.min(d,state.n+1);draw('mainFood',food,state.n,d)};$('ready').onclick=()=>state.n===d?next(`${d}/${d} is één volledig geheel.`):wrong(`Er ontbreken nog ${d-state.n} gelijke stukken.`)}
function showAdd([a,d,b,,food]){state.joined=false;shell(`${a}/${d} + ${b}/${d}`,`Voeg de twee groepjes samen.`, `<div class="sum-row">${canvas('id="left"')}<span class="operator">+</span>${canvas('id="right"')}<span class="operator">=</span>${canvas('id="result"')}</div>`,`<button id="join">Samenvoegen</button><button id="ready">Klaar</button>`);draw('left',food,a,d);draw('right',food,b,d);draw('result',food,0,d);$('join').onclick=()=>{state.joined=true;draw('result',food,a+b,d)};$('ready').onclick=()=>state.joined?next(`${a}/${d} + ${b}/${d} = ${a+b}/${d}${a+b===d?' = 1':a+b>d?` = 1 ${a+b-d}/${d}`:''}`):wrong('Voeg de stukken eerst samen.')}
function showEqual([n,d,opts]){shell(`Welke vorm toont ook ${n}/${d}?`,'De vorm mag anders zijn, maar de hoeveelheid moet gelijk blijven.',`<div class="choice-row">${opts.map((o,i)=>`<button class="choice" data-i="${i}"><canvas id="opt${i}"></canvas></button>`).join('')}</div>`);opts.forEach((o,i)=>drawBar(`opt${i}`,o[0],o[1],i%2));document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const o=opts[+b.dataset.i];o[0]*d===n*o[1]?next(`${o[0]}/${o[1]} is evenveel als ${n}/${d}.`):wrong('Deze hoeveelheid is niet even groot. Kijk waar het gekleurde deel eindigt.')})}
function showCompare([a,d,b,e]){state.sign='';shell(`Vergelijk ${a}/${d} en ${b}/${e}`,'Kijk naar de twee even lange stroken.',`<div class="food-row"><div>${bar(a,d)}<label>${a}/${d}</label></div><div>${bar(b,e)}<label>${b}/${e}</label></div></div><div class="signs"><button>&lt;</button><button>=</button><button>&gt;</button></div>`);document.querySelectorAll('.signs button').forEach(x=>x.onclick=()=>{const right=a/d>b/e?'>':a/d<b/e?'<':'=';x.textContent===right?next(`Juist: ${a}/${d} ${right} ${b}/${e}.`):wrong('Kijk opnieuw welke gekleurde strook het verst komt.')})}
function showCup([a,d,b,e]){state.poured=false;const total=a/d+b/e;shell(`${a}/${d} L + ${b}/${e} L`,`Giet beide hoeveelheden in één maatbeker van 1 liter.`,`<div class="cup-scene"><div><div class="cup"><div class="liquid" style="height:${a/d*100}%"></div></div><b>${a}/${d} L</b></div><span class="pour">＋</span><div><div class="cup"><div class="liquid" style="height:${b/e*100}%"></div></div><b>${b}/${e} L</b></div><span class="pour">→</span><div><div class="cup" id="resultCup"><div class="liquid" id="resultLiquid"></div></div><b>1 L maatbeker</b></div></div>`,`<button id="pour">Giet samen</button><button id="ready">Klaar</button>`);$('pour').onclick=()=>{state.poured=true;$('resultLiquid').style.height=`${Math.min(1,total)*100}%`};$('ready').onclick=()=>state.poured?next(total===1?'Samen vullen de hoeveelheden precies 1 liter.':`Samen is dit ${a*e+b*d}/${d*e} liter.`):wrong('Giet de hoeveelheden eerst samen in de maatbeker.')}
function draw(id,food,n,d){const c=$(id),x=c.getContext('2d'),s=300;c.width=c.height=s;x.clearRect(0,0,s,s);if(food==='chocolade'){const im=imgs.chocolade;x.drawImage(im,10,55,280,190);const cols=4,rows=3;for(let i=n;i<12;i++){const col=i%cols,row=Math.floor(i/cols);x.fillStyle='#f4fbfd';x.fillRect(10+col*70,55+row*63.4,70,63.4)}return}const im=imgs[food];for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/d,b=-Math.PI/2+(i+1)*Math.PI*2/d;x.save();x.beginPath();x.moveTo(150,150);x.arc(150,150,135,a,b);x.closePath();x.clip();x.drawImage(im,15,15,270,270);x.restore();x.strokeStyle='#fff';x.lineWidth=3;x.stroke()}x.beginPath();x.arc(150,150,135,0,Math.PI*2);x.strokeStyle='#9ab5c0';x.stroke()}
function drawBar(id,n,d,kind){const c=$(id),x=c.getContext('2d');c.width=240;c.height=180;x.clearRect(0,0,240,180);if(kind){const w=190,h=90,X=25,Y=45;for(let i=0;i<d;i++){x.fillStyle=i<n?'#55bad8':'#fff';x.fillRect(X+i*w/d,Y,w/d,h);x.strokeStyle='#173f62';x.strokeRect(X+i*w/d,Y,w/d,h)}}else{for(let i=0;i<n;i++){x.beginPath();x.moveTo(120,90);x.arc(120,90,75,-Math.PI/2+i*2*Math.PI/d,-Math.PI/2+(i+1)*2*Math.PI/d);x.closePath();x.fillStyle='#55bad8';x.fill();x.strokeStyle='#fff';x.stroke()}x.beginPath();x.arc(120,90,75,0,Math.PI*2);x.strokeStyle='#173f62';x.stroke()}}
function bar(n,d){return `<div class="bar">${Array.from({length:d},(_,i)=>`<i class="${i<n?'':'empty'}"></i>`).join('')}</div>`}
})();
