(()=>{
const $=id=>document.getElementById(id),dens=[2,3,4,5,6,8,10,12],colors={2:'#ed6fa5',3:'#f29a38',4:'#f4cf45',5:'#65bd69',6:'#52bdd0',8:'#5687d8',10:'#9a65c7',12:'#aeb7bd'};
let q=null,s=null,hints=0,padMode='pen',padColor='#173f62',drawing=false,last=null;
const frac=(n,d)=>`${n}/${d}`,sum=list=>list.reduce((t,d)=>t+1/d,0),near=(a,b)=>Math.abs(a-b)<.0001,gcd=(a,b)=>b?gcd(b,a%b):a,lcm=(a,b)=>a*b/gcd(a,b);
function open(){renderInput()}
function top(){return `<div class="wb-top"><button class="wb-back" id="wbBack">← Oefenvormen</button><h2>📖 Mijn werkboekoefening</h2><span></span></div>`}
function bindBack(){ $('wbBack').onclick=()=>{ $('stage').innerHTML='';$('menu').hidden=false } }
function renderInput(){q=null;s=null;$('stage').innerHTML=`<article class="wb-shell">${top()}<p class="wb-intro">Neem een oefening uit je werkboek over. Jij legt en rekent; de studio controleert alleen je stappen.</p><div class="wb-form"><span class="wb-frac"><input id="wbA" type="number" min="0" max="24" aria-label="Eerste teller"><i></i><input id="wbD" type="number" min="2" max="12" aria-label="Eerste noemer"></span><select class="wb-op" id="wbOp" aria-label="Bewerking"><option value="+">+</option><option value="-">−</option></select><span class="wb-frac"><input id="wbB" type="number" min="0" max="24" aria-label="Tweede teller"><i></i><input id="wbE" type="number" min="2" max="12" aria-label="Tweede noemer"></span><button class="wb-btn wb-start" id="wbStart">Start met leggen →</button></div><div class="wb-error" id="wbInputError"></div><p class="wb-intro"><b>Eerste testversie:</b> noemers 2 t.e.m. 12 en breuken kleiner dan of gelijk aan één geheel.</p></article>`;bindBack();$('wbStart').onclick=start}
function start(){const a=+$('wbA').value,d=+$('wbD').value,b=+$('wbB').value,e=+$('wbE').value,op=$('wbOp').value,err=$('wbInputError');if(!a||!b||!dens.includes(d)||!dens.includes(e)){err.textContent='Vul twee breuken in met een onderste getal uit 2, 3, 4, 5, 6, 8, 10 of 12.';return}if(a>d||b>e){err.textContent='In deze testversie mogen de breuken nog niet groter zijn dan één geheel.';return}if(op==='-'&&a/d<b/e){err.textContent='Kies voorlopig een aftrekking waarbij de eerste breuk de grootste is.';return}q={a,d,b,e,op,common:lcm(d,e)};s={left:[],right:[],convLeft:[],convRight:[],removed:0,phase:'build',selected:null};hints=0;renderWorkspace()}
function piece(d,removed=false){return `<span class="wb-piece${removed?' removed':''}" style="--w:${100/d}%;--color:${colors[d]||'#8fcbd8'}">1/${d}</span>`}
function bars(){if($('wbLeft'))$('wbLeft').innerHTML=s.left.map(d=>piece(d)).join('');if($('wbRight'))$('wbRight').innerHTML=s.right.map(d=>piece(d)).join('');if($('wbConvLeft'))$('wbConvLeft').innerHTML=s.convLeft.map((d,i)=>piece(d,s.phase==='remove'&&i<s.removed)).join('');if($('wbConvRight'))$('wbConvRight').innerHTML=s.convRight.map(d=>piece(d)).join('')}
function baseBuilds(leftTitle,rightTitle,leftId='wbLeft',rightId='wbRight'){return `<div class="wb-builds"><section class="wb-zone"><h4>${leftTitle}</h4><div class="wb-bar" id="${leftId}"></div><div class="wb-zone-actions"><button data-add="left">＋ Leg stuk</button><button data-undo="left">↶ Terug</button></div></section><section class="wb-zone"><h4>${rightTitle}</h4><div class="wb-bar" id="${rightId}"></div><div class="wb-zone-actions"><button data-add="right">＋ Leg stuk</button><button data-undo="right">↶ Terug</button></div></section></div>`}
function renderWorkspace(){$('stage').innerHTML=`<article class="wb-shell">${top()}<p class="wb-intro">Oefening: <b>${frac(q.a,q.d)} ${q.op} ${frac(q.b,q.e)}</b></p><div class="wb-grid"><section class="wb-card"><h3>✏️ Mijn kladblad</h3><div class="wb-pad-tools"><button data-pad="pen" class="active">Pen</button>${['#173f62','#d43b35','#1768ac','#159668'].map(c=>`<button data-color="${c}" style="color:${c}">●</button>`).join('')}<button data-pad="eraser">Gom</button><button id="wbClearPad">Wissen</button></div><canvas class="wb-pad" id="wbPad"></canvas></section><section class="wb-card"><h3>🧩 Materiaaltafel</h3><div class="wb-palette">${dens.map(d=>`<button data-den="${d}">1/${d}</button>`).join('')}</div><div id="wbMaterial">${baseBuilds(`Bouw ${frac(q.a,q.d)}`,`Bouw ${frac(q.b,q.e)}`)}</div><div class="wb-steps" id="wbStep"><b>Stap 1</b>Kies een soort stuk en leg zelf beide breuken.</div><div class="wb-actions"><button id="wbCheck">Controleer mijn stap</button><button class="hint" id="wbHint">💡 Kleine hint</button><button class="wb-new" id="wbNew">Andere oefening</button></div><div class="wb-feedback" id="wbFeedback"></div></section></div></article>`;bindBack();wirePad();wirePalette();wireZones();$('wbCheck').onclick=checkBuild;$('wbHint').onclick=hint;$('wbNew').onclick=renderInput;bars()}
function wirePalette(){document.querySelectorAll('[data-den]').forEach(btn=>btn.onclick=()=>{s.selected=+btn.dataset.den;document.querySelectorAll('[data-den]').forEach(x=>x.classList.toggle('selected',x===btn))})}
function wireZones(){document.querySelectorAll('[data-add]').forEach(btn=>btn.onclick=()=>{if(!s.selected)return feedback('Kies eerst bovenaan een breukstuk.');const key=btn.dataset.add;if(sum(s[key])+1/s.selected<=1.001)s[key].push(s.selected);else feedback('Deze strook is vol. Neem eerst een stuk terug.');bars()});document.querySelectorAll('[data-undo]').forEach(btn=>btn.onclick=()=>{s[btn.dataset.undo].pop();bars()})}
function exact(list,n,d){return list.length===n&&list.every(x=>x===d)}
function feedback(text,good=false){const el=$('wbFeedback');el.className=`wb-feedback ${good?'good':'bad'}`;el.textContent=text}
function checkBuild(){if(!exact(s.left,q.a,q.d)||!exact(s.right,q.b,q.e)){feedback('De stroken kloppen nog niet. Kijk opnieuw naar teller en noemer.');return}hints=0;if(q.d===q.e){s.common=q.d;s.convLeft=[...s.left];s.convRight=[...s.right];goOperate()}else chooseCommon()}
function chooseCommon(){s.phase='common';$('wbStep').innerHTML=`<b>Stap 2 · Maak gelijknamig</b><div class="wb-common"><label>Welke kleinste noemer past bij beide breuken?</label><input id="wbCommon" type="number" min="2" max="120"><button id="wbCheckCommon">Controleer</button></div>`;$('wbCheck').hidden=true;$('wbCheckCommon').onclick=()=>{const v=+$('wbCommon').value;if(v!==q.common){feedback(v&&v%q.d===0&&v%q.e===0?'Dat kan, maar er bestaat een kleinere gemeenschappelijke noemer.':'Die noemer past niet bij beide breuken.');return}beginConvert()};feedback('De oorspronkelijke breuken zijn juist gebouwd.',true)}
function beginConvert(){s.phase='convert';s.selected=q.common;s.convLeft=[];s.convRight=[];$('wbMaterial').innerHTML=`<div class="wb-builds"><section class="wb-zone"><h4>${frac(q.a,q.d)} met stukken van 1/${q.common}</h4><div class="wb-bar" id="wbConvLeft"></div><div class="wb-zone-actions"><button data-convert="left">＋ Leg 1/${q.common}</button><button data-convert-undo="left">↶ Terug</button></div></section><section class="wb-zone"><h4>${frac(q.b,q.e)} met stukken van 1/${q.common}</h4><div class="wb-bar" id="wbConvRight"></div><div class="wb-zone-actions"><button data-convert="right">＋ Leg 1/${q.common}</button><button data-convert-undo="right">↶ Terug</button></div></section></div>`;$('wbStep').innerHTML=`<b>Stap 3</b>Leg onder beide oorspronkelijke breuken een even lange strook met stukken van 1/${q.common}.`;$('wbCheck').hidden=false;$('wbCheck').textContent='Controleer het gelijknamig maken';$('wbCheck').onclick=checkConvert;document.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>{const k=b.dataset.convert==='left'?'convLeft':'convRight';if(s[k].length<q.common)s[k].push(q.common);bars()});document.querySelectorAll('[data-convert-undo]').forEach(b=>b.onclick=()=>{s[b.dataset.convertUndo==='left'?'convLeft':'convRight'].pop();bars()});feedback('Goed gekozen. Bouw de gelijknamige breuken nu zelf.',true);bars()}
function checkConvert(){const ln=q.a*q.common/q.d,rn=q.b*q.common/q.e;if(s.convLeft.length!==ln||s.convRight.length!==rn){feedback('Eén of beide nieuwe stroken zijn nog niet even lang als de oorspronkelijke breuk.');return}hints=0;goOperate()}
function goOperate(){s.phase=q.op==='+'?'add':'remove';$('wbMaterial').innerHTML=`<div class="wb-builds"><section class="wb-zone"><h4>${q.op==='+'?'Eerste gelijknamige breuk':'Tik stukken aan om weg te nemen'}</h4><div class="wb-bar" id="wbConvLeft"></div></section><section class="wb-zone"><h4>${q.op==='+'?'Tweede gelijknamige breuk':'Hoeveel moet weg?'}</h4><div class="wb-bar" id="wbConvRight"></div></section></div>`;if(q.op==='-'){$('wbStep').innerHTML=`<b>Stap 4 · Neem weg</b>Tik in de linker strook zelf evenveel stukken aan als in de rechter strook liggen.`;setTimeout(()=>document.querySelectorAll('#wbConvLeft .wb-piece').forEach((p,i)=>p.onclick=()=>{p.classList.toggle('removed');const removed=[...document.querySelectorAll('#wbConvLeft .wb-piece.removed')].length;s.removed=removed}),0)}else $('wbStep').innerHTML='<b>Stap 4 · Voeg samen</b>Tel de stukken van beide gelijknamige stroken samen.';$('wbCheck').hidden=false;$('wbCheck').textContent=q.op==='-'?'Klaar met wegnemen':'Naar mijn antwoord';$('wbCheck').onclick=()=>{const right=s.convRight.length;if(q.op==='-'&&s.removed!==right){feedback('Je nam nog niet precies de tweede breuk weg.');return}askAnswer()};feedback('De breuken zijn correct gelijknamig gemaakt.',true);bars()}
function askAnswer(){const left=s.convLeft.length,right=s.convRight.length,n=q.op==='+'?left+right:left-right,d=q.common;s.phase='answer';$('wbStep').innerHTML=`<b>Laatste stap · Vul zelf je antwoord in</b><div class="wb-answer"><input id="wbAnsN" type="number" aria-label="Teller antwoord"><span>—</span><input id="wbAnsD" type="number" aria-label="Noemer antwoord"><button id="wbAnswerCheck">Controleer</button></div><div id="wbFinal"></div>`;$('wbCheck').hidden=true;$('wbAnswerCheck').onclick=()=>{const an=+$('wbAnsN').value,ad=+$('wbAnsD').value;if(an!==n||ad!==d){feedback('Kijk opnieuw naar het aantal stukken en naar de naam van elk stuk.');return}const g=gcd(n,d),simple=g>1?` Je kunt nog vereenvoudigen tot ${n/g}/${d/g}.`:n===d?' Dat is precies 1 geheel.':'';$('wbFinal').innerHTML=`<div class="wb-result">✓ ${frac(q.a,q.d)} ${q.op} ${frac(q.b,q.e)} = ${frac(n,d)}.${simple}</div>`;feedback('Mooi! Jij hebt de oefening zelf met materiaal opgelost.',true)}}
function hint(){hints++;if(!q)return;if(s.phase==='build')feedback(hints===1?'De noemer zegt welk soort stuk je kiest. De teller zegt hoeveel stukken je legt.':hints===2?`Kijk eerst naar 1/${q.d} links en 1/${q.e} rechts.`:`Leg links ${q.a} stukken en rechts ${q.b} stukken. Jij moet ze nog zelf toevoegen.`);else if(s.phase==='common')feedback(hints===1?`Zoek een getal in de tafel van ${q.d} én in de tafel van ${q.e}.`:`Tel sprongen van ${q.d} en ${q.e}; waar kom je voor het eerst samen?`);else if(s.phase==='convert')feedback(hints===1?'De nieuwe strook moet exact even lang zijn als de oorspronkelijke.':`Elk stuk van 1/${q.d} wordt ${q.common/q.d} stukjes links; elk stuk van 1/${q.e} wordt ${q.common/q.e} stukjes rechts.`);else if(s.phase==='remove')feedback('De rechter strook toont hoeveel stukken je links moet aantikken.');else feedback('Tel de zichtbare gelijknamige stukken. De noemer blijft de naam van één stukje.')}
function wirePad(){const c=$('wbPad'),ctx=c.getContext('2d');const resize=()=>{const r=c.getBoundingClientRect(),old=document.createElement('canvas');old.width=c.width;old.height=c.height;old.getContext('2d').drawImage(c,0,0);c.width=Math.max(1,Math.round(r.width*devicePixelRatio));c.height=Math.max(1,Math.round(r.height*devicePixelRatio));ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.drawImage(old,0,0,old.width,old.height,0,0,r.width,r.height)};requestAnimationFrame(resize);const point=e=>{const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};c.onpointerdown=e=>{drawing=true;last=point(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=padMode==='eraser'?24:4;ctx.strokeStyle=padMode==='eraser'?'#fff':padColor;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};c.onpointerup=()=>drawing=false;document.querySelectorAll('[data-pad]').forEach(b=>b.onclick=()=>{padMode=b.dataset.pad;document.querySelectorAll('[data-pad]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{padColor=b.dataset.color;padMode='pen';document.querySelectorAll('[data-pad]').forEach(x=>x.classList.toggle('active',x.dataset.pad==='pen'))});$('wbClearPad').onclick=()=>ctx.clearRect(0,0,c.width,c.height)}
window.WorkbookFractions={open};
})();
