/* OV11 — doffe klank in voor- en achtervoegsels (graad 2). */
(function(){"use strict";
const CATS=["voorvoegsel-ge-g2","voorvoegsel-ver-g2","voorvoegsel-be-g2","achtervoegsel-elen-g2","achtervoegsel-eren-g2","achtervoegsel-ig-g2","achtervoegsel-lijk-g2"];
const M={naam:"ov11",graad:2,oefenvormenPerNiveau:["basis","kern","verdieping","uitbreiding"],_maxPerNiveau:{basis:8,kern:8,verdieping:12,uitbreiding:6},renderInstellingen(){return"";},
genereerBlad(opties,metAntwoorden){const o=opties?.ov11||opties||{},niveau=o.niveaus?.[0]||o.niveau||opties?.niveau||"basis",cfg={lijntype:o.lijntype||"type3",lijnhoogte:o.lijnhoogte||"middel"},max=this._maxPerNiveau[niveau]||8,woorden=this._kies(this._woorden(),Math.min(o.aantalWoorden||max,max));if(!woorden.length)return'<div class="werkblad ov11-blad"><p>Geen passende woorden gekozen.</p></div>';const sterren={basis:"⭐",kern:"⭐⭐",verdieping:"⭐⭐⭐",uitbreiding:"⭐⭐⭐⭐"}[niveau],uitleg={basis:["Lees de drie woorden.","Omcirkel het woord dat juist geschreven is.","Schrijf het juiste woord op de lijn."],kern:["Kijk welk woorddeel ontbreekt.","Vul het juiste voor- of achtervoegsel in.","Schrijf daarna het hele woord."],verdieping:["Lees de woorden.","Schrijf elk woord in de juiste kolom.","Kijk goed naar het voor- of achtervoegsel."],uitbreiding:["In elke zin staat een woord met een fout.","Streep het foute woord door.","Schrijf de volledige zin correct over."]}[niveau];const body=niveau==="basis"?this._basis(woorden,cfg,metAntwoorden):niveau==="kern"?this._kern(woorden,cfg,metAntwoorden):niveau==="verdieping"?this._verdieping(woorden,cfg,metAntwoorden):this._uitbreiding(woorden,cfg,metAntwoorden);return`<div class="werkblad ov11-blad lijnhoogte-${cfg.lijnhoogte}"><div class="ov01-header"><div class="ov01-naam-rij"><span>Naam:</span><span class="ov01-lijn-naam"></span><span>Datum:</span><span class="ov01-lijn-datum"></span></div><h2 class="ov01-titel">Doffe klank in woorddelen <span class="ov01-niveau-badge">${sterren}</span>${metAntwoorden?'<span class="oplossingen-badge">OPLOSSINGEN</span>':''}</h2></div><div class="ov01-stappen"><div class="ov01-stappen-label">Opdracht:</div>${uitleg.map(x=>`<div class="ov01-stap-rij"><span class="ov01-vakje"></span><span>${x}</span></div>`).join("")}</div>${body}<div class="ov01-voettekst">www.jufzisa.be — Juf Zisa's spellinggenerator</div></div>`},
_basis(ws,cfg,opl){return`<div class="ov11-grid">${ws.map(w=>{const ks=this._schud([w.tekst,...this._fouten(w).slice(0,2)]);return`<div class="ov11-kaart"><button class="rij-verwijder-knop" data-woord="${w.tekst}" type="button">✕</button><div class="ov11-keuzes">${ks.map(k=>`<span class="${opl&&k===w.tekst?'juist':''}">○ ${k}</span>`).join("")}</div>${this._lijn(cfg,opl?w.tekst:"")}</div>`}).join("")}</div>`},
_kern(ws,cfg,opl){return`<div class="ov11-grid">${ws.map(w=>{const d=this._deel(w),r=this._rest(w,d);return`<div class="ov11-kaart"><button class="rij-verwijder-knop" data-woord="${w.tekst}" type="button">✕</button><div class="ov11-aanvul">${w.voorvoegsel?'<span class="ov11-gat">…</span>'+r:r+'<span class="ov11-gat">…</span>'}</div><div class="ov11-deelkeuzes">${this._deelKeuzes(d).map(x=>`<span class="${opl&&x===d?'juist':''}">${x}</span>`).join("")}</div>${this._lijn(cfg,opl?w.tekst:"")}</div>`}).join("")}</div>`},
_verdieping(ws,cfg,opl){const ds=[...new Set(ws.map(w=>this._deel(w)))];return`<div class="ov11-woordbank">${ws.map(w=>w.tekst).join(" · ")}</div><div class="ov11-sorteer" style="--kolommen:${Math.min(ds.length,4)}">${ds.map(d=>{const voorbeeld=ws.find(w=>this._deel(w)===d),passend=ws.filter(w=>this._deel(w)===d).map(w=>w.tekst).join(", ");return`<section><h3>${voorbeeld?.voorvoegsel?d+'-':'-'+d}</h3><div class="ov11-sorteerlijnen">${opl?`<b>${passend}</b>`:Array.from({length:3},()=>this._lijn(cfg,"")).join("")}</div></section>`}).join("")}</div>`},
_uitbreiding(ws,cfg,opl){const zs=ws.slice(0,6).map((w,i)=>{const fout=this._fouten(w)[i%2],t=[`Ik schrijf het woord ${fout} op mijn blad.`,`In deze zin staat ${fout} niet juist geschreven.`,`De juf ziet het woord ${fout} op het bord.`][i%3];return{fout:t,juist:t.replace(fout,w.tekst)}});return`<div class="ov11-zinnen">${zs.map((z,i)=>`<div class="ov11-zin"><b>${i+1}.</b> <span>${z.fout}</span>${opl?`<div class="ov11-oplossing">${z.juist}</div>`:this._lijn(cfg,"")}</div>`).join("")}</div>`},
_woorden(){const raw=window._weekdictee_gekozenWoorden||[],bib=window.SpellingWoordenbibliotheek?.graad2||{};return raw.filter(w=>CATS.includes(w.categorie)).map(w=>({...w,...(bib[w.categorie]?.woorden?.find(x=>x.tekst===w.tekst)||{})}))},_deel(w){return w.voorvoegsel||w.achtervoegsel||""},_rest(w,d){return w.voorvoegsel?w.tekst.slice(d.length):w.tekst.slice(0,-d.length)},_fouten(w){const d=this._deel(w),r=this._rest(w,d),vs=w.voorvoegsel?[d.replace("e","i"),d.replace("e","u")]:[d.replace(/[ei]/,"a"),d.replace(/[ei]/,"u")];return vs.map(v=>w.voorvoegsel?v+r:r+v).filter(x=>x!==w.tekst)},_deelKeuzes(d){return this._schud([d,d.replace(/[ei]/,"a"),d.replace(/[ei]/,"u")].filter((x,i,a)=>x&&a.indexOf(x)===i))},_lijn(cfg,a){const c=window.SpellingSchrijflijnen?.htmlCanvas(cfg.lijntype,cfg.lijnhoogte,250)||'<span class="ov08-fallback-lijn-inline"></span>';return`<div class="ov11-lijn">${a?`<span>${a}</span>`:""}${c}</div>`},_kies(p,n){return this._schud([...p]).slice(0,n)},_schud(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}};
window.SpellingModules=window.SpellingModules||{};window.SpellingModules.ov11=M;
})();
