'use client';
import {useState} from 'react';
import {Wifi,Zap,Check,ArrowRight} from 'lucide-react';
import Listen from '@/components/listen';
export function Battery({level,charging=false}:{level:number;charging?:boolean}){return <span className={'ipad-battery '+(charging?'charging':level<=20?'low':'')} role="img" aria-label={`Batterij ${level} procent${charging?', wordt opgeladen':''}`}><span className="battery-outline"><span className="battery-amount" style={{width:`${level}%`}}/>{charging&&<Zap fill="currentColor" size={15}/>}</span><span className="battery-cap"/></span>;}
const rounds=[{prompt:'Je gaat een opdracht maken. Welke iPad moet eerst aan de lader?',levels:[85,9,55],charging:[false,false,false],correct:1,feedback:'De tweede iPad heeft nog maar een klein rood stukje batterij. Vraag hulp om hem op te laden.'},{prompt:'De kabel is aangesloten. Op welke iPad zie je dat de batterij oplaadt?',levels:[25,80,25],charging:[false,false,true],correct:2,feedback:'Het bliksemsymbool in de batterij toont dat deze iPad oplaadt.'},{prompt:'Welke iPad heeft de meeste batterij over?',levels:[32,94,11],charging:[false,false,false],correct:1,feedback:'De tweede batterij is bijna helemaal gevuld. Die iPad heeft van deze drie de meeste batterij over.'}];
export default function BatteryLab({onComplete}:{onComplete:()=>void}){
 const [round,setRound]=useState(0),[selected,setSelected]=useState<number|null>(null),[checked,setChecked]=useState(false),[finished,setFinished]=useState(false);
 const q=rounds[round],correct=checked&&selected===q.correct;
 const feedback=selected===q.correct?q.feedback:'Kijk nog eens naar de vulling en het symbool in de batterij.';
 if(finished)return <div className="battery-lab battery-final"><h2>Kijk nu op je eigen iPad.</h2><p>Waar staat de batterij? Is ze bijna leeg, halfvol of bijna vol? Vertel het aan je leerkracht.</p><Listen text="Kijk nu op je eigen iPad. Waar staat de batterij? Is ze bijna leeg, halfvol of bijna vol? Vertel het aan je leerkracht."/></div>;
 return <div className="battery-lab"><div className="lab-instruction"><h2>{q.prompt}</h2><Listen text={q.prompt}/></div><p className="battery-hint">Kijk rechtsboven. · Vraag {round+1} van {rounds.length}</p>
 <div className="battery-devices">{q.levels.map((level,n)=><div className={'battery-option '+(selected===n?'selected':'')} key={n}><button aria-label={`Kies iPad ${n+1}`} aria-pressed={selected===n} onClick={()=>{setSelected(n);setChecked(false);}}><span className="ipad-screen"><span className="ipad-status"><span>9:41</span><span><Wifi size={16}/><Battery level={level} charging={q.charging[n]}/></span></span><span className="ipad-example-content"><span>Tekenen</span><img src="/robot-vriendje.png" alt=""/></span><span className="ipad-home-indicator"/></span></button><div className="battery-option-footer"><strong>iPad {n+1}</strong><Listen text={`iPad ${n+1}. De batterij is ${level} procent gevuld.${q.charging[n]?' Er staat een bliksemsymbool in.':''}`} label={`Beluister iPad ${n+1}`}/></div></div>)}</div>
 <div className="battery-response">{checked?<div className={'exercise-feedback '+(correct?'good':'')} role="status"><p>{feedback}</p><Listen text={feedback}/></div>:<p className="battery-prompt">Tik op een iPad en controleer je antwoord.</p>}
 {correct?<button className="primary" onClick={()=>{if(round===rounds.length-1){setFinished(true);onComplete();}else{setRound(round+1);setSelected(null);setChecked(false);}}}>{round===rounds.length-1?'Mijn eigen iPad':'Volgende vraag'} <ArrowRight/></button>:<button className="primary check-answer" disabled={selected===null} onClick={()=>setChecked(true)}>Controleer <Check/></button>}</div>
 <small>Oefenschermen · dit zijn niet de batterijstanden van je eigen toestel.</small></div>;
}
