'use client';
import {useEffect,useRef,useState} from 'react';
import {Send,Download,Image as ImageIcon,Check,Printer} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import Listen from '@/components/listen';
type Card={name:string;image:string};
function pngBlob(data:string){const bytes=Uint8Array.from(atob(data.split(',')[1]),s=>s.charCodeAt(0));return new Blob([bytes],{type:'image/png'});}
export default function CardDelivery({card,pupil,dirty}:{card:Card;pupil:string;dirty:boolean}){
 const [url,setUrl]=useState(''),[open,setOpen]=useState(false),[preview,setPreview]=useState(false),[code,setCode]=useState(''),[name,setName]=useState(pupil),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[message,setMessage]=useState(''),[downloadMessage,setDownloadMessage]=useState('');const pending=useRef<{key:string;id:string}|null>(null),flight=useRef(false);
 useEffect(()=>{const u=URL.createObjectURL(pngBlob(card.image));setUrl(u);setSent(false);setMessage('');setDownloadMessage('');return()=>URL.revokeObjectURL(u);},[card.image]);
 useEffect(()=>{setName(pupil);setCode((new URLSearchParams(location.search).get('klas')??'').toUpperCase().slice(0,8));},[pupil]);
 function download(){if(!url)return;const a=document.createElement('a');a.href=url;a.download=card.name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setDownloadMessage('De download is aangevraagd. Kijk bij de downloads van je browser. Zie je niets? Gebruik Open afbeelding.');}
 async function submit(e:React.FormEvent){e.preventDefault();if(flight.current||dirty)return;const classCode=code.trim().toUpperCase(),pupilName=name.trim();if(!/^[A-Z2-9]{8}$/.test(classCode)||!pupilName){setMessage('Vul je voornaam en de klascode van 8 tekens in.');return;}flight.current=true;setBusy(true);setMessage('Je naamkaartje wordt verstuurd…');setSent(false);try{const im=new window.Image();im.src=card.image;await im.decode();const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=800;const ctx=canvas.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,1200,800);const scale=Math.min(1200/im.width,800/im.height),w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(1200-w)/2,(800-h)/2,w,h);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('De afbeelding kon niet worden gemaakt.')),'image/png'));const key=classCode+'|'+pupilName+'|'+card.image;if(pending.current?.key!==key){const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const s=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');pending.current={key,id:`${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`};}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch('/api/atelier/submit?'+new URLSearchParams({code:classCode,name:pupilName,id:pending.current.id}),{method:'POST',headers:{'Content-Type':'image/png'},body:blob,signal:controller.signal});const data=await response.json() as {ok?:boolean;error?:string};if(!response.ok||!data.ok)throw new Error(data.error??'Versturen is niet gelukt.');setSent(true);setMessage('Ontvangen! Je naamkaartje staat bij de werkjes van je klas. De juf kan het nu afdrukken.');}finally{clearTimeout(timer);}}catch(e){setMessage((e as Error).name==='AbortError'?'Het duurt te lang. Probeer opnieuw. Je kaartje blijft bewaard.':(e as Error).message==='Failed to fetch'?'Geen verbinding. Probeer opnieuw. Je kaartje blijft bewaard.':(e as Error).message);}finally{flight.current=false;setBusy(false);}}
 return <section className="card-delivery"><div><img src={card.image} alt="Je bewaarde naamkaartje"/><div><h3>Laat je naamkaartje afdrukken</h3><p>Stuur het naar de juf. Zij ontvangt het bij de werkjes van je klas.</p><Listen text="Stuur je naamkaartje naar de juf. Zij ontvangt het bij de werkjes van je klas en kan het afdrukken."/></div></div>{dirty&&<p className="save-error">Je hebt iets veranderd. Bewaar eerst je laatste wijzigingen.</p>}<div className="delivery-actions"><button className="primary" disabled={dirty} onClick={()=>{setOpen(true);if(!sent)setMessage('');}}><Send/> {sent?'Verstuurd naar de juf':'Stuur naar de juf'}</button><a className="card-download-link" href={dirty?undefined:url} download={card.name} aria-disabled={dirty||!url} onClick={e=>{if(dirty||!url){e.preventDefault();return;}setDownloadMessage("De download is aangevraagd. Kijk bij de downloads van je browser. Zie je niets? Gebruik Open afbeelding.");}}><Download/> Download afbeelding</a><button disabled={dirty} onClick={()=>setPreview(true)}><ImageIcon/> Open afbeelding</button></div>{downloadMessage&&<p className="download-status" role="status">{downloadMessage}</p>}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="ipad-confirm-dialog send-card-dialog" showCloseButton={false} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onPointerDownOutside={e=>{if(busy)e.preventDefault();}}><DialogTitle>Stuur naar de juf</DialogTitle><DialogDescription>Je juf ontvangt je naamkaartje en kan het afdrukken.</DialogDescription><img className="send-card-preview" src={card.image} alt="Naamkaartje om te versturen"/><form onSubmit={submit}><label>Jouw voornaam<input required maxLength={40} value={name} disabled={busy} onChange={e=>{setName(e.target.value);setSent(false);setMessage('');}}/></label><label>Klascode<input required value={code} maxLength={8} autoCapitalize="characters" autoComplete="off" disabled={busy} onChange={e=>{setCode(e.target.value.toUpperCase());setSent(false);setMessage('');}}/></label><Listen text="Vul de klascode van de juf in. Die code zorgt dat je naamkaartje bij de juiste klas terechtkomt. Druk daarna op Verstuur."/>{message&&<div className={'send-result '+(sent?'received':'')} role="status">{sent&&<Check/>}<p>{message}</p><Listen text={message}/></div>}<div className="delivery-actions"><button type="button" disabled={busy} onClick={()=>setOpen(false)}>{sent?'Klaar':'Annuleer'}</button><button type="submit" disabled={busy||sent}>{busy?'Versturen…':sent?'Ontvangen door de juf':'Verstuur'} <Send size={20}/></button></div></form></DialogContent></Dialog>
 <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="ipad-save-dialog card-image-dialog" showCloseButton={false}><DialogTitle>{card.name}</DialogTitle><DialogDescription>Dit is je bewaarde naamkaartje. Je kunt de afbeelding downloaden of in een apart tabblad openen.</DialogDescription><img src={card.image} alt={'Naamkaartje van '+pupil}/><div className="delivery-actions"><button onClick={download}><Download/> Download</button><a href={url} target="_blank" rel="noopener">Afbeelding in nieuw tabblad</a><button onClick={()=>setPreview(false)}>Sluiten</button></div>{downloadMessage&&<p role="status">{downloadMessage}</p>}</DialogContent></Dialog>
 </section>;
}
