'use client';
import {useEffect,useState} from 'react';
import * as I from 'lucide-react';
import Listen from '@/components/listen';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {missions,Task} from './lessons';
import FileLab from './file-lab';
import FileTypes from './file-types';
import BatteryLab from './battery-lab';
import RobotLab from './robot-lab';
const icons:Record<string,typeof I.Tablet>={tablet:I.Tablet,care:I.HandHeart,keyboard:I.Keyboard,folder:I.FolderOpen,tools:I.PencilRuler,robot:I.Bot,heart:I.Heart,'battery-full':I.BatteryFull,'battery-low':I.BatteryLow,'battery-medium':I.BatteryMedium,muted:I.VolumeX,stop:I.Square,hand:I.Hand,cup:I.CupSoda,edge:I.TriangleAlert,run:I.PersonStanding,plug:I.Plug,help:I.HandHelping,pencil:I.Pencil,palette:I.Palette,audio:I.AudioLines,video:I.Clapperboard,image:I.Image,book:I.BookOpen,ball:I.CircleDot,star:I.Star,happy:I.Smile,calm:I.Coffee,sad:I.Frown,eye:I.Eye};
export function Pic({name,size=56}:{name:string;size?:number}){if(['rd','dd','lu'].includes(name))return <span className="arrow-pic" aria-hidden="true">{name==='rd'?'→ ↓':name==='dd'?'↓ ↓':'← ↑'}</span>;const Icon=icons[name]??I.Sparkles;return <Icon size={size} aria-hidden="true"/>;}
export default function Discovery(){
 const [teacherOpen,setTeacherOpen]=useState(false);
 const [klass,setKlass]=useState('2A'),[age,setAge]=useState('7-8'),[mission,setMission]=useState<string|null>(null),[index,setIndex]=useState(0),[records,setRecords]=useState<Record<string,string>>({});
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.get('klasmap')==='1A')setKlass('1A');const requested=missions.find(m=>m.id===params.get('missie'));if(params.get('leeftijd')==='6-7')setAge('6-7');if(requested){if(requested.older)setAge('7-8');setMission(requested.id);}},[]);
 const current=missions.find(m=>m.id===mission);const task=current?.tasks[index];
 function mark(status:string){if(current&&task)setRecords(r=>({...r,[current.id+'/'+task.id]:status}));}
 return <div className="discover"><header className="discover-header"><a href="/"><I.House size={23}/> Missies</a><strong>Zisa’s digitale missies</strong><button className="teacher-open" onClick={()=>setTeacherOpen(true)}><I.GraduationCap size={22}/><span>Leerkracht</span></button></header>
 <main className={"discover-main"+(current?" is-working":"")}><Dialog open={teacherOpen} onOpenChange={setTeacherOpen}><DialogContent className="discovery-teacher-dialog"><DialogTitle>Voor de leerkracht</DialogTitle><DialogDescription>Instellingen en observaties bij dit oefenmoment.</DialogDescription><div className="teacher-body"><p><a href="/doelen">Leerplandoelen van alle missies bekijken</a></p>{current&&task&&<details className="observe"><summary>Observatie door de leerkracht</summary><p>Leerplandoelen: {current.goals}</p><div>{['Met hulp gelukt','Zelfstandig gelukt','Nog oefenen'].map(s=><button key={s} aria-pressed={records[current.id+'/'+task.id]===s} onClick={()=>mark(s)}>{s}</button>)}</div></details>}<label>Leeftijd <select value={age} onChange={e=>{setAge(e.target.value);setMission(null);setIndex(0);}}><option value="6-7">6–7 jaar</option><option value="7-8">7–8 jaar</option></select></label><label>Klasmap <select value={klass} onChange={e=>{setKlass(e.target.value);setMission(null);setIndex(0);}}><option value="1A">1A</option><option value="2A">2A</option></select></label><p>Bij het bewaren kiezen kinderen eerst hun klasmap en daarna de juiste map voor hun werkje.</p><p>De oefenmap met bestanden verschijnt alleen bij 7–8 jaar. Opdrachten voor beide leeftijden kunnen samen worden voorgedaan op het bord.</p><p>Een antwoord oefenen is nog geen bewijs van beheersing. Noteer bij praktische opdrachten wat je werkelijk hebt gezien. De observaties hieronder gelden voor dit oefenmoment en verdwijnen bij herladen. De oefenmap bewaart haar bestanden uitsluitend in deze browser.</p><button onClick={()=>window.print()}><I.Printer/> Print observaties</button><div className="observations"><table><thead><tr><th>Missie / opdracht</th><th>Observatie</th></tr></thead><tbody>{missions.filter(m=>!m.older||age==='7-8').flatMap(m=>m.tasks.map(t=><tr key={m.id+t.id}><td>{m.title} · {t.title}</td><td>{records[m.id+'/'+t.id]??'Nog niet geobserveerd'}</td></tr>))}</tbody></table></div></div></DialogContent></Dialog>
 {!current?<><div className="discovery-heading"><div><p>Ontdekken & oefenen · {age.replace('-','–')} jaar</p><h1>Kies je nieuwe missie</h1></div><img src="/robot-vriendje.png" alt=""/></div><div className="discovery-tiles">{missions.filter(m=>!m.older||age==='7-8').map(m=><div className={'discovery-tile '+m.color} key={m.id}><button onClick={()=>{setMission(m.id);setIndex(0);}}><Pic name={m.icon} size={76}/><h2>{m.title}</h2><span>{m.tasks.length===1?'6 stappen':`${m.tasks.length} opdrachten`} <I.ArrowRight size={20}/></span></button><Listen text={m.title} label={'Beluister '+m.title}/></div>)}</div></>:
 <><div className="lesson-toolbar"><button className="back-missions" onClick={()=>{location.href='/?leeftijd='+age;}}><I.ArrowLeft size={20}/> Andere missie</button><div className="lesson-nav"><button disabled={index===0} onClick={()=>setIndex(index-1)} aria-label="Vorige opdracht"><I.ChevronLeft/></button><div><span>{current.title}</span><p>Opdracht {index+1} van {current.tasks.length}</p></div><button disabled={index===current.tasks.length-1} onClick={()=>setIndex(index+1)} aria-label="Volgende opdracht"><I.ChevronRight/></button></div></div>
 {task&&<section key={current.id+task.id} className={'lesson '+current.color+' kind-'+task.kind+' task-'+task.id}><div className="lesson-question"><Pic name={current.icon} size={43}/><div><h1>{task.title}</h1><p>{task.prompt}</p></div><Listen text={task.title+'. '+task.prompt}/></div><Activity task={task} mark={mark} klass={klass}/></section>}
 <div className="lesson-bottom"><span>{task&&records[current.id+'/'+task.id]}</span><button className="primary" onClick={()=>index<current.tasks.length-1?setIndex(index+1):(location.href='/?leeftijd='+age)}>{index<current.tasks.length-1?'Volgende opdracht':'Terug naar missies'} <I.ArrowRight/></button></div></>}
 </main></div>;
}
function Activity({task,mark,klass}:{task:Task;mark:(s:string)=>void;klass:string}){
 const [selected,setSelected]=useState<number[]>([]),[message,setMessage]=useState(''),[success,setSuccess]=useState(false),[value,setValue]=useState(task.initial??''),[sequence,setSequence]=useState<number[]>([]);
 const [order]=useState(()=>task.steps?.map((_,i)=>i).reverse()??[]);
 function result(ok:boolean){setSuccess(ok);setMessage(ok?task.feedback:'Nog niet helemaal. Kijk en luister nog eens. Je mag je antwoord aanpassen.');if(ok)mark(task.kind==='feel'?'Gevoel besproken: nog observeren':'Digitaal geoefend: nog observeren');}
 function check(){if(task.kind==='order'){result(sequence.length===task.steps?.length&&sequence.every((v,i)=>v===i));return;}if(task.kind==='type'){const s=value.trim();result(task.target==='name'?/\p{L}/u.test(s):task.target==='age'?/^Ik ben [678] jaar\.$/.test(s):s===task.target);return;}result(selected.length===(task.correct?.length??0)&&selected.every(n=>task.correct?.includes(n)));}
 const feedback=<>{message&&<div className={'exercise-feedback '+(success?'good':'')} role="status"><p>{message}</p><Listen text={message}/></div>}</>;
 if(task.id==='batterij')return <BatteryLab onComplete={()=>mark('Batterij herkennen geoefend: nog observeren')}/>;
 if(task.kind==='filetypes')return <FileTypes onComplete={()=>mark('Bestandstypes geoefend: nog observeren')}/>;
 if(task.kind==='files')return <FileLab klass={klass} onComplete={()=>mark('Oefenmap doorlopen: nog observeren')}/>;
 if(task.kind==='robot')return <RobotLab task={task} onComplete={()=>mark('Robotroute geoefend: nog observeren')}/>;
 if(task.kind==='do')return <div className="practical"><I.PersonStanding size={76}/><h2>Nu doe jij het!</h2><p>Leg je toestel veilig neer als je het niet nodig hebt.</p><button className="primary" onClick={()=>{setMessage(task.feedback);mark('Uitgevoerd volgens leerling: nog observeren');setSuccess(true);}}>Ik heb het gedaan <I.Check/></button>{feedback}</div>;
 if(task.kind==='input')return <div className="typing"><label htmlFor="letter">Typ één letter</label><input id="letter" maxLength={1} value={value} autoComplete="off" onChange={e=>{setValue(e.target.value);setMessage('');}}/><div className="processing"><span><I.Keyboard/> Ik typ <b>{value||'…'}</b></span><I.ArrowRight/><span><I.Cpu/> Het toestel verwerkt</span><I.ArrowRight/><span><I.Monitor/> Ik zie <b>{value||'…'}</b></span></div><Listen text={task.feedback}/><p>{task.feedback}</p></div>;
 return <div className="activity">
 {task.kind==='type'?<div className="typing">{task.target==='5'&&<I.Dice5 size={90}/>}<label htmlFor="answer">Jouw tekst</label><input id="answer" value={value} onChange={e=>{setValue(e.target.value);setMessage('');setSuccess(false);}} autoComplete="off" autoCapitalize="off" spellCheck={false}/>{task.target&&!['name','age','5','maas'].includes(task.target)&&<p className="copy-example">Voorbeeld: <strong>{task.target}</strong></p>}</div>:
 task.kind==='order'?<><div className="ordered-steps" aria-live="polite">{sequence.length?sequence.map((n,i)=><span key={n}>{i+1}. {task.steps?.[n]}</span>):<span>Tik hieronder op wat eerst gebeurt.</span>}</div><div className="answer-grid">{order.map(n=><div className="answer-card" key={n}><button disabled={sequence.includes(n)} onClick={()=>{setSequence(s=>[...s,n]);setMessage('');}}><I.ListOrdered size={45}/>{task.steps?.[n]}</button><Listen text={task.steps?.[n]??''}/></div>)}</div><button onClick={()=>{setSequence([]);setMessage('');}}>Opnieuw ordenen <I.RotateCcw size={20}/></button></>:
 <><p className="choice-hint">{task.kind==='feel'?'Kies wat bij jou past.':(task.correct?.length??0)>1?'Kies alle antwoorden die passen.':'Kies één antwoord.'}</p><div className="answer-grid">{task.choices?.map((c,n)=><div className={'answer-card '+(selected.includes(n)?'selected':'')} key={n}><button aria-pressed={selected.includes(n)} onClick={()=>{setMessage('');setSuccess(false);setSelected(s=>task.kind==='feel'||task.correct?.length===1?[n]:s.includes(n)?s.filter(x=>x!==n):[...s,n]);if(task.kind==='feel'){setMessage(task.feedback);setSuccess(true);mark('Gevoel gekozen: nog bespreken');}}}><Pic name={c.icon}/><span>{c.text}</span>{selected.includes(n)&&<I.Check className="answer-check" size={23}/>}</button><Listen text={c.text} label={'Beluister antwoord: '+c.text}/></div>)}</div></>}
 {task.kind!=='feel'&&<button className="primary check-answer" disabled={task.kind==='type'?!value.trim():task.kind==='order'?!sequence.length:!selected.length} onClick={check}>Controleer <I.Check/></button>}{feedback}
 </div>;
}
