'use client';
import {useEffect,useRef,useState} from 'react';
import {Folder,FolderOpen,FileText,Image as ImageIcon,Share,Save,X,Trash2,Star,Check,ArrowRight,ChevronLeft,ChevronRight,Tablet,Search,MoreHorizontal,Undo2,Pencil,Printer} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import Listen from '@/components/listen';
import CardDelivery from './card-delivery';
type Work={id:string;name:string;folder:string;image:string;trash?:boolean};
const ROOT='Op mijn iPad';
const folders:Record<string,string[]>={[ROOT]:['1A','2A','Downloads'],[ROOT+'/1A']:['Tekeningen','Verhalen'],[ROOT+'/2A']:['Tekeningen','Verhalen']};
const makeInstructions=(klass:string)=>['Maak een naamkaartje voor op je bank. Typ je voornaam en teken er iets bij.',`Bewaar je kaartje. Geef het een herkenbare naam en kies Op mijn iPad → ${klass} → Tekeningen.`,'Sluit je naamkaartje met het kruisje.','Open Bestanden. Zoek zelf de map waarin je jouw naamkaartje hebt bewaard. Open het kaartje.','Voeg een ster toe en bewaar opnieuw met dezelfde naam. Vervang de vorige versie.','Ruim de map op. Verplaats alleen oefenkladje.png naar Recent verwijderd.'];
export default function FileLab({onComplete,klass}:{onComplete:()=>void;klass:string}){
 const TARGET=ROOT+'/'+klass+'/Tekeningen',instructions=makeInstructions(klass);
 const [receipt,setReceipt]=useState<Work|null>(null),[stage,setStage]=useState(0),[files,setFiles]=useState<Work[]>([]),[ready,setReady]=useState(false),[pupil,setPupil]=useState(''),[drawing,setDrawing]=useState(false),[dirty,setDirty]=useState(false),[opened,setOpened]=useState(true),[current,setCurrent]=useState<Work|null>(null),[path,setPath]=useState(ROOT),[browser,setBrowser]=useState(false),[saveOpen,setSaveOpen]=useState(false),[savePath,setSavePath]=useState(ROOT),[filename,setFilename]=useState('Naamloos'),[pending,setPending]=useState(''),[replace,setReplace]=useState<Work|null>(null),[closeAsk,setCloseAsk]=useState(false),[deleteTarget,setDeleteTarget]=useState<Work|null>(null),[notice,setNotice]=useState(''),[saved,setSaved]=useState(false),[closed,setClosed]=useState(false),[reopened,setReopened]=useState(false),[starred,setStarred]=useState(false),[updated,setUpdated]=useState(false),[deleted,setDeleted]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),pen=useRef(false),draft=useRef(''),seed=useRef(false);
 useEffect(()=>{try{const raw=localStorage.getItem('zisa-files-v2');if(raw){const list=JSON.parse(raw);if(Array.isArray(list))setFiles(list.filter((w:Work)=>typeof w.id==='string'&&typeof w.name==='string'&&typeof w.folder==='string'&&typeof w.image==='string').map((w:Work)=>({...w,folder:w.folder.replace(/^Op mijn iPad\/Zisa(?=\/|$)/,ROOT+'/'+klass)})));}}catch{setError('Je browser kan de oefenmap niet laden. Vraag hulp.');}setReady(true);},[]);
 useEffect(()=>{if(!ready||seed.current)return;seed.current=true;setFiles(old=>old.some(f=>f.id==='oefenkladje')?old.map(f=>f.id==='oefenkladje'?{...f,trash:false,folder:TARGET}:f):[...old,{id:'oefenkladje',name:'oefenkladje.png',folder:TARGET,image:''}]);},[ready]);
 useEffect(()=>{if(!opened||!canvas.current)return;const ctx=canvas.current.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,760,380);if(draft.current){const im=new window.Image();let live=true;im.onload=()=>{if(live)ctx.drawImage(im,0,0,760,380);};im.src=draft.current;return()=>{live=false;};}},[opened]);
 function persist(next:Work[]){try{localStorage.setItem('zisa-files-v2',JSON.stringify(next));setFiles(next);setError('');return true;}catch{setError('Bewaren is niet gelukt. Er is mogelijk geen ruimte of browseropslag beschikbaar. Vraag hulp en probeer opnieuw.');return false;}}
 function capture(){const c=canvas.current;if(!c)return draft.current;const out=document.createElement('canvas');out.width=760;out.height=480;const ctx=out.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,760,480);ctx.drawImage(c,0,100);ctx.fillStyle='#334977';ctx.font='bold 54px Arial';ctx.textAlign='center';ctx.fillText(pupil.trim(),380,70,710);return out.toDataURL('image/png');}
 function requestSave(){if(!canvas.current)return;draft.current=canvas.current.toDataURL('image/png');setPending(capture());setFilename(current?current.name.replace(/\.png$/i,''):'Naamloos');setSavePath(current?.folder??ROOT);setSaveOpen(true);setReplace(null);setError('');}
 function commitSave(existing?:Work){const clean=filename.trim().replace(/\.png$/i,'');if(!clean||/[\\/:*?"<>|]/.test(clean)){setError('Typ een bestandsnaam zonder / of andere bijzondere tekens.');return;}if(clean.toLowerCase()==='naamloos'){setError('Kies een herkenbare naam, bijvoorbeeld: naamkaartje Noor.');return;}const clash=files.find(f=>!f.trash&&f.folder===savePath&&f.name.toLowerCase()===(clean+'.png').toLowerCase());if(clash&&!existing){setReplace(clash);return;}const w:Work={id:existing?.id??('werk-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)),name:clean+'.png',folder:savePath,image:pending};if(!persist([...files.filter(f=>f.id!==w.id),w]))return;setCurrent(w);setDirty(false);setSaveOpen(false);setReplace(null);setReceipt(w);if(savePath===TARGET){setSaved(true);if(stage===4&&starred&&existing)setUpdated(true);setNotice(`Bewaard in ${klass} → Tekeningen als ${w.name}.`);}else{setSaved(false);setUpdated(false);setNotice(`Je bestand is bewaard, maar nog niet in de gevraagde map. Kies de klasmap ${klass} en daarna Tekeningen.`);}}
 function closeDocument(){if(dirty){setCloseAsk(true);return;}doClose();}
 function doClose(){setOpened(false);setClosed(true);setBrowser(false);setPath(ROOT);setCloseAsk(false);setNotice('Je kaartje is gesloten. Open Bestanden om het terug te vinden.');}
 function openFile(w:Work){if(!w.image){setNotice('Dit is het oefenkladje. Zoek je naamkaartje.');return;}if(w.id!==current?.id){setNotice('Dit is een ander kaartje. Zoek het bestand dat je zonet hebt bewaard.');return;}const im=new window.Image();im.onload=()=>{const out=document.createElement('canvas');out.width=760;out.height=380;out.getContext('2d')!.drawImage(im,0,100,760,380,0,0,760,380);draft.current=out.toDataURL('image/png');setOpened(true);setBrowser(false);setReopened(true);setDirty(false);setNotice('Je hebt je bewaarde naamkaartje teruggevonden.');};im.onerror=()=>setError('Dit bestand kon niet geopend worden.');im.src=w.image;}
 function pointer(e:React.PointerEvent<HTMLCanvasElement>,start=false){if(stage===2||stage===3)return;const c=e.currentTarget,ctx=c.getContext('2d')!;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*760/r.width,y=(e.clientY-r.top)*380/r.height;if(start){pen.current=true;c.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+.1,y+.1);}else if(pen.current)ctx.lineTo(x,y);else return;ctx.strokeStyle='#65519c';ctx.lineWidth=6;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();setDrawing(true);setDirty(true);setUpdated(false);}
 function addStar(){const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.fillStyle='#dea20c';ctx.font='74px Arial';ctx.fillText('★',630,80);setStarred(true);setDirty(true);setUpdated(false);}
 const canNext=[pupil.trim().length>0&&drawing,saved&&!dirty,closed,reopened,updated&&!dirty,deleted][stage];
 function folderArea(at:string,change:(s:string)=>void,saving=false){const children=folders[at]??[];const visible=files.filter(f=>at==='Recent verwijderd'?f.trash:!f.trash&&f.folder===at).filter(f=>f.name.toLowerCase().includes(filter.toLowerCase()));return <div className="finder"><aside><p>Locaties</p><button onClick={()=>{change(ROOT);setFilter('');}}><Tablet/> Op mijn iPad</button>{!saving&&<button onClick={()=>{change('Recent verwijderd');setFilter('');}}><Trash2/> Recent verwijderd</button>}</aside><div className="finder-main"><div className="finder-navigation"><button disabled={at===ROOT||at==='Recent verwijderd'} onClick={()=>{change(at.split('/').slice(0,-1).join('/')||ROOT);setFilter('');}} aria-label="Bovenliggende map"><ChevronLeft/></button><strong>{at.split('/').at(-1)}</strong><MoreHorizontal/></div><p className="finder-path">{at.replaceAll('/',' › ')}</p>{!saving&&<label className="finder-search"><Search size={20}/><input aria-label="Zoek in deze map" placeholder="Zoek in deze map" value={filter} onChange={e=>setFilter(e.target.value)}/></label>}<div className="finder-grid">{children.map(child=><button className="finder-item folder-item" key={child} onClick={()=>{change(at+'/'+child);setFilter('');}}><Folder size={65} fill="#64bdff" strokeWidth={1}/><span>{child}</span></button>)}{!saving&&visible.map(w=><div className="finder-file" key={w.id}><button className="finder-item" onClick={()=>openFile(w)}>{w.image?<img src={w.image} alt=""/>:<FileText size={60}/>}<span>{w.name}</span></button>{stage===5&&!w.trash&&<button className="file-trash" aria-label={'Verwijder '+w.name} onClick={()=>setDeleteTarget(w)}><Trash2 size={20}/></button>}{w.trash&&<button onClick={()=>{if(persist(files.map(f=>f.id===w.id?{...f,trash:false}:f))){setNotice('Bestand teruggezet in de oorspronkelijke map.');if(w.id==='oefenkladje')setDeleted(false);}}}><Undo2 size={18}/> Zet terug</button>}</div>)}{!children.length&&(saving||!visible.length)&&<p className="empty-folder">{saving?'Je kunt je bestand in deze map bewaren.':'Deze map is leeg.'}</p>}</div></div></div>;}
 return <div className="file-lab"><div className="file-steps">{instructions.map((_,i)=><span key={i} className={i===stage?'active':i<stage?'done':''}>{i+1}</span>)}</div><div className="lab-instruction"><h2>{instructions[stage]}</h2><Listen text={instructions[stage]}/></div><div className="files-practice-label">Bestanden · oefenomgeving</div>
 {stage<5&&opened?<div className="card-editor"><div className="editor-bar"><button className="disk-save" onClick={requestSave} disabled={!ready||!pupil.trim()||!drawing} aria-label="Bewaar naamkaartje"><Save size={26}/> Bewaar</button><strong>{current?.name??'Nieuw naamkaartje'}</strong><span className={'document-save-state '+(dirty?'unsaved':'saved')}>{dirty?'Nog niet bewaard':current?<><Check size={18}/> Bewaard</>:'Nieuw bestand'}</span><button onClick={closeDocument} disabled={stage<2||stage===4} aria-label="Sluit naamkaartje"><X/></button></div><label className="card-name">{stage<2?<><span>Jouw voornaam</span><input value={pupil} placeholder="Typ je voornaam" maxLength={24} onChange={e=>{setPupil(e.target.value);setDirty(true);setSaved(false);}}/></>:<strong>{pupil}</strong>}</label><canvas ref={canvas} width={760} height={380} className="file-canvas" aria-label="Teken iets op je naamkaartje" onPointerDown={e=>pointer(e,true)} onPointerMove={e=>pointer(e)} onPointerUp={()=>pen.current=false} onPointerCancel={()=>pen.current=false}/><div className="file-toolbar"><Pencil size={20}/><span>Teken met je vinger.</span>{stage===4&&<button disabled={starred} onClick={addStar}><Star/> Voeg een ster toe</button>}</div></div>:<>{!browser&&stage<5?<div className="open-files-app"><button onClick={()=>{setBrowser(true);setPath(ROOT);}}><Folder fill="#64bdff" size={68}/><strong>Bestanden</strong></button></div>:folderArea(path,setPath)}</>}
 {notice&&<div className="exercise-feedback" role="status"><p>{notice}</p><Listen text={notice}/></div>}{error&&!saveOpen&&<p className="save-error" role="alert">{error}</p>}
 {stage<5?<button className="primary" disabled={!canNext} onClick={()=>{setStage(stage+1);setNotice('');if(stage===4){setOpened(false);setBrowser(true);setPath(ROOT);}}}>Volgende stap <ArrowRight/></button>:deleted&&<div className="exercise-feedback good"><p>Je naamkaartje is bewaard en je map is opgeruimd.</p><Listen text="Je naamkaartje is bewaard en je map is opgeruimd."/></div>}
 {current&&<details className="delivery-fold"><summary>Stuur naar de juf of download je kaartje</summary><CardDelivery card={current} pupil={pupil} dirty={dirty}/></details>}
 <Dialog open={saveOpen} onOpenChange={v=>{setSaveOpen(v);if(!v)setReplace(null);}}><DialogContent className="ipad-save-dialog" showCloseButton={false}><div className="save-sheet-top"><button onClick={()=>setSaveOpen(false)}>Annuleer</button><DialogTitle>Bewaar in Bestanden</DialogTitle><button className="save-sheet-action" onClick={()=>commitSave()}><Save size={21}/> Bewaar</button></div><DialogDescription className="save-help">Geef je kaartje een naam en kies de map waarin je het wilt bewaren.</DialogDescription><div className="save-name-row"><ImageIcon size={30}/><label htmlFor="save-filename">Bestandsnaam<input id="save-filename" value={filename} maxLength={70} autoComplete="off" onChange={e=>{setFilename(e.target.value);setReplace(null);setError('');}}/></label><span>.png</span><Listen text={`Geef je bestand een herkenbare naam. Open daarna Op mijn iPad, ${klass} en Tekeningen. Tik bovenaan op Bewaar.`}/></div>{folderArea(savePath,p=>{setSavePath(p);setReplace(null);},true)}{error&&<p className="save-error" role="alert">{error}</p>}{replace&&<div className="replace-question" role="group" aria-label="Bestand bestaat al"><h3>Dit bestand bestaat al.</h3><p>Wil je ‘{replace.name}’ vervangen door je nieuwe versie?</p><Listen text={'Dit bestand bestaat al. Wil je '+replace.name+' vervangen door je nieuwe versie?'}/><div><button onClick={()=>setReplace(null)}>Annuleer</button><button onClick={()=>commitSave(replace)}>Vervang</button></div></div>}<p className="save-simulation-note">Oefenomgeving van Zisa</p></DialogContent></Dialog>
 <Dialog open={!!receipt} onOpenChange={v=>{if(!v)setReceipt(null);}}><DialogContent className="ipad-confirm-dialog saved-receipt" showCloseButton={false}><DialogTitle><Check/> Je naamkaartje is bewaard</DialogTitle><DialogDescription>Je bestand staat nu in deze map:</DialogDescription><p className="saved-location">{receipt?.folder.replaceAll('/',' → ')}</p>{receipt&&<img src={receipt.image} alt="Het naamkaartje dat zojuist bewaard is"/>}<strong>{receipt?.name}</strong><Listen text={'Je naamkaartje is bewaard als '+(receipt?.name??'')+'. In de map '+(receipt?.folder.split('/').at(-1)??'')+'. Je kunt het nu sluiten en terugvinden.'}/><button onClick={()=>setReceipt(null)}>Verder werken</button></DialogContent></Dialog>
 <Dialog open={closeAsk} onOpenChange={setCloseAsk}><DialogContent className="ipad-confirm-dialog" showCloseButton={false}><DialogTitle>Wijzigingen bewaren?</DialogTitle><DialogDescription>Je laatste wijzigingen zijn nog niet bewaard.</DialogDescription><Listen text="Je laatste wijzigingen zijn nog niet bewaard. Wil je teruggaan, bewaren of sluiten zonder bewaren?"/><button onClick={()=>setCloseAsk(false)}>Ga terug</button><button onClick={()=>{setCloseAsk(false);requestSave();}}>Bewaar eerst</button><button onClick={()=>{setDirty(false);draft.current='';doClose();}}>Sluit zonder bewaren</button></DialogContent></Dialog>
 <Dialog open={!!deleteTarget} onOpenChange={v=>{if(!v)setDeleteTarget(null);}}><DialogContent className="ipad-confirm-dialog" showCloseButton={false}><DialogTitle>Verwijder bestand?</DialogTitle><DialogDescription>‘{deleteTarget?.name}’ gaat naar Recent verwijderd.</DialogDescription><Listen text={`Wil je ${deleteTarget?.name??'dit bestand'} verwijderen? Controleer of je het oefenkladje hebt gekozen.`}/><button onClick={()=>setDeleteTarget(null)}>Annuleer</button><button onClick={()=>{if(!deleteTarget)return;if(deleteTarget.id!=='oefenkladje'){setNotice('Bewaar je naamkaartje. De opdracht vraagt alleen het oefenkladje te verwijderen.');setDeleteTarget(null);return;}if(persist(files.map(f=>f.id===deleteTarget.id?{...f,trash:true}:f))){setDeleted(true);setDeleteTarget(null);setNotice('Het oefenkladje staat nu bij Recent verwijderd. Je naamkaartje blijft in Tekeningen.');onComplete();}}}>Verwijder</button></DialogContent></Dialog>
 </div>;
}
