'use client';
import {useEffect,useState} from 'react';
import {ArrowUp,ArrowRight,ArrowDown,ArrowLeft,Play,Square,RotateCcw,Trash2,Star,Flower2} from 'lucide-react';
import Listen from '@/components/listen';
import {Task} from './lessons';
const moves=[{x:0,y:-1,name:'Omhoog',Icon:ArrowUp},{x:1,y:0,name:'Rechts',Icon:ArrowRight},{x:0,y:1,name:'Omlaag',Icon:ArrowDown},{x:-1,y:0,name:'Links',Icon:ArrowLeft}];
export default function RobotLab({task,onComplete}:{task:Task;onComplete:()=>void}){
 const initial=task.id==='fout'?[1,1,2,3]:task.id==='voorspel'?[1,2,1,2]:[];
 const [plan,setPlan]=useState<number[]>(initial),[pos,setPos]=useState({x:0,y:0}),[active,setActive]=useState(-1),[running,setRunning]=useState(false),[selected,setSelected]=useState<number|null>(null),[prediction,setPrediction]=useState<number|null>(null),[flower,setFlower]=useState(false),[message,setMessage]=useState(''),[split,setSplit]=useState<number|null>(null);
 const target=task.id==='voorspel'||task.id==='fout'?{x:2,y:2}:{x:2,y:1};
 useEffect(()=>{if(!running)return;const timer=setTimeout(()=>{const next=active+1;if(next>=plan.length){setRunning(false);const ok=pos.x===target.x&&pos.y===target.y&&(task.id!=='delen'||flower)&&(task.id!=='voorspel'||prediction===pos.y*3+pos.x);setMessage(ok?task.feedback:task.id==='voorspel'?'Vergelijk het eindvak met je voorspelling. Probeer opnieuw.':'De robot is nog niet op de juiste plek. Verander je plan en test opnieuw.');if(ok)onComplete();return;}const d=moves[plan[next]],x=pos.x+d.x,y=pos.y+d.y;setActive(next);if(x<0||x>2||y<0||y>2){setRunning(false);setMessage('Deze stap gaat buiten het veld. Verander de pijl.');return;}setPos({x,y});if(x===2&&y===0)setFlower(true);},650);return()=>clearTimeout(timer);},[running,active,plan,pos,flower,prediction,task,onComplete,target.x,target.y]);
 function reset(){setPos({x:0,y:0});setActive(-1);setRunning(false);setFlower(false);setMessage('');}
 function add(n:number){reset();setPlan(p=>selected===null?[...p,n]:p.map((v,i)=>i===selected?n:v));setSelected(null);}
 return <div className="robot-lab"><p>Elke pijl is één vakje. De pijlen wijzen naar de rand van het scherm.</p><div className="mini-grid">{Array.from({length:9},(_,i)=>{const x=i%3,y=Math.floor(i/3);return <button key={i} disabled={task.id!=='voorspel'||running} aria-label={`Rij ${y+1}, kolom ${x+1}`} aria-pressed={prediction===i} className={prediction===i?'predicted':''} onClick={()=>{setPrediction(i);reset();}}>{task.id!=='voorspel'&&x===target.x&&y===target.y&&<Star className="grid-goal" fill="currentColor"/>}{task.id==='delen'&&x===2&&y===0&&<Flower2 className="grid-flower"/>}{x===pos.x&&y===pos.y&&<img src="/robot-vriendje.png" alt="Robot"/>}</button>;})}</div>
 <div className="robot-lab-controls">{task.id==='voorspel'&&<p>{prediction===null?'Tik op het vakje waar je denkt dat de robot stopt.':'Je voorspelling staat omrand. Test nu het plan.'}</p>}
 <div className="robot-plan">{plan.length?plan.map((n,i)=>{const Icon=moves[n].Icon;return <span key={i}>{split===i&&<b className="plan-divider">Daarna</b>}<button className={active===i?'walking':''} disabled={running||task.id==='voorspel'} aria-pressed={selected===i} aria-label={`Stap ${i+1}: ${moves[n].name}. Tik om te vervangen.`} onClick={()=>setSelected(i)}><small>{i+1}</small><Icon/></button></span>}):<p>Maak eerst je plan.</p>}</div>
 {task.id!=='voorspel'&&<><p>{selected===null?'Tik op een pijl om een stap toe te voegen.':'Kies een nieuwe pijl voor de gekozen stap.'}</p><div className="direction-buttons">{moves.map((m,n)=><button key={n} aria-label={m.name} disabled={running||plan.length>=20&&selected===null} onClick={()=>add(n)}><m.Icon size={30}/></button>)}<button disabled={running||!plan.length} aria-label="Wis gekozen of laatste stap" onClick={()=>{reset();const n=selected??plan.length-1;setPlan(p=>p.filter((_,i)=>i!==n));setSelected(null);setSplit(null);}}><Trash2/></button></div>{task.id==='delen'&&<button disabled={running||!plan.length||split!==null} onClick={()=>{setSplit(plan.length);setSelected(null);}}>Mijn plan tot de bloem is klaar <Flower2/></button>}<button disabled={running||selected===null} onClick={()=>setSelected(null)}>Voeg achteraan toe</button></>}
 <div className="robot-actions"><button className="primary" disabled={running||!plan.length||task.id==='voorspel'&&prediction===null} onClick={()=>{reset();setSelected(null);setRunning(true);}}><Play/> Test mijn plan</button><button disabled={!running} onClick={()=>{setRunning(false);setMessage('Gestopt. Pas je plan aan of test opnieuw vanaf de start.');}}><Square/> Stop</button><button aria-label="Zet robot terug bij de start" onClick={reset}><RotateCcw/></button></div>
 {message&&<div className="exercise-feedback" role="status"><p>{message}</p><Listen text={message}/></div>}</div></div>;
}
