const $=id=>document.getElementById(id), mod=(n,b)=>((n%b)+b)%b;
let time=860,mode='lesson',game=null,drag=null;
const visible={numbers:true,minutes:true,outer:true,zones:true,digital:true,words:true,hourArc:false,minuteArc:false};
const labels={numbers:'Uurgetallen · 1 t/m 12',minutes:'Minuten · 5, 10, 15…',outer:'24 uur · buitenste ring',zones:'Hulpwoorden en kleurvakken',digital:'Digitale tijd',words:'Tijd in woorden',hourArc:'Rode hulprand · uren',minuteArc:'Blauwe hulprand · minuten'};
const nums=['twaalf','één','twee','drie','vier','vijf','zes','zeven','acht','negen','tien','elf'];
function digital(t){return String(Math.floor(mod(t,1440)/60)).padStart(2,'0')+':'+String(mod(t,60)).padStart(2,'0')}
function digital12(t){return String(Math.floor(mod(t,720)/60)||12).padStart(2,'0')+':'+String(mod(t,60)).padStart(2,'0')}
function gameLabel(t){return game.format==='words'?words(t):game.format==='digital12'?digital12(t):digital(t)}
const gameHelpers={numbers:true,minutes:false,outer:false,zones:false,hourArc:false,minuteArc:false};
function words(t){let m=mod(t,60),h=Math.floor(mod(t,1440)/60)%12,n=nums[(h+1)%12],u=nums[h],q=v=>v===1?'één minuut':v+' minuten';if(!m)return u+' uur';if(m===15)return 'kwart over '+u;if(m===30)return 'half '+n;if(m===45)return 'kwart voor '+n;if(m<15)return q(m)+' over '+u;if(m<30)return q(30-m)+' voor half '+n;if(m<45)return q(m-30)+' over half '+n;return q(60-m)+' voor '+n}
function part(t){let h=Math.floor(mod(t,1440)/60);return h<6?'Nacht':h<12?'Voormiddag':h<18?'Namiddag':'Avond'}
function p(a,r){return [300+Math.sin(a*Math.PI/180)*r,300-Math.cos(a*Math.PI/180)*r]}
function txt(a,r,s,size,color,weight=600){let [x,y]=p(a,r);return `<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="central" font-family="Arial,sans-serif" font-size="${size}" font-weight="${weight}" fill="${color}">${s}</text>`}
function faceMarkup(v){let s=v.outer?'<circle cx="300" cy="300" r="294" fill="#6d45ad"/><circle cx="300" cy="300" r="265" fill="#f0f4fa"/>':'<circle cx="300" cy="300" r="265" fill="#f0f4fa"/>';
if(v.zones){const colors=['#e3f1ff','#fff0d8','#e9e3fa','#e1f4ed'];for(let i=0;i<4;i++){let a=p(i*90,245),b=p((i+1)*90,245);s+=`<path d="M300 300 L${a} A245 245 0 0 1 ${b} Z" fill="${colors[i]}"/>`}}
else s+='<circle cx="300" cy="300" r="245" fill="white"/>';
s+='<circle cx="300" cy="300" r="245" fill="none" stroke="#cfd9e7" stroke-width="2"/>';
for(let m=0;m<60;m++){let a=p(m*6,m%5?227:218),b=p(m*6,235);s+=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${m%5?'#9dabbc':'#3b4a60'}" stroke-width="${m%5?1.5:3}"/>`}
for(let i=0;i<12;i++){if(v.numbers)s+=txt(i*30,190,i||12,35,'#24334a');if(v.minutes)s+=txt(i*30,254,i*5,16,'#65758a');if(v.outer)s+=txt(i*30,278,(i===0?'00 / 12':String(i+12)),i===0?14:18,'#ffffff');}
if(v.zones){s+=txt(48,117,'OVER',14,'#37618e');s+=txt(133,111,'VOOR HALF',12,'#86621d');s+=txt(227,111,'OVER HALF',12,'#705d92');s+=txt(312,117,'VOOR',14,'#38725a')}
return s}
function activeGameHelpers(){return {...gameHelpers,...(game?.hintHelp||{}),outer:gameHelpers.outer&&game?.format==='digital'}}
function face(){$('face').innerHTML=faceMarkup(mode==='lesson'?visible:activeGameHelpers())}
function render(){let h=Math.floor(time/60),m=time%60;$('hourHand').setAttribute('transform',`rotate(${(h%12)*30+m/2} 300 300)`);$('minuteHand').setAttribute('transform',`rotate(${m*6} 300 300)`);$('hourHand').setAttribute('aria-valuenow',h);$('minuteHand').setAttribute('aria-valuenow',m);$('hourHand').setAttribute('aria-valuetext',h+' uur');$('minuteHand').setAttribute('aria-valuetext',m+' minuten');$('digital').innerHTML=coloredTime($('lessonFormat').value==='12'?digital12(time):digital(time));$('words').textContent=words(time);$('digital').hidden=mode!=='lesson'||!visible.digital;$('words').hidden=mode!=='lesson'||!visible.words;$('periodBadge').textContent=part(time);$('periodBadge').hidden=mode==='game'||$('lessonFormat').value==='12';$('switchPeriod').hidden=$('lessonFormat').value==='12';$('time').value=digital(time);document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('chosen',Number(b.dataset.period)===Math.floor(time/720)));$('dragHint').textContent=mode==='game'&&game?.type==='read'?'Welke tijd zie je op de klok?':'Sleep de rode uurwijzer of de blauwe minutenwijzer.';document.querySelectorAll('[data-delta]').forEach(b=>b.hidden=mode==='lesson'&&lessonGrid().limited&&Math.abs(Number(b.dataset.delta))<lessonGrid().step);drawArcs();}
function lessonGrid(){const kind=$('lessonPractice').value;return {step:kind==='both'?30:kind==='free'?Number($('snap').value):60,offset:kind==='halves'?30:0,limited:kind!=='free'}}
function set(t){if(mode==='lesson'){const g=lessonGrid();if(g.limited)t=Math.round((t-g.offset)/g.step)*g.step+g.offset;}time=mod(t,1440);render()}
Object.keys(visible).forEach(k=>{let l=document.createElement('label');l.className='toggle';l.innerHTML=`<span>${labels[k]}</span><input type="checkbox" ${visible[k]?'checked':''} aria-label="${labels[k]}">`;l.querySelector('input').onchange=e=>{visible[k]=e.target.checked;face();render()};$('toggles').append(l)});
function allowDrag(){return mode==='lesson'||(game&&game.type==='set'&&!game.solved&&!game.finished)}
function angle(e){let r=$('clock').getBoundingClientRect();return mod(Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2))*180/Math.PI,360)}
for(const [id,kind] of [['hourHand','hour'],['minuteHand','minute']]){let el=$(id);el.onpointerdown=e=>{if(!allowDrag())return;e.preventDefault();drag={kind,last:angle(e),total:time};el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!drag)return;let a=angle(e),diff=mod(a-drag.last+180,360)-180;drag.last=a;drag.total+=diff*(kind==='minute'?1/6:2);const g=mode==='game'?{step:game.step,offset:0}:lessonGrid();set(Math.round((drag.total-g.offset)/g.step)*g.step+g.offset)};el.onpointerup=el.onpointercancel=()=>drag=null;el.onkeydown=e=>{if(!allowDrag())return;if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].includes(e.key)){e.preventDefault();let d=['ArrowUp','ArrowRight'].includes(e.key)?1:-1;set(time+d*(kind==='hour'?60:mode==='game'?game.step:lessonGrid().step))}}}
document.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>{if(allowDrag())set(time+Number(b.dataset.delta))});$('setTime').onclick=()=>{let v=$('time').value;if(v){let [h,m]=v.split(':').map(Number);set(h*60+m)}};$('switchPeriod').onclick=()=>set(time+720);
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('fullscreen').textContent='Gebruik de schermknop van uw browser'}};
function switchMode(m){mode=m;if(m==='lesson')set(time);$('lesson').classList.toggle('selected',m==='lesson');$('play').classList.toggle('selected',m==='game');$('lessonPanel').hidden=m!=='lesson';$('gamePanel').hidden=m!=='game';document.body.classList.toggle('playing',m==='game');$('challenge').hidden=m!=='game'||!game;$('modeLabel').textContent=m==='lesson'?'ONTDEK DE TIJD':'KLASSPEL';$('nudges').hidden=m==='game'&&(!game||game.type==='read');face();render();if(m==='game'&&!game)start()}
$('lesson').onclick=()=>switchMode('lesson');$('play').onclick=()=>switchMode('game');
function start(){game={score:0,step:Number($('level').value),type:$('gameType').value,format:$('format').value};$('challenge').hidden=false;question()}
function question(){game.solved=false;game.finished=false;game.hintHelp={};game.mistakes=0;game.target=Math.floor(Math.random()*((game.format==='digital'?1440:720)/game.step))*game.step;$('stars').textContent='★'.repeat(game.score)+'☆'.repeat(10-game.score);$('feedback').textContent='';$('next').hidden=true;$('answers').innerHTML='';$('check').disabled=false;$('check').hidden=game.type!=='set';$('periodChoice').hidden=game.type!=='set'||game.format!=='digital';$('nudges').hidden=game.type==='read';$('answers').classList.toggle('wordsOptions',game.format==='words');
if(game.type==='set'){$('question').textContent='Zet de klok op '+gameLabel(game.target)+'.';set(mod(game.target+185,1440));}else{$('question').textContent=game.format==='digital'?'Hoe laat is het? ('+part(game.target).toLowerCase()+')':'Hoe laat is het?';set(game.target);let opts=new Map(),format=gameLabel;opts.set(format(game.target),game.target);while(opts.size<4){let t=Math.floor(Math.random()*((game.format==='digital'?1440:720)/game.step))*game.step;opts.set(format(t),t)}for(const [label,t]of [...opts].sort(()=>Math.random()-.5)){let b=document.createElement('button');b.innerHTML=game.format==='words'?label:coloredTime(label);b.onclick=()=>{if(!game.solved){b.classList.add('chosen');answer(game.format==='digital'?t===game.target:t%720===game.target%720,t);if(!game.solved)b.classList.remove('chosen')}};$('answers').append(b)}}face();render()}
function answer(ok,candidate=time){if(!ok){game.mistakes=(game.mistakes||0)+1;game.hintHelp=game.hintHelp||{};const targetHour=Math.floor(game.target/60),givenHour=Math.floor(candidate/60);const hourWrong=(game.format==='digital'?targetHour!==givenHour:targetHour%12!==givenHour%12),minuteWrong=candidate%60!==game.target%60;let hint='';if(hourWrong&&(!game.hintHelp.hourArc||!minuteWrong)){game.hintHelp.numbers=true;game.hintHelp.hourArc=true;hint=game.format==='digital'&&targetHour%12===givenHour%12?'Kijk naar het dagdeel in de opdracht. Welk uur hoort daarbij in de 24-uursnotatie?':'Volg de kleine rode wijzer. Bij welk uurgetal staat hij, of welk uurgetal is hij net voorbij?';}else{game.hintHelp.minuteArc=true;game.hintHelp.minutes=true;hint='Volg de grote blauwe wijzer. Tel vanaf de 12: elk groot streepje is 5 minuten, elk klein streepje 1 minuut.';}if(game.format==='words'&&game.mistakes>1){game.hintHelp.zones=true;hint+=' Gebruik ook de hulpwoorden op de klok.';}$('feedback').textContent='Probeer opnieuw. '+hint;$('feedback').style.color='#a34c14';face();render();return}game.solved=true;game.score++;$('stars').textContent='★'.repeat(game.score)+'☆'.repeat(10-game.score);$('feedback').style.color='#23694d';$('feedback').textContent='Goed gedaan! '+(game.format==='digital'?digital(game.target):digital12(game.target))+' = '+words(game.target)+'.';$('check').disabled=true;document.querySelectorAll('#answers button').forEach(b=>b.disabled=true);if(game.score===10){game.finished=true;$('feedback').textContent='Tien sterren! Jullie zijn klokkenkampioenen! ★';$('next').textContent='Nog een spel →'}else $('next').textContent='Volgende opdracht →';$('next').hidden=false}
$('check').onclick=()=>{if(game&&!game.solved)answer(game.format==='digital'?time===game.target:time%720===game.target%720)};$('next').onclick=()=>game.finished?start():question();$('start').onclick=start;for(let id of ['gameType','level','format'])$(id).onchange=()=>{if(mode==='game')start()};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{if(allowDrag())set(time%720+Number(b.dataset.period)*720)});face();render();

function coloredTime(value){let [h,m]=value.split(':');return `<span class="hourText">${h}</span><span class="colon">:</span><span class="minuteText">${m}</span>`}
function arc(radius,degrees,color){if(degrees<=0)return '';let end=p(degrees,radius);return `<path d="M300 ${300-radius} A${radius} ${radius} 0 ${degrees>180?1:0} 1 ${end[0]} ${end[1]}" fill="none" stroke="${color}" stroke-width="8"/>`}
function drawArcs(){let v=mode==='lesson'?visible:activeGameHelpers();let h=Math.floor(time/60)%12,m=time%60;$('helpArcs').innerHTML=(v.hourArc?arc(305,h*30+m/2,'#e3294b'):'')+(v.minuteArc?arc(319,m*6,'#008fc4'):'')}
for(const k of Object.keys(gameHelpers)){let l=document.createElement('label');l.className='toggle';l.innerHTML=`<span>${labels[k]}</span><input type="checkbox" ${gameHelpers[k]?'checked':''} aria-label="${labels[k]} in klasspel">`;l.querySelector('input').onchange=e=>{gameHelpers[k]=e.target.checked;face();render()};$('gameHelpers').append(l)}
$('lessonFormat').onchange=()=>{if($('lessonFormat').value==='12'){visible.outer=false;const index=Object.keys(visible).indexOf('outer');$('toggles').children[index].querySelector('input').checked=false}face();render()};render();

$('lessonPractice').onchange=()=>{const g=lessonGrid();$('snapSetting').hidden=g.limited;$('lessonPracticeNote').textContent=$('lessonPractice').value==='hours'?'Alleen tijden met 00 minuten.':$('lessonPractice').value==='halves'?'Alleen tijden met 30 minuten, zoals half drie.':$('lessonPractice').value==='both'?'Tijden met 00 of 30 minuten.':'Kies een oefensoort of verplaats de wijzers vrij.';set(time);};
$('lessonRandom').onclick=()=>{const g=lessonGrid(),range=$('lessonFormat').value==='12'?720:1440,options=[];for(let t=g.offset;t<range;t+=g.step)if(t!==time%range)options.push(t);set(options[Math.floor(Math.random()*options.length)]);};

$('settingsToggle').onclick=()=>{const closed=!$('teacherSettings').hidden;$('teacherSettings').hidden=closed;$('singleMain').classList.toggle('settingsClosed',closed);$('settingsToggle').setAttribute('aria-expanded',String(!closed));$('settingsToggle').textContent=closed?'Instellingen openen ◂':'Instellingen dichtklappen ▸';};
