const duoHelp={numbers:true,minutes:false,outer:false,zones:false,hourArc:false,minuteArc:false};
let duel=null,duoTick=null;
for(const k of Object.keys(duoHelp)){const label=document.createElement('label');label.className='toggle';label.innerHTML=`<span>${labels[k]}</span><input type="checkbox" ${duoHelp[k]?'checked':''} aria-label="${labels[k]} in duospel">`;label.querySelector('input').onchange=e=>duoHelp[k]=e.target.checked;$('duoHelpers').append(label)}
function clearDuoTimer(){clearInterval(duoTick);duoTick=null}
function duoView(view){for(const id of ['duoSetup','duoStage','duoResult'])$(id).hidden=id!==view;$('singleMain').hidden=!!view;$('duoTab').classList.toggle('selected',!!view);document.body.classList.toggle('duoActive',!!view);if(view){$('lesson').classList.remove('selected');$('play').classList.remove('selected');document.body.classList.remove('playing')}}
$('duoTab').onclick=()=>{clearDuoTimer();duel=null;duoView('duoSetup')};
for(const [id,m]of [['lesson','lesson'],['play','game']])$(id).onclick=()=>{clearDuoTimer();duel=null;duoView(null);switchMode(m)};
function shuffled(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function duoText(t){return duel.format==='words'?words(t):duel.format==='digital12'?digital12(t):digital(t)}
function duoClock(t){const h=Math.floor(t/60)%12,m=t%60,v={...duel.help,outer:duel.help.outer&&duel.format==='digital'};return `<svg viewBox="-30 -30 660 660" role="img" aria-label="Analoge klok om af te lezen">${faceMarkup(v)}${v.hourArc?arc(305,h*30+m/2,'#e3294b'):''}${v.minuteArc?arc(319,m*6,'#008fc4'):''}<line class="hour" x1="300" y1="315" x2="300" y2="174" transform="rotate(${h*30+m/2} 300 300)"/><line class="minute" x1="300" y1="322" x2="300" y2="106" transform="rotate(${m*6} 300 300)"/><circle cx="300" cy="300" r="13" fill="#25334a"/></svg>`}
$('duoRaceMode').onchange=()=>{const count=$('duoRaceMode').value==='count';$('duoCountWrap').hidden=!count;$('duoDurationWrap').hidden=count};
function startDuo(){clearDuoTimer();const step=Number($('duoLevel').value),format=$('duoFormat').value,duration=Number($('duoDuration').value)*1000;const pool=Array.from({length:(format==='digital'?1440:720)/step},(_,i)=>i*step);duel={format,step,countMode:$('duoRaceMode').value==='count',limit:Number($('duoCount').value),help:{...duoHelp},duration,remaining:duration,deadline:performance.now()+duration,pool,scores:[0,0],teams:[0,1].map(()=>({answered:0,locked:false,done:false,target:null,sequence:shuffled(pool),index:0,readyAt:0})),paused:false,ended:false};duoView('duoStage');$('duoBoards').innerHTML='';$('duoPause').disabled=false;$('duoPause').textContent='Pauze';$('duoRoundStatus').textContent='Kies het juiste uur en wissel meteen van leerling!';for(let i=0;i<2;i++){const panel=document.createElement('article');panel.className='duoBoard team'+i;panel.id='duoTeam'+i;$('duoBoards').append(panel);nextDuoClock(i)}updateDuoTimer();duoTick=setInterval(updateDuoTimer,80)}
function nextDuoClock(i){if(!duel||duel.ended||duel.paused)return;const team=duel.teams[i];if(duel.countMode&&team.answered>=duel.limit){team.done=true;$('duoChoices'+i).innerHTML='';$('duoFeedback'+i).textContent='Klaar! '+duel.scores[i]+'/'+duel.limit+' juist. De andere groep mag afwerken.';if(duel.teams.every(t=>t.done))finishDuo();return}if(team.index>=team.sequence.length){team.sequence=shuffled(duel.pool);team.index=0;if(team.sequence[0]===team.target)[team.sequence[0],team.sequence[1]]=[team.sequence[1],team.sequence[0]]}team.target=team.sequence[team.index++];team.locked=false;const target=team.target,options=shuffled([target,...shuffled(duel.pool.filter(t=>t!==target)).slice(0,3)]);$('duoTeam'+i).innerHTML=`<div class="teamHeading"><h2>Groep ${i+1}</h2><span class="teamScore" id="duoScore${i}">${duel.scores[i]}${duel.countMode?'/'+duel.limit+' juist':' punten'}</span></div><p class="duoPrompt">${duel.countMode?'Klok '+(team.answered+1)+' van '+duel.limit+' · ':''}Hoe laat is het?${duel.format==='digital'?' · '+part(target):''}</p><div class="duoClock">${duoClock(target)}</div><div class="duoChoices ${duel.format==='words'?'wordChoices':''}" id="duoChoices${i}"></div><p id="duoFeedback${i}" class="duoFeedback" role="status" aria-live="polite">${team.answered?'Volgende leerling!':'Klaar? Kies het juiste uur!'}</p>`;for(const t of options){const button=document.createElement('button');button.dataset.time=String(t);button.innerHTML=duel.format==='words'?duoText(t):coloredTime(duoText(t));button.onclick=()=>chooseDuo(i,t);$('duoChoices'+i).append(button)}}
function updateDuoTimer(){if(!duel||duel.ended)return;if(!duel.paused&&!duel.countMode)duel.remaining=Math.max(0,duel.deadline-performance.now());const seconds=Math.ceil(duel.remaining/1000);$('duoTimer').textContent=duel.paused?'Gepauzeerd':duel.countMode?`${duel.limit} klokken per groep`:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('duoTimer').classList.toggle('timeLow',!duel.countMode&&seconds<=10);$('duoTimeBar').style.width=(duel.countMode?(duel.teams[0].answered+duel.teams[1].answered)/(2*duel.limit)*100:duel.remaining/duel.duration*100)+'%';const [a,b]=duel.scores;$('duoRoundLabel').textContent=a===b?'Gelijke stand!':`Groep ${a>b?1:2} staat voor!`;if(duel.paused)return;if(!duel.countMode&&duel.remaining<=0){finishDuo();return}for(let i=0;i<2;i++)if(!duel.teams[i].done&&duel.teams[i].locked&&performance.now()>=duel.teams[i].readyAt)nextDuoClock(i)}
function chooseDuo(i,t){if(!duel||duel.paused||duel.ended)return;if(!duel.countMode&&performance.now()>=duel.deadline){finishDuo();return}const team=duel.teams[i];if(team.locked||team.done)return;team.locked=true;team.answered++;const correct=t===team.target;if(correct)duel.scores[i]++;team.readyAt=performance.now()+(correct?650:1100);$('duoScore'+i).textContent=duel.scores[i]+(duel.countMode?'/'+duel.limit+' juist':' punten');$('duoFeedback'+i).textContent=correct?'Juist! +1 punt. Wissel!':'0 punten. Het is '+duoText(team.target)+'.';$('duoFeedback'+i).className='duoFeedback '+(correct?'correct':'incorrect');for(const b of $('duoChoices'+i).children){b.disabled=true;if(Number(b.dataset.time)===team.target)b.classList.add('correctAnswer');else if(Number(b.dataset.time)===t)b.classList.add('wrongAnswer')}updateDuoTimer()}
function pauseDuo(){if(!duel||duel.ended)return;const now=performance.now();if(!duel.paused){updateDuoTimer();if(duel.ended)return;duel.paused=true;duel.pausedAt=now}else{duel.deadline=now+duel.remaining;for(const team of duel.teams)if(team.locked)team.readyAt+=now-duel.pausedAt;duel.paused=false}$('duoPause').textContent=duel.paused?'Verder spelen':'Pauze';$('duoRoundStatus').textContent=duel.paused?'Pauze. De tijd staat stil.':'Kies het juiste uur en wissel meteen van leerling!';for(let i=0;i<2;i++)for(const b of $('duoChoices'+i).children)b.disabled=duel.paused||duel.teams[i].locked;updateDuoTimer()}
function finishDuo(){if(!duel||duel.ended)return;clearDuoTimer();duel.ended=true;duel.remaining=0;duoView('duoResult');const [a,b]=duel.scores;const tie=a===b;$('duoWinner').textContent=tie?'Gelijkspel! Samen kampioen!':`Groep ${a>b?1:2} wint!`;$('duoPraise').textContent=(duel.countMode?'Alle klokken zijn beantwoord. ':'De tijd is om. ')+(tie?'Jullie hebben evenveel klokken juist gelezen!':'Wat een knappe klokkenrace!');$('duoFinalScores').innerHTML=duel.teams.map((team,i)=>`<div class="team${i}"><b>Groep ${i+1}</b><strong>${duel.scores[i]}${duel.countMode?'/'+duel.limit:''}</strong><span>${duel.countMode?'klokken juist':duel.scores[i]+' punten'}</span><span>${team.answered} klokken beantwoord</span></div>`).join('');$('duoResult').classList.remove('celebrate');void $('duoResult').offsetWidth;$('duoResult').classList.add('celebrate')}
$('duoStart').onclick=startDuo;$('duoPause').onclick=pauseDuo;$('duoExit').onclick=()=>{clearDuoTimer();duel=null;duoView('duoSetup')};$('duoAgain').onclick=startDuo;$('duoSettings').onclick=()=>{clearDuoTimer();duel=null;duoView('duoSetup')};
