'use client';
import {useState} from 'react';
import {BookOpen,Search,House,ExternalLink,PawPrint,Music,Type,FileDown,Printer} from 'lucide-react';
import Listen from '@/components/listen';
import words from './words.json';
const normalize=(s:string)=>s.trim().toLocaleLowerCase('nl').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
export default function Lookup(){
 const [view,setView]=useState('woorden');
 const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState<string|null>(null);
 const found=submitted?words.find(w=>normalize(w.word)===normalize(submitted)):undefined;
 function clearAudio(){if('speechSynthesis'in window){window.dispatchEvent(new Event('zisa-speech'));window.speechSynthesis.cancel();}}
 function search(e:React.FormEvent){e.preventDefault();clearAudio();setSubmitted(query.trim()||null);}
 return <div className="safe-app search-app lookup-app"><header className="safe-header"><a className="safe-brand" href="/"><BookOpen size={33}/><div><strong>Zelf opzoeken</strong><small>Zisa’s digitale missies</small></div></a><a className="safe-home" href="/"><House size={23}/> Missies</a></header><main className="safe-main"><nav className="lookup-switch" aria-label="Kies waar je zoekt"><button aria-pressed={view==='woorden'} onClick={()=>setView('woorden')}><BookOpen/> Woordenbibliotheek</button><button aria-pressed={view==='websites'} onClick={()=>setView('websites')}><Search/> Zoekwebsites</button></nav>
 <section hidden={view!=='woorden'} className="lookup-dictionary" id="woordenboek"><div className="lookup-title"><div><h1>Mijn woordenbibliotheek</h1><p>Typ het woord van je werkblad. Druk op Zoek.</p></div><Listen text="Mijn woordenbibliotheek. Typ het woord van je werkblad. Druk op Zoek. Daarna zie je de uitleg en een afbeelding. Met de luidspreker kun je luisteren." label="Luister naar de zoekopdracht"/></div>
 <form onSubmit={search} className="lookup-form"><label htmlFor="lookup-query">Welk woord zoek je?</label><div><input id="lookup-query" type="search" value={query} onChange={e=>{clearAudio();setQuery(e.target.value);setSubmitted(null);}} placeholder="Typ hier je woord" autoComplete="off" autoCapitalize="none" spellCheck={false}/><button type="submit" disabled={!query.trim()}><Search size={24}/> Zoek</button></div></form>
 <div className="lookup-result" aria-live="polite">{found?<article key={found.word}><div className="word-picture" role="img" aria-label={found.alt} style={{backgroundPosition:`${(found.image%3)*50}% ${Math.floor(found.image/3)*100/3}%`}}/><div className="word-explanation"><div><h2>{found.word}</h2><Listen text={found.word+'. '+found.meaning+' Voorbeeld: '+found.example+(found.note?' '+found.note:'')} label={'Luister naar '+found.word}/></div><p className="word-meaning">{found.meaning}</p><p className="word-example"><strong>Voorbeeld</strong><br/>{found.example}</p>{found.note&&<p className="word-note">{found.note}</p>}</div></article>:submitted?<div className="lookup-not-found"><p>Dit woord vinden we nog niet. Kijk of je het juist hebt getypt. Vraag hulp als het niet lukt.</p><Listen text="Dit woord vinden we nog niet. Kijk of je het juist hebt getypt. Vraag hulp als het niet lukt." label="Luister naar de zoekhulp"/></div>:<div className="lookup-empty"><Search size={35}/><p>Zoek een woord. Hier verschijnt de uitleg.</p></div>}</div>
 <p className="lookup-count">Deze oefenbibliotheek bevat {words.length} woorden voor de werkbladen.</p></section>
 <section hidden={view!=='websites'} className="search-shelf"><h2>Zelf opzoeken</h2><p>De websites openen in een nieuw tabblad. Vraag hulp als je vastloopt.</p><div className="search-links">{[{name:'Dieren en weetjes',site:'Schooltv',url:'https://schooltv.nl/',icon:PawPrint},{name:'Dansen en meedoen',site:'Zappelin',url:'https://www.zappelin.nl/programmas/zin-in-zappelin',icon:Music},{name:'Samen informatie lezen',site:'WikiKids · met hulp',url:'https://wikikids.nl/',icon:BookOpen},{name:'Samen een woord opzoeken',site:'Woorden.org · gratis',url:'https://www.woorden.org/',icon:Type}].map(link=><div key={link.site}><a href={link.url} target="_blank" rel="noopener noreferrer"><link.icon size={40}/><strong>{link.name}</strong><span>{link.site} <ExternalLink size={15}/></span></a><Listen text={link.name+'. '+link.site+'. Opent een nieuwe website.'} label={'Luister: '+link.name}/></div>)}</div></section>

 <details className="lookup-print"><summary><Printer size={24}/> Voor de leerkracht: werkbladen afdrukken</summary><p>Vier losse A4-werkbladen bij deze twaalf woorden. Kies het blad dat past bij je leerlingen: verbinden, afbeeldingen kiezen, woorden in zinnen invullen of verklaringen overschrijven. Open deze woordenbibliotheek via de tegel Zelf opzoeken.</p><div className="lookup-downloads"><a href="/werkbladen/woordenbibliotheek-opdrachten.pdf" target="_blank" rel="noopener noreferrer"><FileDown size={25}/><span><strong>Opdrachten</strong><small>PDF · 4 pagina’s</small></span></a><a href="/werkbladen/woordenbibliotheek-oplossingen.pdf" target="_blank" rel="noopener noreferrer"><FileDown size={25}/><span><strong>Oplossingen en lestips</strong><small>PDF · 2 pagina’s</small></span></a></div><p>Gebruik één iPad per kind of per duo. De leerling zoekt telkens zelf het volledige woord. De verklaring en afbeelding verschijnen pas na Zoek. Woorden uit deze bundel: winterslaap, zoogdier, schuilplaats, voedsel, giftig, onderzoeken, bron, route, toestemming, privé, pauze, vergelijken.</p></details>
 <details className="safe-teacher"><summary>Voor de leerkracht: websites kiezen</summary><p>Schooltv biedt uitlegfilmpjes; kies vooraf materiaal dat past bij 7–8 jaar. Bij Zappelin zijn dansen en meedoen visueel. WikiKids richt zich op 8–15 jaar: voor veel leerlingen van het tweede leerjaar is begeleiding bij het lezen nodig. Er kunnen meerdere goede bronnen zijn voor één vraag. Bespreek ook boeken en een deskundige als zoekmiddel.</p><p><a href="https://www.woorden.org/" target="_blank" rel="noopener noreferrer">Woorden.org</a> is gratis en vraagt geen abonnement. Het is geen specifiek kinderwoordenboek; help leerlingen bij moeilijke betekenissen. De leerlingknop heet daarom ‘Samen een woord opzoeken’. De eigen woordenbibliotheek hierboven bevat twaalf oefenwoorden met eenvoudige uitleg en vervangt geen volledig woordenboek.</p><p><a href="https://support.google.com/youtubekids/answer/6130561?hl=nl" target="_blank" rel="noopener noreferrer">YouTube Kids</a> heeft een instelling voor 5–8 jaar. Een ouder of begeleider moet het instellen; filtering is niet foutloos. Voor de eerste zoekopdrachten gebruiken we daarom de gerichte Zappelin-knop. Controleer externe inhoud vooraf; afspelen kan van regio, cookies en schoolinstellingen afhangen.</p><p>Paddenstoelen: dit is een oefening in bronnen kiezen, nooit in eetbaarheid vaststellen. Laat kinderen niets proeven of zelf identificeren via foto’s. Zie <a href="https://www.antigifcentrum.be/Toxinfos/oproepen-rond-paddenstoelen/" target="_blank" rel="noopener noreferrer">Antigifcentrum</a> voor achtergrond voor volwassenen.</p></details>
 </main></div>;
}

