'use client';
import {useState} from 'react';
import {ShieldCheck,MessageCircle,House,Users,Hand,LockKeyhole,Send,Camera,Eye,Timer,CircleDot,Moon,HeartHandshake,Gift,Smile,ArrowRight,ChevronLeft,ChevronRight,Check,RotateCcw} from 'lucide-react';
import Listen from '@/components/listen';
import {scenarios,IconName} from './scenarios';
const icons={message:MessageCircle,home:House,people:Users,hand:Hand,lock:LockKeyhole,send:Send,camera:Camera,eye:Eye,timer:Timer,ball:CircleDot,moon:Moon,help:HeartHandshake,gift:Gift,smile:Smile};
export default function Safety(){const [index,setIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[solved,setSolved]=useState<number[]>([]),[finished,setFinished]=useState(false);const task=scenarios[index];const Scene=icons[task.icon];const correct=answer===task.correct;
 function cancel(){if('speechSynthesis'in window){window.dispatchEvent(new Event('zisa-speech'));window.speechSynthesis.cancel();}}
 function move(n:number){cancel();setIndex(n);setAnswer(null);setFinished(false);}
 function choose(n:number){cancel();setAnswer(n);if(n===task.correct)setSolved(previous=>previous.includes(index)?previous:[...previous,index]);}
 return <div className="safe-app"><header className="safe-header"><a className="safe-brand" href="/"><ShieldCheck size={33}/><div><strong>Veilig met media</strong><small>Zisa’s digitale missies</small></div></a><a className="safe-home" href="/"><House size={23}/> Missies</a></header><main className="safe-main">
 {finished?<section className="safe-finish"><ShieldCheck size={85}/><h1>Goed geoefend!</h1><p>Je oefende {solved.length} van de {scenarios.length} situaties.</p><p>Twijfel je? Stop even en vraag hulp aan een volwassene die je vertrouwt.</p><Listen text="Goed geoefend! Twijfel je? Stop even en vraag hulp aan een volwassene die je vertrouwt." label="Luister naar de afsluiting"/><div><button onClick={()=>{move(0);setSolved([]);}}><RotateCcw/> Nog eens</button><a href="/">Naar de missies <ArrowRight/></a></div></section>:<>
 <div className="safe-nav"><button onClick={()=>move(index-1)} disabled={index===0} aria-label="Vorige situatie"><ChevronLeft/></button><span>Opdracht {index+1} van {scenarios.length} · {task.topic}</span><button onClick={()=>move(index+1)} disabled={index===scenarios.length-1} aria-label="Volgende situatie"><ChevronRight/></button></div>
 <section className="safe-story"><div className="safe-scene" aria-hidden="true"><Scene size={76} strokeWidth={1.7}/></div><div><h1>{task.title}</h1><p>{task.story}</p></div><Listen text={task.title+'. '+task.story} label="Luister naar de opdracht"/></section>
 <div className="safe-choice-heading"><h2>Wat kies jij?</h2><span>Luister met <span aria-hidden="true">🔊</span>. Tik om te kiezen.</span></div>
 <div className="safe-choices">{task.choices.map((choice,n)=>{const Icon=icons[choice.icon as IconName];return <div className={'safe-choice '+(answer===n?(correct?'chosen-right':'chosen-try'):'')} key={index+'-'+n}><button className="safe-answer" onClick={()=>choose(n)} disabled={correct} aria-pressed={answer===n}><Icon size={46} strokeWidth={1.8}/><span>{choice.label}</span>{answer===n&&correct&&<Check className="safe-answer-check" size={24}/>}</button><div className="safe-answer-audio"><Listen text={choice.label} label={`Luister naar antwoord ${n+1}: ${choice.label}`}/></div></div>;})}</div>
 {answer!==null&&<section className={'safe-feedback '+(correct?'safe-positive':'')} aria-live="polite"><div><h2>{correct?'Dat is een veilige keuze.':'Denk nog eens na.'}</h2><p>{task.choices[answer].feedback}</p>{correct&&<p className="safe-remember">{task.remember}</p>}</div><Listen text={(correct?'Dat is een veilige keuze. ':'Denk nog eens na. ')+task.choices[answer].feedback+(correct?' '+task.remember:'')} label="Luister naar de uitleg"/></section>}
 {correct&&<button className="safe-next" onClick={()=>{if(index<scenarios.length-1)move(index+1);else{cancel();setFinished(true);}}}>{index<scenarios.length-1?'Volgende opdracht':'Klaar!'} <ArrowRight size={23}/></button>}
 <nav className="safe-progress" aria-label="Kies een situatie">{scenarios.map((s,i)=><button key={s.title} onClick={()=>move(i)} aria-label={`Situatie ${i+1}: ${s.title}`} aria-current={i===index?'step':undefined} className={solved.includes(i)?'solved':''}>{solved.includes(i)?<Check size={19}/>:i+1}</button>)}</nav></>}
 <details className="safe-teacher"><summary>Voor de leerkracht</summary><p>Oefen samen of zelfstandig. Opdracht, antwoorden en uitleg hebben elk een eigen luidspreker. Luisteren kiest nooit een antwoord. De stem hangt af van de beschikbare Nederlandse stemmen op het toestel; een Belgische stem krijgt voorrang.</p><p>De situaties zijn verzonnen. Vraag geen echte wachtwoorden, adressen of persoonlijke ervaringen in de groep. Benadruk dat een kind altijd hulp mag zoeken. Bij jonge kinderen mag een ouder of verzorger helpen met wachtwoorden. Een bericht dat zich als een ouder voordoet, is iets anders dan samen naast elkaar aanmelden.</p><p>De twintig minuten in de oefening zijn een voorbeeld van een gezinsafspraak, geen algemene schermtijdnorm. Bespreek ook wat kinderen doen op een scherm en de afwisseling met bewegen, slapen en samenspelen.</p><p>De vinkjes gelden alleen tijdens deze oefensessie; er worden geen antwoorden naar de leerkracht verstuurd.</p><p>Inhoudelijke bronnen: <a href="https://childfocus.be/nl-be/Online-veiligheid/Ouders" target="_blank" rel="noopener noreferrer">Child Focus: online veiligheid</a> en <a href="https://www.mediawijs.be/nl/artikels/zo-maak-je-afspraken-met-kinderen-over-hun-mediagebruik" target="_blank" rel="noopener noreferrer">Mediawijs: afspraken over mediagebruik</a>. Eigen oefeningen van Zisa; geen officiële toets of samenwerking.</p></details>
 </main></div>;
}
