export type IconName='message'|'home'|'people'|'hand'|'lock'|'send'|'camera'|'eye'|'timer'|'ball'|'moon'|'help'|'gift'|'smile';
type Answer={label:string;icon:IconName;feedback:string};
export type Scenario={topic:string;title:string;story:string;icon:IconName;choices:Answer[];correct:number;remember:string};
export const scenarios:Scenario[]=[
 {topic:'Berichten',title:'Waar woon jij?',story:'In een spel vraagt iemand die je niet kent: “Wat is je adres?” Wat doe je?',icon:'message',correct:1,choices:[{label:'Ik stuur mijn adres.',icon:'home',feedback:'Je adres is privé. Geef het niet aan iemand die je niet kent.'},{label:'Ik toon het aan mijn papa of mama.',icon:'people',feedback:'Je geeft je adres niet door. Samen met je papa of mama bekijk je het bericht.'},{label:'Ik stuur een foto van mijn huis.',icon:'camera',feedback:'Ook op een foto kan iemand zien waar je woont. Deel die niet zomaar.'}],remember:'Privégegevens houd je voor jezelf. Vraag hulp als je twijfelt.'},
 {topic:'Berichten',title:'Zullen we afspreken?',story:'Iemand die je alleen uit een spel kent, wil je ontmoeten in het park. Wat doe je?',icon:'people',correct:2,choices:[{label:'Ik ga alleen naar het park.',icon:'ball',feedback:'Je weet niet zeker wie er achter het scherm zit. Ga niet zelf naar die afspraak.'},{label:'Ik neem een vriendje mee.',icon:'people',feedback:'Ook samen met een vriendje ga je niet zelf naar zo’n afspraak. Betrek je papa of mama.'},{label:'Ik bespreek het met mijn papa of mama.',icon:'help',feedback:'Spreek niets zelf af en ga niet op eigen houtje. Laat je papa of mama het bericht zien.'}],remember:'Online afspreken? Eerst praten met je papa of mama.'},
 {topic:'Berichten',title:'Ons geheimpje?',story:'Iemand stuurt je een vervelend bericht en zegt: “Niet aan de juf vertellen!” Wat doe je?',icon:'message',correct:0,choices:[{label:'Ik vertel het aan de juf.',icon:'help',feedback:'Je mag hulp vragen, ook als iemand zegt dat het geheim moet blijven. Je papa of mama of andere vertrouwde volwassene kan ook helpen.'},{label:'Ik houd het geheim.',icon:'lock',feedback:'Een geheim dat je bang of verdrietig maakt, hoef je niet te bewaren. Vertel het aan een volwassene die je vertrouwt.'},{label:'Ik blijf berichtjes sturen.',icon:'send',feedback:'Je hoeft niet verder te praten als iets niet fijn voelt. Stop en haal hulp.'}],remember:'Een naar geheim mag je altijd vertellen.'},
 {topic:'Wachtwoorden',title:'Mijn beste vriend',story:'Je beste vriend wil jouw wachtwoord om met jouw spelaccount te spelen. Wat kies je?',icon:'lock',correct:1,choices:[{label:'Ik geef mijn wachtwoord.',icon:'send',feedback:'Ook aan een beste vriend geef je je wachtwoord niet. Het beschermt jouw account.'},{label:'Mijn wachtwoord blijft privé.',icon:'lock',feedback:'Je kunt samen spelen zonder je wachtwoord door te geven.'},{label:'Ik stuur het naar de hele klas.',icon:'people',feedback:'Dan kunnen anderen jouw account gebruiken. Je wachtwoord is niet voor de klas.'}],remember:'Een wachtwoord geef je niet aan vrienden of onbekenden.'},
 {topic:'Wachtwoorden',title:'Samen met mijn papa of mama',story:'Je bent zeven. Je papa of mama zit naast je en helpt je veilig aanmelden. Mag die jouw wachtwoord weten?',icon:'people',correct:0,choices:[{label:'Ja, om mij te helpen.',icon:'people',feedback:'Je papa of mama mag je op jouw leeftijd helpen en je wachtwoord kennen. Spreek samen af hoe jullie het veilig bewaren.'},{label:'Nee, ook mijn papa of mama nooit.',icon:'hand',feedback:'Je hoeft dit niet alleen te doen. Je papa of mama mag je helpen je account veilig te gebruiken.'},{label:'Ja, dan mag iedereen het weten.',icon:'send',feedback:'Hulp van je papa of mama is iets anders dan je wachtwoord aan iedereen geven.'}],remember:'Je papa of mama mag helpen. Je wachtwoord is niet voor iedereen.'},
 {topic:'Wachtwoorden',title:'Een gratis prijs?',story:'Een bericht belooft gratis spelmunten als je jouw wachtwoord stuurt. Wat doe je?',icon:'gift',correct:2,choices:[{label:'Ik stuur het snel.',icon:'send',feedback:'Een mooie belofte maakt een bericht niet betrouwbaar. Stuur je wachtwoord niet.'},{label:'Ik stuur het wachtwoord van een vriend.',icon:'people',feedback:'Ook andermans wachtwoord houd je privé. Je geeft geen enkel wachtwoord door.'},{label:'Ik stuur niets en vraag hulp.',icon:'help',feedback:'Laat het bericht aan je papa of mama zien. Die helpt je controleren en zo nodig blokkeren of melden.'}],remember:'Een prijs in ruil voor je wachtwoord? Niet doen.'},
 {topic:'Foto’s',title:'Een grappige foto',story:'Je hebt een grappige foto van een klasgenoot. Je wilt hem doorsturen. Wat doe je eerst?',icon:'camera',correct:1,choices:[{label:'Ik stuur de foto meteen.',icon:'send',feedback:'De ander mag mee beslissen over zijn of haar foto. Stuur niet zomaar door.'},{label:'Ik vraag toestemming en hulp.',icon:'people',feedback:'Vraag het aan je klasgenoot en laat je papa of mama of leerkracht helpen nagaan of delen mag. Bij een nee deel je de foto niet.'},{label:'Ik vraag alleen of vrienden hem leuk vinden.',icon:'smile',feedback:'Dat vrienden de foto leuk vinden, betekent niet dat de persoon op de foto toestemming geeft.'}],remember:'Eerst toestemming. Zegt iemand nee? Dan deel je niet.'},
 {topic:'Foto’s',title:'Stuur eens een foto',story:'Iemand die je niet kent vraagt in een spel om een foto van jou. Wat doe je?',icon:'camera',correct:0,choices:[{label:'Ik stuur niets en haal mijn papa of mama.',icon:'help',feedback:'Je hoeft geen foto te sturen. Bespreek het verzoek met je papa of mama.'},{label:'Ik maak snel een foto.',icon:'camera',feedback:'Je weet niet wat iemand met je foto doet. Laat eerst je papa of mama meekijken.'},{label:'Ik stuur een foto van mijn vriend.',icon:'people',feedback:'Ook foto’s van anderen stuur je niet zomaar door.'}],remember:'Je hoeft geen foto te sturen omdat iemand dat vraagt.'},
 {topic:'Gevoelens',title:'Dat wil ik niet zien',story:'Er verschijnt een filmpje dat je bang maakt. Wat helpt?',icon:'eye',correct:2,choices:[{label:'Ik blijf kijken, ook al ben ik bang.',icon:'eye',feedback:'Je hoeft niet verder te kijken. Kijk weg of sluit het beeld en vraag hulp.'},{label:'Ik stuur het naar mijn vrienden.',icon:'send',feedback:'Daar kunnen je vrienden ook van schrikken. Zoek hulp bij een volwassene.'},{label:'Ik stop en vertel het aan een volwassene.',icon:'help',feedback:'Kijk weg of sluit het beeld. Vertel aan een vertrouwde volwassene wat je zag. Je hebt niets verkeerd gedaan door te schrikken.'}],remember:'Stop, kijk weg en praat. Je hoeft het niet alleen op te lossen.'},
 {topic:'Schermtijd',title:'De timer gaat',story:'Je hebt met je papa of mama afgesproken: vandaag twintig minuten spelen. De timer gaat. Wat doe je?',icon:'timer',correct:1,choices:[{label:'Ik zet stiekem de timer opnieuw.',icon:'timer',feedback:'Zo verander je de afspraak zonder overleg. Bespreek het eerlijk met je papa of mama.'},{label:'Ik stop volgens onze afspraak.',icon:'hand',feedback:'Je rondt af zoals afgesproken en doet iets anders. Twintig minuten is hier een voorbeeldafspraak, geen regel voor elk kind.'},{label:'Ik blijf spelen tot ik alles win.',icon:'gift',feedback:'Een spel kan lang doorgaan. Daarom helpt een duidelijke afspraak om te stoppen.'}],remember:'Hoe lang je een scherm gebruikt, spreek je samen af.'},
 {topic:'Schermtijd',title:'Tijd voor iets anders',story:'Je hebt een tijd naar een scherm gekeken. Je lijf wil bewegen. Wat kies je nu?',icon:'ball',correct:0,choices:[{label:'Ik leg het weg en ga bewegen.',icon:'ball',feedback:'Fijn! Wissel schermen af met bewegen, spelen en tijd met andere mensen.'},{label:'Ik pak meteen een ander scherm.',icon:'eye',feedback:'Een ander scherm is nog geen beweegpauze. Geef je lijf ruimte om te bewegen.'},{label:'Ik blijf zitten tot het donker is.',icon:'moon',feedback:'Je lijf heeft ook beweging en afwisseling nodig. Neem een pauze.'}],remember:'Schermen zijn leuk. Spelen en bewegen horen er ook bij.'},
 {topic:'Hulp vragen',title:'Oei, al verstuurd',story:'Je hebt toch iets doorgestuurd en je hebt er spijt van. Wat doe je?',icon:'help',correct:2,choices:[{label:'Ik durf het aan niemand te vertellen.',icon:'lock',feedback:'Je mag hulp vragen, ook als je zelf iets verstuurde. Je hoeft dit niet alleen op te lossen.'},{label:'Ik stuur nog meer berichtjes.',icon:'send',feedback:'Stop even. Meer sturen helpt niet altijd. Vraag een vertrouwde volwassene om samen te kijken.'},{label:'Ik vertel het en vraag hulp.',icon:'people',feedback:'Goed dat je hulp zoekt. Je papa, mama of leerkracht kan met je kijken wat nu nodig is.'}],remember:'Ook als er iets misgaat, mag je altijd hulp vragen.'},
];
